# Generated by Django 5.1.2 on 2024-12-01 17:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_auto_20241201_1618"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalBuild",
            new_name="HistoricalList",
        ),
        migrations.RenameModel(
            old_name="Build",
            new_name="List",
        ),
    ]
