# Generated by Django 5.1.2 on 2024-12-01 17:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_auto_20241201_1618"),
        ("core", "0002_rename_historicalbuild_historicallist_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalBuildFighter",
            new_name="HistoricalListFighter",
        ),
        migrations.RenameModel(
            old_name="BuildFighter",
            new_name="ListFighter",
        ),
        migrations.AlterModelOptions(
            name="historicallistfighter",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical List Fighter",
                "verbose_name_plural": "historical List Fighters",
            },
        ),
        migrations.AlterModelOptions(
            name="listfighter",
            options={
                "verbose_name": "List Fighter",
                "verbose_name_plural": "List Fighters",
            },
        ),
    ]
