# Generated by Django 5.1.2 on 2024-10-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_fighterequipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("AMMO", "Ammo"),
                    ("ARMOR", "Armor"),
                    ("BASIC_WEAPONS", "Basic Weapons"),
                    ("BIONICS", "Bionics"),
                    ("BODY_UPGRADES", "Body Upgrades"),
                    ("CHEMS", "Chems"),
                    ("CLOSE_COMBAT", "Close Combat"),
                    ("DRIVE_UPGRADES", "Drive Upgrades"),
                    ("ENGINE_UPGRADES", "Engine Upgrades"),
                    ("EQUIPMENT", "Equipment"),
                    ("GRENADES", "Grenades"),
                    ("HARDPOINT_UPGRADES", "Hardpoint Upgrades"),
                    ("HEAVY_WEAPONS", "Heavy Weapons"),
                    ("MOUNTS", "Mounts"),
                    ("PISTOLS", "Pistols"),
                    ("SPECIAL_WEAPONS", "Special Weapons"),
                    ("STATUS_ITEMS", "Status Items"),
                    ("VEHICLE_EQUIPMENT", "Vehicle Equipment"),
                ],
                max_length=255,
            ),
        ),
    ]
