# Generated by Django 5.1.2 on 2024-10-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_category_name_alter_equipmentcategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fighterequipment",
            name="cost",
            field=models.IntegerField(default=0),
        ),
    ]
