# Generated by Django 5.1.2 on 2024-12-01 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_historicalbuildfighter_historicallistfighter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicallistfighter",
            old_name="build",
            new_name="list",
        ),
        migrations.RenameField(
            model_name="listfighter",
            old_name="build",
            new_name="list",
        ),
    ]
