# Generated by Django 5.1.2 on 2024-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_historicalbuild_historicalbuildfighter"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="buildfighter",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="historicalbuild",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="historicalbuildfighter",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
    ]
