# Generated by Django 5.1.2 on 2024-12-01 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_build_historicallistfighter_list_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicallist",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical List",
                "verbose_name_plural": "historical Lists",
            },
        ),
        migrations.AlterModelOptions(
            name="list",
            options={"verbose_name": "List", "verbose_name_plural": "Lists"},
        ),
    ]
