# Generated by Django 5.1.2 on 2024-10-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_fighterequipment_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                ("version", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("rules", models.JSONField()),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.fighter"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
