# Generated by Django 5.1.2 on 2024-12-01 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_auto_20241201_1618"),
        ("core", "0006_historicallistfighterequipmentassignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="weapon_profile",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentweaponprofile",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="weapon_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentweaponprofile",
            ),
        ),
    ]
