# Generated by Django 5.1.2 on 2024-10-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_importversion"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="ContentCategory",
        ),
        migrations.RenameModel(
            old_name="Equipment",
            new_name="ContentEquipment",
        ),
        migrations.RenameModel(
            old_name="EquipmentCategory",
            new_name="ContentEquipmentCategory",
        ),
        migrations.RenameModel(
            old_name="Fighter",
            new_name="ContentFighter",
        ),
        migrations.RenameModel(
            old_name="FighterEquipment",
            new_name="ContentFighterEquipment",
        ),
        migrations.RenameModel(
            old_name="House",
            new_name="ContentHouse",
        ),
        migrations.RenameModel(
            old_name="ImportVersion",
            new_name="ContentImportVersion",
        ),
        migrations.RenameModel(
            old_name="Policy",
            new_name="ContentPolicy",
        ),
    ]
