# Generated by Django 5.1.2 on 2024-12-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        (
            "core",
            "0007_historicallistfighterequipmentassignment_weapon_profile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listfighter",
            name="skills",
            field=models.ManyToManyField(blank=True, to="content.contentskill"),
        ),
    ]
