# Generated by Django 5.1.2 on 2024-10-26 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_category_contentcategory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="ContentSkill",
        ),
    ]
