# Generated by Django 5.1.2 on 2024-10-27 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_rename_skill_contentskill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentcategory",
            options={
                "verbose_name": "Content Category",
                "verbose_name_plural": "Content Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="contentequipment",
            options={
                "verbose_name": "Content Equipment",
                "verbose_name_plural": "Content Equipment",
            },
        ),
        migrations.AlterModelOptions(
            name="contentequipmentcategory",
            options={
                "verbose_name": "Content Equipment Category",
                "verbose_name_plural": "Content Equipment Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="contentfighter",
            options={
                "verbose_name": "Content Fighter",
                "verbose_name_plural": "Content Fighters",
            },
        ),
        migrations.AlterModelOptions(
            name="contentfighterequipment",
            options={
                "verbose_name": "Content Fighter Equipment Join",
                "verbose_name_plural": "Content Fighter Equipment Joins",
            },
        ),
        migrations.AlterModelOptions(
            name="contenthouse",
            options={
                "verbose_name": "Content House",
                "verbose_name_plural": "Content Houses",
            },
        ),
        migrations.AlterModelOptions(
            name="contentimportversion",
            options={
                "verbose_name": "Content Import Version",
                "verbose_name_plural": "Content Import Versions",
            },
        ),
        migrations.AlterModelOptions(
            name="contentpolicy",
            options={
                "verbose_name": "Content Policy",
                "verbose_name_plural": "Content Policies",
            },
        ),
        migrations.AlterModelOptions(
            name="contentskill",
            options={
                "verbose_name": "Content Skill",
                "verbose_name_plural": "Content Skills",
            },
        ),
    ]
