# Generated by Django 5.1.2 on 2024-10-27 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_contentcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentfighterequipment",
            unique_together={("fighter", "equipment")},
        ),
    ]
