# Generated by Django 5.1.4 on 2024-12-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("core", "0010_historicallist_public_list_public"),
        ("core", "0011_alter_historicallist_public_alter_list_public"),
    ]

    dependencies = [
        ("core", "0009_alter_historicallist_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallist",
            name="public",
            field=models.BooleanField(
                default=True, help_text="Public lists are visible to all users."
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="public",
            field=models.BooleanField(
                default=True, help_text="Public lists are visible to all users."
            ),
        ),
    ]
