# Generated by Django 5.1.4 on 2024-12-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_historicallist_public_list_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallist",
            name="public",
            field=models.BooleanField(
                default=True, help_text="Public lists are visible to all users."
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="public",
            field=models.BooleanField(
                default=True, help_text="Public lists are visible to all users."
            ),
        ),
    ]
