# Generated by Django 5.1.2 on 2024-10-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_contentimportversion_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("house_uuid", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="BuildFighter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("fighter_uuid", models.UUIDField()),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.build"
                    ),
                ),
            ],
        ),
    ]
