# Generated by Django 5.1.4 on 2025-01-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0028_alter_contentpageref_page_and_more"),
        (
            "core",
            "0010_historicallist_public_list_public_squashed_0011_alter_historicallist_public_alter_list_public",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="weapon_profiles_field",
            field=models.ManyToManyField(
                blank=True,
                related_name="weapon_profiles",
                to="content.contentweaponprofile",
            ),
        ),
    ]
