# Generated by Django 5.1.4 on 2025-01-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0028_alter_contentpageref_page_and_more"),
        ("core", "0012_listfighterequipmentassignment_weapon_profiles_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistfighterequipmentassignment",
            name="weapon_profile",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="This field is deprecated and should not be used. Use weapon profiles instead.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentweaponprofile",
                verbose_name="weapon profile (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="weapon_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="This field is deprecated and should not be used. Use weapon profiles instead.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentweaponprofile",
                verbose_name="weapon profile (deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="weapon_profiles_field",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the costed weapon profiles to assign to this equipment. The standard profiles are automatically included in the cost of the equipment.",
                related_name="weapon_profiles",
                to="content.contentweaponprofile",
                verbose_name="weapon profiles",
            ),
        ),
    ]
