# Generated by Django 5.1.2 on 2024-10-27 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_build_buildfighter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="build",
            old_name="house_uuid",
            new_name="content_house_uuid",
        ),
        migrations.RenameField(
            model_name="buildfighter",
            old_name="fighter_uuid",
            new_name="content_fighter_uuid",
        ),
    ]
