# Generated by Django 5.1.2 on 2024-10-28 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_house_uuid_build_content_house_uuid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="build",
            options={"verbose_name": "Build", "verbose_name_plural": "Builds"},
        ),
        migrations.AlterModelOptions(
            name="buildfighter",
            options={
                "verbose_name": "Build Fighter",
                "verbose_name_plural": "Build Fighters",
            },
        ),
        migrations.RemoveField(
            model_name="contentpolicy",
            name="name",
        ),
    ]
