# Generated by Django 5.1.4 on 2025-01-01 15:47

from django.db import migrations, transaction

from gyrinx.core.models.list import (
    ListFighterEquipmentAssignment as ListFighterEquipmentAssignmentModel,
)


def do_migration(apps, schema_editor):
    ListFighterEquipmentAssignment: type[ListFighterEquipmentAssignmentModel] = (
        apps.get_model("core", "ListFighterEquipmentAssignment")
    )

    for assignment in ListFighterEquipmentAssignment.objects.all():
        with transaction.atomic():
            if assignment.weapon_profile:
                assignment.weapon_profiles_field.add(assignment.weapon_profile)
                assignment.weapon_profile = None
                assignment.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0013_alter_historicallistfighterequipmentassignment_weapon_profile_and_more",
        ),
    ]

    operations = [migrations.RunPython(do_migration)]
