# Generated by Django 5.1.4 on 2025-01-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_auto_20250101_1547"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listfighter",
            options={
                "ordering": [
                    models.Case(
                        models.When(content_fighter__category="LEADER", then=0),
                        models.When(content_fighter__category="CHAMPION", then=1),
                        models.When(content_fighter__category="PROSPECT", then=2),
                        models.When(content_fighter__category="SPECIALIST", then=3),
                        models.When(content_fighter__category="GANGER", then=4),
                        models.When(content_fighter__category="JUVE", then=5),
                        default=99,
                    ),
                    "content_fighter__category",
                    "name",
                ],
                "verbose_name": "List Fighter",
                "verbose_name_plural": "List Fighters",
            },
        ),
    ]
