# Generated by Django 5.1.2 on 2024-10-28 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_build_options_alter_buildfighter_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfighter",
            name="skills",
            field=models.ManyToManyField(to="core.contentskill"),
        ),
        migrations.CreateModel(
            name="ContentFighterEquipmentAssignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                ("qty", models.IntegerField(default=0)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contentequipment",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contentfighter",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contentimportversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Fighter Equipment Assignment",
                "verbose_name_plural": "Content Fighter Equipment Assignments",
                "unique_together": {("fighter", "equipment")},
            },
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="equipment",
            field=models.ManyToManyField(
                through="core.ContentFighterEquipmentAssignment",
                to="core.contentequipment",
            ),
        ),
    ]
