# Generated by Django 5.1.4 on 2025-01-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_listfighter_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallist",
            name="narrative",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="narrative",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="list",
            name="narrative",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="narrative",
            field=models.TextField(blank=True),
        ),
    ]
