# Generated by Django 5.1.2 on 2024-10-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_contentfighter_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentskill",
            name="category",
            field=models.CharField(default="None", max_length=255),
        ),
    ]
