# Generated by Django 5.1.4 on 2025-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_historicallist_narrative_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallist",
            name="narrative",
            field=models.TextField(
                blank=True,
                help_text="Narrative description of the gang in this list: their history and how to play them.",
                verbose_name="about",
            ),
        ),
        migrations.AlterField(
            model_name="historicallistfighter",
            name="narrative",
            field=models.TextField(
                blank=True,
                help_text="Narrative description of the Fighter: their history and how to play them.",
                verbose_name="about",
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="narrative",
            field=models.TextField(
                blank=True,
                help_text="Narrative description of the gang in this list: their history and how to play them.",
                verbose_name="about",
            ),
        ),
        migrations.AlterField(
            model_name="listfighter",
            name="narrative",
            field=models.TextField(
                blank=True,
                help_text="Narrative description of the Fighter: their history and how to play them.",
                verbose_name="about",
            ),
        ),
    ]
