# Generated by Django 5.1.5 on 2025-01-18 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_historicallist_narrative_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallistfighterequipmentassignment",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="listfighterequipmentassignment",
            name="owner",
        ),
    ]
