# Generated by Django 5.1.5 on 2025-01-18 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_remove_historicallistfighterequipmentassignment_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallistfighterequipmentassignment",
            name="weapon_profile",
        ),
        migrations.RemoveField(
            model_name="listfighterequipmentassignment",
            name="weapon_profile",
        ),
    ]
