# Generated by Django 5.1.5 on 2025-01-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0054_contentfighterdefaultassignment_weapon_accessories_field"),
        (
            "core",
            "0019_remove_historicallistfighterequipmentassignment_weapon_profile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="weapon_accessories_field",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the weapon accessories to assign to this equipment.",
                related_name="weapon_accessories",
                to="content.contentweaponaccessory",
                verbose_name="weapon accessories",
            ),
        ),
    ]
