# Generated by Django 5.1.5 on 2025-01-25 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_listfighterequipmentassignment_weapon_accessories_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listfighter",
            options={
                "verbose_name": "List Fighter",
                "verbose_name_plural": "List Fighters",
            },
        ),
    ]
