# Generated by Django 5.1.5 on 2025-01-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_listfighter_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="linked_fighter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The ListFighter that this equipment assignment is linked to.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.listfighter",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="linked_fighter",
            field=models.ForeignKey(
                blank=True,
                help_text="The ListFighter that this equipment assignment is linked to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_fighter",
                to="core.listfighter",
            ),
        ),
    ]
