# Generated by Django 5.1.5 on 2025-01-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0064_alter_contentequipmentfighterprofile_options_and_more"),
        (
            "core",
            "0022_historicallistfighterequipmentassignment_linked_fighter_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistfighterequipmentassignment",
            name="content_equipment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The ContentEquipment that this assignment is linked to.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentequipment",
                verbose_name="Equipment",
            ),
        ),
        migrations.AlterField(
            model_name="historicallistfighterequipmentassignment",
            name="linked_fighter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The ListFighter that this Equipment assignment is linked to (e.g. Exotic Beast, Vehicle).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.listfighter",
            ),
        ),
        migrations.AlterField(
            model_name="historicallistfighterequipmentassignment",
            name="list_fighter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The ListFighter that this equipment assignment is linked to.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.listfighter",
                verbose_name="Fighter",
            ),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="content_equipment",
            field=models.ForeignKey(
                help_text="The ContentEquipment that this assignment is linked to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentequipment",
                verbose_name="Equipment",
            ),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="linked_fighter",
            field=models.ForeignKey(
                blank=True,
                help_text="The ListFighter that this Equipment assignment is linked to (e.g. Exotic Beast, Vehicle).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_fighter",
                to="core.listfighter",
            ),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="list_fighter",
            field=models.ForeignKey(
                help_text="The ListFighter that this equipment assignment is linked to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.listfighter",
                verbose_name="Fighter",
            ),
        ),
    ]
