# Generated by Django 5.1.5 on 2025-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        (
            "core",
            "0023_alter_historicallistfighterequipmentassignment_content_equipment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listfighter",
            name="disabled_default_assignments",
            field=models.ManyToManyField(
                blank=True, to="content.contentfighterdefaultassignment"
            ),
        ),
    ]
