# Generated by Django 5.1.5 on 2025-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_listfighter_disabled_default_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="cost_override",
            field=models.IntegerField(
                blank=True,
                help_text="If set, this will be the cost of this assignment, ignoring equipment list and trading post costs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="cost_override",
            field=models.IntegerField(
                blank=True,
                help_text="If set, this will be the cost of this assignment, ignoring equipment list and trading post costs",
                null=True,
            ),
        ),
    ]
