# Generated by Django 5.1.5 on 2025-02-08 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0025_historicallistfighterequipmentassignment_cost_override_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={
                "ordering": ["name"],
                "verbose_name": "List",
                "verbose_name_plural": "Lists",
            },
        ),
    ]
