# Generated by Django 5.1.5 on 2025-02-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        ("core", "0026_alter_list_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="from_default_assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The default assignment that this equipment assignment was created from",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentfighterdefaultassignment",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="from_default_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="The default assignment that this equipment assignment was created from",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="content.contentfighterdefaultassignment",
            ),
        ),
    ]
