# Generated by Django 5.1.5 on 2025-02-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        (
            "core",
            "0027_historicallistfighterequipmentassignment_from_default_assignment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="upgrade",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The upgrade that this equipment assignment is set to.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentequipmentupgrade",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="upgrade",
            field=models.ForeignKey(
                blank=True,
                help_text="The upgrade that this equipment assignment is set to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.contentequipmentupgrade",
            ),
        ),
    ]
