# Generated by Django 5.1.5 on 2025-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0073_alter_contentequipmentupgrade_name_and_more"),
        ("core", "0029_listfighter_additional_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listfighter",
            name="additional_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional rules for this fighter. Must be from the same house as the fighter.",
                to="content.contenthouseadditionalrule",
            ),
        ),
    ]
