# Generated by Django 5.1.5 on 2025-02-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_alter_listfighter_additional_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighter",
            name="cost_override",
            field=models.IntegerField(
                blank=True,
                help_text="If set, this will be base cost of this fighter.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="cost_override",
            field=models.IntegerField(
                blank=True,
                help_text="If set, this will be base cost of this fighter.",
                null=True,
            ),
        ),
    ]
