# Generated by Django 5.1.5 on 2025-02-15 21:57

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0075_contentpsykerdiscipline_and_more"),
        ("core", "0031_historicallistfighter_cost_override_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalListFighterPsykerPowerAssignment",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list_fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The ListFighter that this psyker power assignment is linked to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighter",
                        verbose_name="Fighter",
                    ),
                ),
                (
                    "psyker_power",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The ContentSkill that this assignment is linked to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentpsykerpower",
                        verbose_name="Psyker Power",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fighter Psyker Power Assignment",
                "verbose_name_plural": "historical Fighter Psyker Power Assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ListFighterPsykerPowerAssignment",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "list_fighter",
                    models.ForeignKey(
                        help_text="The ListFighter that this psyker power assignment is linked to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psyker_powers",
                        to="core.listfighter",
                        verbose_name="Fighter",
                    ),
                ),
                (
                    "psyker_power",
                    models.ForeignKey(
                        help_text="The ContentSkill that this assignment is linked to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_fighters",
                        to="content.contentpsykerpower",
                        verbose_name="Psyker Power",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fighter Psyker Power Assignment",
                "verbose_name_plural": "Fighter Psyker Power Assignments",
            },
        ),
    ]
