# Generated by Django 5.1.5 on 2025-02-16 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0001_squashed_0116_add_visible_only_if_in_equipment_list",
        ),
        ("core", "0032_historicallistfighterpsykerpowerassignment_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="listfighterpsykerpowerassignment",
            unique_together={("list_fighter", "psyker_power")},
        ),
    ]
