# Generated by Django 5.1.6 on 2025-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_listfighterpsykerpowerassignment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistfighterequipmentassignment",
            name="cost_override",
            field=models.IntegerField(
                blank=True,
                help_text="If set, this will be the cost of the base equipment of this assignment, ignoring equipment list and trading post costs",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="cost_override",
            field=models.IntegerField(
                blank=True,
                help_text="If set, this will be the cost of the base equipment of this assignment, ignoring equipment list and trading post costs",
                null=True,
            ),
        ),
    ]
