# Generated by Django 5.1.6 on 2025-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0034_alter_historicallistfighterequipmentassignment_cost_override_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="total_cost_override",
            field=models.IntegerField(
                blank=True,
                help_text="If set, this will be the total cost of this assignment, ignoring profiles, accessories, and upgrades",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="total_cost_override",
            field=models.IntegerField(
                blank=True,
                help_text="If set, this will be the total cost of this assignment, ignoring profiles, accessories, and upgrades",
                null=True,
            ),
        ),
    ]
