# Generated by Django 5.1.7 on 2025-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        (
            "core",
            "0035_historicallistfighterequipmentassignment_total_cost_override_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listfighter",
            name="disabled_pskyer_default_powers",
            field=models.ManyToManyField(
                blank=True, to="content.contentfighterpsykerpowerdefaultassignment"
            ),
        ),
    ]
