# Generated by Django 5.2 on 2025-04-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        ("core", "0036_listfighter_disabled_pskyer_default_powers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listfighter",
            name="equipment",
            field=models.ManyToManyField(
                blank=True,
                through="core.ListFighterEquipmentAssignment",
                through_fields=("list_fighter", "content_equipment"),
                to="content.contentequipment",
            ),
        ),
    ]
