# Generated by Django 5.1.7 on 2025-04-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        ("core", "0037_alter_listfighter_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="upgrades_field",
            field=models.ManyToManyField(
                blank=True,
                help_text="The upgrades that this equipment assignment has.",
                related_name="fighter_equipment_assignments",
                to="content.contentequipmentupgrade",
            ),
        ),
    ]
