# Generated by Django 5.2 on 2025-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_auto_20250418_1607"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighter",
            name="attacks_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="A"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="ballistic_skill_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="BS"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="cool_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Cl"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="initiative_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="I"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="intelligence_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Int"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="leadership_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Ld"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="movement_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="M"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="strength_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="S"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="toughness_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="T"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="weapon_skill_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="WS"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="willpower_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Wil"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="wounds_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="W"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="attacks_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="A"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="ballistic_skill_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="BS"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="cool_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Cl"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="initiative_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="I"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="intelligence_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Int"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="leadership_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Ld"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="movement_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="M"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="strength_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="S"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="toughness_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="T"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="weapon_skill_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="WS"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="willpower_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Wil"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="wounds_override",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="W"
            ),
        ),
    ]
