# Generated by Django 5.2 on 2025-04-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_historicallistfighter_attacks_override_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListFighterEquipmentEquipmentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_parent_links",
                        to="core.listfighterequipmentassignment",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_children_links",
                        to="core.listfighterequipmentassignment",
                    ),
                ),
            ],
        ),
    ]
