# Generated by Django 5.2 on 2025-04-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_listfighterequipmentequipmentlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="linked_equipment_parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The parent equipment assignment that this assignment is linked to.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.listfighterequipmentassignment",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="linked_equipment_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent equipment assignment that this assignment is linked to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_equipment_children",
                to="core.listfighterequipmentassignment",
            ),
        ),
    ]
