# Generated by Django 5.2 on 2025-04-21 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0042_historicallistfighterequipmentassignment_linked_equipment_parent_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="ListFighterEquipmentEquipmentLink",
        ),
    ]
