# Generated by Django 5.1.7 on 2025-05-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0100_historicalcontentequipmentequipmentprofile_and_more"),
        ("core", "0043_delete_listfighterequipmentequipmentlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighter",
            name="legacy_content_fighter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="This supports a ListFighter having a Content Fighter legacy which provides access to (and costs from) the legacy fighter's equipment list.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentfighter",
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="legacy_content_fighter",
            field=models.ForeignKey(
                blank=True,
                help_text="This supports a ListFighter having a Content Fighter legacy which provides access to (and costs from) the legacy fighter's equipment list.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list_fighter_legacy",
                to="content.contentfighter",
            ),
        ),
    ]
