# Generated by Django 5.2.1 on 2025-05-18 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_campaign_historicalcampaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="narrative",
            field=models.TextField(
                blank=True,
                help_text="A longer narrative of the campaign. This will be displayed on the campaign detail page.",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="A short summary of the campaign. This will be displayed on the campaign list page.",
                validators=[django.core.validators.MaxLengthValidator(300)],
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="narrative",
            field=models.TextField(
                blank=True,
                help_text="A longer narrative of the campaign. This will be displayed on the campaign detail page.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="A short summary of the campaign. This will be displayed on the campaign list page.",
                validators=[django.core.validators.MaxLengthValidator(300)],
            ),
        ),
    ]
