# Generated by Django 5.2.1 on 2025-05-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_campaign_narrative_campaign_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="lists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Lists that are part of this campaign.",
                related_name="campaigns",
                to="core.list",
            ),
        ),
    ]
