# Generated by Django 5.2.1 on 2025-05-30 21:41

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_add_lists_to_campaigns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignAction",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the action taken",
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True, help_text="Optional outcome or result of the action"
                    ),
                ),
                (
                    "dice_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of D6 dice rolled (0 if no roll)"
                    ),
                ),
                (
                    "dice_results",
                    models.JSONField(
                        blank=True, default=list, help_text="Results of each die rolled"
                    ),
                ),
                (
                    "dice_total",
                    models.PositiveIntegerField(
                        default=0, help_text="Total sum of all dice rolled"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="The campaign this action belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="core.campaign",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who performed this action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Action",
                "verbose_name_plural": "Campaign Actions",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCampaignAction",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the action taken",
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True, help_text="Optional outcome or result of the action"
                    ),
                ),
                (
                    "dice_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of D6 dice rolled (0 if no roll)"
                    ),
                ),
                (
                    "dice_results",
                    models.JSONField(
                        blank=True, default=list, help_text="Results of each die rolled"
                    ),
                ),
                (
                    "dice_total",
                    models.PositiveIntegerField(
                        default=0, help_text="Total sum of all dice rolled"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The campaign this action belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.campaign",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The user who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Campaign Action",
                "verbose_name_plural": "historical Campaign Actions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
