# Generated by Django 5.2.1 on 2025-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_add_campaign_action_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_campaign", "Pre-Campaign"),
                    ("in_progress", "In Progress"),
                    ("post_campaign", "Post-Campaign"),
                ],
                default="pre_campaign",
                help_text="Current status of the campaign.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_campaign", "Pre-Campaign"),
                    ("in_progress", "In Progress"),
                    ("post_campaign", "Post-Campaign"),
                ],
                default="pre_campaign",
                help_text="Current status of the campaign.",
                max_length=20,
            ),
        ),
    ]
