# Generated by Django 5.2.1 on 2025-06-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_add_campaign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="status",
            field=models.CharField(
                choices=[
                    ("list_building", "List Building"),
                    ("campaign_mode", "Campaign Mode"),
                ],
                default="list_building",
                help_text="Current status of the list.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="original_list",
            field=models.ForeignKey(
                blank=True,
                help_text="The original list this was cloned from for a campaign.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_clones",
                to="core.list",
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="The campaign this list is participating in (if in campaign mode).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_lists",
                to="core.campaign",
            ),
        ),
        migrations.AddField(
            model_name="historicallist",
            name="status",
            field=models.CharField(
                choices=[
                    ("list_building", "List Building"),
                    ("campaign_mode", "Campaign Mode"),
                ],
                default="list_building",
                help_text="Current status of the list.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicallist",
            name="original_list",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The original list this was cloned from for a campaign.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.list",
            ),
        ),
        migrations.AddField(
            model_name="historicallist",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The campaign this list is participating in (if in campaign mode).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.campaign",
            ),
        ),
    ]
