# Generated by Django 5.2.2 on 2025-06-07 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_add_uploadedfile_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallist",
            name="theme_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Theme color for this gang in hex format (e.g., #FF0000).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^#(?:[0-9a-fA-F]{3}){1,2}$|^$",
                        "Enter a valid hex color code (e.g., #FF0000) or leave empty.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="theme_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Theme color for this gang in hex format (e.g., #FF0000).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^#(?:[0-9a-fA-F]{3}){1,2}$|^$",
                        "Enter a valid hex color code (e.g., #FF0000) or leave empty.",
                    )
                ],
            ),
        ),
    ]
