# Generated by Django 5.1.4 on 2025-06-07 19:20

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        ("core", "0054_add_theme_color_to_list"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListFighterInjury",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "date_received",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this injury was sustained."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about how this injury was received.",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        help_text="The fighter who has sustained this injury.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injuries",
                        to="core.listfighter",
                    ),
                ),
                (
                    "injury",
                    models.ForeignKey(
                        help_text="The specific injury sustained.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentinjury",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_listfighterinjury",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fighter Injury",
                "verbose_name_plural": "Fighter Injuries",
                "ordering": ["-date_received"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalListFighterInjury",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "date_received",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When this injury was sustained.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about how this injury was received.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The fighter who has sustained this injury.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "injury",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The specific injury sustained.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentinjury",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fighter Injury",
                "verbose_name_plural": "historical Fighter Injuries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
