# Generated by Django 5.2.2 on 2025-06-07 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        ("core", "0056_historicallistfighterinjury_archived_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="listfighterinjury",
            constraint=models.UniqueConstraint(
                fields=("fighter", "injury"), name="unique_fighter_injury"
            ),
        ),
    ]
