# Generated by Django 5.2.2 on 2025-06-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_add_fighter_injury_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignaction",
            name="list",
            field=models.ForeignKey(
                blank=True,
                help_text="The list this action is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_actions",
                to="core.list",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaignaction",
            name="list",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The list this action is related to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.list",
            ),
        ),
    ]