# Generated by Django 5.2.2 on 2025-06-08 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_add_list_to_campaign_action"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="listfighterinjury",
            name="unique_fighter_injury",
        ),
    ]
