# Generated by Django 5.1.4 on 2025-06-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_remove_listfighterinjury_unique_fighter_injury"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighter",
            name="xp_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Current XP available to spend"
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="xp_total",
            field=models.PositiveIntegerField(
                default=0, help_text="Total XP ever earned"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="xp_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Current XP available to spend"
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="xp_total",
            field=models.PositiveIntegerField(
                default=0, help_text="Total XP ever earned"
            ),
        ),
    ]
