# Generated by Django 5.2.2 on 2025-06-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_add_credit_tracking_to_listfighter"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallist",
            name="credits_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Current credits available"
            ),
        ),
        migrations.AddField(
            model_name="historicallist",
            name="credits_earned",
            field=models.PositiveIntegerField(
                default=0, help_text="Total credits ever earned"
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="credits_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Current credits available"
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="credits_earned",
            field=models.PositiveIntegerField(
                default=0, help_text="Total credits ever earned"
            ),
        ),
    ]
