# Generated by Django 5.2.2 on 2025-06-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_add_campaign_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="budget",
            field=models.PositiveIntegerField(
                default=1500,
                help_text="Starting budget for each gang in credits. When the campaign starts, gangs receive max(0, budget - list cost) credits.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcampaign",
            name="budget",
            field=models.PositiveIntegerField(
                default=1500,
                help_text="Starting budget for each gang in credits. When the campaign starts, gangs receive max(0, budget - list cost) credits.",
            ),
        ),
    ]
