# Generated by Django 5.2.2 on 2025-06-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_update_campaign_budget_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="budget",
            field=models.PositiveIntegerField(
                default=1500, help_text="Starting budget for each gang in credits."
            ),
        ),
        migrations.AlterField(
            model_name="historicalcampaign",
            name="budget",
            field=models.PositiveIntegerField(
                default=1500, help_text="Starting budget for each gang in credits."
            ),
        ),
    ]
