# Generated by Django 5.2.3 on 2025-06-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_alter_campaign_budget_and_more"),
    ]

    operations = [
        # Add single field indexes for ListFighter
        migrations.AddIndex(
            model_name="listfighter",
            index=models.Index(
                fields=["injury_state"], name="core_listfi_injury__2adf42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listfighter",
            index=models.Index(
                fields=["xp_current"], name="core_listfi_xp_curr_9b3e1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listfighter",
            index=models.Index(
                fields=["xp_total"], name="core_listfi_xp_tota_c4f892_idx"
            ),
        ),
        # Add composite indexes for common query patterns on ListFighter
        migrations.AddIndex(
            model_name="listfighter",
            index=models.Index(
                fields=["list", "archived"], name="core_listfi_list_ar_8e7f3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listfighter",
            index=models.Index(
                fields=["list", "injury_state", "archived"],
                name="core_listfi_list_in_4a9c2e_idx",
            ),
        ),
        # Add single field indexes for List
        migrations.AddIndex(
            model_name="list",
            index=models.Index(fields=["status"], name="core_list_status_3f8a91_idx"),
        ),
        # Add single field indexes for Campaign
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["status"], name="core_campai_status_7e2b43_idx"),
        ),
    ]
