# Generated by Django 5.2.3 on 2025-06-29 11:05

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_add_missing_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="The date the battle took place")),
                (
                    "mission",
                    models.CharField(
                        help_text="The mission name or type", max_length=200
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created"],
            },
        ),
        migrations.CreateModel(
            name="BattleNote",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Note content (supports rich text formatting)"
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBattle",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("date", models.DateField(help_text="The date the battle took place")),
                (
                    "mission",
                    models.CharField(
                        help_text="The mission name or type", max_length=200
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical battle",
                "verbose_name_plural": "historical battles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBattleNote",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "content",
                    models.TextField(
                        help_text="Note content (supports rich text formatting)"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical battle note",
                "verbose_name_plural": "historical battle notes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="battle",
            name="campaign",
            field=models.ForeignKey(
                help_text="The campaign this battle belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battles",
                to="core.campaign",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="participants",
            field=models.ManyToManyField(
                help_text="Lists/gangs that participated in the battle",
                related_name="battles_participated",
                to="core.list",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="winners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Lists/gangs that won the battle (leave empty for draws)",
                related_name="battles_won",
                to="core.list",
            ),
        ),
        migrations.AddField(
            model_name="campaignaction",
            name="battle",
            field=models.ForeignKey(
                blank=True,
                help_text="The battle this action is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="core.battle",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaignaction",
            name="battle",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The battle this action is related to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.battle",
            ),
        ),
        migrations.AddField(
            model_name="battlenote",
            name="battle",
            field=models.ForeignKey(
                help_text="The battle this note belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="core.battle",
            ),
        ),
        migrations.AddField(
            model_name="battlenote",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbattle",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The campaign this battle belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.campaign",
            ),
        ),
        migrations.AddField(
            model_name="historicalbattle",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbattle",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbattlenote",
            name="battle",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The battle this note belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.battle",
            ),
        ),
        migrations.AddField(
            model_name="historicalbattlenote",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbattlenote",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="battle",
            index=models.Index(
                fields=["campaign", "date"], name="core_battle_campaig_872846_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="battle",
            index=models.Index(fields=["date"], name="core_battle_date_e8424d_idx"),
        ),
        migrations.AddIndex(
            model_name="battlenote",
            index=models.Index(
                fields=["battle", "created"], name="core_battle_battle__9274ee_idx"
            ),
        ),
    ]
