# Generated by Django 5.2.3 on 2025-06-29 11:44

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_add_missing_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapturedFighter",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "captured_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the fighter was captured"
                    ),
                ),
                (
                    "sold_to_guilders",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the fighter has been sold to guilders",
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the fighter was sold to guilders",
                        null=True,
                    ),
                ),
                (
                    "ransom_amount",
                    models.IntegerField(
                        blank=True,
                        help_text="Credits paid as ransom or received for selling",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Captured Fighter",
                "verbose_name_plural": "Captured Fighters",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCapturedFighter",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "captured_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the fighter was captured",
                    ),
                ),
                (
                    "sold_to_guilders",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the fighter has been sold to guilders",
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the fighter was sold to guilders",
                        null=True,
                    ),
                ),
                (
                    "ransom_amount",
                    models.IntegerField(
                        blank=True,
                        help_text="Credits paid as ransom or received for selling",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Captured Fighter",
                "verbose_name_plural": "historical Captured Fighters",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveIndex(
            model_name="campaign",
            name="core_campai_status_7e2b43_idx",
        ),
        migrations.RemoveIndex(
            model_name="list",
            name="core_list_status_3f8a91_idx",
        ),
        migrations.RemoveIndex(
            model_name="listfighter",
            name="core_listfi_injury__2adf42_idx",
        ),
        migrations.RemoveIndex(
            model_name="listfighter",
            name="core_listfi_xp_curr_9b3e1a_idx",
        ),
        migrations.RemoveIndex(
            model_name="listfighter",
            name="core_listfi_xp_tota_c4f892_idx",
        ),
        migrations.RemoveIndex(
            model_name="listfighter",
            name="core_listfi_list_ar_8e7f3b_idx",
        ),
        migrations.RemoveIndex(
            model_name="listfighter",
            name="core_listfi_list_in_4a9c2e_idx",
        ),
        migrations.AddField(
            model_name="capturedfighter",
            name="capturing_list",
            field=models.ForeignKey(
                help_text="The gang currently holding this fighter captive",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="captured_fighters",
                to="core.list",
            ),
        ),
        migrations.AddField(
            model_name="capturedfighter",
            name="fighter",
            field=models.OneToOneField(
                help_text="The fighter who has been captured",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capture_info",
                to="core.listfighter",
            ),
        ),
        migrations.AddField(
            model_name="capturedfighter",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcapturedfighter",
            name="capturing_list",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The gang currently holding this fighter captive",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.list",
            ),
        ),
        migrations.AddField(
            model_name="historicalcapturedfighter",
            name="fighter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The fighter who has been captured",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.listfighter",
            ),
        ),
        migrations.AddField(
            model_name="historicalcapturedfighter",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcapturedfighter",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
