# Generated by Django 5.2.2 on 2025-06-29 21:37

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
        ("core", "0070_add_battle_model_and_link_to_campaign_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalListAttributeAssignment",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "attribute_value",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The attribute value assigned to the list.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentattributevalue",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The list this attribute is assigned to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.list",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical List Attribute Assignment",
                "verbose_name_plural": "historical List Attribute Assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ListAttributeAssignment",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "attribute_value",
                    models.ForeignKey(
                        help_text="The attribute value assigned to the list.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentattributevalue",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        help_text="The list this attribute is assigned to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.list",
                    ),
                ),
            ],
            options={
                "verbose_name": "List Attribute Assignment",
                "verbose_name_plural": "List Attribute Assignments",
                "unique_together": {("list", "attribute_value")},
            },
        ),
        migrations.AddField(
            model_name="list",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gang attributes like Alignment, Alliance, Affiliation",
                through="core.ListAttributeAssignment",
                through_fields=("list", "attribute_value"),
                to="content.contentattributevalue",
            ),
        ),
    ]
