# Generated by Django 5.2.2 on 2025-06-30 09:52

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_add_missing_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapturedFighter",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "captured_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the fighter was captured"
                    ),
                ),
                (
                    "sold_to_guilders",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the fighter has been sold to guilders",
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the fighter was sold to guilders",
                        null=True,
                    ),
                ),
                (
                    "ransom_amount",
                    models.IntegerField(
                        blank=True,
                        help_text="Credits paid as ransom or received for selling",
                        null=True,
                    ),
                ),
                (
                    "capturing_list",
                    models.ForeignKey(
                        help_text="The gang currently holding this fighter captive",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captured_fighters",
                        to="core.list",
                    ),
                ),
                (
                    "fighter",
                    models.OneToOneField(
                        help_text="The fighter who has been captured",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_info",
                        to="core.listfighter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Captured Fighter",
                "verbose_name_plural": "Captured Fighters",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCapturedFighter",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "captured_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the fighter was captured",
                    ),
                ),
                (
                    "sold_to_guilders",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the fighter has been sold to guilders",
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the fighter was sold to guilders",
                        null=True,
                    ),
                ),
                (
                    "ransom_amount",
                    models.IntegerField(
                        blank=True,
                        help_text="Credits paid as ransom or received for selling",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "capturing_list",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The gang currently holding this fighter captive",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.list",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The fighter who has been captured",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Captured Fighter",
                "verbose_name_plural": "historical Captured Fighters",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
