# Generated by Django 5.2.3 on 2025-07-02 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0073_capturedfighter_historicalcapturedfighter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "noun",
                    models.CharField(
                        choices=[
                            ("list", "List"),
                            ("list_fighter", "List Fighter"),
                            ("campaign", "Campaign"),
                            ("battle", "Battle"),
                            ("equipment_assignment", "Equipment Assignment"),
                            ("skill_assignment", "Skill Assignment"),
                            ("user", "User"),
                            ("upload", "Upload"),
                            ("fighter_advancement", "Fighter Advancement"),
                            ("campaign_action", "Campaign Action"),
                            ("campaign_resource", "Campaign Resource"),
                            ("campaign_asset", "Campaign Asset"),
                        ],
                        help_text="The type of object being acted upon",
                        max_length=50,
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("archive", "Archive"),
                            ("restore", "Restore"),
                            ("view", "View"),
                            ("clone", "Clone"),
                            ("join", "Join"),
                            ("leave", "Leave"),
                            ("assign", "Assign"),
                            ("unassign", "Unassign"),
                            ("activate", "Activate"),
                            ("deactivate", "Deactivate"),
                            ("submit", "Submit"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("import", "Import"),
                            ("export", "Export"),
                        ],
                        help_text="The action being performed",
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the object being acted upon",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the user when the action was taken",
                        null=True,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data in JSON format",
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of the object for generic relations",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="core_event_created_409a4e_idx"
                    ),
                    models.Index(
                        fields=["noun", "verb"], name="core_event_noun_20866e_idx"
                    ),
                    models.Index(
                        fields=["owner"], name="core_event_owner_i_e0a4d8_idx"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="core_event_object__934a15_idx",
                    ),
                ],
            },
        ),
    ]
