# Generated by Django 5.2.3 on 2025-07-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_add_event_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Session ID of the user when the action was taken",
                max_length=40,
                null=True,
            ),
        ),
    ]
