# Generated by Django 5.2.3 on 2025-07-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_add_session_id_to_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="verb",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("view", "View"),
                    ("archive", "Archive"),
                    ("restore", "Restore"),
                    ("submit", "Submit"),
                    ("confirm", "Confirm"),
                    ("join", "Join"),
                    ("leave", "Leave"),
                    ("assign", "Assign"),
                    ("unassign", "Unassign"),
                    ("activate", "Activate"),
                    ("deactivate", "Deactivate"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("import", "Import"),
                    ("export", "Export"),
                    ("add", "Add"),
                    ("remove", "Remove"),
                    ("clone", "Clone"),
                    ("reset", "Reset"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("signup", "Signup"),
                ],
                help_text="The action being performed",
                max_length=50,
            ),
        ),
    ]
