# Generated by Django 5.2.3 on 2025-07-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_alter_event_verb"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("password", "Password"),
                    ("email", "Email"),
                    ("mfa", "Multi-Factor Authentication"),
                    ("session", "Session"),
                ],
                help_text="The field being modified for UPDATE events",
                max_length=50,
                null=True,
            ),
        ),
    ]
