# Generated by Django 5.2.4 on 2025-07-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_add_field_column_to_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighter",
            name="image",
            field=models.TextField(
                blank=True,
                help_text="Fighter portrait or image (appears in Info section)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="private_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes about the fighter (only visible to you)",
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="save",
            field=models.CharField(
                blank=True,
                help_text="Fighter's typical save roll (e.g. '5+' or '4+ inv')",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Fighter portrait or image (appears in Info section)",
                null=True,
                upload_to="fighter-images/",
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="private_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes about the fighter (only visible to you)",
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="save",
            field=models.CharField(
                blank=True,
                help_text="Fighter's typical save roll (e.g. '5+' or '4+ inv')",
                max_length=10,
            ),
        ),
    ]
