# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_add_field_column_to_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listfighter",
            name="additional_rules",
        ),
    ]
