# Generated by Django 5.2.4 on 2025-07-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_add_fighter_image_save_private_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("password", "Password"),
                    ("email", "Email"),
                    ("mfa", "Multi-Factor Authentication"),
                    ("session", "Session"),
                    ("info", "Info"),
                ],
                help_text="The field being modified for UPDATE events",
                max_length=50,
                null=True,
            ),
        ),
    ]
