# Generated by Django 5.2.4 on 2025-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_alter_event_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistfighter",
            name="private_notes",
            field=models.TextField(
                blank=True, help_text="Notes about the fighter (only visible to you)"
            ),
        ),
        migrations.AlterField(
            model_name="listfighter",
            name="private_notes",
            field=models.TextField(
                blank=True, help_text="Notes about the fighter (only visible to you)"
            ),
        ),
    ]
