# Generated by Django 5.2.4 on 2025-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_add_banner_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ["-modified"],
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
            },
        ),
        migrations.AlterField(
            model_name="historicalbanner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbanner",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name="banner",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="historicalbanner",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="historicalbanner",
            name="updated_at",
        ),
    ]
