# Generated by Django 5.2.4 on 2025-07-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0127_alter_contentequipmentcategoryfighterrestriction_equipment_category",
        ),
        ("core", "0087_alter_historicallist_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listfighter",
            name="custom_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Custom rules added to this fighter beyond their default rules.",
                related_name="custom_for_fighters",
                to="content.contentrule",
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="disabled_rules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Default rules from the ContentFighter that have been disabled for this fighter.",
                related_name="disabled_by_fighters",
                to="content.contentrule",
            ),
        ),
    ]
