# Generated by Django 5.2.4 on 2025-07-31 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_add_rule_overrides_to_listfighter"),
        ("core", "0088_auto_20250731_1146"),
    ]

    operations = []
