# Generated by Django 5.2.4 on 2025-07-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_merge_20250731_1611"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="noun",
            field=models.CharField(
                choices=[
                    ("list", "List"),
                    ("list_fighter", "List Fighter"),
                    ("campaign", "Campaign"),
                    ("battle", "Battle"),
                    ("equipment_assignment", "Equipment Assignment"),
                    ("skill_assignment", "Skill Assignment"),
                    ("user", "User"),
                    ("upload", "Upload"),
                    ("fighter_advancement", "Fighter Advancement"),
                    ("campaign_action", "Campaign Action"),
                    ("campaign_resource", "Campaign Resource"),
                    ("campaign_asset", "Campaign Asset"),
                    ("banner", "Banner"),
                ],
                help_text="The type of object being acted upon",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="verb",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("view", "View"),
                    ("archive", "Archive"),
                    ("restore", "Restore"),
                    ("submit", "Submit"),
                    ("confirm", "Confirm"),
                    ("join", "Join"),
                    ("leave", "Leave"),
                    ("assign", "Assign"),
                    ("unassign", "Unassign"),
                    ("activate", "Activate"),
                    ("deactivate", "Deactivate"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("import", "Import"),
                    ("export", "Export"),
                    ("add", "Add"),
                    ("remove", "Remove"),
                    ("clone", "Clone"),
                    ("reset", "Reset"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("signup", "Signup"),
                    ("click", "Click"),
                ],
                help_text="The action being performed",
                max_length=50,
            ),
        ),
    ]
