# Generated by Django 5.2.4 on 2025-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_alter_printconfig_help_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="noun",
            field=models.CharField(
                choices=[
                    ("list", "List"),
                    ("list_fighter", "List Fighter"),
                    ("campaign", "Campaign"),
                    ("battle", "Battle"),
                    ("equipment_assignment", "Equipment Assignment"),
                    ("skill_assignment", "Skill Assignment"),
                    ("user", "User"),
                    ("upload", "Upload"),
                    ("fighter_advancement", "Fighter Advancement"),
                    ("campaign_action", "Campaign Action"),
                    ("campaign_resource", "Campaign Resource"),
                    ("campaign_asset", "Campaign Asset"),
                    ("banner", "Banner"),
                    ("print_config", "Print Config"),
                ],
                help_text="The type of object being acted upon",
                max_length=50,
            ),
        ),
    ]
