# Generated by Django 5.2.4 on 2025-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_add_in_repair_state_to_listfighter"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighter",
            name="category_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                    ("STASH", "Stash"),
                    ("VEHICLE", "Vehicle"),
                    ("GANG_TERRAIN", "Gang Terrain"),
                ],
                help_text="Override the fighter's category without changing their type. Used for situations like elevating a hired gun to leader.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="category_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                    ("STASH", "Stash"),
                    ("VEHICLE", "Vehicle"),
                    ("GANG_TERRAIN", "Gang Terrain"),
                ],
                help_text="Override the fighter's category without changing their type. Used for situations like elevating a hired gun to leader.",
                max_length=255,
                null=True,
            ),
        ),
    ]
