# Generated by Django 5.2.4 on 2025-08-06 07:50

import gyrinx.core.models.list
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0095_add_category_override_to_listfighter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistfighter",
            name="category_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                ],
                help_text="Override the fighter's category without changing their type. Limited to Leader, Champion, Ganger, Juve, Prospect, and Specialist.",
                max_length=255,
                null=True,
                validators=[gyrinx.core.models.list.validate_category_override],
            ),
        ),
        migrations.AlterField(
            model_name="listfighter",
            name="category_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                ],
                help_text="Override the fighter's category without changing their type. Limited to Leader, Champion, Ganger, Juve, Prospect, and Specialist.",
                max_length=255,
                null=True,
                validators=[gyrinx.core.models.list.validate_category_override],
            ),
        ),
    ]
