# Generated by Django 5.2.4 on 2025-08-06 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0096_restrict_category_override_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listfighter",
            name="additional_rules",
        ),
    ]
