# Generated by Django 5.2.4 on 2025-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0139_alter_contentequipmentcategoryfighterrestriction_fighter_category_and_more",
        ),
        ("core", "0099_add_campaign_invitation_event_noun"),
    ]

    operations = [
        migrations.AddField(
            model_name="listfighter",
            name="disabled_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Default skills from the ContentFighter that have been disabled for this fighter.",
                related_name="disabled_for_fighters",
                to="content.contentskill",
            ),
        ),
    ]
