# Generated by Django 5.2.4 on 2025-08-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0100_add_disabled_skills_to_listfighter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="banner",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="battle",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="battle",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="battle",
            name="date",
            field=models.DateField(
                db_index=True, help_text="The date the battle took place"
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="battlenote",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="battlenote",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="battlenote",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Public Campaigns are visible to all users.",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_campaign", "Pre-Campaign"),
                    ("in_progress", "In Progress"),
                    ("post_campaign", "Post-Campaign"),
                ],
                db_index=True,
                default="pre_campaign",
                help_text="Current status of the campaign.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaignaction",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaignaction",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaignaction",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaignasset",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaignasset",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaignasset",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaignassettype",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaignassettype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaignassettype",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaigninvitation",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaigninvitation",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaigninvitation",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaigninvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                db_index=True,
                default="pending",
                help_text="Current status of the invitation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaignlistresource",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaignlistresource",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaignlistresource",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaignresourcetype",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="campaignresourcetype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="campaignresourcetype",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="capturedfighter",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="capturedfighter",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="capturedfighter",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalbanner",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalbanner",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalbanner",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalbattle",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalbattle",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalbattle",
            name="date",
            field=models.DateField(
                db_index=True, help_text="The date the battle took place"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbattle",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalbattlenote",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalbattlenote",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalbattlenote",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaign",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaign",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaign",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaign",
            name="public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Public Campaigns are visible to all users.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_campaign", "Pre-Campaign"),
                    ("in_progress", "In Progress"),
                    ("post_campaign", "Post-Campaign"),
                ],
                db_index=True,
                default="pre_campaign",
                help_text="Current status of the campaign.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcampaignaction",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignaction",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignaction",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignasset",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignasset",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignasset",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignassettype",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignassettype",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignassettype",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaigninvitation",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaigninvitation",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaigninvitation",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaigninvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                db_index=True,
                default="pending",
                help_text="Current status of the invitation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcampaignlistresource",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignlistresource",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignlistresource",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignresourcetype",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignresourcetype",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcampaignresourcetype",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcapturedfighter",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalcapturedfighter",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalcapturedfighter",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallist",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicallist",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallist",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallist",
            name="public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Public lists are visible to all users.",
            ),
        ),
        migrations.AlterField(
            model_name="historicallist",
            name="status",
            field=models.CharField(
                choices=[
                    ("list_building", "List Building"),
                    ("campaign_mode", "Campaign Mode"),
                ],
                db_index=True,
                default="list_building",
                help_text="Current status of the list.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicallistattributeassignment",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicallistattributeassignment",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistattributeassignment",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighter",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighter",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighter",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighteradvancement",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighteradvancement",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighteradvancement",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterequipmentassignment",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterequipmentassignment",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterequipmentassignment",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterinjury",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterinjury",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterinjury",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterpsykerpowerassignment",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterpsykerpowerassignment",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterpsykerpowerassignment",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterstatoverride",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterstatoverride",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicallistfighterstatoverride",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalprintconfig",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalprintconfig",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalprintconfig",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicaluploadedfile",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicaluploadedfile",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicaluploadedfile",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="list",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="list",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="list",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="list",
            name="public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Public lists are visible to all users.",
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="status",
            field=models.CharField(
                choices=[
                    ("list_building", "List Building"),
                    ("campaign_mode", "Campaign Mode"),
                ],
                db_index=True,
                default="list_building",
                help_text="Current status of the list.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listattributeassignment",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="listattributeassignment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listattributeassignment",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighter",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="listfighter",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighter",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighteradvancement",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="listfighteradvancement",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighteradvancement",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighterinjury",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="listfighterinjury",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighterinjury",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighterpsykerpowerassignment",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="listfighterpsykerpowerassignment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighterpsykerpowerassignment",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighterstatoverride",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="listfighterstatoverride",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listfighterstatoverride",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="printconfig",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="printconfig",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="printconfig",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
