# Generated by Django 5.2.4 on 2025-08-20 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0142_alter_contentweaponprofile_traits"),
        ("core", "0101_add_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listfighter",
            index=models.Index(
                condition=models.Q(("archived", False)),
                fields=["list_id", "id"],
                name="idx_listfighter_list_active",
            ),
        ),
    ]
