# Generated by Django 5.2.6 on 2025-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_listfighter_idx_listfighter_list_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistfighteradvancement",
            name="stat_increased",
            field=models.CharField(
                blank=True,
                help_text="For stat increases, which characteristic was improved.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="listfighteradvancement",
            name="stat_increased",
            field=models.CharField(
                blank=True,
                help_text="For stat increases, which characteristic was improved.",
                max_length=20,
                null=True,
            ),
        ),
    ]
