# Generated by Django 5.2.5 on 2025-09-12 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0103_remove_stat_choices_from_advancement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listfighterequipmentassignment",
            old_name="linked_fighter",
            new_name="child_fighter",
        ),
        migrations.RenameField(
            model_name="historicallistfighterequipmentassignment",
            old_name="linked_fighter",
            new_name="child_fighter",
        ),
    ]
