# Generated by Django 5.2.6 on 2025-09-12 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0151_add_advancement_assignment_model"),
        ("core", "0104_add_equipment_advancement_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighteradvancement",
            name="equipment_assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="For equipment advancements, which assignment configuration was selected.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentadvancementassignment",
            ),
        ),
        migrations.AddField(
            model_name="listfighteradvancement",
            name="equipment_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="For equipment advancements, which assignment configuration was selected.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentadvancementassignment",
            ),
        ),
    ]
