# Generated by Django 5.2.6 on 2025-09-13 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0105_add_equipment_assignment_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallistfighteradvancement",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="listfighteradvancement",
            name="equipment",
        ),
    ]
