# Generated by Django 5.2.7 on 2025-11-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0110_historicallistaction_applied_listaction_applied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistaction",
            name="applied",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this action has been applied to the list.",
            ),
        ),
        migrations.AlterField(
            model_name="listaction",
            name="applied",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this action has been applied to the list.",
            ),
        ),
    ]
