# Generated by Django 5.2.5 on 2025-11-11 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_add_clone_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprintconfig",
            name="blank_fighter_cards",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of blank fighter cards to include (max 20).",
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AddField(
            model_name="historicalprintconfig",
            name="blank_vehicle_cards",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of blank vehicle/crew cards to include (max 20).",
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AddField(
            model_name="printconfig",
            name="blank_fighter_cards",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of blank fighter cards to include (max 20).",
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AddField(
            model_name="printconfig",
            name="blank_vehicle_cards",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of blank vehicle/crew cards to include (max 20).",
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
    ]
