# Generated by Django 5.2.8 on 2025-11-11 00:00

from django.db import migrations


def migrate_upgrade_to_upgrades_field(apps, schema_editor):
    """Migrate data from deprecated upgrade field to upgrades_field."""
    ListFighterEquipmentAssignment = apps.get_model(
        "core", "ListFighterEquipmentAssignment"
    )

    # Find all assignments that have upgrade set
    assignments_with_upgrade = ListFighterEquipmentAssignment.objects.filter(
        upgrade__isnull=False
    )

    migrated_count = 0
    for assignment in assignments_with_upgrade:
        # Add the upgrade to upgrades_field (this is idempotent - won't create duplicates)
        assignment.upgrades_field.add(assignment.upgrade)
        # Clear the deprecated upgrade field
        assignment.upgrade = None
        assignment.save(update_fields=["upgrade"])
        migrated_count += 1

    if migrated_count > 0:
        print(
            f"Migrated {migrated_count} equipment assignment(s) from upgrade to upgrades_field"
        )


def reverse_migrate_upgrade(apps, schema_editor):
    # This is a data migration to fix deprecated data, so we don't need a reverse
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_add_clone_action_type"),
    ]

    operations = [
        migrations.RunPython(
            migrate_upgrade_to_upgrades_field, reverse_migrate_upgrade
        ),
    ]
