# Generated by Django 5.2.8 on 2025-11-12 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0113_migrate_upgrade_to_upgrades_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallistfighterequipmentassignment",
            name="upgrade",
        ),
        migrations.RemoveField(
            model_name="listfighterequipmentassignment",
            name="upgrade",
        ),
    ]
