# Generated by Django 5.2.8 on 2025-11-14 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0114_merge_20251111_2156"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallistfighterequipmentassignment",
            name="upgrade",
        ),
        migrations.RemoveField(
            model_name="listfighterequipmentassignment",
            name="upgrade",
        ),
    ]
