# Generated by Django 5.2.7 on 2025-11-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0115_remove_upgrade_field_from_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("CLONE", "Clone"),
                    ("ADD_FIGHTER", "Add Fighter"),
                    ("REMOVE_FIGHTER", "Remove Fighter"),
                    ("UPDATE_FIGHTER", "Update Fighter"),
                    ("ADD_EQUIPMENT", "Add Equipment"),
                    ("REMOVE_EQUIPMENT", "Remove Equipment"),
                    ("UPDATE_EQUIPMENT", "Update Equipment"),
                    ("CAMPAIGN_START", "Campaign Start"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="listaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("CLONE", "Clone"),
                    ("ADD_FIGHTER", "Add Fighter"),
                    ("REMOVE_FIGHTER", "Remove Fighter"),
                    ("UPDATE_FIGHTER", "Update Fighter"),
                    ("ADD_EQUIPMENT", "Add Equipment"),
                    ("REMOVE_EQUIPMENT", "Remove Equipment"),
                    ("UPDATE_EQUIPMENT", "Update Equipment"),
                    ("CAMPAIGN_START", "Campaign Start"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
