# Generated by Django 5.2.7 on 2025-11-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0116_alter_historicallistaction_action_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("CLONE", "Clone"),
                    ("ADD_FIGHTER", "Add Fighter"),
                    ("REMOVE_FIGHTER", "Remove Fighter"),
                    ("UPDATE_FIGHTER", "Update Fighter"),
                    ("ADD_EQUIPMENT", "Add Equipment"),
                    ("REMOVE_EQUIPMENT", "Remove Equipment"),
                    ("UPDATE_EQUIPMENT", "Update Equipment"),
                    ("CAMPAIGN_START", "Campaign Start"),
                    ("CAPTURE_FIGHTER", "Capture Fighter"),
                    ("SELL_FIGHTER", "Sell Fighter"),
                    ("RETURN_FIGHTER", "Return Fighter"),
                    ("RELEASE_FIGHTER", "Release Fighter"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="listaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("CLONE", "Clone"),
                    ("ADD_FIGHTER", "Add Fighter"),
                    ("REMOVE_FIGHTER", "Remove Fighter"),
                    ("UPDATE_FIGHTER", "Update Fighter"),
                    ("ADD_EQUIPMENT", "Add Equipment"),
                    ("REMOVE_EQUIPMENT", "Remove Equipment"),
                    ("UPDATE_EQUIPMENT", "Update Equipment"),
                    ("CAMPAIGN_START", "Campaign Start"),
                    ("CAPTURE_FIGHTER", "Capture Fighter"),
                    ("SELL_FIGHTER", "Sell Fighter"),
                    ("RETURN_FIGHTER", "Return Fighter"),
                    ("RELEASE_FIGHTER", "Release Fighter"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
