# Generated by Django 5.2.8 on 2025-12-01 22:16

from django.db import migrations, models


def set_existing_advancements_to_legacy(apps, schema_editor):
    """
    Set uses_mod_system=False for all existing stat advancements.

    These advancements have already applied their stat changes via the legacy
    override fields. We don't want them to also apply via the mod system,
    which would double-apply the improvement.
    """
    ListFighterAdvancement = apps.get_model("core", "ListFighterAdvancement")

    # Update all existing stat advancements to use legacy system
    updated = ListFighterAdvancement.objects.filter(
        advancement_type="stat",
    ).update(uses_mod_system=False)

    if updated > 0:
        print(f"\n  Set uses_mod_system=False for {updated} existing stat advancements")


def reverse_migration(apps, schema_editor):
    """Reverse: set all advancements back to using mod system."""
    ListFighterAdvancement = apps.get_model("core", "ListFighterAdvancement")
    ListFighterAdvancement.objects.filter(
        advancement_type="stat",
    ).update(uses_mod_system=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0118_add_update_credits_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighteradvancement",
            name="uses_mod_system",
            field=models.BooleanField(
                default=True,
                help_text="If True, stat advancements use the mod system (computed at display time). If False, uses legacy override fields (mutates fighter state).",
            ),
        ),
        migrations.AddField(
            model_name="listfighteradvancement",
            name="uses_mod_system",
            field=models.BooleanField(
                default=True,
                help_text="If True, stat advancements use the mod system (computed at display time). If False, uses legacy override fields (mutates fighter state).",
            ),
        ),
        migrations.RunPython(
            set_existing_advancements_to_legacy,
            reverse_migration,
        ),
    ]
