# Generated by Django 6.0 on 2025-12-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0119_add_uses_mod_system_to_advancement"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallist",
            name="dirty",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True if cached values may be stale due to content changes",
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="dirty",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True if cached values may be stale",
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="rating_current",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cached total rating of this fighter (base + equipment + advancements)",
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="dirty",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True if cached values may be stale",
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="rating_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Cached total rating of this assignment"
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="dirty",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True if cached values may be stale due to content changes",
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="dirty",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True if cached values may be stale",
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="rating_current",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cached total rating of this fighter (base + equipment + advancements)",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="dirty",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True if cached values may be stale",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="rating_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Cached total rating of this assignment"
            ),
        ),
    ]
