# Generated by Django 6.0 on 2025-12-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0150_update_equipment_advancement_meta_options"),
        ("core", "0120_add_cached_rating_and_dirty_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("CLONE", "Clone"),
                    ("ADD_FIGHTER", "Add Fighter"),
                    ("REMOVE_FIGHTER", "Remove Fighter"),
                    ("UPDATE_FIGHTER", "Update Fighter"),
                    ("ADD_EQUIPMENT", "Add Equipment"),
                    ("REMOVE_EQUIPMENT", "Remove Equipment"),
                    ("UPDATE_EQUIPMENT", "Update Equipment"),
                    ("CAMPAIGN_START", "Campaign Start"),
                    ("CAPTURE_FIGHTER", "Capture Fighter"),
                    ("SELL_FIGHTER", "Sell Fighter"),
                    ("RETURN_FIGHTER", "Return Fighter"),
                    ("RELEASE_FIGHTER", "Release Fighter"),
                    ("UPDATE_CREDITS", "Update Credits"),
                    ("CONTENT_COST_CHANGE", "Content Cost Change"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="listaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("CLONE", "Clone"),
                    ("ADD_FIGHTER", "Add Fighter"),
                    ("REMOVE_FIGHTER", "Remove Fighter"),
                    ("UPDATE_FIGHTER", "Update Fighter"),
                    ("ADD_EQUIPMENT", "Add Equipment"),
                    ("REMOVE_EQUIPMENT", "Remove Equipment"),
                    ("UPDATE_EQUIPMENT", "Update Equipment"),
                    ("CAMPAIGN_START", "Campaign Start"),
                    ("CAPTURE_FIGHTER", "Capture Fighter"),
                    ("SELL_FIGHTER", "Sell Fighter"),
                    ("RETURN_FIGHTER", "Return Fighter"),
                    ("RELEASE_FIGHTER", "Release Fighter"),
                    ("UPDATE_CREDITS", "Update Credits"),
                    ("CONTENT_COST_CHANGE", "Content Cost Change"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="listfighterequipmentassignment",
            index=models.Index(
                fields=["content_equipment"], name="idx_assignment_content_equip"
            ),
        ),
    ]
