# Generated by Django 6.0 on 2025-12-31 17:44

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0122_add_campaign_phase_and_asset_properties"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignassettype",
            name="sub_asset_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Schema defining sub-asset types for this asset type. Format: {'structure': {'label': 'Structure', 'label_plural': 'Structures', 'property_schema': [{'key': 'benefit', 'label': 'Benefit'}, ...]}, ...}",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaignassettype",
            name="sub_asset_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Schema defining sub-asset types for this asset type. Format: {'structure': {'label': 'Structure', 'label_plural': 'Structures', 'property_schema': [{'key': 'benefit', 'label': 'Benefit'}, ...]}, ...}",
            ),
        ),
        migrations.CreateModel(
            name="CampaignSubAsset",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "sub_asset_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of sub-asset (key in parent asset type's sub_asset_schema)",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the sub-asset (e.g., 'Generator Hall')",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom properties for this sub-asset based on schema",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_asset",
                    models.ForeignKey(
                        help_text="The parent asset this sub-asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_assets",
                        to="core.campaignasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Sub-Asset",
                "verbose_name_plural": "Campaign Sub-Assets",
                "ordering": ["sub_asset_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCampaignSubAsset",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "sub_asset_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of sub-asset (key in parent asset type's sub_asset_schema)",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the sub-asset (e.g., 'Generator Hall')",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom properties for this sub-asset based on schema",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The parent asset this sub-asset belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.campaignasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Campaign Sub-Asset",
                "verbose_name_plural": "historical Campaign Sub-Assets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
