# Generated by Django 6.0 on 2026-01-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0123_add_campaign_sub_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Template campaigns appear as pre-configured options when copying assets.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="template",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Template campaigns appear as pre-configured options when copying assets.",
            ),
        ),
    ]
