# Generated by Django 6.0.1 on 2026-01-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0124_add_campaign_template_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistfighter",
            name="rating_current",
            field=models.IntegerField(
                default=0,
                help_text="Cached total rating of this fighter (base + equipment + advancements). Can be negative if equipment has negative cost.",
            ),
        ),
        migrations.AlterField(
            model_name="historicallistfighterequipmentassignment",
            name="rating_current",
            field=models.IntegerField(
                default=0,
                help_text="Cached total rating of this assignment. Can be negative if equipment or upgrades have negative cost.",
            ),
        ),
        migrations.AlterField(
            model_name="listfighter",
            name="rating_current",
            field=models.IntegerField(
                default=0,
                help_text="Cached total rating of this fighter (base + equipment + advancements). Can be negative if equipment has negative cost.",
            ),
        ),
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="rating_current",
            field=models.IntegerField(
                default=0,
                help_text="Cached total rating of this assignment. Can be negative if equipment or upgrades have negative cost.",
            ),
        ),
    ]
