# Generated by Django 6.0 on 2026-01-08 16:27

import gyrinx.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0124_add_campaign_template_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="A short summary of the campaign. This will be displayed on the campaign list page.",
                validators=[gyrinx.core.validators.HTMLTextMaxLengthValidator(300)],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcampaign",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="A short summary of the campaign. This will be displayed on the campaign list page.",
                validators=[gyrinx.core.validators.HTMLTextMaxLengthValidator(300)],
            ),
        ),
    ]
