# Generated by Django 6.0.1 on 2026-01-16 22:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0124_add_campaign_template_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateTransition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("object_id", models.UUIDField(db_index=True)),
                (
                    "from_status",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("to_status", models.CharField(db_index=True, max_length=50)),
                (
                    "transitioned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-transitioned_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_statet_content_a59677_idx",
                    ),
                    models.Index(
                        fields=["content_type", "to_status"],
                        name="core_statet_content_c27871_idx",
                    ),
                ],
            },
        ),
    ]
