# Generated by Django 6.0.1 on 2026-01-24 21:41

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0125_allow_negative_rating_for_equipment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="noun",
            field=models.CharField(
                choices=[
                    ("list", "List"),
                    ("list_fighter", "List Fighter"),
                    ("campaign", "Campaign"),
                    ("campaign_invitation", "Campaign Invitation"),
                    ("battle", "Battle"),
                    ("equipment_assignment", "Equipment Assignment"),
                    ("skill_assignment", "Skill Assignment"),
                    ("user", "User"),
                    ("upload", "Upload"),
                    ("fighter_advancement", "Fighter Advancement"),
                    ("campaign_action", "Campaign Action"),
                    ("campaign_resource", "Campaign Resource"),
                    ("campaign_asset", "Campaign Asset"),
                    ("banner", "Banner"),
                    ("print_config", "Print Config"),
                    ("crew_template", "Crew Template"),
                ],
                help_text="The type of object being acted upon",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CrewTemplate",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this crew template.",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "random_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of additional random fighters to select from remaining active fighters (max 20).",
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                (
                    "chosen_fighters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific fighters to include in the crew.",
                        related_name="crew_templates",
                        to="core.listfighter",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        help_text="The list this crew template belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_templates",
                        to="core.list",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crew Template",
                "verbose_name_plural": "Crew Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCrewTemplate",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this crew template.",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "random_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of additional random fighters to select from remaining active fighters (max 20).",
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The list this crew template belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.list",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Crew Template",
                "verbose_name_plural": "historical Crew Templates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
