# Generated by Django 6.0.1 on 2026-02-05 21:09

from django.db import migrations


def create_custom_content_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Custom Content")


def remove_custom_content_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Custom Content").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0126_add_custom_content_pack_models"),
    ]

    operations = [
        migrations.RunPython(
            create_custom_content_group,
            remove_custom_content_group,
        ),
    ]
