# Generated by Django 6.0.1 on 2026-02-06 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0127_create_custom_content_group"),
        ("core", "0127_update_campaign_summary_validator"),
    ]

    operations = []
