# Generated by Django 6.0.2 on 2026-02-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0156_add_counter_and_roll_table_models"),
        ("core", "0130_add_list_fighter_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listfightercounter",
            name="counter",
            field=models.ForeignKey(
                help_text="The counter definition.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fighter_values",
                to="content.contentcounter",
            ),
        ),
    ]
