# Generated by Django 6.0.2 on 2026-02-10 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0132_add_campaign_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="group_attribute_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The attribute type used to group and visually divide lists in the campaign view. Must be single-select.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.campaignattributetype",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="group_attribute_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The attribute type used to group and visually divide lists in the campaign view. Must be single-select.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.campaignattributetype",
            ),
        ),
    ]
