# Generated by Django 6.0.2 on 2026-02-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0132_add_campaign_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignattributetype",
            name="is_group",
            field=models.BooleanField(
                default=False,
                help_text="If True, this attribute is used to group and visually divide lists in the campaign view. Only one attribute per campaign can be the group attribute, and it must be single-select.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaignattributetype",
            name="is_group",
            field=models.BooleanField(
                default=False,
                help_text="If True, this attribute is used to group and visually divide lists in the campaign view. Only one attribute per campaign can be the group attribute, and it must be single-select.",
            ),
        ),
    ]
