# Generated by Django 6.0.2 on 2026-03-01 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0135_add_pack_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customcontentpackitem",
            name="unique_pack_content_item",
        ),
        migrations.AddConstraint(
            model_name="customcontentpackitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived", False)),
                fields=("pack", "content_type", "object_id"),
                name="unique_pack_content_item",
            ),
        ),
    ]
