# Generated by Django 6.0.3 on 2026-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0136_add_notes_to_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighter",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes about the fighter"),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="notes",
            field=models.TextField(blank=True, help_text="Notes about the fighter"),
        ),
        migrations.AlterField(
            model_name="historicallist",
            name="narrative",
            field=models.TextField(
                blank=True,
                help_text="Lore for the gang in this list: their history and how to play them.",
                verbose_name="lore",
            ),
        ),
        migrations.AlterField(
            model_name="historicallistfighter",
            name="private_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes about the fighter (only visible to you)",
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="narrative",
            field=models.TextField(
                blank=True,
                help_text="Lore for the gang in this list: their history and how to play them.",
                verbose_name="lore",
            ),
        ),
        migrations.AlterField(
            model_name="listfighter",
            name="private_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes about the fighter (only visible to you)",
            ),
        ),
    ]
