# Generated by Django 6.0.2 on 2026-03-14 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0136_partial_unique_constraint_on_pack_item"),
        ("core", "0137_add_notes_to_list_fighter"),
    ]

    operations = []
