# Generated by Django 6.0.2 on 2026-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0138_merge_20260314_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="patreon_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email address from Patreon webhook",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="patreon_member_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Patreon member UUID for deduplication",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="patreon_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("former", "Former"),
                    ("declined", "Declined"),
                ],
                default="",
                help_text="Current Patreon membership status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicaluserprofile",
            name="patreon_tier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Patreon tier title (e.g. Scummer)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="patreon_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email address from Patreon webhook",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="patreon_member_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Patreon member UUID for deduplication",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="patreon_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("former", "Former"),
                    ("declined", "Declined"),
                ],
                default="",
                help_text="Current Patreon membership status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="patreon_tier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Patreon tier title (e.g. Scummer)",
                max_length=100,
            ),
        ),
    ]
