# Generated by Django 6.0.3 on 2026-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0141_remove_custom_content_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="customcontentpack",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Whether this content pack is featured on the Customisation page.",
            ),
        ),
        migrations.AddField(
            model_name="customcontentpack",
            name="featured_description",
            field=models.TextField(
                blank=True,
                help_text="A short description shown when this pack is featured.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomcontentpack",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Whether this content pack is featured on the Customisation page.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomcontentpack",
            name="featured_description",
            field=models.TextField(
                blank=True,
                help_text="A short description shown when this pack is featured.",
            ),
        ),
    ]
