# Generated by Django 6.0.5 on 2026-05-24 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0143_campaign_content_pack_through"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have pinned this campaign to their own home page.",
                related_name="pinned_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="starred_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have starred this campaign.",
                related_name="starred_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have pinned this list to their own home page.",
                related_name="pinned_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="starred_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have starred this list.",
                related_name="starred_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
