# Generated by Django 6.0.5 on 2026-06-05 17:30

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0145_create_house_icons_alpha_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Backfill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            (
                                "migrate_persistent_stash",
                                "Migrate persistent stash items (#1825)",
                            )
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "list_id_scope",
                    models.UUIDField(
                        blank=True,
                        help_text="If set, the run was scoped to this single List.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Done"), ("failed", "Failed")],
                        default="done",
                        max_length=16,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "backfill",
                "verbose_name_plural": "backfills",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBackfill",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            (
                                "migrate_persistent_stash",
                                "Migrate persistent stash items (#1825)",
                            )
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "list_id_scope",
                    models.UUIDField(
                        blank=True,
                        help_text="If set, the run was scoped to this single List.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Done"), ("failed", "Failed")],
                        default="done",
                        max_length=16,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical backfill",
                "verbose_name_plural": "historical backfills",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
