# Generated by Django 6.0.5 on 2026-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0146_backfill_historicalbackfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="selected_badge",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slug of the supporter badge the user has chosen to display (blank = no badge).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="selected_badge",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slug of the supporter badge the user has chosen to display (blank = no badge).",
                max_length=50,
            ),
        ),
    ]
