# Generated by Django 6.0.6 on 2026-06-13 07:49

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0174_gang_wide_skills"),
        ("core", "0148_add_content_pack_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalListSkillTreeAssignment",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        help_text="1-based rank of this skill tree within the gang's selection."
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The list this skill-tree pick belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.list",
                    ),
                ),
                (
                    "skill_category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The skill tree chosen for this slot.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentskillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical List Skill Tree Assignment",
                "verbose_name_plural": "historical List Skill Tree Assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ListSkillTreeAssignment",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        help_text="1-based rank of this skill tree within the gang's selection."
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        help_text="The list this skill-tree pick belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.list",
                    ),
                ),
                (
                    "skill_category",
                    models.ForeignKey(
                        help_text="The skill tree chosen for this slot.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentskillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "List Skill Tree Assignment",
                "verbose_name_plural": "List Skill Tree Assignments",
                "ordering": ["list", "slot"],
            },
        ),
    ]
