# Generated by Django 6.0.6 on 2026-06-13 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0175_gang_skill_constraints"),
        ("core", "0149_list_skill_tree_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistskilltreeassignment",
            name="slot",
            field=models.PositiveSmallIntegerField(
                help_text="1-based rank of this skill tree within the gang's selection.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="listskilltreeassignment",
            name="slot",
            field=models.PositiveSmallIntegerField(
                help_text="1-based rank of this skill tree within the gang's selection.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddConstraint(
            model_name="listskilltreeassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived", False)),
                fields=("list", "slot"),
                name="uniq_active_list_skill_tree_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="listskilltreeassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived", False)),
                fields=("list", "skill_category"),
                name="uniq_active_list_skill_tree_category",
            ),
        ),
    ]
