# Generated by Django 6.0.6 on 2026-07-03 22:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0176_contentmod_unique_constraints"),
        ("core", "0151_assignment_component_through_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="pinned_base_amount",
            field=models.IntegerField(
                blank=True,
                help_text="The resolved base cost at acquisition. Null only while unpinned.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="pinned_base_state",
            field=models.CharField(
                choices=[
                    ("unpinned", "Unpinned"),
                    ("source", "Source"),
                    ("catalog", "Catalog"),
                    ("derived", "Derived"),
                    ("orphaned", "Orphaned"),
                ],
                default="unpinned",
                help_text="Attribution state for the base-cost pin.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="pinned_equipment_list_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The equipment-list row whose price was captured for the base cost at acquisition.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentfighterequipmentlistitem",
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighterequipmentassignment",
            name="pinned_expansion_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The expansion item whose price was captured for the base cost at acquisition.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentequipmentlistexpansionitem",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="pinned_base_amount",
            field=models.IntegerField(
                blank=True,
                help_text="The resolved base cost at acquisition. Null only while unpinned.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="pinned_base_state",
            field=models.CharField(
                choices=[
                    ("unpinned", "Unpinned"),
                    ("source", "Source"),
                    ("catalog", "Catalog"),
                    ("derived", "Derived"),
                    ("orphaned", "Orphaned"),
                ],
                default="unpinned",
                help_text="Attribution state for the base-cost pin.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="pinned_equipment_list_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The equipment-list row whose price was captured for the base cost at acquisition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_base_assignments",
                to="content.contentfighterequipmentlistitem",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignment",
            name="pinned_expansion_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The expansion item whose price was captured for the base cost at acquisition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_base_assignments",
                to="content.contentequipmentlistexpansionitem",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentaccessory",
            name="pin_state",
            field=models.CharField(
                choices=[
                    ("unpinned", "Unpinned"),
                    ("source", "Source"),
                    ("catalog", "Catalog"),
                    ("derived", "Derived"),
                    ("orphaned", "Orphaned"),
                ],
                default="unpinned",
                help_text="Attribution state for this component's pin.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentaccessory",
            name="pinned_amount",
            field=models.IntegerField(
                blank=True,
                help_text="The resolved cost at acquisition. Null only while unpinned.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentaccessory",
            name="pinned_equipment_list_accessory",
            field=models.ForeignKey(
                blank=True,
                help_text="The equipment-list accessory row whose price was captured at acquisition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_accessory_rows",
                to="content.contentfighterequipmentlistweaponaccessory",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentprofile",
            name="pin_state",
            field=models.CharField(
                choices=[
                    ("unpinned", "Unpinned"),
                    ("source", "Source"),
                    ("catalog", "Catalog"),
                    ("derived", "Derived"),
                    ("orphaned", "Orphaned"),
                ],
                default="unpinned",
                help_text="Attribution state for this component's pin.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentprofile",
            name="pinned_amount",
            field=models.IntegerField(
                blank=True,
                help_text="The resolved cost at acquisition. Null only while unpinned.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentprofile",
            name="pinned_equipment_list_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The equipment-list row whose price was captured at acquisition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_profile_rows",
                to="content.contentfighterequipmentlistitem",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentprofile",
            name="pinned_expansion_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The expansion item whose price was captured at acquisition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_profile_rows",
                to="content.contentequipmentlistexpansionitem",
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentupgrade",
            name="pin_state",
            field=models.CharField(
                choices=[
                    ("unpinned", "Unpinned"),
                    ("source", "Source"),
                    ("catalog", "Catalog"),
                    ("derived", "Derived"),
                    ("orphaned", "Orphaned"),
                ],
                default="unpinned",
                help_text="Attribution state for this component's pin.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentupgrade",
            name="pinned_amount",
            field=models.IntegerField(
                blank=True,
                help_text="The resolved cost at acquisition. Null only while unpinned.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listfighterequipmentassignmentupgrade",
            name="pinned_equipment_list_upgrade",
            field=models.ForeignKey(
                blank=True,
                help_text="The equipment-list upgrade row whose price was captured at acquisition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_upgrade_rows",
                to="content.contentfighterequipmentlistupgrade",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalListFighterEquipmentAssignmentAccessory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "pinned_amount",
                    models.IntegerField(
                        blank=True,
                        help_text="The resolved cost at acquisition. Null only while unpinned.",
                        null=True,
                    ),
                ),
                (
                    "pin_state",
                    models.CharField(
                        choices=[
                            ("unpinned", "Unpinned"),
                            ("source", "Source"),
                            ("catalog", "Catalog"),
                            ("derived", "Derived"),
                            ("orphaned", "Orphaned"),
                        ],
                        default="unpinned",
                        help_text="Attribution state for this component's pin.",
                        max_length=16,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contentweaponaccessory",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentweaponaccessory",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listfighterequipmentassignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighterequipmentassignment",
                    ),
                ),
                (
                    "pinned_equipment_list_accessory",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The equipment-list accessory row whose price was captured at acquisition.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentfighterequipmentlistweaponaccessory",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical weapon accessory row",
                "verbose_name_plural": "historical weapon accessory rows",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalListFighterEquipmentAssignmentProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "pinned_amount",
                    models.IntegerField(
                        blank=True,
                        help_text="The resolved cost at acquisition. Null only while unpinned.",
                        null=True,
                    ),
                ),
                (
                    "pin_state",
                    models.CharField(
                        choices=[
                            ("unpinned", "Unpinned"),
                            ("source", "Source"),
                            ("catalog", "Catalog"),
                            ("derived", "Derived"),
                            ("orphaned", "Orphaned"),
                        ],
                        default="unpinned",
                        help_text="Attribution state for this component's pin.",
                        max_length=16,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contentweaponprofile",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentweaponprofile",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listfighterequipmentassignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighterequipmentassignment",
                    ),
                ),
                (
                    "pinned_equipment_list_item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The equipment-list row whose price was captured at acquisition.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentfighterequipmentlistitem",
                    ),
                ),
                (
                    "pinned_expansion_item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The expansion item whose price was captured at acquisition.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipmentlistexpansionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical weapon profile row",
                "verbose_name_plural": "historical weapon profile rows",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalListFighterEquipmentAssignmentUpgrade",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "pinned_amount",
                    models.IntegerField(
                        blank=True,
                        help_text="The resolved cost at acquisition. Null only while unpinned.",
                        null=True,
                    ),
                ),
                (
                    "pin_state",
                    models.CharField(
                        choices=[
                            ("unpinned", "Unpinned"),
                            ("source", "Source"),
                            ("catalog", "Catalog"),
                            ("derived", "Derived"),
                            ("orphaned", "Orphaned"),
                        ],
                        default="unpinned",
                        help_text="Attribution state for this component's pin.",
                        max_length=16,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contentequipmentupgrade",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipmentupgrade",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listfighterequipmentassignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighterequipmentassignment",
                    ),
                ),
                (
                    "pinned_equipment_list_upgrade",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The equipment-list upgrade row whose price was captured at acquisition.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentfighterequipmentlistupgrade",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical equipment upgrade row",
                "verbose_name_plural": "historical equipment upgrade rows",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
