# Generated by Django 6.0.6 on 2026-07-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0153_pin_state_amount_invariants"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprintconfig",
            name="card_style",
            field=models.CharField(
                choices=[
                    ("web", "Web cards (standard)"),
                    ("classic", "Classic cards (grimdark, 4 per A4 sheet)"),
                ],
                default="web",
                help_text="Which card style to print.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="printconfig",
            name="card_style",
            field=models.CharField(
                choices=[
                    ("web", "Web cards (standard)"),
                    ("classic", "Classic cards (grimdark, 4 per A4 sheet)"),
                ],
                default="web",
                help_text="Which card style to print.",
                max_length=20,
            ),
        ),
    ]
