# Generated by Django 6.0.6 on 2026-07-05 11:43

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0155_backfill_pin_operations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalListFighterEquipmentSet",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this equipment set / card.",
                        max_length=255,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list_fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The fighter this equipment set belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Equipment Set",
                "verbose_name_plural": "historical Equipment Sets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ListFighterEquipmentSet",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this equipment set / card.",
                        max_length=255,
                    ),
                ),
                (
                    "assignments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The fighter's direct equipment assignments included in this set. Assignments not listed here are hidden while this set is active, but remain assigned to the fighter.",
                        related_name="equipment_sets",
                        to="core.listfighterequipmentassignment",
                    ),
                ),
                (
                    "list_fighter",
                    models.ForeignKey(
                        help_text="The fighter this equipment set belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_sets",
                        to="core.listfighter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Set",
                "verbose_name_plural": "Equipment Sets",
                "ordering": ["name", "created"],
            },
        ),
        migrations.AddField(
            model_name="historicallistfighter",
            name="active_equipment_set",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The fighter's currently-selected equipment set (card). NULL shows all equipment (the Default card).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.listfighterequipmentset",
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="active_equipment_set",
            field=models.ForeignKey(
                blank=True,
                help_text="The fighter's currently-selected equipment set (card). NULL shows all equipment (the Default card).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.listfighterequipmentset",
            ),
        ),
    ]
