# Generated by Django 6.0.6 on 2026-07-04 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0154_reconcile_action_type"),
        ("core", "0155_drop_stale_card_theme_column"),
    ]

    operations = []
