# Generated by Django 6.0.6 on 2026-07-05 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0157_equipment_sets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("list", "List"),
                            ("campaign", "Campaign"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft-delete timestamp. Deleted rows disappear from every inbox view.",
                        null=True,
                    ),
                ),
                (
                    "show_as_banner",
                    models.BooleanField(
                        default=False,
                        help_text="Also show this on the related List/Campaign page as a banner.",
                    ),
                ),
                (
                    "banner_colour",
                    models.CharField(
                        blank=True,
                        default="info",
                        help_text="Bootstrap colour for the in-page banner (info/warning/success/danger).",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bootstrap icon class, e.g. 'bi-info-circle'.",
                        max_length=50,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="core.campaign",
                    ),
                ),
                (
                    "related_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="core.list",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who caused this notification. Null for background/system jobs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("archived", False),
                            ("deleted_at__isnull", True),
                            ("is_read", False),
                        ),
                        fields=["owner"],
                        name="notif_unread_idx",
                    ),
                    models.Index(fields=["owner", "-created"], name="notif_inbox_idx"),
                    models.Index(
                        fields=["related_list", "show_as_banner"],
                        name="notif_banner_list_idx",
                    ),
                    models.Index(
                        fields=["related_campaign", "show_as_banner"],
                        name="notif_banner_camp_idx",
                    ),
                ],
            },
        ),
    ]
