# Generated by Django 6.0.6 on 2026-07-06 20:07

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0177_add_counter_warning_stat"),
        ("core", "0160_add_notification_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalListFighterCounterSpend",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="Counter points spent."),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why the points were spent."
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        help_text="What the points were spent on (intended outcome).",
                    ),
                ),
                (
                    "date_spent",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="When the points were spent.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campaign_action",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The campaign action recording this spend, if in a campaign.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.campaignaction",
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The counter that was spent, kept for refunds on removal.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentcounter",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The fighter who spent the counter points.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fighter Counter Spend",
                "verbose_name_plural": "historical Fighter Counter Spends",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ListFighterCounterSpend",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="Counter points spent."),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why the points were spent."
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        help_text="What the points were spent on (intended outcome).",
                    ),
                ),
                (
                    "date_spent",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the points were spent."
                    ),
                ),
                (
                    "campaign_action",
                    models.OneToOneField(
                        blank=True,
                        help_text="The campaign action recording this spend, if in a campaign.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counter_spend",
                        to="core.campaignaction",
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        blank=True,
                        help_text="The counter that was spent, kept for refunds on removal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spends",
                        to="content.contentcounter",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        help_text="The fighter who spent the counter points.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counter_spends",
                        to="core.listfighter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fighter Counter Spend",
                "verbose_name_plural": "Fighter Counter Spends",
                "ordering": ["-date_spent"],
            },
        ),
    ]
