# Generated by Django 6.0.6 on 2026-07-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0161_drop_backfill_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backfill",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="done",
                max_length=16,
            ),
        ),
    ]
