# Generated by Django 6.0.7 on 2026-07-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0164_battle_state_and_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallist",
            name="status",
            field=models.CharField(
                choices=[
                    ("list_building", "List Building"),
                    ("campaign_mode", "Campaign Mode"),
                    ("cloning_in_progress", "Joining Campaign"),
                ],
                db_index=True,
                default="list_building",
                help_text="Current status of the list.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="status",
            field=models.CharField(
                choices=[
                    ("list_building", "List Building"),
                    ("campaign_mode", "Campaign Mode"),
                    ("cloning_in_progress", "Joining Campaign"),
                ],
                db_index=True,
                default="list_building",
                help_text="Current status of the list.",
                max_length=20,
            ),
        ),
    ]
