# Generated by Django 6.0.7 on 2026-07-12 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0166_impersonation_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have shared administrative rights for this campaign.",
                related_name="administered_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
