# Generated by Django 6.0.7 on 2026-07-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0174_crew_rating_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="loadout_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Advisory pre-lock intent: which equipment set each fighter should bring when a whole-gang crew is enrolled at lock. Shape: {"<list_fighter_id>": {"equipment_set": "<set_id>"}}, where a stored null means the Default card. Never authoritative — see Crew.resolve_loadout.',
            ),
        ),
        migrations.AddField(
            model_name="historicalcrew",
            name="loadout_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Advisory pre-lock intent: which equipment set each fighter should bring when a whole-gang crew is enrolled at lock. Shape: {"<list_fighter_id>": {"equipment_set": "<set_id>"}}, where a stored null means the Default card. Never authoritative — see Crew.resolve_loadout.',
            ),
        ),
    ]
