# Generated by Django 6.0.7 on 2026-07-20 19:07

import gyrinx.core.models.crew
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0179_crew_member_linked_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="included_categories",
            field=models.JSONField(
                blank=True,
                default=gyrinx.core.models.crew.default_included_categories,
                help_text='Fighter categories this crew opts into beyond the always-eligible set. Hangers-on and vehicle crew are excluded from selection by default — hangers-on don\'t normally fight, and crew are an Ash Wastes thing — and a player adds them here per crew. A list of FighterCategoryChoices values (e.g. ["HANGER_ON", "CREW"]).',
            ),
        ),
        migrations.AddField(
            model_name="historicalcrew",
            name="included_categories",
            field=models.JSONField(
                blank=True,
                default=gyrinx.core.models.crew.default_included_categories,
                help_text='Fighter categories this crew opts into beyond the always-eligible set. Hangers-on and vehicle crew are excluded from selection by default — hangers-on don\'t normally fight, and crew are an Ash Wastes thing — and a player adds them here per crew. A list of FighterCategoryChoices values (e.g. ["HANGER_ON", "CREW"]).',
            ),
        ),
    ]
