# Generated by Django 6.0.7 on 2026-07-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0180_crew_included_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="default_included_crew_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Fighter categories that start opted in when picking a crew in this campaign — hangers-on and vehicle crew, which are hidden by default. Players can still change it per crew. A list of FighterCategoryChoices values (e.g. ["CREW"] for an Ash-Wastes campaign).',
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="default_included_crew_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Fighter categories that start opted in when picking a crew in this campaign — hangers-on and vehicle crew, which are hidden by default. Players can still change it per crew. A list of FighterCategoryChoices values (e.g. ["CREW"] for an Ash-Wastes campaign).',
            ),
        ),
    ]
