# Generated by Django 6.0.6 on 2026-07-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0181_seed_promotion_paths"),
        ("core", "0181_campaign_default_crew_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighteradvancement",
            name="promotion_path",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="For promotion advancements, which promotion path was taken.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentpromotionpath",
            ),
        ),
        migrations.AddField(
            model_name="listfighteradvancement",
            name="promotion_path",
            field=models.ForeignKey(
                blank=True,
                help_text="For promotion advancements, which promotion path was taken.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advancements",
                to="content.contentpromotionpath",
            ),
        ),
        migrations.AlterField(
            model_name="historicallistfighteradvancement",
            name="advancement_type",
            field=models.CharField(
                choices=[
                    ("stat", "Characteristic Increase"),
                    ("skill", "New Skill"),
                    ("equipment", "New Equipment"),
                    ("promotion", "Promotion"),
                    ("other", "Other"),
                ],
                help_text="The type of advancement purchased.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="listfighteradvancement",
            name="advancement_type",
            field=models.CharField(
                choices=[
                    ("stat", "Characteristic Increase"),
                    ("skill", "New Skill"),
                    ("equipment", "New Equipment"),
                    ("promotion", "Promotion"),
                    ("other", "Other"),
                ],
                help_text="The type of advancement purchased.",
                max_length=10,
            ),
        ),
    ]
