# Generated by Django 6.0.7 on 2026-07-21 08:38

import gyrinx.core.models.crew
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0182_crew_member_included_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="eligibility_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-fighter eligibility set on the eligibility screen, overriding the category default. Shape: {"<list_fighter_id>": "<state>"} where state is one of eligible / included / excluded. Only fighters the player changed from their default are stored; everyone else uses the computed default (see handlers.crew.crew_eligibility).',
            ),
        ),
        migrations.AddField(
            model_name="historicalcrew",
            name="eligibility_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-fighter eligibility set on the eligibility screen, overriding the category default. Shape: {"<list_fighter_id>": "<state>"} where state is one of eligible / included / excluded. Only fighters the player changed from their default are stored; everyone else uses the computed default (see handlers.crew.crew_eligibility).',
            ),
        ),
        migrations.AlterField(
            model_name="crew",
            name="included_categories",
            field=models.JSONField(
                blank=True,
                default=gyrinx.core.models.crew.default_included_categories,
                help_text='Fighter categories this crew opts into beyond the always-eligible set. Hangers-on and vehicle crew are excluded from selection by default — hangers-on don\'t normally fight, and crew are an Ash Wastes thing — and a player adds them here per crew. A list of FighterCategoryChoices values (e.g. ["HANGER_ON", "CREW"]). Seeds the eligibility screen\'s per-category defaults.',
            ),
        ),
        migrations.AlterField(
            model_name="historicalcrew",
            name="included_categories",
            field=models.JSONField(
                blank=True,
                default=gyrinx.core.models.crew.default_included_categories,
                help_text='Fighter categories this crew opts into beyond the always-eligible set. Hangers-on and vehicle crew are excluded from selection by default — hangers-on don\'t normally fight, and crew are an Ash Wastes thing — and a player adds them here per crew. A list of FighterCategoryChoices values (e.g. ["HANGER_ON", "CREW"]). Seeds the eligibility screen\'s per-category defaults.',
            ),
        ),
    ]
