# Generated by Django 6.0.6 on 2026-07-21 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0181_seed_promotion_paths"),
        ("core", "0182_advancement_promotion_type_and_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighter",
            name="promoted_content_fighter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The fighter type this fighter counts as (for equipment, skill and special-rule access) after a type-change promotion.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentfighter",
            ),
        ),
        migrations.AddField(
            model_name="historicallistfighteradvancement",
            name="promotion_target",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="For type-change promotions with a choice of targets, which fighter type was chosen (e.g. Forge Boss vs Stimmer).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentfighter",
            ),
        ),
        migrations.AddField(
            model_name="listfighter",
            name="promoted_content_fighter",
            field=models.ForeignKey(
                blank=True,
                help_text="The fighter type this fighter counts as (for equipment, skill and special-rule access) after a type-change promotion.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="list_fighter_promoted",
                to="content.contentfighter",
            ),
        ),
        migrations.AddField(
            model_name="listfighteradvancement",
            name="promotion_target",
            field=models.ForeignKey(
                blank=True,
                help_text="For type-change promotions with a choice of targets, which fighter type was chosen (e.g. Forge Boss vs Stimmer).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotion_advancements",
                to="content.contentfighter",
            ),
        ),
    ]
