# Generated by Django 6.0.7 on 2026-07-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0186_crew_stash_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="default_gang_sort",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default ordering for the gang table on the campaign page — a metric name, prefixed with '-' for descending: e.g. '-wealth', 'name', or '-resource:<resource type id>'. Blank means wealth, highest first.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="default_gang_sort",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Default ordering for the gang table on the campaign page — a metric name, prefixed with '-' for descending: e.g. '-wealth', 'name', or '-resource:<resource type id>'. Blank means wealth, highest first.",
                max_length=64,
            ),
        ),
    ]
