# Generated by Django 6.0.7 on 2026-07-26 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0188_crew_membership_locked_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="credits_charged",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Credits actually taken from the gang when the battle started. May be less than the crew's spending if the gang could not cover it — the balance is floored at zero rather than going negative, so the difference is a real debt the arbitrator has to settle.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="credits_charged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the battle charged this crew's spending. Also the idempotency guard: a crew that has been charged is never charged again.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="ready_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the gang declared this crew ready. Blank until they say so, and cleared again if they withdraw it. Deliberately separate from status: locking freezes who is in the crew and cannot be undone, while readiness just says the player has finished setting up.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="ready_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who declared the crew ready.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crews_marked_ready",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcrew",
            name="credits_charged",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Credits actually taken from the gang when the battle started. May be less than the crew's spending if the gang could not cover it — the balance is floored at zero rather than going negative, so the difference is a real debt the arbitrator has to settle.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcrew",
            name="credits_charged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the battle charged this crew's spending. Also the idempotency guard: a crew that has been charged is never charged again.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcrew",
            name="ready_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the gang declared this crew ready. Blank until they say so, and cleared again if they withdraw it. Deliberately separate from status: locking freezes who is in the crew and cannot be undone, while readiness just says the player has finished setting up.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcrew",
            name="ready_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Who declared the crew ready.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
