# Generated by Django 6.0.7 on 2026-07-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0189_crew_ready_and_credits_charged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewlineitem",
            name="payment",
            field=models.CharField(
                choices=[
                    ("credits", "Gang credits"),
                    ("free", "Free"),
                    ("allowance", "Balancing"),
                ],
                default="credits",
                help_text="How this is paid for (descriptive; no credits are moved).",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcrewlineitem",
            name="payment",
            field=models.CharField(
                choices=[
                    ("credits", "Gang credits"),
                    ("free", "Free"),
                    ("allowance", "Balancing"),
                ],
                default="credits",
                help_text="How this is paid for (descriptive; no credits are moved).",
                max_length=12,
            ),
        ),
    ]
