# Generated by Django 6.0.7 on 2026-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0190_crew_line_item_balancing_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewlineitem",
            name="payment",
            field=models.CharField(
                choices=[
                    ("credits", "Gang credits"),
                    ("free", "Free"),
                    ("allowance", "Balancing"),
                ],
                default="credits",
                help_text="Where the credits come from. Gang credits are charged at battle start; balancing and free entries are recorded only.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="crewlineitem",
            name="reason",
            field=models.CharField(
                blank=True,
                help_text="Why, when free or from balancing.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcrewlineitem",
            name="payment",
            field=models.CharField(
                choices=[
                    ("credits", "Gang credits"),
                    ("free", "Free"),
                    ("allowance", "Balancing"),
                ],
                default="credits",
                help_text="Where the credits come from. Gang credits are charged at battle start; balancing and free entries are recorded only.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcrewlineitem",
            name="reason",
            field=models.CharField(
                blank=True,
                help_text="Why, when free or from balancing.",
                max_length=255,
            ),
        ),
    ]
