# Generated by Django 6.0.7 on 2026-07-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0191_crew_line_item_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewlineitem",
            name="label",
            field=models.CharField(
                help_text="What this is (e.g. 'Tactics Card').", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="historicalcrewlineitem",
            name="label",
            field=models.CharField(
                help_text="What this is (e.g. 'Tactics Card').", max_length=255
            ),
        ),
    ]
