# Generated by Django 6.0.7 on 2026-07-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0194_crew_line_item_split_amounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="credits_owed",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="What the crew's spending came to when the battle charged it. Snapshotted because the extras stay editable afterwards: the shortfall is a fact about that moment, and recomputing it live would invent a debt when an extra is added later, or hide a real one when an extra is removed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcrew",
            name="credits_owed",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="What the crew's spending came to when the battle charged it. Snapshotted because the extras stay editable afterwards: the shortfall is a fact about that moment, and recomputing it live would invent a debt when an extra is added later, or hide a real one when an extra is removed.",
                null=True,
            ),
        ),
    ]
