# Generated by Django 6.0.7 on 2026-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0196_convert_legacy_stat_advancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprintconfig",
            name="include_xp",
            field=models.BooleanField(
                default=True, help_text="Show each fighter's current XP on their card."
            ),
        ),
        migrations.AddField(
            model_name="printconfig",
            name="include_xp",
            field=models.BooleanField(
                default=True, help_text="Show each fighter's current XP on their card."
            ),
        ),
    ]
