# Generated by Django 6.0.7 on 2026-07-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0198_print_config_include_lore_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backfill",
            name="operation",
            field=models.CharField(
                choices=[
                    (
                        "migrate_persistent_stash",
                        "Migrate persistent stash items (#1825)",
                    ),
                    ("reconcile_lists", "Reconcile list cost caches (#1826 Phase 8)"),
                    ("backfill_pins", "Backfill acquisition receipts (#1826 Phase 8)"),
                    (
                        "fix_stat_advancements",
                        "Finish the stat-advancement cleanup (#2070)",
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
