# Generated by Django 5.2.4 on 2025-07-17 15:38

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0118_merge_armoured_undersuit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentStatlineType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Statline Type",
                "verbose_name_plural": "Statline Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentStatline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "stat_values",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object storing stat values, e.g., {'movement': '5\"', 'front': '12', ...}",
                    ),
                ),
                (
                    "content_fighter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_statline",
                        to="content.contentfighter",
                    ),
                ),
                (
                    "statline_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentstatlinetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fighter Statline",
                "verbose_name_plural": "Fighter Statlines",
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentStatline",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "stat_values",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object storing stat values, e.g., {'movement': '5\"', 'front': '12', ...}",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentfighter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statline_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentstatlinetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fighter Statline",
                "verbose_name_plural": "historical Fighter Statlines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContentStatlineType",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Statline Type",
                "verbose_name_plural": "historical Statline Types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContentStatlineTypeStat",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "field_name",
                    models.CharField(
                        help_text="Internal field name (e.g., 'movement', 'front_toughness')",
                        max_length=50,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short display name (e.g., 'M', 'Fr')", max_length=10
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full display name (e.g., 'Movement', 'Front Toughness')",
                        max_length=50,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="Display order position (lower numbers appear first)"
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this stat should be highlighted in the UI (like Ld, Cl, Wil, Int)",
                    ),
                ),
                (
                    "is_first_of_group",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this stat starts a new visual group (adds border)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statline_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentstatlinetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Statline Type Stat",
                "verbose_name_plural": "historical Statline Type Stats",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentStatlineTypeStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "field_name",
                    models.CharField(
                        help_text="Internal field name (e.g., 'movement', 'front_toughness')",
                        max_length=50,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short display name (e.g., 'M', 'Fr')", max_length=10
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full display name (e.g., 'Movement', 'Front Toughness')",
                        max_length=50,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="Display order position (lower numbers appear first)"
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this stat should be highlighted in the UI (like Ld, Cl, Wil, Int)",
                    ),
                ),
                (
                    "is_first_of_group",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this stat starts a new visual group (adds border)",
                    ),
                ),
                (
                    "statline_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="content.contentstatlinetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statline Type Stat",
                "verbose_name_plural": "Statline Type Stats",
                "ordering": ["statline_type", "position"],
                "unique_together": {("statline_type", "field_name")},
            },
        ),
    ]
