# Generated by Django 5.2.4 on 2025-07-19 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0123_refactor_statline_to_use_contentstat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentmodfighterstat",
            name="stat",
            field=models.CharField(
                choices=[
                    ("movement", "Movement"),
                    ("weapon_skill", "Weapon Skill"),
                    ("ballistic_skill", "Ballistic Skill"),
                    ("strength", "Strength"),
                    ("toughness", "Toughness"),
                    ("wounds", "Wounds"),
                    ("initiative", "Initiative"),
                    ("attacks", "Attacks"),
                    ("leadership", "Leadership"),
                    ("cool", "Cool"),
                    ("willpower", "Willpower"),
                    ("intelligence", "Intelligence"),
                    ("front", "Front"),
                    ("side", "Side"),
                    ("rear", "Rear"),
                    ("hull_points", "Hull Points"),
                    ("handling", "Handling"),
                    ("save", "Save"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contentstat",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentstat",
            name="id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
