# Generated by Django 5.2.4 on 2025-07-22 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0126_add_contentfighterequipmentcategorylimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentequipmentcategoryfighterrestriction",
            name="equipment_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fighter_restrictions",
                to="content.contentequipmentcategory",
            ),
        ),
    ]
