# Generated by Django 5.2.4 on 2025-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0126_add_cost_expression_to_weapon_accessory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentweaponaccessory",
            name="cost_expression",
            field=models.CharField(
                blank=True,
                help_text="Optional cost calculation expression. If provided, this will be used instead of the base cost. Available variables: cost_int (the base cost of the weapon). Available functions: min(), max(), round(), ceil(), floor(). Example: 'ceil(cost_int * 0.25 / 5) * 5' for 25% of cost rounded up to nearest 5.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponaccessory",
            name="cost_expression",
            field=models.CharField(
                blank=True,
                help_text="Optional cost calculation expression. If provided, this will be used instead of the base cost. Available variables: cost_int (the base cost of the weapon). Available functions: min(), max(), round(), ceil(), floor(). Example: 'ceil(cost_int * 0.25 / 5) * 5' for 25% of cost rounded up to nearest 5.",
                max_length=255,
            ),
        ),
    ]
