# Generated by Django 5.2.4 on 2025-08-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0128_add_gang_terrain_fighter_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenthouse",
            name="can_buy_any",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this House can buy any equipment from any equipment list and trading post.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontenthouse",
            name="can_buy_any",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this House can buy any equipment from any equipment list and trading post.",
            ),
        ),
    ]
