# Generated by Django 5.2.5 on 2025-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0144_fix_smart_quotes_in_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfightercategoryterms",
            name="recovery_singular",
            field=models.CharField(
                default="Recovery",
                help_text="Singular form of recovery (e.g., 'Recovery', 'Repair')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfightercategoryterms",
            name="recovery_singular",
            field=models.CharField(
                default="Recovery",
                help_text="Singular form of recovery (e.g., 'Recovery', 'Repair')",
                max_length=255,
            ),
        ),
    ]
