# Generated by Django 6.0.1 on 2026-02-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0153_add_availability_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentavailabilitypreset",
            name="fighter_can_buy_any",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this fighter defaults to showing all equipment (filter=all) on weapons/gear pages, similar to house-level can_buy_any.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentavailabilitypreset",
            name="fighter_can_buy_any",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this fighter defaults to showing all equipment (filter=all) on weapons/gear pages, similar to house-level can_buy_any.",
            ),
        ),
    ]
