# Generated by Django 6.0.2 on 2026-02-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0154_add_fighter_can_buy_any_to_availability_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrule",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcontentrule",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
