# Generated by Django 6.0.2 on 2026-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0157_add_counter_and_roll_table_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentweapontrait",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="An optional description of what this trait does.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentweapontrait",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="An optional description of what this trait does.",
            ),
        ),
        migrations.AlterField(
            model_name="contentweapontrait",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalcontentweapontrait",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
