# Generated by Django 6.0.3 on 2026-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0161_add_description_to_house_and_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentweaponaccessory",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="An optional description of what this accessory does.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentweaponaccessory",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="An optional description of what this accessory does.",
            ),
        ),
        migrations.AlterField(
            model_name="contentweaponaccessory",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponaccessory",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
