# Generated by Django 6.0.4 on 2026-04-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0162_weapon_accessory_pack_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipment",
            name="auto_companion_for_fighter",
            field=models.OneToOneField(
                blank=True,
                help_text="Set only by the pack vehicle/exotic-beast auto-create flow. This equipment is the read-only companion that lets list-buyers purchase the linked fighter. Manually-authored equipment must leave this NULL.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_companion_equipment",
                to="content.contentfighter",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentequipment",
            name="auto_companion_for_fighter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Set only by the pack vehicle/exotic-beast auto-create flow. This equipment is the read-only companion that lets list-buyers purchase the linked fighter. Manually-authored equipment must leave this NULL.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentfighter",
            ),
        ),
    ]
