# Generated by Django 6.0.4 on 2026-05-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0163_add_auto_companion_for_fighter"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpsykerdiscipline",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contentpsykerpower",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcontentpsykerdiscipline",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcontentpsykerpower",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
