# Generated by Django 6.0.5 on 2026-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0168_dedupe_content_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentrule",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalcontentrule",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
