# Generated by Django 6.0.6 on 2026-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0176_contentmod_unique_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcounter",
            name="warning_stat",
            field=models.CharField(
                blank=True,
                help_text="Optional statline short name (e.g. T). When the counter value exceeds this stat, the counter is highlighted on the fighter card.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentcounter",
            name="warning_stat",
            field=models.CharField(
                blank=True,
                help_text="Optional statline short name (e.g. T). When the counter value exceeds this stat, the counter is highlighted on the fighter card.",
                max_length=10,
            ),
        ),
    ]
