# Generated by Django 6.0.6 on 2026-07-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0181_seed_promotion_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrule",
            name="shed_on_promotion",
            field=models.BooleanField(
                default=False,
                help_text="If checked, a fighter loses this rule when they take a type-change promotion (the promotion-scaffolding rules — Gang Fighter (Juve), the Promotion rule itself, Fast Learner, and so on). By default a fighter keeps all their rules on promotion and gains the new type's rules on top.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentrule",
            name="shed_on_promotion",
            field=models.BooleanField(
                default=False,
                help_text="If checked, a fighter loses this rule when they take a type-change promotion (the promotion-scaffolding rules — Gang Fighter (Juve), the Promotion rule itself, Fast Learner, and so on). By default a fighter keeps all their rules on promotion and gains the new type's rules on top.",
            ),
        ),
    ]
