# Generated by Django 6.0.7 on 2026-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0182_content_rule_shed_on_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipment",
            name="crew_always_brought",
            field=models.BooleanField(
                default=False,
                help_text="When this equipment sits in a gang's stash, it is brought to every battle automatically — it appears in each crew's stash section and can't be left behind (e.g. the Iron Automaton, which is effectively part of the gang once owned).",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentequipment",
            name="crew_always_brought",
            field=models.BooleanField(
                default=False,
                help_text="When this equipment sits in a gang's stash, it is brought to every battle automatically — it appears in each crew's stash section and can't be left behind (e.g. the Iron Automaton, which is effectively part of the gang once owned).",
            ),
        ),
    ]
