# Generated by Django 6.0.7 on 2026-07-26 19:38

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0184_equipment_crew_treated_as_fighter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalContentEquipmentInjuryLink",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("offset", "Offset (injury effects still apply)"),
                            ("suppress", "Suppress (injury effects stop applying)"),
                        ],
                        default="offset",
                        help_text="Offset: the equipment's own modifiers cancel the injury, which keeps applying (Trading Post bionics). Suppress: the injury's modifiers stop applying entirely (Van Saar Cyberteknika).",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The equipment that treats the injury.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "injury",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The injury this equipment treats.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentinjury",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Equipment Injury Link",
                "verbose_name_plural": "historical Equipment Injury Links",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentEquipmentInjuryLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("offset", "Offset (injury effects still apply)"),
                            ("suppress", "Suppress (injury effects stop applying)"),
                        ],
                        default="offset",
                        help_text="Offset: the equipment's own modifiers cancel the injury, which keeps applying (Trading Post bionics). Suppress: the injury's modifiers stop applying entirely (Van Saar Cyberteknika).",
                        max_length=10,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="The equipment that treats the injury.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injury_links",
                        to="content.contentequipment",
                    ),
                ),
                (
                    "injury",
                    models.ForeignKey(
                        help_text="The injury this equipment treats.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treated_by",
                        to="content.contentinjury",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Injury Link",
                "verbose_name_plural": "Equipment Injury Links",
                "ordering": ["injury__name", "equipment__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("equipment", "injury"),
                        name="uniq_equipment_injury_link",
                    )
                ],
            },
        ),
    ]
