# Generated by Django 6.0.7 on 2026-08-05 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0188_flag_shed_on_promotion_rules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentfighter",
            name="attacks",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="ballistic_skill",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="cool",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="initiative",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="intelligence",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="leadership",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="movement",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="strength",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="toughness",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="weapon_skill",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="willpower",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="wounds",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="attacks",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="ballistic_skill",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="cool",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="initiative",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="intelligence",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="leadership",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="movement",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="strength",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="toughness",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="weapon_skill",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="willpower",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighter",
            name="wounds",
        ),
    ]
