# Render the YAML proposal into checked-in HTML and Markdown. No application imports.
require 'yaml'
require 'cgi'
root = __dir__
d=YAML.safe_load(File.read("#{root}/action-data-model.yaml"))
# Check references in the current four definitions and the new shape.
raise 'Action missing use_price list' unless d['actions'].values.all? { |a| a['use_price'].is_a?(Array) }
raise 'Unknown outcome' unless d['actions'].values.all? { |a| a['outcomes'].all? { |o| d['outcomes'].key?(o) } }
raise 'Old effect still wired' if d['availability_bindings']['bindings'].values.any? { |b| b['effect']['kind']!='AddsAssignable' }
raise 'Fixed rank table on action' if d['actions']['model_advancement']['allowance_rule'].key?('rank_table')
raise 'Glitches not fully cleared' unless d['outcomes']['clear_glitches']['operation']['changes'].map { |c| c['kind'] }==['counter_change','remove_picks']

def esc(s); CGI.escapeHTML(s.to_s);end
def code(obj);'<pre><code>'+esc(YAML.dump(obj,line_width:100).sub(/\A---\n/,'').rstrip)+'</code></pre>';end
def section(id,title,body);'<section id="'+id+'"><h2>'+title+'</h2>'+body+'</section>';end
body='<p class="eyebrow">n26 · accepted design</p><h1>Assignable actions, allowances and payments</h1><p class="lead">Grant access with existing assignments and modifiers. Record each paid or earned use separately.</p><p>This page preserves the accepted design sketch. The application implements the flows; NEW, EXTEND and REUSE labels record the work identified during design.</p><p><a href="index.html">Flow prototype</a> · <a href="action-data-model.yaml">Full YAML</a> · <a href="action-data-model.md">Markdown</a> · <a href="../../../n26/design/fighter-actions.md">Implementation guide</a></p><nav><a href="#naming">Names</a><a href="#relationships">Relationships</a><a href="#process">Allowance flow</a><a href="#rank-changes">Simpler rank changes</a><a href="#assignable">Assignable objects</a><a href="#purchase">Shared payments</a><a href="#reuse">Reuse map</a><a href="#access">Access wiring</a><a href="#actions">Four actions</a><a href="#domain">Domain definitions</a><a href="#outcomes">Outcomes</a><a href="#decisions">Decisions</a></nav>'
names = d.fetch('naming')
rows = names.fetch('alternatives').map do |option|
  labels = { 'name' => 'Name', 'example' => 'In conversation', 'benefit' => 'Why use it?', 'trade_off' => 'Trade-off' }
  '<tr>' + labels.map { |key, label| '<td data-label="' + esc(label) + '">' + esc(option[key]) + '</td>' }.join + '</tr>'
end.join
naming_body = '<p>' + esc(names['recommendation']) + '</p>'
naming_body += '<div class="table-wrap"><table><thead><tr><th>Name</th><th>In conversation</th><th>Why use it?</th><th>Trade-off</th></tr></thead><tbody>' + rows + '</tbody></table></div>'
naming_body += '<h3>Names in code</h3><ul>' + names.fetch('code_names').map { |entry| '<li><code>' + esc(entry['name']) + '</code>: ' + esc(entry['meaning']) + '</li>' }.join + '</ul>'
naming_body += '<p>' + esc(names['collision']) + '</p><p class="muted">' + esc(names['previous_name']) + '</p>'
body += section('naming', 'What should we call the assignable action?', naming_body)
body+=section('relationships','Entity relationships','<p>An allowance rule is content. An allowance is one earned use. An action record is one attempt to perform the action. Paid actions have no allowance.</p><div class="diagram"><img src="action-relationships.svg" alt="Entity relationships between actions, allowance rules, allowances, action records, payments and changes"></div><p class="muted">Arrows show references and grant relationships. An allowance has at most one started or completed record; cancelled pre-roll attempts remain in history. <a href="action-relationships.svg">Open diagram</a> · <a href="action-relationships.mmd">Mermaid source</a></p>')
body+=section('process','From a rule to an allowance to a completed action','<div class="diagram"><img src="action-allowance-flow.svg" alt="Earned and paid routes into an action record, with atomic creation and completion"></div><p class="muted"><a href="action-allowance-flow.svg">Open diagram</a> · <a href="action-allowance-flow.mmd">Mermaid source</a></p><p>Saving an XP increase from 48 to 61 records separate allowances for 49 and 61. Starting the 49 allowance reserves only that one. Continuing it reuses its recorded roll; completion leaves the 61 allowance available.</p><p>A fighter with a different assigned rank table uses that table’s thresholds. Changing the table itself does nothing. The next player-saved XP increase uses the replacement table to find newly crossed thresholds.</p>')
body+=section('rank-changes','Rank grants when XP increases','<p>Agreed: record newly crossed ranks during the player’s XP save. Changing the rank table itself needs no special handling or extra baseline.</p>'+code(d['rank_change_simplification']))
body+=section('payment-flow','Paid actions: one atomic purchase','<p><strong>Agreed:</strong> finish the choices before paying. Unfinished actions can be resumed or cancelled. Final confirmation writes the payment and result together.</p><div class="diagram"><img src="action-payment-flow.svg" alt="Unpaid choices followed by final confirmation, validation and atomic payment with result changes"></div><p><a href="action-payment-flow.svg">Open payment diagram</a> · <a href="action-payment-flow.mmd">Mermaid source</a></p>')
body+=section('assignable','Which objects should be assignable?',d['assignability'].map { |r| '<article><p class="status">'+esc(r['recommendation'])+'</p><h3>'+esc(r['name'])+'</h3><p>'+esc(r['reason'])+'</p></article>' }.join)
body+=section('purchase','Prices and payments can be shared with purchases','<p>'+esc(d['purchase_refactoring']['recommendation'])+'</p>'+d['purchase_refactoring'].reject { |k,_| k=='recommendation' }.map { |k,v| '<h3>'+esc(k.tr('_',' ').capitalize)+'</h3><ol>'+v.map { |x| '<li>'+esc(x)+'</li>' }.join+'</ol>' }.join+'<h3>A price can require both resources</h3>'+code(d['illustrative_mixed_price']))
body+=section('reuse','What exists and what changes',d['reuse_and_extensions'].map { |r| '<article><p class="status">'+esc(r['status'])+'</p><h3>'+esc(r['concept'])+'</h3><p>'+esc(r['implementation'])+'</p><p>'+esc(r['use'])+'</p>'+(r['source'] ? '<p class="muted"><code>'+esc(r['source'])+'</code></p>' : '')+'</article>' }.join)
body+=section('access','Availability wiring','<p>TargetsMiniature and AddsAssignable already exist. Registering Action and RankTable as supported kinds, and reading their effective access, is the extension. No OffersAction effect is proposed.</p>'+d['availability_bindings']['bindings'].map { |k,v| '<article><h3>'+esc(k.tr('_',' '))+'</h3>'+code(v)+'</article>' }.join+'<ul>'+d['availability_bindings']['reference_notes'].map { |x| '<li>'+esc(x)+'</li>' }.join+'</ul>')
body+=section('actions','The four actions','<p>use_price is the list paid to perform the action. The inherited price field is the credit price of acquiring the capability and remains zero in these examples.</p>'+d['actions'].map { |k,v| '<article><h3>'+esc(v['name'])+'</h3>'+code({'id'=>k}.merge(v))+'</article>' }.join)
body+=section('domain','Domain definitions',d['domain'].map { |name,v| '<details><summary>'+esc(name)+' <span class="status">'+esc(v['status'])+'</span></summary><p>'+esc(v['meaning'])+'</p><p class="muted">'+esc(v['storage'])+'</p>'+code(v['fields'])+'<ul>'+v['invariants'].map { |x| '<li>'+esc(x)+'</li>' }.join+'</ul></details>' }.join)
body+=section('outcomes','Shared outcomes','<p>Clear glitches now composes two named mutations. CounterChange reuses the current set/add/subtract configuration; RemovePicks is a new typed mutation using existing assignment removal.</p>'+d['outcomes'].map { |k,v| '<article><h3>'+esc(v['name'])+'</h3>'+code({'id'=>k}.merge(v))+'</article>' }.join)
body+=section('content','Tables and tiers',d['referenced_content'].map { |k,v| '<details><summary>'+esc(k.tr('_',' '))+'</summary>'+code(v)+'</details>' }.join)
body+=section('records','Example player records','<p>Selected fields illustrate successive states and separate fighters. Common metadata is defined above.</p>'+d['example_records'].map { |r| '<details><summary>'+esc(r['id'] || r['fighter'])+' · '+esc(r['state'] || 'allowances')+'</summary>'+code(r)+'</details>' }.join)
body+=section('decisions','Design notes and decisions',d['design_notes'].map { |n| '<article><h3>'+esc(n['title'])+'</h3><p>'+esc(n['text'])+'</p></article>' }.join)
body+='<footer><a href="README.md">About this exploration and how to rebuild it</a>. Sources: n26 assignments, grants, access, scopes, selectors, slots, counter effects, operations and ledger; local n26 rules.</footer>'
template = File.read("#{root}/data-model.template.html")
File.write("#{root}/action-data-model.html", template.sub("{{content}}") { body }.gsub(/[ \t]+(?=\n)/, ''))
md=['# Actions, allowances and payments — accepted design','This document preserves the accepted design sketch. The application implements Action and RankTable as assignable kinds. See `n26/design/fighter-actions.md` for canonical model and API details.','## Entity relationships','```mermaid',File.read("#{root}/action-relationships.mmd").strip,'```','## Allowance and payment flow','```mermaid',File.read("#{root}/action-allowance-flow.mmd").strip,'```','## Payment flow','```mermaid',File.read("#{root}/action-payment-flow.mmd").strip,'```','Rank grants use the current table during the player-triggered XP-change operation. There is no scheduled assessment or special handling when the table changes.']
md.insert(2, '## Naming', names['recommendation'], *names['alternatives'].flat_map { |o| ['### ' + o['name'], o['example'], o['benefit'], 'Trade-off: ' + o['trade_off']] }, '### Names in code', *names['code_names'].map { |n| '- `' + n['name'] + '`: ' + n['meaning'] }, names['collision'], names['previous_name'])
[['Rank grants on XP changes — agreed','rank_change_simplification'],['Assignability','assignability'],['Shared purchase/payment refactoring','purchase_refactoring'],['Mixed-price example','illustrative_mixed_price'],['Reuse and extensions','reuse_and_extensions'],['Availability wiring','availability_bindings'],['Four actions','actions']].each { |title,key| md+=['## '+title,'```yaml',YAML.dump(d[key],line_width:100),'```'] }
md+=['## Domain definitions']
d['domain'].each { |name,v| md+=["### #{name} — #{v['status']}",v['meaning'],v['storage'],'```yaml',YAML.dump(v['fields'],line_width:100),'```'];md+=v['invariants'].map { |x| '- '+x } }
[['Shared outcomes','outcomes'],['Referenced content','referenced_content'],['Example records','example_records']].each { |title,key| md+=['## '+title,'```yaml',YAML.dump(d[key],line_width:100),'```'] }
md+=['## Design notes'];d['design_notes'].each { |n| md+=['### '+n['title'],n['text']] }
File.write("#{root}/action-data-model.md", (md.join("\n\n")+"\n").gsub(/[ \t]+(?=\n)/, ''))
puts 'Rendered YAML into HTML/Markdown. Shape and reference checks passed.'
