# Generated by Django 6.0.1 on 2026-01-16 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("status", models.CharField(db_index=True, max_length=50)),
                ("task_name", models.CharField(db_index=True, max_length=255)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=dict)),
                ("return_value", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                ("enqueued_at", models.DateTimeField(db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Task Execution",
                "verbose_name_plural": "Task Executions",
                "ordering": ["-enqueued_at"],
                "indexes": [
                    models.Index(
                        fields=["task_name", "status"],
                        name="tasks_taske_task_na_c9bb97_idx",
                    ),
                    models.Index(
                        fields=["status", "enqueued_at"],
                        name="tasks_taske_status_281838_idx",
                    ),
                ],
            },
        ),
    ]
