# Generated by Django 6.0 on 2026-01-17 22:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_add_task_execution_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("RUNNING", "Running"),
                    ("SUCCESSFUL", "Successful"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="READY",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="TaskExecutionStateTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("to_status", models.CharField(db_index=True, max_length=50)),
                (
                    "transitioned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_state_transitions",
                        to="tasks.taskexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Execution state transition",
                "verbose_name_plural": "Task Execution state transitions",
                "ordering": ["-transitioned_at"],
            },
        ),
    ]
