# Generated by Django 6.0.7 on 2026-07-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_add_task_id_to_taskexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexecution",
            name="group_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Logical operation this task run belongs to (e.g. 'campaign-start:<uuid>').",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="taskexecution",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable name for this unit of work within its group.",
                max_length=255,
            ),
        ),
    ]
