# Generated by Django 6.0.7 on 2026-07-12 09:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_execution_group_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuedTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Matches TaskExecution.task_id (the Django TaskResult.id).",
                        max_length=255,
                    ),
                ),
                ("task_name", models.CharField(db_index=True, max_length=255)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=dict)),
                ("enqueued_at", models.DateTimeField()),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Earliest delivery time. Set forward for deferred tasks and for retry backoff.",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Visibility lease: while set and in the future, the row is hidden from other workers.",
                        null=True,
                    ),
                ),
                ("locked_by", models.CharField(blank=True, default="", max_length=64)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Queued Task",
                "verbose_name_plural": "Queued Tasks",
                "ordering": ["available_at", "created"],
                "indexes": [
                    models.Index(
                        fields=["available_at", "locked_until"],
                        name="tasks_queue_availab_4f99a0_idx",
                    ),
                    models.Index(
                        fields=["task_name"], name="tasks_queue_task_na_02ed72_idx"
                    ),
                ],
            },
        ),
    ]
