# Generated by Django 5.1.2 on 2024-11-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Category",
                "verbose_name_plural": "Content Categories",
            },
        ),
        migrations.CreateModel(
            name="ContentEquipmentCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("AMMO", "Ammo"),
                            ("ARMOR", "Armor"),
                            ("BASIC_WEAPONS", "Basic Weapons"),
                            ("BIONICS", "Bionics"),
                            ("BODY_UPGRADES", "Body Upgrades"),
                            ("CHEMS", "Chems"),
                            ("CLOSE_COMBAT", "Close Combat"),
                            ("DRIVE_UPGRADES", "Drive Upgrades"),
                            ("ENGINE_UPGRADES", "Engine Upgrades"),
                            ("EQUIPMENT", "Equipment"),
                            ("GRENADES", "Grenades"),
                            ("HARDPOINT_UPGRADES", "Hardpoint Upgrades"),
                            ("HEAVY_WEAPONS", "Heavy Weapons"),
                            ("MOUNTS", "Mounts"),
                            ("PISTOLS", "Pistols"),
                            ("SPECIAL_WEAPONS", "Special Weapons"),
                            ("STATUS_ITEMS", "Status Items"),
                            ("VEHICLE_EQUIPMENT", "Vehicle Equipment"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Equipment Category",
                "verbose_name_plural": "Content Equipment Categories",
            },
        ),
        migrations.CreateModel(
            name="ContentHouse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("VENATORS", "Venators"),
                            ("VAN_SAAR_HOA", "Van Saar (HoA)"),
                            ("VAN_SAAR_GOTU", "Van Saar (GotU)"),
                            ("SQUAT_PROSPECTORS", "Squat Prospectors"),
                            ("SLAVE_OGRYN", "Slave Ogryn"),
                            ("ORLOCK_HOI", "Orlock (HoI)"),
                            ("ORLOCK_GOTU", "Orlock (GotU)"),
                            ("GOLIATH_HOC", "Goliath (HoC)"),
                            ("GOLIATH_GOTU", "Goliath (GotU)"),
                            ("GENESTEALER_CULT", "Genestealer Cult"),
                            ("ESCHER_HOB", "Escher (HoB)"),
                            ("ESCHER_GOTU", "Escher (GotU)"),
                            ("ENFORCERS", "Enforcers"),
                            ("DELAQUE_HOS", "Delaque (HoS)"),
                            ("DELAQUE_GOTU", "Delaque (GotU)"),
                            ("CORPSE_GRINDER_CULT", "Corpse Grinder Cult"),
                            ("CHAOS_CULT", "Chaos Cult"),
                            ("CAWDOR_HOF", "Cawdor (HoF)"),
                            ("CAWDOR_GOTU", "Cawdor (GotU)"),
                            ("ASH_WASTE_NOMADS", "Ash Waste Nomads"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content House",
                "verbose_name_plural": "Content Houses",
            },
        ),
        migrations.CreateModel(
            name="ContentImportVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                (
                    "ruleset",
                    models.CharField(default="necromunda-2018", max_length=255),
                ),
                ("directory", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Content Import Version",
                "verbose_name_plural": "Content Import Versions",
            },
        ),
        migrations.CreateModel(
            name="ContentEquipment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentequipmentcategory",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentimportversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Equipment",
                "verbose_name_plural": "Content Equipment",
            },
        ),
        migrations.CreateModel(
            name="ContentFighter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                ("type", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Fighter",
                "verbose_name_plural": "Content Fighters",
            },
        ),
        migrations.CreateModel(
            name="ContentFighterEquipmentAssignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                ("qty", models.IntegerField(default=0)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentequipment",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentfighter",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentimportversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Fighter Equipment Assignment",
                "verbose_name_plural": "Content Fighter Equipment Assignments",
                "unique_together": {("fighter", "equipment")},
            },
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="equipment",
            field=models.ManyToManyField(
                through="content.ContentFighterEquipmentAssignment",
                to="content.contentequipment",
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contenthouse",
            ),
        ),
        migrations.AddField(
            model_name="contenthouse",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentimportversion",
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentimportversion",
            ),
        ),
        migrations.AddField(
            model_name="contentequipmentcategory",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentimportversion",
            ),
        ),
        migrations.AddField(
            model_name="contentcategory",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentimportversion",
            ),
        ),
        migrations.CreateModel(
            name="ContentPolicy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                ("rules", models.JSONField()),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentfighter",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentimportversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Policy",
                "verbose_name_plural": "Content Policies",
            },
        ),
        migrations.CreateModel(
            name="ContentSkill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(default="None", max_length=255)),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentimportversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Skill",
                "verbose_name_plural": "Content Skills",
            },
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="skills",
            field=models.ManyToManyField(to="content.contentskill"),
        ),
        migrations.CreateModel(
            name="ContentFighterEquipment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(db_index=True, editable=False)),
                ("cost", models.IntegerField(default=0)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentequipment",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentfighter",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentimportversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Fighter Equipment List",
                "verbose_name_plural": "Content Fighter Equipment Lists",
                "unique_together": {("fighter", "equipment")},
            },
        ),
    ]
