# Generated by Django 5.1.2 on 2024-11-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenthouse",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalcontenthouse",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
