# Generated by Django 5.1.2 on 2024-11-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_contentcategory_id_alter_contentequipment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipment",
            name="trading_post_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="base_cost",
            field=models.IntegerField(default=0),
        ),
    ]
