# Generated by Django 5.1.2 on 2024-11-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_contenthouse_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcontentfighter",
            name="category",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="contentfighter",
            name="category",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                ],
                max_length=255,
            ),
        ),
        migrations.RemoveField(
            model_name="historicalcontentcategory",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="ContentCategory",
        ),
        migrations.DeleteModel(
            name="HistoricalContentCategory",
        ),
    ]
