# Generated by Django 5.1.2 on 2024-11-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_historicalcontentfighter_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentfighter",
            name="skills",
            field=models.ManyToManyField(blank=True, to="content.contentskill"),
        ),
    ]
