# Generated by Django 5.1.2 on 2024-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_contentequipment_trading_post_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentcategory",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contentfighterequipment",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contenthouse",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contentequipment",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contentfighterequipmentassignment",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contentpolicy",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contentequipmentcategory",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contentskill",
            name="version",
        ),
        migrations.RemoveField(
            model_name="contentcategory",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contentequipment",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contentequipmentcategory",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contentfighter",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contentfighterequipment",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contentfighterequipmentassignment",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contenthouse",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contentpolicy",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contentskill",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="contentcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                    ("PROSPECT", "Prospect"),
                ],
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="ContentImportVersion",
        ),
    ]
