# Generated by Django 5.1.2 on 2024-11-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_alter_contentequipment_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipment",
            name="trading_post_available",
            field=models.BooleanField(
                default=False,
                help_text="Is the equipment available at the Trading Post?",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentequipment",
            name="trading_post_available",
            field=models.BooleanField(
                default=False,
                help_text="Is the equipment available at the Trading Post?",
            ),
        ),
        migrations.AlterField(
            model_name="contentequipment",
            name="trading_post_cost",
            field=models.IntegerField(
                blank=True,
                help_text="The cost of the equipment at the Trading Post.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipment",
            name="trading_post_cost",
            field=models.IntegerField(
                blank=True,
                help_text="The cost of the equipment at the Trading Post.",
                null=True,
            ),
        ),
    ]
