# Generated by Django 5.1.2 on 2024-11-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_contentweaponprofile_contentweapontrait_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipment",
            name="cost",
            field=models.CharField(
                blank=True,
                help_text="The credit cost of the equipment at the Trading Post. Note that, in weapons, this is overridden by the default weapon profile cost.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentequipment",
            name="cost",
            field=models.CharField(
                blank=True,
                help_text="The credit cost of the equipment at the Trading Post. Note that, in weapons, this is overridden by the default weapon profile cost.",
            ),
        ),
        migrations.AlterField(
            model_name="contentequipment",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipment",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                max_length=1,
            ),
        ),
    ]
