# Generated by Django 5.1.2 on 2024-11-24 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_contentequipment_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentequipment",
            name="weapon_profiles",
        ),
        migrations.RemoveField(
            model_name="historicalcontentweaponprofileassignment",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="historicalcontentweaponprofileassignment",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcontentweaponprofileassignment",
            name="profile",
        ),
        migrations.AddField(
            model_name="contentweaponprofile",
            name="cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contentweaponprofile",
            name="equipment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentequipment",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentweaponprofile",
            name="cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalcontentweaponprofile",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentequipment",
            ),
        ),
        migrations.DeleteModel(
            name="ContentWeaponProfileAssignment",
        ),
        migrations.DeleteModel(
            name="HistoricalContentWeaponProfileAssignment",
        ),
    ]
