# Generated by Django 5.1.2 on 2024-11-24 17:56

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_remove_contentequipment_weapon_profiles_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcontentfighterequipment",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighterequipment",
            name="fighter",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighterequipment",
            name="history_user",
        ),
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="cost",
            field=models.IntegerField(
                default=0,
                help_text="The credit cost of the weapon profile at the Trading Post. If the cost is zero, then the profile is free to use and standard. Note that this can be overridden in a fighter's equipment list.",
            ),
        ),
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponprofile",
            name="cost",
            field=models.IntegerField(
                default=0,
                help_text="The credit cost of the weapon profile at the Trading Post. If the cost is zero, then the profile is free to use and standard. Note that this can be overridden in a fighter's equipment list.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponprofile",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="ContentFighterEquipmentListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("cost", models.IntegerField(default=0)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentequipment",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentfighter",
                    ),
                ),
                (
                    "weapon_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="The weapon profile to use for this equipment list item.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentweaponprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Fighter Equipment List Item",
                "verbose_name_plural": "Content Fighter Equipment List Items",
                "unique_together": {("fighter", "equipment")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentFighterEquipmentListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("cost", models.IntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipment",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentfighter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weapon_profile",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The weapon profile to use for this equipment list item.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentweaponprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Content Fighter Equipment List Item",
                "verbose_name_plural": "historical Content Fighter Equipment List Items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="ContentFighterEquipment",
        ),
        migrations.DeleteModel(
            name="HistoricalContentFighterEquipment",
        ),
    ]
