# Generated by Django 5.1.2 on 2024-11-24 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_remove_historicalcontentfighterequipment_equipment_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentfighterequipmentlistitem",
            unique_together={("fighter", "equipment", "weapon_profile")},
        ),
    ]
