# Generated by Django 5.1.2 on 2024-11-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_alter_contentfighterequipmentlistitem_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentfighter",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighterequipmentassignment",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighterequipmentassignment",
            name="fighter",
        ),
        migrations.RemoveField(
            model_name="historicalcontentfighterequipmentassignment",
            name="history_user",
        ),
        migrations.AlterModelOptions(
            name="contentequipment",
            options={"verbose_name": "Equipment", "verbose_name_plural": "Equipment"},
        ),
        migrations.AlterModelOptions(
            name="contentfighter",
            options={"verbose_name": "Fighter", "verbose_name_plural": "Fighters"},
        ),
        migrations.AlterModelOptions(
            name="contentfighterequipmentlistitem",
            options={
                "verbose_name": "Equipment List Item",
                "verbose_name_plural": "Equipment List Items",
            },
        ),
        migrations.AlterModelOptions(
            name="contenthouse",
            options={"verbose_name": "House", "verbose_name_plural": "Houses"},
        ),
        migrations.AlterModelOptions(
            name="contentpolicy",
            options={"verbose_name": "Policy", "verbose_name_plural": "Policies"},
        ),
        migrations.AlterModelOptions(
            name="contentskill",
            options={"verbose_name": "Skill", "verbose_name_plural": "Skills"},
        ),
        migrations.AlterModelOptions(
            name="contentweaponprofile",
            options={
                "verbose_name": "Weapon Profile",
                "verbose_name_plural": "Weapon Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="contentweapontrait",
            options={
                "verbose_name": "Weapon Trait",
                "verbose_name_plural": "Weapon Traits",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentequipment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Equipment",
                "verbose_name_plural": "historical Equipment",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentfighter",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Fighter",
                "verbose_name_plural": "historical Fighters",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentfighterequipmentlistitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Equipment List Item",
                "verbose_name_plural": "historical Equipment List Items",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontenthouse",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical House",
                "verbose_name_plural": "historical Houses",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentpolicy",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Policy",
                "verbose_name_plural": "historical Policies",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentskill",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Skill",
                "verbose_name_plural": "historical Skills",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentweaponprofile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Weapon Profile",
                "verbose_name_plural": "historical Weapon Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentweapontrait",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Weapon Trait",
                "verbose_name_plural": "historical Weapon Traits",
            },
        ),
        migrations.AddField(
            model_name="contentweaponprofile",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="contentweaponprofile",
            name="rarity_roll",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontentweaponprofile",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentweaponprofile",
            name="rarity_roll",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ContentFighterEquipmentAssignment",
        ),
        migrations.DeleteModel(
            name="HistoricalContentFighterEquipmentAssignment",
        ),
    ]
