# Generated by Django 5.1.2 on 2024-11-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_remove_contentfighter_equipment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentweaponprofile",
            old_name="Acc L",
            new_name="accuracy_long",
        ),
        migrations.RenameField(
            model_name="contentweaponprofile",
            old_name="Acc S",
            new_name="accuracy_short",
        ),
        migrations.RenameField(
            model_name="contentweaponprofile", old_name="Am", new_name="ammo"
        ),
        migrations.RenameField(
            model_name="contentweaponprofile", old_name="Ap", new_name="armour_piercing"
        ),
        migrations.RenameField(
            model_name="contentweaponprofile", old_name="D", new_name="damage"
        ),
        migrations.RenameField(
            model_name="contentweaponprofile", old_name="Rng L", new_name="range_long"
        ),
        migrations.RenameField(
            model_name="contentweaponprofile", old_name="Rng S", new_name="range_short"
        ),
        migrations.RenameField(
            model_name="contentweaponprofile", old_name="Str", new_name="strength"
        ),
        migrations.RenameField(
            model_name="historicalcontentweaponprofile",
            old_name="Acc L",
            new_name="accuracy_long",
        ),
        migrations.RenameField(
            model_name="historicalcontentweaponprofile",
            old_name="Acc S",
            new_name="accuracy_short",
        ),
        migrations.RenameField(
            model_name="historicalcontentweaponprofile", old_name="Am", new_name="ammo"
        ),
        migrations.RenameField(
            model_name="historicalcontentweaponprofile",
            old_name="Ap",
            new_name="armour_piercing",
        ),
        migrations.RenameField(
            model_name="historicalcontentweaponprofile", old_name="D", new_name="damage"
        ),
        migrations.RenameField(
            model_name="historicalcontentweaponprofile",
            old_name="Rng L",
            new_name="range_long",
        ),
        migrations.RenameField(
            model_name="historicalcontentweaponprofile",
            old_name="Rng S",
            new_name="range_short",
        ),
        migrations.RenameField(
            model_name="historicalcontentweaponprofile",
            old_name="Str",
            new_name="strength",
        ),
        migrations.AlterField(
            model_name="contentequipment",
            name="cost",
            field=models.CharField(
                blank=True,
                help_text="The credit cost of the equipment at the Trading Post. Note that, in weapons, this is overridden by the 'Standard' weapon profile cost.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipment",
            name="cost",
            field=models.CharField(
                blank=True,
                help_text="The credit cost of the equipment at the Trading Post. Note that, in weapons, this is overridden by the 'Standard' weapon profile cost.",
            ),
        ),
    ]
