# Generated by Django 5.1.2 on 2024-11-24 21:50

from django.db import migrations

from gyrinx.models import EquipmentCategoryChoices


def create_example_weapons_profiles(apps, schema_editor):
    ContentEquipment = apps.get_model("content", "ContentEquipment")
    ContentWeaponProfile = apps.get_model("content", "ContentWeaponProfile")
    ContentWeaponTrait = apps.get_model("content", "ContentWeaponTrait")

    t_blaze = ContentWeaponTrait.objects.create(name="Blaze")
    t_rapid_fire = ContentWeaponTrait.objects.create(name="Rapid Fire (1)")
    t_shock = ContentWeaponTrait.objects.create(name="Shock")
    t_blaze.save()
    t_rapid_fire.save()
    t_shock.save()

    arc_rifle = ContentEquipment.objects.create(
        name="Arc rifle", category=EquipmentCategoryChoices.BASIC_WEAPONS
    )
    arc_rifle_profile = ContentWeaponProfile.objects.create(
        equipment=arc_rifle,
        name="",
        cost=100,
        cost_sign="",
        rarity="R",
        rarity_roll=13,
        range_short='9"',
        range_long='24"',
        accuracy_short="+2",
        accuracy_long="-1",
        strength="5",
        armour_piercing="",
        damage="1",
        ammo="6+",
    )
    arc_rifle_profile.traits.set([t_blaze, t_rapid_fire, t_shock])

    arc_rifle.save()
    arc_rifle_profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_contentweaponprofile_cost_sign_and_more"),
    ]

    operations = [migrations.RunPython(create_example_weapons_profiles)]
