# Generated by Django 5.1.2 on 2024-11-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_auto_20241124_2150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentweapontrait",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalcontentweapontrait",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
