# Generated by Django 5.1.2 on 2024-11-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_alter_contentweapontrait_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="cost_sign",
            field=models.CharField(
                blank=True, choices=[("+", "+")], default="", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponprofile",
            name="cost_sign",
            field=models.CharField(
                blank=True, choices=[("+", "+")], default="", max_length=1
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentequipment",
            unique_together={("name", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="contentweaponprofile",
            unique_together={("equipment", "name")},
        ),
    ]
