# Generated by Django 5.1.2 on 2024-11-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_auto_20241127_1840"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfighter",
            name="attacks",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="A"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="ballistic_skill",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="BS"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="cool",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Cl"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="initiative",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="I"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="intelligence",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Int"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="leadership",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Ld"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="movement",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="M"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="strength",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="S"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="toughness",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="T"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="weapon_skill",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="WS"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="willpower",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Wil"
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="wounds",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="W"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="attacks",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="A"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="ballistic_skill",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="BS"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="cool",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Cl"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="initiative",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="I"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="intelligence",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Int"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="leadership",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Ld"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="movement",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="M"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="strength",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="S"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="toughness",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="T"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="weapon_skill",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="WS"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="willpower",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Wil"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="wounds",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="W"
            ),
        ),
    ]
