# Generated by Django 5.1.2 on 2024-11-27 20:57

from django.db import migrations

from gyrinx.content.models import ContentRule as ContentRuleModel


def do_migration(apps, schema_editor):
    ContentRule: type[ContentRuleModel] = apps.get_model("content", "ContentRule")

    rules = [
        "Gang Leader",
        "Gang Hierarchy (Leader)",
        "Gang Hierarchy (Champion)",
        "Gang Fighter (Ganger)",
        "Gang Fighter (Juve)",
        "Gang Fighter (Crew)",
        "Promotion (Specialist)",
        "Tools of the Trade",
        "Tools of the Trade (Specialist only)",
        "Group Activation (1)",
        "Group Activation (2)",
        "Fast Learner",
        "Vehicle Crew",
    ]

    for rule in rules:
        ContentRule.objects.get_or_create(name=rule)


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_contentrule_contentfighter_rules_and_more"),
    ]

    operations = [migrations.RunPython(do_migration, elidable=True)]
