# Generated by Django 5.1.2 on 2024-12-01 16:18

from django.db import migrations

from gyrinx.models import EquipmentCategoryChoices


def do_migration(apps, schema_editor):
    """Fix the costs of the Arc rifle and its profile."""
    ContentEquipment = apps.get_model("content", "ContentEquipment")
    ContentWeaponProfile = apps.get_model("content", "ContentWeaponProfile")

    arc_rifle = ContentEquipment.objects.get(
        name="Arc rifle",
        category=EquipmentCategoryChoices.BASIC_WEAPONS,
    )
    arc_rifle.cost = 100

    profile = ContentWeaponProfile.objects.get(equipment=arc_rifle, name="")
    profile.cost = 0

    arc_rifle.save()
    profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0023_auto_20241201_0940"),
    ]

    operations = [migrations.RunPython(do_migration)]
    operations = [migrations.RunPython(do_migration)]
