# Generated by Django 5.1.2 on 2024-12-03 20:49

import json
from pathlib import Path

from django.db import migrations

from gyrinx.content.models import ContentSkill as ContentSkillModel


def do_migration(apps, schema_editor):
    ContentSkill: type[ContentSkillModel] = apps.get_model("content", "ContentSkill")

    # Resolve the content folder relative to this file
    root = Path(__file__).parent / "../../../content/exports"
    top_skills_path = root / "top_skills.json"
    with open(top_skills_path, "r") as file:
        top_skills = json.load(file)

    for skill in top_skills:
        if int(skill.get("skill_count", 0)) > 500:
            _, created = ContentSkill.objects.get_or_create(name=skill["skill"])
            if created:
                print(f"Created {skill['skill']}")


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_auto_20241201_1618"),
    ]

    operations = [migrations.RunPython(do_migration)]
