# Generated by Django 5.1.4 on 2024-12-12 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0026_contentbook_alter_contentequipment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentpageref",
            options={
                "ordering": ["category", "book__name", "title"],
                "verbose_name": "Page Reference",
                "verbose_name_plural": "Page References",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentpageref",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Page Reference",
                "verbose_name_plural": "historical Page References",
            },
        ),
    ]
