# Generated by Django 5.1.4 on 2024-12-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0027_alter_contentpageref_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpageref",
            name="page",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalcontentpageref",
            name="page",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
