# Generated by Django 5.1.4 on 2025-01-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0028_alter_contentpageref_page_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentfighter",
            options={
                "ordering": [
                    "house__name",
                    models.Case(
                        models.When(category="LEADER", then=0),
                        models.When(category="CHAMPION", then=1),
                        models.When(category="PROSPECT", then=2),
                        models.When(category="SPECIALIST", then=3),
                        models.When(category="GANGER", then=4),
                        models.When(category="JUVE", then=5),
                        default=99,
                    ),
                    "type",
                ],
                "verbose_name": "Fighter",
                "verbose_name_plural": "Fighters",
            },
        ),
        migrations.AlterModelOptions(
            name="contentweaponprofile",
            options={
                "ordering": [
                    "equipment__name",
                    models.Case(models.When(name="", then=0), default=99),
                ],
                "verbose_name": "Weapon Profile",
                "verbose_name_plural": "Weapon Profiles",
            },
        ),
    ]
