# Generated by Django 5.1.4 on 2025-01-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0029_alter_contentfighter_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentweaponprofile",
            options={
                "ordering": [
                    "equipment__name",
                    models.Case(models.When(name="", then=0), default=99),
                    "cost",
                ],
                "verbose_name": "Weapon Profile",
                "verbose_name_plural": "Weapon Profiles",
            },
        ),
    ]
