# Generated by Django 5.1.4 on 2025-01-03 09:35

from django.db import migrations


def do_migration(apps, schema_editor):
    ContentWeaponProfile = apps.get_model("content", "ContentWeaponProfile")
    ContentEquipment = apps.get_model("content", "ContentEquipment")

    ContentWeaponProfile.objects.filter(name="(Standard)").update(name="")
    ContentEquipment.objects.filter(cost="-").update(cost="")


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0030_alter_contentweaponprofile_options"),
    ]

    operations = [
        migrations.RunPython(do_migration, migrations.RunPython.noop, elidable=True),
    ]
