# Generated by Django 5.1.4 on 2025-01-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0031_auto_20250103_0935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="cost",
            field=models.IntegerField(
                default=0,
                help_text="The credit cost of the weapon profile at the Trading Post. If the cost is zero, then the profile is free to use and standard. This cost is overridden if the profile is in the fighter's equipment list.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponprofile",
            name="cost",
            field=models.IntegerField(
                default=0,
                help_text="The credit cost of the weapon profile at the Trading Post. If the cost is zero, then the profile is free to use and standard. This cost is overridden if the profile is in the fighter's equipment list.",
            ),
        ),
    ]
