# Generated by Django 5.1.4 on 2025-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0033_alter_contentequipment_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentequipment",
            name="category",
            field=models.CharField(
                choices=[
                    ("AMMO", "Ammo"),
                    ("ARMOR", "Armor"),
                    ("BASIC_WEAPONS", "Basic Weapons"),
                    ("BIONICS", "Bionics"),
                    ("BODY_UPGRADES", "Body Upgrades"),
                    ("CHEMS", "Chems"),
                    ("CLOSE_COMBAT", "Close Combat Weapons"),
                    ("DRIVE_UPGRADES", "Drive Upgrades"),
                    ("ENGINE_UPGRADES", "Engine Upgrades"),
                    ("EQUIPMENT", "Equipment"),
                    ("GRENADES", "Grenades"),
                    ("HARDPOINT_UPGRADES", "Hardpoint Upgrades"),
                    ("HEAVY_WEAPONS", "Heavy Weapons"),
                    ("MOUNTS", "Mounts"),
                    ("PISTOLS", "Pistols"),
                    ("SPECIAL_WEAPONS", "Special Weapons"),
                    ("STATUS_ITEMS", "Status Items"),
                    ("VEHICLE_EQUIPMENT", "Vehicle Equipment"),
                    ("BOOBY_TRAPS", "Booby Traps"),
                    ("GANG_TERRAIN", "Gang Terrain"),
                    ("CHEM_ALCHEMY_ELIXIRS", "Chem-alchemy Elixirs"),
                    ("GENE_SMITHING", "Gene-smithing"),
                    ("CYBERTEKNIKA", "Cyberteknika"),
                    ("FIELD_ARMOUR", "Field Armour"),
                    ("PERSONAL_EQUIPMENT", "Personal Equipment"),
                    ("GANG_EQUIPMENT", "Gang Equipment"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipment",
            name="category",
            field=models.CharField(
                choices=[
                    ("AMMO", "Ammo"),
                    ("ARMOR", "Armor"),
                    ("BASIC_WEAPONS", "Basic Weapons"),
                    ("BIONICS", "Bionics"),
                    ("BODY_UPGRADES", "Body Upgrades"),
                    ("CHEMS", "Chems"),
                    ("CLOSE_COMBAT", "Close Combat Weapons"),
                    ("DRIVE_UPGRADES", "Drive Upgrades"),
                    ("ENGINE_UPGRADES", "Engine Upgrades"),
                    ("EQUIPMENT", "Equipment"),
                    ("GRENADES", "Grenades"),
                    ("HARDPOINT_UPGRADES", "Hardpoint Upgrades"),
                    ("HEAVY_WEAPONS", "Heavy Weapons"),
                    ("MOUNTS", "Mounts"),
                    ("PISTOLS", "Pistols"),
                    ("SPECIAL_WEAPONS", "Special Weapons"),
                    ("STATUS_ITEMS", "Status Items"),
                    ("VEHICLE_EQUIPMENT", "Vehicle Equipment"),
                    ("BOOBY_TRAPS", "Booby Traps"),
                    ("GANG_TERRAIN", "Gang Terrain"),
                    ("CHEM_ALCHEMY_ELIXIRS", "Chem-alchemy Elixirs"),
                    ("GENE_SMITHING", "Gene-smithing"),
                    ("CYBERTEKNIKA", "Cyberteknika"),
                    ("FIELD_ARMOUR", "Field Armour"),
                    ("PERSONAL_EQUIPMENT", "Personal Equipment"),
                    ("GANG_EQUIPMENT", "Gang Equipment"),
                ],
                max_length=255,
            ),
        ),
    ]
