# Generated by Django 5.1.4 on 2025-01-05 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0036_alter_contentequipment_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentfighterdefaultassignment",
            name="weapon_profiles",
        ),
    ]
