# Generated by Django 5.1.4 on 2025-01-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0038_contentfighterdefaultassignment_weapon_profiles_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="cost",
            field=models.IntegerField(
                default=0,
                help_text="The credit cost of the weapon profile at the Trading Post. If the cost is zero, then the profile is free to use and standard. This cost can be overridden by the fighter's equipment list.",
            ),
        ),
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Leave blank if the profile has no name (i.e. is the default statline). Don't include the hyphen for named profiles.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this profile from the Trading Post.",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponprofile",
            name="cost",
            field=models.IntegerField(
                default=0,
                help_text="The credit cost of the weapon profile at the Trading Post. If the cost is zero, then the profile is free to use and standard. This cost can be overridden by the fighter's equipment list.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponprofile",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Leave blank if the profile has no name (i.e. is the default statline). Don't include the hyphen for named profiles.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponprofile",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this profile from the Trading Post.",
                max_length=1,
            ),
        ),
    ]
