# Generated by Django 5.1.4 on 2025-01-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0039_alter_contentweaponprofile_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentequipment",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this equipment from the Trading Post.",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipment",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this equipment from the Trading Post.",
                max_length=1,
            ),
        ),
    ]
