# Generated by Django 5.1.4 on 2025-01-14 21:06

from pathlib import Path

import yaml
from django.db import migrations

from gyrinx.content.models import ContentSkill as ContentSkillModel


def do_migration(apps, schema_editor):
    ContentSkill: type[ContentSkillModel] = apps.get_model("content", "ContentSkill")

    # Resolve the content folder relative to this file
    root = Path(__file__).parent / "../../../content/necromunda-2018"
    skill_path = root / "data" / "skill.yaml"
    with open(skill_path, "r") as file:
        skills = yaml.load(file, Loader=yaml.SafeLoader)

    for skill in skills["skill"]:
        if "type" in skill and skill["type"] == "Skill":
            qs = ContentSkill.objects.filter(name=skill["name"])
            qs.update(
                category=skill.get("category", ""),
            )

    # Find all skills with category == "None" and delete
    ContentSkill.objects.filter(category="None").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0040_alter_contentequipment_rarity_and_more"),
    ]

    operations = [migrations.RunPython(do_migration, migrations.RunPython.noop)]
