# Generated by Django 5.1.4 on 2025-01-14 21:23

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0041_auto_20250114_2106"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSkillCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="contentequipment",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this equipment from the Trading Post.",
                max_length=1,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="contentequipment",
            name="rarity_roll",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Availability Level"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipment",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this equipment from the Trading Post.",
                max_length=1,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipment",
            name="rarity_roll",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Availability Level"
            ),
        ),
        migrations.AddField(
            model_name="contenthouse",
            name="skill_categories",
            field=models.ManyToManyField(
                blank=True, related_name="houses", to="content.contentskillcategory"
            ),
        ),
        migrations.AddField(
            model_name="contentskill",
            name="category_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skills",
                to="content.contentskillcategory",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentskill",
            name="category_obj",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentskillcategory",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalContentSkillCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Skill Category",
                "verbose_name_plural": "historical Skill Categories",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
