# Generated by Django 5.1.4 on 2025-01-14 21:24


from django.db import migrations

from gyrinx.content.models import ContentSkill as ContentSkillModel
from gyrinx.content.models import ContentSkillCategory as ContentSkillCategoryModel


def do_migration(apps, schema_editor):
    ContentSkill: type[ContentSkillModel] = apps.get_model("content", "ContentSkill")
    ContentSkillCategory: type[ContentSkillCategoryModel] = apps.get_model(
        "content", "ContentSkillCategory"
    )

    skill_categories = set(
        ContentSkill.objects.all().values_list("category", flat=True)
    )
    ContentSkillCategory.objects.bulk_create(
        ContentSkillCategory(name=category) for category in skill_categories
    )


def undo_migration(apps, schema_editor):
    ContentSkillCategory: type[ContentSkillCategoryModel] = apps.get_model(
        "content", "ContentSkillCategory"
    )
    ContentSkillCategory.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0042_contentskillcategory_alter_contentequipment_rarity_and_more"),
    ]

    operations = [migrations.RunPython(do_migration, undo_migration)]
