# Generated by Django 5.1.4 on 2025-01-14 21:27

from django.db import migrations

from gyrinx.content.models import ContentSkill as ContentSkillModel
from gyrinx.content.models import ContentSkillCategory as ContentSkillCategoryModel


def do_migration(apps, schema_editor):
    ContentSkill: type[ContentSkillModel] = apps.get_model("content", "ContentSkill")
    ContentSkillCategory: type[ContentSkillCategoryModel] = apps.get_model(
        "content", "ContentSkillCategory"
    )

    for skill in ContentSkill.objects.all():
        category_obj = ContentSkillCategory.objects.get(name=skill.category)
        skill.category_obj = category_obj
        skill.save()


def undo_migration(apps, schema_editor):
    ContentSkill: type[ContentSkillModel] = apps.get_model("content", "ContentSkill")

    for skill in ContentSkill.objects.all():
        skill.category_obj = None
        skill.save()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0043_auto_20250114_2124"),
    ]

    operations = [migrations.RunPython(do_migration, undo_migration, elidable=True)]
