# Generated by Django 5.1.4 on 2025-01-14 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0044_auto_20250114_2127"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentskill",
            name="category",
        ),
        migrations.RemoveField(
            model_name="historicalcontentskill",
            name="category",
        ),
    ]
