# Generated by Django 5.1.4 on 2025-01-14 21:35

import django.db.models.deletion
from django.db import migrations, models

from gyrinx.content.models import ContentSkill as ContentSkillModel


def do_migration(apps, schema_editor):
    ContentSkill: type[ContentSkillModel] = apps.get_model("content", "ContentSkill")

    if ContentSkill.objects.filter(category_obj=None).exists():
        raise ValueError("Some ContentSkill objects have no category_obj")


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0045_remove_contentskill_category_and_more"),
    ]

    operations = [
        migrations.RunPython(do_migration),
        migrations.AlterField(
            model_name="contentskill",
            name="category_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="content.contentskillcategory",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentskill",
            name="category_obj",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentskillcategory",
                verbose_name="category",
            ),
        ),
    ]
