# Generated by Django 5.1.4 on 2025-01-14 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0046_alter_contentskill_category_obj_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentskill",
            old_name="category_obj",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="historicalcontentskill",
            old_name="category_obj",
            new_name="category",
        ),
    ]
