# Generated by Django 5.1.4 on 2025-01-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0047_rename_category_obj_contentskill_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenthouse",
            name="skill_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="houses",
                to="content.contentskillcategory",
                verbose_name="Unique Skill Categories",
            ),
        ),
    ]
