# Generated by Django 5.1.4 on 2025-01-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0048_alter_contenthouse_skill_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfighter",
            name="primary_skill_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="primary_fighters",
                to="content.contentskillcategory",
                verbose_name="Primary Skill Categories",
            ),
        ),
        migrations.AddField(
            model_name="contentfighter",
            name="secondary_skill_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="secondary_fighters",
                to="content.contentskillcategory",
                verbose_name="Secondary Skill Categories",
            ),
        ),
        migrations.AlterField(
            model_name="contentfighter",
            name="skills",
            field=models.ManyToManyField(
                blank=True, to="content.contentskill", verbose_name="Default Skills"
            ),
        ),
    ]
