# Generated by Django 5.1.5 on 2025-01-18 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0051_alter_contentfighter_primary_skill_categories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentskill",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
    ]
