# Generated by Django 5.1.5 on 2025-01-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0053_contentweaponaccessory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfighterdefaultassignment",
            name="weapon_accessories_field",
            field=models.ManyToManyField(
                blank=True, to="content.contentweaponaccessory"
            ),
        ),
    ]
