# Generated by Django 5.1.5 on 2025-01-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0054_contentfighterdefaultassignment_weapon_accessories_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentweaponaccessory",
            name="cost",
            field=models.IntegerField(
                default=0,
                help_text="The credit cost of the weapon accessory at the Trading Post. This cost can be overridden by the fighter's equipment list.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentweaponaccessory",
            name="cost",
            field=models.IntegerField(
                default=0,
                help_text="The credit cost of the weapon accessory at the Trading Post. This cost can be overridden by the fighter's equipment list.",
            ),
        ),
    ]
