# Generated by Django 5.1.5 on 2025-01-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0056_historicalcontentfighterequipmentlistweaponaccessory_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contentweaponaccessory",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this profile from the Trading Post.",
                max_length=1,
                verbose_name="Availability",
            ),
        ),
        migrations.AddField(
            model_name="contentweaponaccessory",
            name="rarity_roll",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Availability Level"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentweaponaccessory",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this profile from the Trading Post.",
                max_length=1,
                verbose_name="Availability",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentweaponaccessory",
            name="rarity_roll",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Availability Level"
            ),
        ),
    ]
