# Generated by Django 5.1.5 on 2025-01-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0058_alter_contentequipment_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentequipment",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "Gear",
                        [
                            ("ARMOR", "Armor"),
                            ("BIONICS", "Bionics"),
                            ("BODY_UPGRADES", "Body Upgrades"),
                            ("BOOBY_TRAPS", "Booby Traps"),
                            ("CHEM_ALCHEMY_ELIXIRS", "Chem-alchemy Elixirs"),
                            ("CHEMS", "Chems"),
                            ("CYBERTEKNIKA", "Cyberteknika"),
                            ("EQUIPMENT", "Personal Equipment"),
                            ("FIELD_ARMOUR", "Field Armour"),
                            ("GANG_EQUIPMENT", "Gang Equipment"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                            ("GENE_SMITHING", "Gene-smithing"),
                            ("RELICS", "Relics"),
                            ("STATUS_ITEMS", "Status Items"),
                        ],
                    ),
                    (
                        "Vehicle & Mount",
                        [
                            ("DRIVE_UPGRADES", "Drive Upgrades"),
                            ("ENGINE_UPGRADES", "Engine Upgrades"),
                            ("HARDPOINT_UPGRADES", "Hardpoint Upgrades"),
                            ("MOUNTS", "Mounts"),
                            ("VEHICLE_EQUIPMENT", "Vehicle Wargear"),
                            ("VEHICLES", "Vehicles"),
                        ],
                    ),
                    (
                        "Weapons & Ammo",
                        [
                            ("AMMO", "Ammo"),
                            ("BASIC_WEAPONS", "Basic Weapons"),
                            ("CLOSE_COMBAT", "Close Combat Weapons"),
                            ("GRENADES", "Grenades"),
                            ("HEAVY_WEAPONS", "Heavy Weapons"),
                            ("PISTOLS", "Pistols"),
                            ("POWER_PACK_WEAPONS", "Power Pack Weapons"),
                            ("SPECIAL_WEAPONS", "Special Weapons"),
                        ],
                    ),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipment",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "Gear",
                        [
                            ("ARMOR", "Armor"),
                            ("BIONICS", "Bionics"),
                            ("BODY_UPGRADES", "Body Upgrades"),
                            ("BOOBY_TRAPS", "Booby Traps"),
                            ("CHEM_ALCHEMY_ELIXIRS", "Chem-alchemy Elixirs"),
                            ("CHEMS", "Chems"),
                            ("CYBERTEKNIKA", "Cyberteknika"),
                            ("EQUIPMENT", "Personal Equipment"),
                            ("FIELD_ARMOUR", "Field Armour"),
                            ("GANG_EQUIPMENT", "Gang Equipment"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                            ("GENE_SMITHING", "Gene-smithing"),
                            ("RELICS", "Relics"),
                            ("STATUS_ITEMS", "Status Items"),
                        ],
                    ),
                    (
                        "Vehicle & Mount",
                        [
                            ("DRIVE_UPGRADES", "Drive Upgrades"),
                            ("ENGINE_UPGRADES", "Engine Upgrades"),
                            ("HARDPOINT_UPGRADES", "Hardpoint Upgrades"),
                            ("MOUNTS", "Mounts"),
                            ("VEHICLE_EQUIPMENT", "Vehicle Wargear"),
                            ("VEHICLES", "Vehicles"),
                        ],
                    ),
                    (
                        "Weapons & Ammo",
                        [
                            ("AMMO", "Ammo"),
                            ("BASIC_WEAPONS", "Basic Weapons"),
                            ("CLOSE_COMBAT", "Close Combat Weapons"),
                            ("GRENADES", "Grenades"),
                            ("HEAVY_WEAPONS", "Heavy Weapons"),
                            ("PISTOLS", "Pistols"),
                            ("POWER_PACK_WEAPONS", "Power Pack Weapons"),
                            ("SPECIAL_WEAPONS", "Special Weapons"),
                        ],
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
