# Generated by Django 5.1.5 on 2025-01-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0059_alter_contentequipment_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this profile from the Trading Post.",
                max_length=1,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="rarity_roll",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Availability Level"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponprofile",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Rare (R)"),
                    ("I", "Illegal (I)"),
                    ("E", "Exclusive (E)"),
                    ("C", "Common (C)"),
                ],
                default="C",
                help_text="Use 'E' to exclude this profile from the Trading Post.",
                max_length=1,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentweaponprofile",
            name="rarity_roll",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Availability Level"
            ),
        ),
    ]
