# Generated by Django 5.1.5 on 2025-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0060_alter_contentweaponprofile_rarity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentfighter",
            options={"verbose_name": "Fighter", "verbose_name_plural": "Fighters"},
        ),
        migrations.AlterModelOptions(
            name="contentweaponprofile",
            options={
                "verbose_name": "Weapon Profile",
                "verbose_name_plural": "Weapon Profiles",
            },
        ),
        migrations.AddField(
            model_name="contenthouse",
            name="generic",
            field=models.BooleanField(
                default=False,
                help_text="If checked, fighters in this House can join lists and gangs of any other House.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontenthouse",
            name="generic",
            field=models.BooleanField(
                default=False,
                help_text="If checked, fighters in this House can join lists and gangs of any other House.",
            ),
        ),
    ]
