# Generated by Django 5.1.5 on 2025-01-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0062_alter_contentequipment_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentEquipmentFighterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentfighter",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentequipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipment-fighter link",
                "verbose_name_plural": "equipment-fighter links",
                "unique_together": {("equipment", "content_fighter")},
            },
        ),
    ]
