# Generated by Django 5.1.5 on 2025-01-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0063_contentequipmentfighterprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentequipmentfighterprofile",
            options={
                "verbose_name": "Equipment-Fighter Link",
                "verbose_name_plural": "Equipment-Fighter Links",
            },
        ),
        migrations.AlterField(
            model_name="contentequipmentfighterprofile",
            name="content_fighter",
            field=models.ForeignKey(
                help_text="This type of Fighter will be created when this Equipment is assigned",
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentfighter",
                verbose_name="Fighter",
            ),
        ),
        migrations.AlterField(
            model_name="contentequipmentfighterprofile",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentequipment",
                verbose_name="Equipment",
            ),
        ),
    ]
