# Generated by Django 5.1.5 on 2025-02-08 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0065_historicalcontentequipmentfighterprofile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentfighterdefaultassignment",
            unique_together=set(),
        ),
    ]
