# Generated by Django 5.1.5 on 2025-02-09 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0066_alter_contentfighterdefaultassignment_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentFighterHouseOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "cost",
                    models.IntegerField(
                        blank=True,
                        help_text="What should this Fighter cost when added to this House?",
                        null=True,
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_overrides",
                        to="content.contentfighter",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fighter_overrides",
                        to="content.contenthouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fighter-House Override",
                "verbose_name_plural": "Fighter-House Overrides",
                "ordering": ["house__name", "fighter__type"],
            },
        ),
    ]
