# Generated by Django 5.1.5 on 2025-02-10 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0067_contentfighterhouseoverride"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentfighterhouseoverride",
            unique_together={("fighter", "house")},
        ),
    ]
