# Generated by Django 5.1.5 on 2025-02-10 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0069_contentequipment_upgrade_stack_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentequipmentupgrade",
            unique_together={("equipment", "name")},
        ),
    ]
