# Generated by Django 5.1.5 on 2025-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0071_contenthouse_house_additional_rules_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenthouse",
            name="house_additional_rules_name",
            field=models.CharField(
                blank=True,
                help_text="If applicable, the name of the unique additional rules for this house (e.g. Legendary Name).",
                max_length=255,
                null=True,
                verbose_name="House Additional Rules Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontenthouse",
            name="house_additional_rules_name",
            field=models.CharField(
                blank=True,
                help_text="If applicable, the name of the unique additional rules for this house (e.g. Legendary Name).",
                max_length=255,
                null=True,
                verbose_name="House Additional Rules Type",
            ),
        ),
    ]
