# Generated by Django 5.1.5 on 2025-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0072_alter_contenthouse_house_additional_rules_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentequipmentupgrade",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipmentupgrade",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
