# Generated by Django 5.1.5 on 2025-02-14 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0073_alter_contentequipmentupgrade_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentweaponprofile",
            name="cost_sign",
        ),
        migrations.RemoveField(
            model_name="historicalcontentweaponprofile",
            name="cost_sign",
        ),
    ]
