# Generated by Django 5.1.6 on 2025-02-16 14:17

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0076_historicalcontentfighterpsykerpowerdefaultassignment_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentMod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modification",
                "verbose_name_plural": "Modifications",
            },
        ),
        migrations.AlterModelOptions(
            name="contentfighterdefaultassignment",
            options={
                "ordering": ["fighter__type", "equipment__name"],
                "verbose_name": "Default Equipment Assignment",
                "verbose_name_plural": "Default Equipment Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="contentfighterpsykerpowerdefaultassignment",
            options={
                "ordering": ["fighter__type", "psyker_power__name"],
                "verbose_name": "Psyker Fighter-Power Default Assignment",
                "verbose_name_plural": "Psyker Fighter-Power Default Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentfighterdefaultassignment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Default Equipment Assignment",
                "verbose_name_plural": "historical Default Equipment Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentfighterpsykerpowerdefaultassignment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Psyker Fighter-Power Default Assignment",
                "verbose_name_plural": "historical Psyker Fighter-Power Default Assignments",
            },
        ),
        migrations.CreateModel(
            name="ContentModStat",
            fields=[
                (
                    "contentmod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentmod",
                    ),
                ),
                ("stat", models.CharField(max_length=255)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("improve", "Improve"),
                            ("worsen", "Worsen"),
                            ("set", "Set"),
                        ],
                        max_length=255,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Stat Modifier",
                "verbose_name_plural": "Stat Modifiers",
                "ordering": ["stat"],
            },
            bases=("content.contentmod",),
        ),
        migrations.CreateModel(
            name="HistoricalContentMod",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Modification",
                "verbose_name_plural": "historical Modifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentModTrait",
            fields=[
                (
                    "contentmod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentmod",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("add", "Add"), ("remove", "Remove")], max_length=255
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_by",
                        to="content.contentweapontrait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trait Modifier",
                "verbose_name_plural": "Trait Modifiers",
                "ordering": ["trait__name", "mode"],
            },
            bases=("content.contentmod",),
        ),
    ]
