# Generated by Django 5.1.6 on 2025-02-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0078_contentweaponaccessory_modifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentmodstat",
            name="stat",
            field=models.CharField(
                choices=[
                    ("strength", "Strength"),
                    ("range_short", "Range (Short)"),
                    ("range_long", "Range (Long)"),
                    ("accuracy_short", "Accuracy (Short)"),
                    ("accuracy_long", "Accuracy (Long)"),
                    ("armour_piercing", "Armour Piercing"),
                    ("damage", "Damage"),
                    ("ammo", "Ammo"),
                ],
                max_length=255,
            ),
        ),
    ]
