# Generated by Django 5.1.6 on 2025-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0079_alter_contentmodstat_stat"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipmentupgrade",
            name="modifiers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Modifiers to apply to the equipment's statline and traits.",
                to="content.contentmod",
            ),
        ),
    ]
