# Generated by Django 5.2 on 2025-04-13 12:49

from django.db import migrations

from gyrinx.content.models import (
    ContentEquipmentCategory as ContentEquipmentCategoryModel,
)
from gyrinx.models import equipment_category_choices


def do_migration(apps, schema_editor):
    ContentEquipmentCategory: type[ContentEquipmentCategoryModel] = apps.get_model(
        "content", "ContentEquipmentCategory"
    )

    for group in equipment_category_choices.keys():
        for cat in equipment_category_choices[group].keys():
            name = equipment_category_choices[group][cat]
            category_obj = ContentEquipmentCategory.objects.create(
                name=name, group=group
            )
            category_obj.save()


def undo_migration(apps, schema_editor):
    ContentEquipmentCategory: type[ContentEquipmentCategoryModel] = apps.get_model(
        "content", "ContentEquipmentCategory"
    )

    for group in equipment_category_choices.keys():
        for cat in equipment_category_choices[group].keys():
            try:
                category_obj = ContentEquipmentCategory.objects.get(
                    name=cat, group=group
                )
                category_obj.delete()
            except ContentEquipmentCategory.DoesNotExist:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0082_contentequipmentcategory_and_more"),
    ]

    operations = [migrations.RunPython(do_migration, undo_migration, elidable=True)]
