# Generated by Django 5.2 on 2025-04-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0083_auto_20250413_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipment",
            name="category_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="content.contentequipmentcategory",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentequipment",
            name="category_obj",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentequipmentcategory",
            ),
        ),
    ]
