# Generated by Django 5.2 on 2025-04-13 12:56

from django.db import migrations

from gyrinx.content.models import ContentEquipment as ContentEquipmentModel
from gyrinx.content.models import (
    ContentEquipmentCategory as ContentEquipmentCategoryModel,
)
from gyrinx.models import equipment_category_choices_flat


def do_migration(apps, schema_editor):
    ContentEquipmentCategory: type[ContentEquipmentCategoryModel] = apps.get_model(
        "content", "ContentEquipmentCategory"
    )
    ContentEquipment: type[ContentEquipmentModel] = apps.get_model(
        "content", "ContentEquipment"
    )

    equipment_category_choices_flat_inverse = {
        v: k for k, v in equipment_category_choices_flat.items()
    }

    for category in ContentEquipmentCategory.objects.all():
        enum_value = equipment_category_choices_flat_inverse.get(category.name)
        ContentEquipment.objects.filter(category=enum_value).update(
            category_obj=category
        )


def undo_migration(apps, schema_editor):
    ContentEquipment: type[ContentEquipmentModel] = apps.get_model(
        "content", "ContentEquipment"
    )

    ContentEquipment.objects.update(category_obj=None)


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0084_contentequipment_category_obj_and_more"),
    ]

    operations = [migrations.RunPython(do_migration, undo_migration, elidable=True)]
