# Generated by Django 5.2 on 2025-04-13 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0085_auto_20250413_1256"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentequipment",
            unique_together={("name", "category_obj")},
        ),
    ]
