# Generated by Django 5.2 on 2025-04-13 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0086_alter_contentequipment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentequipment",
            name="category_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="content.contentequipmentcategory",
            ),
        ),
    ]
