# Generated by Django 5.2 on 2025-04-13 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0087_alter_contentequipment_category_obj"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentequipment",
            unique_together={("name", "category")},
        ),
    ]
