# Generated by Django 5.2 on 2025-04-13 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0089_alter_contentequipment_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentequipment",
            old_name="category_obj",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="historicalcontentequipment",
            old_name="category_obj",
            new_name="category",
        ),
        migrations.AlterUniqueTogether(
            name="contentequipment",
            unique_together={("name", "category")},
        ),
    ]
