# Generated by Django 5.2 on 2025-04-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0090_rename_category_obj_contentequipment_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipmentcategory",
            name="restricted_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="If provided, this equipment category is only available to specific gang houses.",
                related_name="restricted_equipment_categories",
                to="content.contenthouse",
                verbose_name="Restricted To",
            ),
        ),
    ]
