# Generated by Django 5.1.7 on 2025-04-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0091_contentequipmentcategory_restricted_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipment",
            name="upgrade_mode",
            field=models.CharField(
                choices=[("SINGLE", "Single"), ("MULTI", "Multi")],
                default="SINGLE",
                help_text="If applicable, does this equipment have an upgrade stack (single, e.g. cyberteknika) or options (multi, e.g. genesmithing)?",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentequipment",
            name="upgrade_mode",
            field=models.CharField(
                choices=[("SINGLE", "Single"), ("MULTI", "Multi")],
                default="SINGLE",
                help_text="If applicable, does this equipment have an upgrade stack (single, e.g. cyberteknika) or options (multi, e.g. genesmithing)?",
                max_length=6,
            ),
        ),
    ]
