# Generated by Django 5.1.7 on 2025-04-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0093_alter_contentequipmentupgrade_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentequipmentupgrade",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="The position in which this upgrade sits in the stack, if applicable.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentequipmentupgrade",
            name="position",
            field=models.IntegerField(
                default=0,
                help_text="The position in which this upgrade sits in the stack, if applicable.",
            ),
        ),
    ]
