# Generated by Django 5.1.7 on 2025-04-18 20:51

import django.db.models.deletion
import gyrinx.content.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0094_alter_contentequipmentupgrade_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentModFighterStat",
            fields=[
                (
                    "contentmod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentmod",
                    ),
                ),
                (
                    "stat",
                    models.CharField(
                        choices=[
                            ("movement", "Movement"),
                            ("weapon_skill", "Weapon Skill"),
                            ("ballistic_skill", "Ballistic Skill"),
                            ("strength", "Strength"),
                            ("toughness", "Toughness"),
                            ("wounds", "Wounds"),
                            ("initiative", "Initiative"),
                            ("attacks", "Attacks"),
                            ("leadership", "Leadership"),
                            ("cool", "Cool"),
                            ("willpower", "Willpower"),
                            ("intelligence", "Intelligence"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("improve", "Improve"),
                            ("worsen", "Worsen"),
                            ("set", "Set"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=5)),
            ],
            options={
                "verbose_name": "Figher Stat Modifier",
                "verbose_name_plural": "Figher Stat Modifiers",
                "ordering": ["stat"],
            },
            bases=(
                "content.contentmod",
                gyrinx.content.models.ContentModStatApplyMixin,
            ),
        ),
        migrations.AlterModelOptions(
            name="contentmodstat",
            options={
                "ordering": ["stat"],
                "verbose_name": "Weapon Stat Modifier",
                "verbose_name_plural": "Weapon Stat Modifiers",
            },
        ),
        migrations.AlterField(
            model_name="contentmodstat",
            name="mode",
            field=models.CharField(
                choices=[("improve", "Improve"), ("worsen", "Worsen"), ("set", "Set")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contentmodstat",
            name="stat",
            field=models.CharField(
                choices=[
                    ("strength", "Strength"),
                    ("range_short", "Range (Short)"),
                    ("range_long", "Range (Long)"),
                    ("accuracy_short", "Accuracy (Short)"),
                    ("accuracy_long", "Accuracy (Long)"),
                    ("armour_piercing", "Armour Piercing"),
                    ("damage", "Damage"),
                    ("ammo", "Ammo"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contentmodstat",
            name="value",
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name="ContentModFighterRule",
            fields=[
                (
                    "contentmod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentmod",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("add", "Add"), ("remove", "Remove")], max_length=255
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_by",
                        to="content.contentrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Modifier",
                "verbose_name_plural": "Rule Modifiers",
                "ordering": ["rule__name", "mode"],
            },
            bases=("content.contentmod",),
        ),
    ]
