# Generated by Django 5.1.7 on 2025-04-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0095_contentmodfighterstat_alter_contentmodstat_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentequipmentupgrade",
            name="modifiers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Modifiers to apply to the equipment or fighter's statline and traits.",
                to="content.contentmod",
            ),
        ),
    ]
