# Generated by Django 5.1.7 on 2025-04-19 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0096_alter_contentequipmentupgrade_modifiers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentmodfighterrule",
            options={
                "ordering": ["rule__name", "mode"],
                "verbose_name": "Fighter Rule Modifier",
                "verbose_name_plural": "Fighter Rule Modifiers",
            },
        ),
        migrations.AlterModelOptions(
            name="contentmodfighterstat",
            options={
                "ordering": ["stat"],
                "verbose_name": "Fighter Stat Modifier",
                "verbose_name_plural": "Fighter Stat Modifiers",
            },
        ),
        migrations.AlterModelOptions(
            name="contentmodtrait",
            options={
                "ordering": ["trait__name", "mode"],
                "verbose_name": "Weapon Trait Modifier",
                "verbose_name_plural": "Weapon Trait Modifiers",
            },
        ),
    ]
