# Generated by Django 5.1.7 on 2025-04-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0097_alter_contentmodfighterrule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipment",
            name="modifiers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Modifiers to apply to the fighter's statline and traits.",
                to="content.contentmod",
            ),
        ),
    ]
