# Generated by Django 5.2 on 2025-04-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0098_contentequipment_modifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentModFighterSkill",
            fields=[
                (
                    "contentmod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentmod",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("add", "Add"), ("remove", "Remove")], max_length=255
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_by",
                        to="content.contentskill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fighter Skill Modifier",
                "verbose_name_plural": "Fighter Skill Modifiers",
                "ordering": ["skill__name", "mode"],
            },
            bases=("content.contentmod",),
        ),
    ]
