# Generated by Django 5.2 on 2025-04-21 12:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0099_contentmodfighterskill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalContentEquipmentEquipmentProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipment",
                        verbose_name="Equipment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_equipment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="This Equipment will be auto-assigned when the main Equipment is assigned",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipment",
                        verbose_name="Auto-assigned Equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Equipment-Equipment Link",
                "verbose_name_plural": "historical Equipment-Equipment Links",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentEquipmentEquipmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentequipment",
                        verbose_name="Equipment",
                    ),
                ),
                (
                    "linked_equipment",
                    models.ForeignKey(
                        help_text="This Equipment will be auto-assigned when the main Equipment is assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equip_equip_link_profiles",
                        to="content.contentequipment",
                        verbose_name="Auto-assigned Equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment-Equipment Link",
                "verbose_name_plural": "Equipment-Equipment Links",
                "unique_together": {("equipment", "linked_equipment")},
            },
        ),
    ]
