# Generated by Django 5.1.7 on 2025-05-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0100_historicalcontentequipmentequipmentprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfighter",
            name="can_take_legacy",
            field=models.BooleanField(
                default=False,
                help_text="If checked, list fighters of this type can take on legacy content fighters.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="can_take_legacy",
            field=models.BooleanField(
                default=False,
                help_text="If checked, list fighters of this type can take on legacy content fighters.",
            ),
        ),
    ]
