# Generated by Django 5.1.7 on 2025-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0101_contentfighter_can_take_legacy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfighter",
            name="can_be_legacy",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this fighter can be assigned as a legacy content fighter.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="can_be_legacy",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this fighter can be assigned as a legacy content fighter.",
            ),
        ),
    ]
