# Generated by Django 5.1.4 on 2025-06-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0102_contentfighter_can_be_legacy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentInjury",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("recovery", "Recovery"),
                            ("convalescence", "Convalescence"),
                            ("permanent", "Permanent"),
                            ("out_cold", "Out Cold"),
                        ],
                        default="permanent",
                        help_text="The phase that this injury applies to (recovery, convalescence, permanent, or out cold).",
                        max_length=20,
                    ),
                ),
                (
                    "modifiers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Modifiers applied when this injury is active.",
                        related_name="injuries",
                        to="content.contentmod",
                    ),
                ),
                (
                    "page_refs",
                    models.ManyToManyField(blank=True, to="content.contentpageref"),
                ),
            ],
            options={
                "verbose_name": "Injury",
                "verbose_name_plural": "Injuries",
                "ordering": ["phase", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentInjury",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("recovery", "Recovery"),
                            ("convalescence", "Convalescence"),
                            ("permanent", "Permanent"),
                            ("out_cold", "Out Cold"),
                        ],
                        default="permanent",
                        help_text="The phase that this injury applies to (recovery, convalescence, permanent, or out cold).",
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Injury",
                "verbose_name_plural": "historical Injuries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
