# Generated by Django 5.1.4 on 2025-06-07 19:20

from django.db import migrations

# This migration is intentionally left empty as a placeholder.
# It is used to ensure that the migration history is consistent
# and to allow for future migrations to be added without conflicts.


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0103_add_injury_models"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
