# Generated by Django 5.2.2 on 2025-06-07 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0104_add_sample_injuries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentinjury",
            name="page_refs",
        ),
    ]
