# Generated by Django 5.2.2 on 2025-06-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0105_remove_contentinjury_page_refs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentinjury",
            options={
                "ordering": [
                    models.Case(
                        models.When(phase="recovery", then=0),
                        models.When(phase="convalescence", then=1),
                        models.When(phase="permanent", then=2),
                        models.When(phase="out_cold", then=3),
                        default=99,
                    ),
                    "name",
                ],
                "verbose_name": "Injury",
                "verbose_name_plural": "Injuries",
            },
        ),
    ]
