# Generated by Django 5.2.2 on 2025-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0107_update_injury_phase_to_default_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfighter",
            name="is_stash",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this fighter represents a gang's stash and should only show gear/weapons.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfighter",
            name="is_stash",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this fighter represents a gang's stash and should only show gear/weapons.",
            ),
        ),
    ]
