# Generated by Django 5.2.2 on 2025-06-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0108_add_is_stash_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentfighter",
            name="category",
            field=models.CharField(
                choices=[
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                    ("STASH", "Stash"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentfighter",
            name="category",
            field=models.CharField(
                choices=[
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                    ("STASH", "Stash"),
                ],
                max_length=255,
            ),
        ),
    ]
