# Generated by Django 5.2.2 on 2025-06-29 21:37

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0112_add_content_fighter_equipment_list_upgrade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the attribute (e.g., 'Alignment', 'Alliance', 'Affiliation').",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_single_select",
                    models.BooleanField(
                        default=True,
                        help_text="If True, only one value can be selected. If False, multiple values can be selected.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gang Attribute",
                "verbose_name_plural": "Gang Attributes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the attribute (e.g., 'Alignment', 'Alliance', 'Affiliation').",
                        max_length=255,
                    ),
                ),
                (
                    "is_single_select",
                    models.BooleanField(
                        default=True,
                        help_text="If True, only one value can be selected. If False, multiple values can be selected.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Gang Attribute",
                "verbose_name_plural": "historical Gang Attributes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContentAttributeValue",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The value name (e.g., 'Law Abiding', 'Outlaw', 'Chaos Cult').",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of what this value represents.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The attribute this value belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentattribute",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Gang Attribute Value",
                "verbose_name_plural": "historical Gang Attribute Values",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentAttributeValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The value name (e.g., 'Law Abiding', 'Outlaw', 'Chaos Cult').",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of what this value represents.",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="The attribute this value belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="content.contentattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gang Attribute Value",
                "verbose_name_plural": "Gang Attribute Values",
                "ordering": ["attribute__name", "name"],
                "unique_together": {("attribute", "name")},
            },
        ),
    ]
