# Generated by Django 5.2.3 on 2025-07-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0113_contentattribute_historicalcontentattribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentattribute",
            name="restricted_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="If provided, this attribute is only available to specific gang houses.",
                related_name="restricted_attributes",
                to="content.contenthouse",
                verbose_name="Restricted To",
            ),
        ),
    ]
