# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0114_add_restricted_to_content_attribute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contenthouseadditionalruletree",
            name="house",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouseadditionalrule",
            name="tree",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouseadditionalrule",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouseadditionalruletree",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouseadditionalruletree",
            name="house",
        ),
        migrations.RemoveField(
            model_name="contenthouse",
            name="house_additional_rules_name",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouse",
            name="house_additional_rules_name",
        ),
        migrations.DeleteModel(
            name="ContentHouseAdditionalRule",
        ),
        migrations.DeleteModel(
            name="ContentHouseAdditionalRuleTree",
        ),
        migrations.DeleteModel(
            name="HistoricalContentHouseAdditionalRule",
        ),
        migrations.DeleteModel(
            name="HistoricalContentHouseAdditionalRuleTree",
        ),
    ]
