# Generated by Django 5.2.3 on 2025-07-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0114_add_restricted_to_content_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenthouse",
            name="legacy",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this House is considered a legacy/older faction.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontenthouse",
            name="legacy",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this House is considered a legacy/older faction.",
            ),
        ),
    ]
