# Generated by Django 5.2.4 on 2025-07-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_squashed_0116_add_visible_only_if_in_equipment_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenthouse",
            name="can_hire_any",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this House can hire any fighter from any house (except stash fighters).",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontenthouse",
            name="can_hire_any",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this House can hire any fighter from any house (except stash fighters).",
            ),
        ),
    ]
