# Generated by Django 5.2.4 on 2025-07-10 21:30

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0116_add_visible_only_if_in_equipment_list"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "display_text",
                    models.CharField(
                        help_text="Short text shown on badge", max_length=10
                    ),
                ),
                (
                    "color_class",
                    models.CharField(
                        choices=[
                            ("text-bg-primary", "Primary"),
                            ("text-bg-secondary", "Secondary"),
                            ("text-bg-success", "Success"),
                            ("text-bg-danger", "Danger"),
                            ("text-bg-warning", "Warning"),
                            ("text-bg-info", "Info"),
                            ("text-bg-light", "Light"),
                            ("text-bg-dark", "Dark"),
                        ],
                        default="text-bg-secondary",
                        help_text="Bootstrap color class",
                        max_length=30,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g., bi-star-fill)",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(db_index=True, max_length=50)),
                (
                    "display_text",
                    models.CharField(
                        help_text="Short text shown on badge", max_length=10
                    ),
                ),
                (
                    "color_class",
                    models.CharField(
                        choices=[
                            ("text-bg-primary", "Primary"),
                            ("text-bg-secondary", "Secondary"),
                            ("text-bg-success", "Success"),
                            ("text-bg-danger", "Danger"),
                            ("text-bg-warning", "Warning"),
                            ("text-bg-info", "Info"),
                            ("text-bg-light", "Light"),
                            ("text-bg-dark", "Dark"),
                        ],
                        default="text-bg-secondary",
                        help_text="Bootstrap color class",
                        max_length=30,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g., bi-star-fill)",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical User Badge",
                "verbose_name_plural": "historical User Badges",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
