# Generated by Django 5.2.4 on 2025-07-18 08:26

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0119_add_flexible_statline_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentstatline",
            name="stat_values",
        ),
        migrations.RemoveField(
            model_name="historicalcontentstatline",
            name="stat_values",
        ),
        migrations.CreateModel(
            name="HistoricalContentStatlineStat",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "value",
                    models.CharField(
                        help_text="The stat value (e.g., '5\"', '12', '4+', '-')",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentstatline",
                    ),
                ),
                (
                    "statline_type_stat",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentstatlinetypestat",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Statline Stat",
                "verbose_name_plural": "historical Statline Stats",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentStatlineStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        help_text="The stat value (e.g., '5\"', '12', '4+', '-')",
                        max_length=10,
                    ),
                ),
                (
                    "statline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="content.contentstatline",
                    ),
                ),
                (
                    "statline_type_stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentstatlinetypestat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statline Stat",
                "verbose_name_plural": "Statline Stats",
                "ordering": ["statline_type_stat__position"],
                "unique_together": {("statline", "statline_type_stat")},
            },
        ),
    ]
