# Generated by Django 5.2.4 on 2025-07-18 16:40:00

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0122_add_hide_flags_to_contentfighter"),
    ]

    operations = [
        # Create the ContentStat model
        migrations.CreateModel(
            name="ContentStat",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "field_name",
                    models.CharField(
                        help_text="Internal field name (e.g., 'movement', 'front_toughness')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short display name (e.g., 'M', 'Fr')", max_length=10
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full display name (e.g., 'Movement', 'Front Toughness')",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stat",
                "verbose_name_plural": "Stats",
                "ordering": ["full_name"],
            },
        ),
        # Create the historical ContentStat model
        migrations.CreateModel(
            name="HistoricalContentStat",
            fields=[
                ("id", models.UUIDField(db_index=True, editable=False)),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "field_name",
                    models.CharField(
                        db_index=True,
                        help_text="Internal field name (e.g., 'movement', 'front_toughness')",
                        max_length=50,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Short display name (e.g., 'M', 'Fr')", max_length=10
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full display name (e.g., 'Movement', 'Front Toughness')",
                        max_length=50,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="auth.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Stat",
                "verbose_name_plural": "historical Stats",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        # First remove the old unique_together constraint
        migrations.AlterUniqueTogether(
            name="contentstatlinetypestat",
            unique_together=set(),
        ),
        # Remove old fields from ContentStatlineTypeStat
        migrations.RemoveField(
            model_name="contentstatlinetypestat",
            name="field_name",
        ),
        migrations.RemoveField(
            model_name="contentstatlinetypestat",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="contentstatlinetypestat",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="historicalcontentstatlinetypestat",
            name="field_name",
        ),
        migrations.RemoveField(
            model_name="historicalcontentstatlinetypestat",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="historicalcontentstatlinetypestat",
            name="full_name",
        ),
        # Add the stat ForeignKey to ContentStatlineTypeStat
        # Since there are no existing records as mentioned, we can add it without a default
        migrations.AddField(
            model_name="contentstatlinetypestat",
            name="stat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statline_type_stats",
                to="content.contentstat",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontentstatlinetypestat",
            name="stat",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentstat",
            ),
            preserve_default=False,
        ),
        # Update unique_together constraint
        migrations.AlterUniqueTogether(
            name="contentstatlinetypestat",
            unique_together={("statline_type", "stat")},
        ),
    ]
