# Generated by Django 5.2.4 on 2025-07-19 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0123_refactor_statline_to_use_contentstat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentmodfighterstat",
            name="stat",
            field=models.CharField(
                choices=[
                    ("movement", "Movement"),
                    ("weapon_skill", "Weapon Skill"),
                    ("ballistic_skill", "Ballistic Skill"),
                    ("strength", "Strength"),
                    ("toughness", "Toughness"),
                    ("wounds", "Wounds"),
                    ("initiative", "Initiative"),
                    ("attacks", "Attacks"),
                    ("leadership", "Leadership"),
                    ("cool", "Cool"),
                    ("willpower", "Willpower"),
                    ("intelligence", "Intelligence"),
                    ("front", "Front"),
                    ("side", "Side"),
                    ("rear", "Rear"),
                    ("hull_points", "Hull Points"),
                    ("handling", "Handling"),
                    ("save", "Save"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contentstat",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentstat",
            name="id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name="ContentEquipmentCategoryFighterRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fighter_category",
                    models.CharField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "equipment_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentequipmentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Category Fighter Restriction",
                "verbose_name_plural": "Equipment Category Fighter Restrictions",
                "unique_together": {("equipment_category", "fighter_category")},
            },
        ),
    ]
