# Generated by Django 5.2.4 on 2025-07-20 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0124_alter_contentmodfighterstat_stat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentEquipmentCategoryFighterRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fighter_category",
                    models.CharField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "equipment_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentequipmentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Category Fighter Restriction",
                "verbose_name_plural": "Equipment Category Fighter Restrictions",
                "unique_together": {("equipment_category", "fighter_category")},
            },
        ),
    ]
