# Generated by Django 5.2.4 on 2025-07-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0125_contentequipmentcategoryfighterrestriction"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentweaponaccessory",
            name="cost_expression",
            field=models.CharField(
                blank=True,
                help_text="Optional cost calculation expression. If provided, this will be used instead of the base cost. Available variables: cost_int (the base cost of the weapon). Available functions: round(), ceil(), floor(), round_up(). Example: 'ceil(cost_int * 0.25 / 5) * 5' for 25% of cost rounded up to nearest 5.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentweaponaccessory",
            name="cost_expression",
            field=models.CharField(
                blank=True,
                help_text="Optional cost calculation expression. If provided, this will be used instead of the base cost. Available variables: cost_int (the base cost of the weapon). Available functions: round(), ceil(), floor(), round_up(). Example: 'ceil(cost_int * 0.25 / 5) * 5' for 25% of cost rounded up to nearest 5.",
                max_length=255,
            ),
        ),
    ]
