# Generated by Django 5.2.4 on 2025-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0127_alter_contentequipmentcategoryfighterrestriction_equipment_category",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfighterdefaultassignment",
            name="upgrades_field",
            field=models.ManyToManyField(
                blank=True,
                help_text="The upgrades that this default assignment has.",
                related_name="default_assignments",
                to="content.contentequipmentupgrade",
            ),
        ),
    ]
