# Generated by Django 5.2.4 on 2025-08-01 12:20

import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0128_add_gang_terrain_fighter_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentInjuryGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "restricted_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("LEADER", "Leader"),
                                ("CHAMPION", "Champion"),
                                ("GANGER", "Ganger"),
                                ("JUVE", "Juve"),
                                ("CREW", "Crew"),
                                ("EXOTIC_BEAST", "Exotic Beast"),
                                ("HANGER_ON", "Hanger-on"),
                                ("BRUTE", "Brute"),
                                ("HIRED_GUN", "Hired Gun"),
                                ("BOUNTY_HUNTER", "Bounty Hunter"),
                                ("HOUSE_AGENT", "House Agent"),
                                ("HIVE_SCUM", "Hive Scum"),
                                ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                                ("PROSPECT", "Prospect"),
                                ("SPECIALIST", "Specialist"),
                                ("STASH", "Stash"),
                                ("VEHICLE", "Vehicle"),
                                ("GANG_TERRAIN", "Gang Terrain"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Fighter categories that can see this injury group. If empty, all can see it.",
                        size=None,
                    ),
                ),
                (
                    "unavailable_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("LEADER", "Leader"),
                                ("CHAMPION", "Champion"),
                                ("GANGER", "Ganger"),
                                ("JUVE", "Juve"),
                                ("CREW", "Crew"),
                                ("EXOTIC_BEAST", "Exotic Beast"),
                                ("HANGER_ON", "Hanger-on"),
                                ("BRUTE", "Brute"),
                                ("HIRED_GUN", "Hired Gun"),
                                ("BOUNTY_HUNTER", "Bounty Hunter"),
                                ("HOUSE_AGENT", "House Agent"),
                                ("HIVE_SCUM", "Hive Scum"),
                                ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                                ("PROSPECT", "Prospect"),
                                ("SPECIALIST", "Specialist"),
                                ("STASH", "Stash"),
                                ("VEHICLE", "Vehicle"),
                                ("GANG_TERRAIN", "Gang Terrain"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Fighter categories that cannot see this injury group.",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Injury Group",
                "verbose_name_plural": "Injury Groups",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="contentinjury",
            options={
                "ordering": ["injury_group__name", "group", "name"],
                "verbose_name": "Injury",
                "verbose_name_plural": "Injuries",
            },
        ),
        migrations.AlterField(
            model_name="contentinjury",
            name="group",
            field=models.CharField(
                blank=True,
                help_text="Legacy field for grouping. Use injury_group instead.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="contentinjury",
            name="phase",
            field=models.CharField(
                choices=[
                    ("no_change", "No Change"),
                    ("active", "Active"),
                    ("recovery", "Recovery"),
                    ("convalescence", "Convalescence"),
                    ("dead", "Dead"),
                    ("in_repair", "In Repair"),
                ],
                default="no_change",
                help_text="The default fighter state outcome when this injury is applied.",
                max_length=20,
                verbose_name="Default Outcome",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentinjury",
            name="group",
            field=models.CharField(
                blank=True,
                help_text="Legacy field for grouping. Use injury_group instead.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontentinjury",
            name="phase",
            field=models.CharField(
                choices=[
                    ("no_change", "No Change"),
                    ("active", "Active"),
                    ("recovery", "Recovery"),
                    ("convalescence", "Convalescence"),
                    ("dead", "Dead"),
                    ("in_repair", "In Repair"),
                ],
                default="no_change",
                help_text="The default fighter state outcome when this injury is applied.",
                max_length=20,
                verbose_name="Default Outcome",
            ),
        ),
        migrations.AddField(
            model_name="contentinjury",
            name="injury_group",
            field=models.ForeignKey(
                blank=True,
                help_text="The injury group this injury belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="injuries",
                to="content.contentinjurygroup",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentinjury",
            name="injury_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The injury group this injury belongs to.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentinjurygroup",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalContentInjuryGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "restricted_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("LEADER", "Leader"),
                                ("CHAMPION", "Champion"),
                                ("GANGER", "Ganger"),
                                ("JUVE", "Juve"),
                                ("CREW", "Crew"),
                                ("EXOTIC_BEAST", "Exotic Beast"),
                                ("HANGER_ON", "Hanger-on"),
                                ("BRUTE", "Brute"),
                                ("HIRED_GUN", "Hired Gun"),
                                ("BOUNTY_HUNTER", "Bounty Hunter"),
                                ("HOUSE_AGENT", "House Agent"),
                                ("HIVE_SCUM", "Hive Scum"),
                                ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                                ("PROSPECT", "Prospect"),
                                ("SPECIALIST", "Specialist"),
                                ("STASH", "Stash"),
                                ("VEHICLE", "Vehicle"),
                                ("GANG_TERRAIN", "Gang Terrain"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Fighter categories that can see this injury group. If empty, all can see it.",
                        size=None,
                    ),
                ),
                (
                    "unavailable_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("LEADER", "Leader"),
                                ("CHAMPION", "Champion"),
                                ("GANGER", "Ganger"),
                                ("JUVE", "Juve"),
                                ("CREW", "Crew"),
                                ("EXOTIC_BEAST", "Exotic Beast"),
                                ("HANGER_ON", "Hanger-on"),
                                ("BRUTE", "Brute"),
                                ("HIRED_GUN", "Hired Gun"),
                                ("BOUNTY_HUNTER", "Bounty Hunter"),
                                ("HOUSE_AGENT", "House Agent"),
                                ("HIVE_SCUM", "Hive Scum"),
                                ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                                ("PROSPECT", "Prospect"),
                                ("SPECIALIST", "Specialist"),
                                ("STASH", "Stash"),
                                ("VEHICLE", "Vehicle"),
                                ("GANG_TERRAIN", "Gang Terrain"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Fighter categories that cannot see this injury group.",
                        size=None,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Injury Group",
                "verbose_name_plural": "historical Injury Groups",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
