# Generated by Django 5.2.4 on 2025-08-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0129_contenthouse_can_buy_any_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentModSkillTreeAccess",
            fields=[
                (
                    "contentmod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentmod",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("add_primary", "Add as Primary"),
                            ("add_secondary", "Add as Secondary"),
                            ("remove_primary", "Remove from Primary"),
                            ("remove_secondary", "Remove from Secondary"),
                            ("disable", "Disable Access"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "skill_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_by_skill_tree_access",
                        to="content.contentskillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Tree Access Modifier",
                "verbose_name_plural": "Skill Tree Access Modifiers",
                "ordering": ["skill_category__name", "mode"],
            },
            bases=("content.contentmod",),
        ),
    ]
