# Generated by Django 5.2.4 on 2025-08-02 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0129_contenthouse_can_buy_any_and_more"),
        ("content", "0130_populate_injury_groups"),
    ]

    operations = []
