# Generated by Django 5.2.4 on 2025-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0132_populate_injury_groups_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentinjurygroup",
            name="restricted_to_house",
            field=models.ManyToManyField(
                blank=True,
                help_text="If set, only these houses can use injuries from this group.",
                related_name="injury_groups",
                to="content.contenthouse",
            ),
        ),
    ]
