# Generated by Django 5.2.4 on 2025-08-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0133_add_restricted_to_house_to_injury_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentModPsykerDisciplineAccess",
            fields=[
                (
                    "contentmod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentmod",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("add", "Add Discipline"),
                            ("remove", "Remove Discipline"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_by_psyker_discipline_access",
                        to="content.contentpsykerdiscipline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Psyker Discipline Access Modifier",
                "verbose_name_plural": "Psyker Discipline Access Modifiers",
                "ordering": ["discipline__name", "mode"],
            },
            bases=("content.contentmod",),
        ),
    ]
