# Generated by Django 5.2.4 on 2025-08-04 12:18

import django.db.models.deletion
import multiselectfield.db.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0133_add_restricted_to_house_to_injury_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentFighterCategoryTerms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        help_text="Fighter categories that use these terms",
                        max_length=172,
                    ),
                ),
                (
                    "proximal_demonstrative",
                    models.CharField(
                        default="This fighter",
                        help_text="How to refer to this fighter (e.g., 'This fighter', 'The stash', 'The vehicle')",
                        max_length=255,
                    ),
                ),
                (
                    "injury_singular",
                    models.CharField(
                        default="Injury",
                        help_text="Singular form of injury (e.g., 'Injury', 'Damage', 'Glitch')",
                        max_length=255,
                    ),
                ),
                (
                    "injury_plural",
                    models.CharField(
                        default="Injuries",
                        help_text="Plural form of injury (e.g., 'Injuries', 'Damage')",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fighter Category Terms",
                "verbose_name_plural": "Fighter Category Terms",
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentFighterCategoryTerms",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "categories",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        help_text="Fighter categories that use these terms",
                        max_length=172,
                    ),
                ),
                (
                    "proximal_demonstrative",
                    models.CharField(
                        default="This fighter",
                        help_text="How to refer to this fighter (e.g., 'This fighter', 'The stash', 'The vehicle')",
                        max_length=255,
                    ),
                ),
                (
                    "injury_singular",
                    models.CharField(
                        default="Injury",
                        help_text="Singular form of injury (e.g., 'Injury', 'Damage', 'Glitch')",
                        max_length=255,
                    ),
                ),
                (
                    "injury_plural",
                    models.CharField(
                        default="Injuries",
                        help_text="Plural form of injury (e.g., 'Injuries', 'Damage')",
                        max_length=255,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fighter Category Terms",
                "verbose_name_plural": "historical Fighter Category Terms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
