# Generated by Django 5.2.4 on 2025-08-04 09:24

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0133_add_restricted_to_house_to_injury_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentFighterCategoryTerms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "proximal_demonstrative",
                    models.CharField(
                        default="This fighter",
                        help_text="How to refer to this fighter (e.g., 'This fighter', 'The stash', 'The vehicle')",
                        max_length=255,
                    ),
                ),
                (
                    "injury_singular",
                    models.CharField(
                        default="Injury",
                        help_text="Singular form of injury (e.g., 'Injury', 'Damage', 'Glitch')",
                        max_length=255,
                    ),
                ),
                (
                    "injury_plural",
                    models.CharField(
                        default="Injuries",
                        help_text="Plural form of injury (e.g., 'Injuries', 'Damage')",
                        max_length=255,
                    ),
                ),
                (
                    "content_fighter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_terms",
                        to="content.contentfighter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fighter Category Terms",
                "verbose_name_plural": "Fighter Category Terms",
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentFighterCategoryTerms",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "proximal_demonstrative",
                    models.CharField(
                        default="This fighter",
                        help_text="How to refer to this fighter (e.g., 'This fighter', 'The stash', 'The vehicle')",
                        max_length=255,
                    ),
                ),
                (
                    "injury_singular",
                    models.CharField(
                        default="Injury",
                        help_text="Singular form of injury (e.g., 'Injury', 'Damage', 'Glitch')",
                        max_length=255,
                    ),
                ),
                (
                    "injury_plural",
                    models.CharField(
                        default="Injuries",
                        help_text="Plural form of injury (e.g., 'Injuries', 'Damage')",
                        max_length=255,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentfighter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fighter Category Terms",
                "verbose_name_plural": "historical Fighter Category Terms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
