# Generated by Django 5.2.4 on 2025-08-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0134_add_content_fighter_category_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfightercategoryterms",
            name="singular",
            field=models.CharField(
                default="Fighter",
                help_text="Singular form of fighter (e.g., 'Fighter', 'Vehicle')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentfightercategoryterms",
            name="singular",
            field=models.CharField(
                default="Fighter",
                help_text="Singular form of fighter (e.g., 'Fighter', 'Vehicle')",
                max_length=255,
            ),
        ),
    ]
