# Generated by Django 5.2.4 on 2025-08-06 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0136_contentmodpsykerdisciplineaccess"),
        ("core", "0097_remove_deprecated_house_additional_rules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contenthouseadditionalruletree",
            name="house",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouseadditionalrule",
            name="tree",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouseadditionalrule",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouseadditionalruletree",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouseadditionalruletree",
            name="house",
        ),
        migrations.RemoveField(
            model_name="contenthouse",
            name="house_additional_rules_name",
        ),
        migrations.RemoveField(
            model_name="historicalcontenthouse",
            name="house_additional_rules_name",
        ),
        migrations.DeleteModel(
            name="ContentHouseAdditionalRule",
        ),
        migrations.DeleteModel(
            name="ContentHouseAdditionalRuleTree",
        ),
        migrations.DeleteModel(
            name="HistoricalContentHouseAdditionalRule",
        ),
        migrations.DeleteModel(
            name="HistoricalContentHouseAdditionalRuleTree",
        ),
    ]
