# Generated by Django 5.2.4 on 2025-08-07 09:00

import django.db.models.deletion
import multiselectfield.db.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0137_remove_deprecated_house_additional_rules"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentEquipmentListExpansionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment List Expansion Rule",
                "verbose_name_plural": "Equipment List Expansion Rules",
            },
        ),
        migrations.CreateModel(
            name="ContentEquipmentListExpansionRuleByFighterCategory",
            fields=[
                (
                    "contentequipmentlistexpansionrule_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentequipmentlistexpansionrule",
                    ),
                ),
                (
                    "fighter_categories",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        help_text="Fighter categories that must match",
                        max_length=172,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expansion Rule by Fighter Category",
                "verbose_name_plural": "Expansion Rules by Fighter Category",
            },
            bases=("content.contentequipmentlistexpansionrule",),
        ),
        migrations.CreateModel(
            name="ContentEquipmentListExpansion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this equipment list expansion",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "rules",
                    models.ManyToManyField(
                        help_text="All rules must match (AND logic) for this expansion to apply",
                        related_name="expansions",
                        to="content.contentequipmentlistexpansionrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment List Expansion",
                "verbose_name_plural": "Equipment List Expansions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentEquipmentListExpansion",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of this equipment list expansion",
                        max_length=255,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Equipment List Expansion",
                "verbose_name_plural": "historical Equipment List Expansions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContentEquipmentListExpansionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "cost",
                    models.IntegerField(
                        blank=True,
                        help_text="Override cost for this equipment in the expansion (null = use base cost)",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The equipment that becomes available",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipment",
                    ),
                ),
                (
                    "expansion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The expansion this item belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipmentlistexpansion",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Equipment List Expansion Item",
                "verbose_name_plural": "historical Equipment List Expansion Items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContentEquipmentListExpansionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Equipment List Expansion Rule",
                "verbose_name_plural": "historical Equipment List Expansion Rules",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentEquipmentListExpansionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "cost",
                    models.IntegerField(
                        blank=True,
                        help_text="Override cost for this equipment in the expansion (null = use base cost)",
                        null=True,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        help_text="The equipment that becomes available",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentequipment",
                    ),
                ),
                (
                    "expansion",
                    models.ForeignKey(
                        help_text="The expansion this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.contentequipmentlistexpansion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment List Expansion Item",
                "verbose_name_plural": "Equipment List Expansion Items",
                "ordering": ["expansion", "equipment__name"],
                "unique_together": {("expansion", "equipment")},
            },
        ),
        migrations.CreateModel(
            name="ContentEquipmentListExpansionRuleByAttribute",
            fields=[
                (
                    "contentequipmentlistexpansionrule_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentequipmentlistexpansionrule",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="The attribute to match on",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentattribute",
                    ),
                ),
                (
                    "attribute_values",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific values to match (empty = any value except 'not set')",
                        to="content.contentattributevalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expansion Rule by Attribute",
                "verbose_name_plural": "Expansion Rules by Attribute",
            },
            bases=("content.contentequipmentlistexpansionrule",),
        ),
        migrations.CreateModel(
            name="ContentEquipmentListExpansionRuleByHouse",
            fields=[
                (
                    "contentequipmentlistexpansionrule_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.contentequipmentlistexpansionrule",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        help_text="The house to match",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contenthouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expansion Rule by House",
                "verbose_name_plural": "Expansion Rules by House",
            },
            bases=("content.contentequipmentlistexpansionrule",),
        ),
    ]
