# Generated by Django 5.2.4 on 2025-08-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0139_alter_contentequipmentcategoryfighterrestriction_fighter_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentequipmentlistexpansionitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contentequipmentlistexpansionitem",
            name="weapon_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="The weapon profile to use for this expansion item (e.g., specific ammo type)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentweaponprofile",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentequipmentlistexpansionitem",
            name="weapon_profile",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The weapon profile to use for this expansion item (e.g., specific ammo type)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentweaponprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentequipmentlistexpansionitem",
            unique_together={("expansion", "equipment", "weapon_profile")},
        ),
    ]
