# Generated by Django 5.2.4 on 2025-08-12 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0140_add_weapon_profile_to_expansion_item"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contentfightercategoryterms",
            unique_together={("categories",)},
        ),
    ]
