# Generated by Django 5.2.4 on 2025-08-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0141_alter_contentfightercategoryterms_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentweaponprofile",
            name="traits",
            field=models.ManyToManyField(
                blank=True, db_index=True, to="content.contentweapontrait"
            ),
        ),
    ]
