# Generated by Django 5.2.5 on 2025-09-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0145_add_recovery_singular_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentstat",
            name="is_inches",
            field=models.BooleanField(
                default=False,
                help_text='This stat represents a distance measured in inches and gets a quote-mark when displayed e.g. Movement 3"',
            ),
        ),
        migrations.AddField(
            model_name="contentstat",
            name="is_inverted",
            field=models.BooleanField(
                default=False,
                help_text='If inverted, "improving" this stat means decreasing the number e.g. Cool 4+ to 3+',
            ),
        ),
        migrations.AddField(
            model_name="contentstat",
            name="is_modifier",
            field=models.BooleanField(
                default=False,
                help_text="This stat modifies a roll and gets a plus prefix when displayed, e.g. Acc S +3",
            ),
        ),
        migrations.AddField(
            model_name="contentstat",
            name="is_target",
            field=models.BooleanField(
                default=False,
                help_text="This stat is a target of a roll and gets a plus suffix when displayed, e.g. WS 3+",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentstat",
            name="is_inches",
            field=models.BooleanField(
                default=False,
                help_text='This stat represents a distance measured in inches and gets a quote-mark when displayed e.g. Movement 3"',
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentstat",
            name="is_inverted",
            field=models.BooleanField(
                default=False,
                help_text='If inverted, "improving" this stat means decreasing the number e.g. Cool 4+ to 3+',
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentstat",
            name="is_modifier",
            field=models.BooleanField(
                default=False,
                help_text="This stat modifies a roll and gets a plus prefix when displayed, e.g. Acc S +3",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentstat",
            name="is_target",
            field=models.BooleanField(
                default=False,
                help_text="This stat is a target of a roll and gets a plus suffix when displayed, e.g. WS 3+",
            ),
        ),
    ]
