# Generated by Django 5.2.5 on 2025-09-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0145_add_recovery_singular_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentmodfighterstat",
            name="stat",
            field=models.CharField(max_length=50),
        ),
    ]
