# Generated by Django 5.2.6 on 2025-09-13 14:05

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0148_ensure_contentstat_entries_exist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAdvancementEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this advancement (e.g., 'Legendary Name')",
                        max_length=255,
                    ),
                ),
                (
                    "xp_cost",
                    models.PositiveIntegerField(
                        help_text="XP cost to acquire this equipment through advancement"
                    ),
                ),
                (
                    "cost_increase",
                    models.IntegerField(
                        default=0,
                        help_text="Fighter cost increase when this equipment is gained",
                    ),
                ),
                (
                    "restricted_to_fighter_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of fighter categories that can gain this equipment (e.g., ['GANGER', 'CHAMPION'])",
                    ),
                ),
                (
                    "enable_random",
                    models.BooleanField(
                        default=False,
                        help_text="Allow random selection from the equipment list",
                    ),
                ),
                (
                    "enable_chosen",
                    models.BooleanField(
                        default=False,
                        help_text="Allow player to choose from the equipment list",
                    ),
                ),
                (
                    "restricted_to_houses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If set, only these houses can gain this equipment via advancement",
                        related_name="advancement_equipment",
                        to="content.contenthouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advancement Equipment",
                "verbose_name_plural": "Advancement Equipment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentAdvancementAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advancement_assignments",
                        to="content.contentequipment",
                    ),
                ),
                (
                    "upgrades_field",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Upgrades that come with this equipment assignment",
                        related_name="advancement_assignments",
                        to="content.contentequipmentupgrade",
                    ),
                ),
                (
                    "advancement",
                    models.ForeignKey(
                        blank=True,
                        help_text="The equipment advancement this assignment belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="content.contentadvancementequipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advancement Assignment",
                "verbose_name_plural": "Advancement Assignments",
                "ordering": ["equipment__name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentAdvancementAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "advancement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The equipment advancement this assignment belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentadvancementequipment",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Advancement Assignment",
                "verbose_name_plural": "historical Advancement Assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContentAdvancementEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this advancement (e.g., 'Legendary Name')",
                        max_length=255,
                    ),
                ),
                (
                    "xp_cost",
                    models.PositiveIntegerField(
                        help_text="XP cost to acquire this equipment through advancement"
                    ),
                ),
                (
                    "cost_increase",
                    models.IntegerField(
                        default=0,
                        help_text="Fighter cost increase when this equipment is gained",
                    ),
                ),
                (
                    "restricted_to_fighter_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of fighter categories that can gain this equipment (e.g., ['GANGER', 'CHAMPION'])",
                    ),
                ),
                (
                    "enable_random",
                    models.BooleanField(
                        default=False,
                        help_text="Allow random selection from the equipment list",
                    ),
                ),
                (
                    "enable_chosen",
                    models.BooleanField(
                        default=False,
                        help_text="Allow player to choose from the equipment list",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Advancement Equipment",
                "verbose_name_plural": "historical Advancement Equipment",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
