# Generated by Django 5.2.6 on 2025-09-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0149_add_advancement_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentadvancementequipment",
            name="enable_chosen",
            field=models.BooleanField(
                default=False,
                help_text="Allow player to choose from the equipment list",
            ),
        ),
        migrations.AddField(
            model_name="contentadvancementequipment",
            name="enable_random",
            field=models.BooleanField(
                default=False,
                help_text="Allow random selection from the equipment list",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentadvancementequipment",
            name="enable_chosen",
            field=models.BooleanField(
                default=False,
                help_text="Allow player to choose from the equipment list",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentadvancementequipment",
            name="enable_random",
            field=models.BooleanField(
                default=False,
                help_text="Allow random selection from the equipment list",
            ),
        ),
    ]
