# Generated by Django 5.2.6 on 2025-09-13 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0149_contentadvancementequipment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentadvancementassignment",
            options={
                "ordering": ["advancement__name", "equipment__name"],
                "verbose_name": "Equipment Advancement Assignment",
                "verbose_name_plural": "Equipment Advancement Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="contentadvancementequipment",
            options={
                "ordering": ["name"],
                "verbose_name": "Equipment Advancement",
                "verbose_name_plural": "Equipment Advancements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentadvancementassignment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Equipment Advancement Assignment",
                "verbose_name_plural": "historical Equipment Advancement Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontentadvancementequipment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Equipment Advancement",
                "verbose_name_plural": "historical Equipment Advancements",
            },
        ),
    ]
