# Generated by Django 5.2.6 on 2025-09-12 21:33

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0150_add_enable_flags_to_advancement_equipment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentadvancementequipment",
            name="equipment",
            field=models.ManyToManyField(
                blank=True,
                help_text="Equipment that can be gained through advancement - fighter chooses one from this list (deprecated, use assignments instead)",
                related_name="advancement_options",
                to="content.contentequipment",
            ),
        ),
        migrations.CreateModel(
            name="ContentAdvancementAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advancement_assignments",
                        to="content.contentequipment",
                    ),
                ),
                (
                    "upgrades_field",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Upgrades that come with this equipment assignment",
                        related_name="advancement_assignments",
                        to="content.contentequipmentupgrade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advancement Assignment",
                "verbose_name_plural": "Advancement Assignments",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="contentadvancementequipment",
            name="assignments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Equipment assignments that can be gained through advancement - fighter chooses one from this list",
                related_name="advancement_options",
                to="content.contentadvancementassignment",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalContentAdvancementAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentequipment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Advancement Assignment",
                "verbose_name_plural": "historical Advancement Assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
