# Generated by Django 6.0 on 2026-01-03 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0150_update_equipment_advancement_meta_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcontentpack",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcontentpack",
            name="owner",
        ),
        migrations.DeleteModel(
            name="ContentPack",
        ),
        migrations.DeleteModel(
            name="HistoricalContentPack",
        ),
    ]
