# Generated by Django 5.2.6 on 2025-09-13 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0151_add_advancement_assignment_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentadvancementequipment",
            name="equipment",
        ),
    ]
