# Generated by Django 6.0 on 2026-01-11 18:11

import django.db.models.deletion
import multiselectfield.db.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0152_remove_contentpack_m2m_tables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalContentAvailabilityPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("ALLY", "Ally"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        db_index=True,
                        help_text="Fighter category this preset applies to",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "availability_types",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("C", "Common (C)"),
                            ("R", "Rare (R)"),
                            ("I", "Illegal (I)"),
                            ("E", "Exclusive (E)"),
                            ("U", "Unique (U)"),
                        ],
                        default=["C", "R"],
                        help_text="Availability types to show by default (C/R/I/E/U)",
                        max_length=9,
                    ),
                ),
                (
                    "max_availability_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum availability level (rarity roll). Leave blank for no limit.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Specific fighter this preset applies to (most specific match)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentfighter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="House this preset applies to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contenthouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Availability Preset",
                "verbose_name_plural": "historical Availability Presets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentAvailabilityPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("ALLY", "Ally"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        db_index=True,
                        help_text="Fighter category this preset applies to",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "availability_types",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("C", "Common (C)"),
                            ("R", "Rare (R)"),
                            ("I", "Illegal (I)"),
                            ("E", "Exclusive (E)"),
                            ("U", "Unique (U)"),
                        ],
                        default=["C", "R"],
                        help_text="Availability types to show by default (C/R/I/E/U)",
                        max_length=9,
                    ),
                ),
                (
                    "max_availability_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum availability level (rarity roll). Leave blank for no limit.",
                        null=True,
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific fighter this preset applies to (most specific match)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_presets",
                        to="content.contentfighter",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        help_text="House this preset applies to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_presets",
                        to="content.contenthouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability Preset",
                "verbose_name_plural": "Availability Presets",
                "ordering": ["-created"],
                "unique_together": {("fighter", "category", "house")},
            },
        ),
    ]
