# Generated by Django 6.0.2 on 2026-02-07 20:58

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0156_ensure_fighter_statline_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentRollTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "dice",
                    models.CharField(
                        choices=[("D6", "D6"), ("D66", "D66"), ("2D6", "2D6")],
                        help_text="Dice configuration for this table.",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Roll Table",
                "verbose_name_plural": "Roll Tables",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordering on the fighter card (lower = first).",
                    ),
                ),
                (
                    "restricted_to_fighters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which content fighters show this counter. If empty, no fighters show it.",
                        related_name="counters",
                        to="content.contentfighter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counter",
                "verbose_name_plural": "Counters",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentRollFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "cost",
                    models.PositiveIntegerField(
                        help_text="How many counter points to spend."
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        help_text="Which counter to spend.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="content.contentcounter",
                    ),
                ),
                (
                    "roll_table",
                    models.ForeignKey(
                        help_text="Table to roll on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="content.contentrolltable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roll Flow",
                "verbose_name_plural": "Roll Flows",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordering on the fighter card (lower = first).",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Counter",
                "verbose_name_plural": "historical Counters",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContentRollFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "cost",
                    models.PositiveIntegerField(
                        help_text="How many counter points to spend."
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Which counter to spend.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentcounter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roll_table",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Table to roll on.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentrolltable",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Roll Flow",
                "verbose_name_plural": "historical Roll Flows",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContentRollTable",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "dice",
                    models.CharField(
                        choices=[("D6", "D6"), ("D66", "D66"), ("2D6", "2D6")],
                        help_text="Dice configuration for this table.",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Roll Table",
                "verbose_name_plural": "historical Roll Tables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContentRollTableRow",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "roll_value",
                    models.CharField(
                        help_text='Dice result or range (e.g. "1", "2-3", "4-5", "6").',
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rating_increase",
                    models.IntegerField(
                        default=0,
                        help_text="Rating increase when this result is gained.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display ordering within the table."
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The roll table this row belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentrolltable",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Roll Table Row",
                "verbose_name_plural": "historical Roll Table Rows",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentRollTableRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "roll_value",
                    models.CharField(
                        help_text='Dice result or range (e.g. "1", "2-3", "4-5", "6").',
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rating_increase",
                    models.IntegerField(
                        default=0,
                        help_text="Rating increase when this result is gained.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display ordering within the table."
                    ),
                ),
                (
                    "modifiers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Modifiers applied when this result is gained.",
                        related_name="roll_table_rows",
                        to="content.contentmod",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="The roll table this row belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="content.contentrolltable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roll Table Row",
                "verbose_name_plural": "Roll Table Rows",
                "ordering": ["table", "sort_order"],
                "unique_together": {("table", "sort_order")},
            },
        ),
    ]
