# Generated by Django 6.0.2 on 2026-02-28 21:32

import multiselectfield.db.fields
from django.db import migrations


# Standard fighter categories that default to the "Fighter" statline type.
# VEHICLE, CREW, GANG_TERRAIN, and STASH are excluded — they either have
# their own statline type or don't need one.
_FIGHTER_CATEGORIES = [
    "LEADER",
    "CHAMPION",
    "GANGER",
    "JUVE",
    "EXOTIC_BEAST",
    "HANGER_ON",
    "BRUTE",
    "HIRED_GUN",
    "BOUNTY_HUNTER",
    "HOUSE_AGENT",
    "HIVE_SCUM",
    "DRAMATIS_PERSONAE",
    "PROSPECT",
    "SPECIALIST",
    "ALLY",
]


def set_fighter_default_categories(apps, schema_editor):
    ContentStatlineType = apps.get_model("content", "ContentStatlineType")
    try:
        fighter_type = ContentStatlineType.objects.get(name="Fighter")
    except ContentStatlineType.DoesNotExist:
        return
    fighter_type.default_for_categories = ",".join(_FIGHTER_CATEGORIES)
    fighter_type.save(update_fields=["default_for_categories"])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0158_weapon_trait_remove_unique_add_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentstatlinetype",
            name="default_for_categories",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                    ("STASH", "Stash"),
                    ("VEHICLE", "Vehicle"),
                    ("ALLY", "Ally"),
                    ("GANG_TERRAIN", "Gang Terrain"),
                ],
                help_text="Fighter categories that default to this statline type when created in content packs.",
                max_length=177,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentstatlinetype",
            name="default_for_categories",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("LEADER", "Leader"),
                    ("CHAMPION", "Champion"),
                    ("GANGER", "Ganger"),
                    ("JUVE", "Juve"),
                    ("CREW", "Crew"),
                    ("EXOTIC_BEAST", "Exotic Beast"),
                    ("HANGER_ON", "Hanger-on"),
                    ("BRUTE", "Brute"),
                    ("HIRED_GUN", "Hired Gun"),
                    ("BOUNTY_HUNTER", "Bounty Hunter"),
                    ("HOUSE_AGENT", "House Agent"),
                    ("HIVE_SCUM", "Hive Scum"),
                    ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                    ("PROSPECT", "Prospect"),
                    ("SPECIALIST", "Specialist"),
                    ("STASH", "Stash"),
                    ("VEHICLE", "Vehicle"),
                    ("ALLY", "Ally"),
                    ("GANG_TERRAIN", "Gang Terrain"),
                ],
                help_text="Fighter categories that default to this statline type when created in content packs.",
                max_length=177,
            ),
        ),
        migrations.RunPython(
            set_fighter_default_categories,
            migrations.RunPython.noop,
        ),
    ]
