# Generated by Django 6.0.3 on 2026-04-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0159_contentstatlinetype_default_for_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentskill",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcontentskill",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
