# Generated by Django 6.0.3 on 2026-04-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0160_add_description_to_content_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipment",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contenthouse",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcontentequipment",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcontenthouse",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
