# Generated by Django 6.0.5 on 2026-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0165_add_content_mod_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenthouse",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="Optional SVG icon rendered inline next to the house name. Stored SVGs are untrusted and only safe to render via the house_icon template tag, which sanitises them. Display is currently gated to the 'House Icons Alpha' group.",
                null=True,
                upload_to="house-icons/",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontenthouse",
            name="icon",
            field=models.TextField(
                blank=True,
                help_text="Optional SVG icon rendered inline next to the house name. Stored SVGs are untrusted and only safe to render via the house_icon template tag, which sanitises them. Display is currently gated to the 'House Icons Alpha' group.",
                max_length=100,
                null=True,
            ),
        ),
    ]
