# Generated by Django 6.0.5 on 2026-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0165_add_content_mod_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentequipmentcategory",
            name="persistent",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If True, equipment in this category stays with a fighter when they die — it remains on the fighter rather than being transferred to the stash.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontentequipmentcategory",
            name="persistent",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If True, equipment in this category stays with a fighter when they die — it remains on the fighter rather than being transferred to the stash.",
            ),
        ),
    ]
