# Generated by Django 6.0.6 on 2026-06-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0172_refresh_house_icons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenthouse",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="Optional SVG icon rendered inline next to the house name. Stored SVGs are untrusted and only safe to render via the house_icon template tag, which sanitises them.",
                null=True,
                upload_to="house-icons/",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontenthouse",
            name="icon",
            field=models.TextField(
                blank=True,
                help_text="Optional SVG icon rendered inline next to the house name. Stored SVGs are untrusted and only safe to render via the house_icon template tag, which sanitises them.",
                max_length=100,
                null=True,
            ),
        ),
    ]
