# Generated by Django 6.0.6 on 2026-06-13 07:48

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0173_update_house_icon_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contenthouse",
            name="gang_skill_tree_choices",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional pool of skill trees a gang may pick from. Leave empty to allow any non-restricted skill tree (restricted trees can still be revealed via a filter).",
                related_name="gang_choice_houses",
                to="content.contentskillcategory",
                verbose_name="Gang Skill Tree Pool",
            ),
        ),
        migrations.AddField(
            model_name="contenthouse",
            name="gang_skill_tree_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="How many skill trees the gang ranks (e.g. 4 for Venators). Only used when Gang-wide skills is checked.",
            ),
        ),
        migrations.AddField(
            model_name="contenthouse",
            name="gang_wide_skills",
            field=models.BooleanField(
                default=False,
                help_text="If checked, gangs of this House pick a ranked set of skill trees at creation; those trees become fighters' primary/secondary skills by rank (via the House's Skill Rank Rules). Fighter templates' own primary/secondary skill trees are ignored in this mode.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontenthouse",
            name="gang_skill_tree_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="How many skill trees the gang ranks (e.g. 4 for Venators). Only used when Gang-wide skills is checked.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontenthouse",
            name="gang_wide_skills",
            field=models.BooleanField(
                default=False,
                help_text="If checked, gangs of this House pick a ranked set of skill trees at creation; those trees become fighters' primary/secondary skills by rank (via the House's Skill Rank Rules). Fighter templates' own primary/secondary skill trees are ignored in this mode.",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalContentHouseSkillRankAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "fighter_category",
                    models.CharField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("ALLY", "Ally"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        help_text="The fighter rank this rule applies to.",
                        max_length=255,
                    ),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        help_text="1-based rank of the gang skill tree this rule refers to."
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        help_text="Whether the tree at this slot is primary or secondary for this rank.",
                        max_length=16,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The House this rule applies to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contenthouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical House Skill Rank Rule",
                "verbose_name_plural": "historical House Skill Rank Rules",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContentHouseSkillRankAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "fighter_category",
                    models.CharField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("ALLY", "Ally"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        help_text="The fighter rank this rule applies to.",
                        max_length=255,
                    ),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        help_text="1-based rank of the gang skill tree this rule refers to."
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        help_text="Whether the tree at this slot is primary or secondary for this rank.",
                        max_length=16,
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        help_text="The House this rule applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_rank_rules",
                        to="content.contenthouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "House Skill Rank Rule",
                "verbose_name_plural": "House Skill Rank Rules",
                "ordering": ["house__name", "fighter_category", "slot"],
                "unique_together": {("house", "fighter_category", "slot")},
            },
        ),
    ]
