# Generated by Django 6.0.6 on 2026-06-13 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0174_gang_wide_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenthouseskillrankaccess",
            name="slot",
            field=models.PositiveSmallIntegerField(
                help_text="1-based rank of the gang skill tree this rule refers to.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontenthouseskillrankaccess",
            name="slot",
            field=models.PositiveSmallIntegerField(
                help_text="1-based rank of the gang skill tree this rule refers to.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
