# Generated by Django 6.0.6 on 2026-06-25 21:36

from django.db import migrations, models
from django.db.models import Count

# Modifier subclasses keyed by the fields that make them interchangeable.
# Production accumulated duplicate rows here before the uniqueness constraints
# below existed (#1915), so they must be merged before the constraints apply.
MOD_GROUPS = [
    ("ContentModStat", ["stat", "mode", "value"]),
    ("ContentModFighterStat", ["stat", "mode", "value"]),
    ("ContentModTrait", ["trait", "mode"]),
    ("ContentModFighterRule", ["rule", "mode"]),
    ("ContentModFighterSkill", ["skill", "mode"]),
    ("ContentModSkillTreeAccess", ["skill_category", "mode"]),
    ("ContentModPsykerDisciplineAccess", ["discipline", "mode"]),
]

# Every relation that points at ContentMod and must be re-pointed from a
# redundant duplicate onto the surviving canonical row.
M2M_OWNERS = [
    ("ContentEquipment", "modifiers"),
    ("ContentEquipmentUpgrade", "modifiers"),
    ("ContentInjury", "modifiers"),
    ("ContentRollTableRow", "modifiers"),
    ("ContentWeaponAccessory", "modifiers"),
]
FK_OWNERS = [
    ("ContentModApplication", "modifier"),
]


def dedup_mods(apps, schema_editor):
    """Merge duplicate ContentMod rows onto a single canonical row per group.

    The canonical row is the earliest by ``pk`` (deterministic). Every
    reference on the redundant rows is re-pointed onto the canonical row before
    the redundant rows — and their ContentMod base rows, via
    multi-table-inheritance cascade — are deleted.

    This is behaviour-preserving for stat stacking: mods are applied once per
    *source* (see ``ListFighterEquipmentAssignment._mods`` and
    ``List.pack_mods_by_target``), never deduplicated by row identity, so two
    sources that referenced two duplicate rows still apply twice once both
    point at the canonical row.

    ``_base_manager`` is used throughout (rather than ``objects``) so the dedup
    runs against an unfiltered queryset in every context. Frozen migration
    models already expose a plain manager, but this function is also exercised
    in tests against the real models — whose ``objects`` is the polymorphic /
    pack-excluding content manager — and ``_base_manager`` keeps both paths
    identical and unable to hide a row that needs re-pointing.
    """
    m2m_owners = [
        (apps.get_model("content", name), field) for name, field in M2M_OWNERS
    ]
    fk_owners = [(apps.get_model("content", name), field) for name, field in FK_OWNERS]

    for model_name, fields in MOD_GROUPS:
        Model = apps.get_model("content", model_name)
        dupe_keys = list(
            Model._base_manager.values(*fields).annotate(n=Count("pk")).filter(n__gt=1)
        )
        for key in dupe_keys:
            filt = {f: key[f] for f in fields}
            pks = list(
                Model._base_manager.filter(**filt)
                .order_by("pk")
                .values_list("pk", flat=True)
            )
            canonical, redundant = pks[0], pks[1:]

            for OwnerModel, field in m2m_owners:
                owners = OwnerModel._base_manager.filter(
                    **{f"{field}__in": redundant}
                ).distinct()
                for owner in owners:
                    manager = getattr(owner, field)
                    manager.add(canonical)
                    manager.remove(*redundant)

            for OwnerModel, field in fk_owners:
                OwnerModel._base_manager.filter(**{f"{field}__in": redundant}).update(
                    **{field: canonical}
                )

            Model._base_manager.filter(pk__in=redundant).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0175_gang_skill_constraints"),
    ]

    operations = [
        # Merge existing duplicates first, otherwise the constraints below
        # would fail to apply against the production data.
        migrations.RunPython(dedup_mods, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="contentmodfighterrule",
            constraint=models.UniqueConstraint(
                fields=("rule", "mode"), name="uniq_contentmodfighterrule_rule_mode"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentmodfighterskill",
            constraint=models.UniqueConstraint(
                fields=("skill", "mode"), name="uniq_contentmodfighterskill_skill_mode"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentmodfighterstat",
            constraint=models.UniqueConstraint(
                fields=("stat", "mode", "value"),
                name="uniq_contentmodfighterstat_stat_mode_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentmodpsykerdisciplineaccess",
            constraint=models.UniqueConstraint(
                fields=("discipline", "mode"),
                name="uniq_contentmodpsykerdiscaccess_disc_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentmodskilltreeaccess",
            constraint=models.UniqueConstraint(
                fields=("skill_category", "mode"),
                name="uniq_contentmodskilltreeaccess_skillcat_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentmodstat",
            constraint=models.UniqueConstraint(
                fields=("stat", "mode", "value"),
                name="uniq_contentmodstat_stat_mode_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentmodtrait",
            constraint=models.UniqueConstraint(
                fields=("trait", "mode"), name="uniq_contentmodtrait_trait_mode"
            ),
        ),
    ]
