# Generated by Django 6.0.6 on 2026-07-05 11:19

from django.db import migrations

# Import the shared seed data/helper (data only — no model reference), so the seed and the
# invariant test (A4/G6) consume one source of truth. See gyrinx/content/models/promotion.py.
from gyrinx.content.models.promotion import (
    DEFAULT_CATEGORY_PROMOTIONS,
    seed_category_promotions,
)


def forwards(apps, schema_editor):
    model = apps.get_model("content", "ContentPromotionCategoryPath")
    seed_category_promotions(model)


def backwards(apps, schema_editor):
    model = apps.get_model("content", "ContentPromotionCategoryPath")
    pairs = [
        (e["from_category"], e["to_category"]) for e in DEFAULT_CATEGORY_PROMOTIONS
    ]
    for from_category, to_category in pairs:
        model.objects.filter(
            from_category=from_category, to_category=to_category
        ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0177_add_content_promotion_category_path"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
