# Generated by Django 6.0.6 on 2026-07-05 11:19

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0177_add_counter_warning_stat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPromotionCategoryPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Promote to Specialist'", max_length=255
                    ),
                ),
                (
                    "from_category",
                    models.CharField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("ALLY", "Ally"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        help_text="The fighter category this promotion is offered to.",
                        max_length=50,
                    ),
                ),
                (
                    "to_category",
                    models.CharField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("ALLY", "Ally"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        help_text="The category the fighter is relabelled to (a promotable target).",
                        max_length=50,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordinal seniority of the target category. On reversal a fighter falls back to the highest-ranked promotion it still holds (e.g. Champion=2 outranks Specialist=1).",
                    ),
                ),
                (
                    "xp_cost",
                    models.PositiveIntegerField(
                        help_text="XP spent to take this promotion."
                    ),
                ),
                (
                    "cost_increase",
                    models.IntegerField(
                        default=0,
                        help_text="Flat fighter-rating increase applied by this promotion.",
                    ),
                ),
                (
                    "rolls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="2d6 totals that offer this promotion in the roll-driven flow, e.g. [2, 12].",
                    ),
                ),
                (
                    "grants_skill",
                    models.CharField(
                        choices=[
                            ("none", "No skill"),
                            ("primary_random", "Random Primary Skill"),
                            ("primary_chosen", "Chosen Primary Skill"),
                            ("secondary_random", "Random Secondary Skill"),
                            ("secondary_chosen", "Chosen Secondary Skill"),
                            ("any_random", "Random Skill (Any Set)"),
                        ],
                        default="primary_random",
                        help_text="Which skill (if any) the fighter gains alongside the promotion.",
                        max_length=32,
                    ),
                ),
                (
                    "restricted_to_houses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If set, only fighters in these houses are offered this promotion.",
                        related_name="promotion_category_paths",
                        to="content.contenthouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion (category)",
                "verbose_name_plural": "Promotions (category)",
                "ordering": ["rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContentPromotionCategoryPath",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Promote to Specialist'", max_length=255
                    ),
                ),
                (
                    "from_category",
                    models.CharField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("ALLY", "Ally"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        help_text="The fighter category this promotion is offered to.",
                        max_length=50,
                    ),
                ),
                (
                    "to_category",
                    models.CharField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("CHAMPION", "Champion"),
                            ("GANGER", "Ganger"),
                            ("JUVE", "Juve"),
                            ("CREW", "Crew"),
                            ("EXOTIC_BEAST", "Exotic Beast"),
                            ("HANGER_ON", "Hanger-on"),
                            ("BRUTE", "Brute"),
                            ("HIRED_GUN", "Hired Gun"),
                            ("BOUNTY_HUNTER", "Bounty Hunter"),
                            ("HOUSE_AGENT", "House Agent"),
                            ("HIVE_SCUM", "Hive Scum"),
                            ("DRAMATIS_PERSONAE", "Dramatis Personae"),
                            ("PROSPECT", "Prospect"),
                            ("SPECIALIST", "Specialist"),
                            ("STASH", "Stash"),
                            ("VEHICLE", "Vehicle"),
                            ("ALLY", "Ally"),
                            ("GANG_TERRAIN", "Gang Terrain"),
                        ],
                        help_text="The category the fighter is relabelled to (a promotable target).",
                        max_length=50,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordinal seniority of the target category. On reversal a fighter falls back to the highest-ranked promotion it still holds (e.g. Champion=2 outranks Specialist=1).",
                    ),
                ),
                (
                    "xp_cost",
                    models.PositiveIntegerField(
                        help_text="XP spent to take this promotion."
                    ),
                ),
                (
                    "cost_increase",
                    models.IntegerField(
                        default=0,
                        help_text="Flat fighter-rating increase applied by this promotion.",
                    ),
                ),
                (
                    "rolls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="2d6 totals that offer this promotion in the roll-driven flow, e.g. [2, 12].",
                    ),
                ),
                (
                    "grants_skill",
                    models.CharField(
                        choices=[
                            ("none", "No skill"),
                            ("primary_random", "Random Primary Skill"),
                            ("primary_chosen", "Chosen Primary Skill"),
                            ("secondary_random", "Random Secondary Skill"),
                            ("secondary_chosen", "Chosen Secondary Skill"),
                            ("any_random", "Random Skill (Any Set)"),
                        ],
                        default="primary_random",
                        help_text="Which skill (if any) the fighter gains alongside the promotion.",
                        max_length=32,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Promotion (category)",
                "verbose_name_plural": "historical Promotions (category)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
