# Generated by Django 5.1.4 on 2025-01-12 16:59

from django.contrib.sites.models import Site as SiteModel
from django.db import migrations


def do_migration(apps, schema_editor):
    Site: type[SiteModel] = apps.get_model("sites", "Site")

    default_site = Site.objects.filter(id=1)
    if default_site.exists():
        default_site.update(domain="gyrinx.app", name="gyrinx.app")
    else:
        Site.objects.create(domain="gyrinx.app", name="gyrinx.app")


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [migrations.RunPython(do_migration)]
