# Generated by Django 5.1.4 on 2025-01-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pages", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flatpagevisibility",
            options={
                "verbose_name": "flat page visibility rule",
                "verbose_name_plural": "flat page visibility rules",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalflatpagevisibility",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical flat page visibility rule",
                "verbose_name_plural": "historical flat page visibility rules",
            },
        ),
        migrations.AlterField(
            model_name="flatpagevisibility",
            name="groups",
            field=models.ManyToManyField(
                help_text="Select the groups that can view this page. If no groups are selected, the page is public.",
                to="auth.group",
                verbose_name="Visible to Groups",
            ),
        ),
    ]
