# Generated by Django 5.2.3

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_flatpagevisibility_options_and_more"),
    ]

    operations = [
        # Remove all waitlist-related tables
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS pages_waitinglistentry_skills CASCADE;",
                "DROP TABLE IF EXISTS pages_waitinglistentry CASCADE;",
                "DROP TABLE IF EXISTS pages_waitinglistskill CASCADE;",
                "DROP TABLE IF EXISTS pages_historicalwaitinglistentry CASCADE;",
                "DROP TABLE IF EXISTS pages_historicalwaitinglistskill CASCADE;",
            ],
            reverse_sql=[],  # No reverse migration
        ),
    ]
