# Generated by Django 5.1.5 on 2025-01-21 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_waitinglistskill_historicalwaitinglistentry_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="waitinglistentry",
            old_name="desired_contribution",
            new_name="skills",
        ),
    ]
