# Generated by Django 5.2.3 on 2025-06-29 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_remove_waitinglist"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="",  # Extension removal is typically not desired
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS django_flatpage_url_trgm_idx ON django_flatpage USING gin (url gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS django_flatpage_url_trgm_idx;",
        ),
    ]
