# Generated by Django 5.1.5 on 2025-01-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_rename_desired_contribution_waitinglistentry_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitinglistentry",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="waiting_list_entries",
                to="pages.waitinglistskill",
            ),
        ),
    ]
