# Generated by Django 5.2.4 on 2025-08-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_add_trigram_index_to_flatpages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatpagevisibility",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="flatpagevisibility",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalflatpagevisibility",
            name="created",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalflatpagevisibility",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
    ]
