# Generated by Django 6.0.7 on 2026-09-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_flatpageoptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="flatpageoptions",
            name="introduction",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Shown at the top of the page, above the contents list and the page content. Optional.",
                verbose_name="Introduction",
            ),
        ),
        migrations.AddField(
            model_name="historicalflatpageoptions",
            name="introduction",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Shown at the top of the page, above the contents list and the page content. Optional.",
                verbose_name="Introduction",
            ),
        ),
    ]
