# Generated by Django 5.1.5 on 2025-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_historicalwaitinglistentry_referred_by_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwaitinglistentry",
            name="referred_by_code",
            field=models.UUIDField(
                blank=True,
                help_text="The share code of the user who referred this user.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="waitinglistentry",
            name="referred_by_code",
            field=models.UUIDField(
                blank=True,
                help_text="The share code of the user who referred this user.",
                null=True,
            ),
        ),
    ]
