# Generated by Django 5.1.6 on 2025-02-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_alter_historicalwaitinglistentry_referred_by_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwaitinglistentry",
            name="desired_username",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="historicalwaitinglistentry",
            name="yaktribe_username",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="waitinglistentry",
            name="desired_username",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="waitinglistentry",
            name="yaktribe_username",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
