# Generated by Django 5.1.6 on 2025-02-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_alter_historicalwaitinglistentry_desired_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwaitinglistentry",
            name="desired_username",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="waitinglistentry",
            name="desired_username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
