# Generated by Django 5.1.6 on 2025-02-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_alter_historicalwaitinglistentry_desired_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwaitinglistentry",
            name="invited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="waitinglistentry",
            name="invited",
            field=models.BooleanField(default=False),
        ),
    ]
