# Generated by Django 6.0.7 on 2026-08-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0005_weapon_accessory"),
    ]

    operations = [
        migrations.AddField(
            model_name="gang",
            name="colour",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shown against the gang wherever it is listed.",
                max_length=50,
            ),
        ),
    ]
