# Generated by Django 6.0.7 on 2026-08-08 13:36

import django.db.models.deletion
import django.db.models.functions.text
import ulid
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0006_gang_colour"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintConfig",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Blank is the gang's scratch config — the one ad-hoc prints rewrite. Named configs are the saved list.",
                        max_length=200,
                    ),
                ),
                (
                    "include_header",
                    models.BooleanField(
                        default=True, help_text="Print the gang's own header block."
                    ),
                ),
                (
                    "include_stash",
                    models.BooleanField(
                        default=True, help_text="Print the stash listing."
                    ),
                ),
                (
                    "assignments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The weapons shown on this print's cards.",
                        related_name="print_configs",
                        to="n26.assignment",
                    ),
                ),
                (
                    "gang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_configs",
                        to="n26.gang",
                    ),
                ),
                (
                    "miniatures",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The models that get a card on this print.",
                        related_name="print_configs",
                        to="n26.miniature",
                    ),
                ),
            ],
            options={
                "verbose_name": "print config",
                "verbose_name_plural": "print configs",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("gang"),
                        django.db.models.functions.text.Lower("name"),
                        name="print_config_unique_per_gang",
                    )
                ],
            },
        ),
    ]
