# Generated by Django 6.0.7 on 2026-08-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0007_print_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                ],
                max_length=20,
            ),
        ),
    ]
