# Generated by Django 6.0.7 on 2026-08-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0008_sold_ledger_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="miniature",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
