# Generated by Django 6.0.7 on 2026-08-13 21:12

import django.db.models.deletion
import ulid
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0051_the_use_lists_say_what_they_ask_for"),
        ("n26", "0009_miniature_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatOverride",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "value",
                    models.CharField(
                        help_text="The raw value, e.g. '5\"', '12', '4+', '-'.",
                        max_length=10,
                    ),
                ),
                (
                    "miniature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_overrides",
                        to="n26.miniature",
                    ),
                ),
                (
                    "statline_type_stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="library.statlinetypestat",
                    ),
                ),
            ],
            options={
                "verbose_name": "stat override",
                "verbose_name_plural": "stat overrides",
                "ordering": ["statline_type_stat__position"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("miniature"),
                        models.F("statline_type_stat"),
                        name="stat_override_unique_per_model",
                    )
                ],
            },
        ),
    ]
