# Generated by Django 6.0.7 on 2026-08-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0058_ties_fall_back_to_name"),
        ("n26", "0011_an_assignment_may_be_a_slot_or_its_pick"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="chosen_for_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="library.slot",
            ),
        ),
    ]
