# Generated by Django 6.0.7 on 2026-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0061_reach_is_said_not_implied"),
        ("n26", "0013_events_stand_alone_pinned_to_their_gang"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="removes",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="reason",
            field=models.CharField(
                choices=[
                    ("bought", "Bought"),
                    ("default", "Default equipment"),
                    ("granted", "Granted by something else"),
                    ("reward", "Reward"),
                    ("free", "Free"),
                    ("edited", "Edited by the owner"),
                ],
                default="bought",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("removes", False))
                | (
                    models.Q(("miniature__isnull", False))
                    & (
                        models.Q(("subtype__isnull", False))
                        | models.Q(("rule__isnull", False))
                    )
                ),
                name="assignment_removes_names_subtype_or_rule",
            ),
        ),
    ]
