# Generated by Django 6.0.7 on 2026-08-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0061_reach_is_said_not_implied"),
        ("n26", "0014_the_owner_edits_what_a_model_is"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="chosen_for_offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="library.offerschoice",
            ),
        ),
    ]
