# Generated by Django 6.0.7 on 2026-08-16 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # The library dependency is only for the offerschoice table the new
    # column points at — deliberately not the library head: the Paths
    # conversion (library.0062) runs live code that reads this column,
    # so it must come after this migration, not before.
    dependencies = [
        ("library", "0061_reach_is_said_not_implied"),
        ("n26", "0014_the_owner_edits_what_a_model_is"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="chosen_for_offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="library.offerschoice",
            ),
        ),
    ]
