# Generated by Django 6.0.7 on 2026-08-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0015_a_pick_names_the_offer_it_settles"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerevent",
            name="batch",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
