# Generated by Django 6.0.7 on 2026-08-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0016_the_events_of_one_act_share_a_mark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("budget_set", "Budget set"),
                ],
                max_length=20,
            ),
        ),
    ]
