# Generated by Django 6.0.7 on 2026-08-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0017_the_budget_is_part_of_the_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="gang",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="gang-images/"),
        ),
        migrations.AddField(
            model_name="gang",
            name="lore",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="gang",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="miniature",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="model-images/"),
        ),
        migrations.AddField(
            model_name="miniature",
            name="lore",
            field=models.TextField(blank=True, default=""),
        ),
    ]
