# Generated by Django 6.0.7 on 2026-08-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0018_the_owner_writes_notes_lore_and_shows_a_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("budget_set", "Budget set"),
                ],
                max_length=20,
            ),
        ),
    ]
