# Generated by Django 6.0.7 on 2026-08-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0019_the_journal_learns_lore_and_picture_verbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="printconfig",
            name="include_notes",
            field=models.BooleanField(
                default=True,
                help_text="Print the gang's notes and a notes card per model that has any.",
            ),
        ),
    ]
