# Generated by Django 6.0.7 on 2026-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("n26", "0025_the_campaigns_feature_starts_shut"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("availability__in", ["off", "allowlist", "everyone"])
                ),
                name="n26_feature_flag_availability_known",
            ),
        ),
    ]
