# Generated by Django 6.0.7 on 2026-08-25 17:10

import uuid

import django.db.models.deletion
import django.utils.timezone
import ulid
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0066_standing_profile_members_take_their_gun"),
        ("n26", "0026_a_flag_may_only_hold_a_word_that_can_be_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("budget_set", "Budget set"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReconcileObligation",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "default_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="library.defaultassignmentset",
                    ),
                ),
            ],
            options={
                "verbose_name": "reconcile obligation",
                "verbose_name_plural": "reconcile obligations",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ReconcileObligationStateTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("to_status", models.CharField(db_index=True, max_length=50)),
                (
                    "transitioned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_state_transitions",
                        to="n26.reconcileobligation",
                    ),
                ),
            ],
            options={
                "verbose_name": "reconcile obligation state transition",
                "verbose_name_plural": "reconcile obligation state transitions",
                "ordering": ["-transitioned_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="reconcileobligation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("default_set",),
                name="one_pending_obligation_per_set",
            ),
        ),
    ]
