# Generated by Django 6.0.7 on 2026-08-23 16:07

import django.db.models.deletion
import ulid
from django.conf import settings
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0026_a_flag_may_only_hold_a_word_that_can_be_read"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "budget",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="What a gang may spend to join, where the campaign says. Null means no ceiling — gangs enter at whatever they are worth.",
                        null=True,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="n26_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign",
                "verbose_name_plural": "campaigns",
                "ordering": ["name"],
            },
        ),
    ]
