# Generated by Django 6.0.7 on 2026-08-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0030_drop_archetype_skill_tree_specialisation_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miniature",
            name="membership",
            field=models.OneToOneField(
                blank=True,
                help_text="The gang-hosted assignment that brought this model in.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member",
                to="n26.assignment",
            ),
        ),
    ]
