# Generated by Django 6.0.7 on 2026-08-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0031_a_gang_deleted_takes_its_models_with_it"),
    ]

    operations = [
        migrations.AddField(
            model_name="gang",
            name="starting_trade_points",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="What a Visit Trading Post action brought, while one is open. Null means no visit: the post is shut, which is a different state from a visit that has spent everything. Unlike credits there is no pinned counterpart — what is left is this less what the ledger records after the visit began.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                ],
                max_length=20,
            ),
        ),
    ]
