# Generated by Django 6.0.7 on 2026-08-26 17:03

import django.db.models.deletion
import ulid
from django.conf import settings
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0032_a_gang_may_be_at_the_trading_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignEvent",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Set up"),
                            ("renamed", "Renamed"),
                            ("budget_set", "Budget set"),
                            ("summary_edited", "Summary edited"),
                            ("archived", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("batch", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="n26.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign event",
                "verbose_name_plural": "campaign events",
                "ordering": ["created"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "created"], name="campaign_event_log_idx"
                    )
                ],
            },
        ),
    ]
