# Generated by Django 6.0.7 on 2026-08-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0033_a_campaign_keeps_a_log_of_what_changed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="note",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
