# Generated by Django 6.0.7 on 2026-08-26 20:26

import django.db.models.deletion
import ulid
from django.conf import settings
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0033_a_campaign_keeps_a_log_of_what_changed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignMembership",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("left", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "campaign membership",
                "verbose_name_plural": "campaign memberships",
                "ordering": ["created"],
            },
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gang_events",
                to="n26.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                    ("joined_campaign", "Joined a campaign"),
                    ("left_campaign", "Left a campaign"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerevent",
            index=models.Index(
                fields=["campaign", "created"], name="ledger_event_camp_idx"
            ),
        ),
        migrations.AddField(
            model_name="campaignmembership",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="n26.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignmembership",
            name="gang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_memberships",
                to="n26.gang",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignmembership",
            index=models.Index(
                fields=["campaign", "left"], name="campaign_membership_roll_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left__isnull", True)),
                fields=("gang",),
                name="campaign_membership_one_open_per_gang",
            ),
        ),
    ]
