# Generated by Django 6.0.7 on 2026-08-28 06:58

import django.db.models.deletion
import ulid
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0034_a_gang_plays_one_campaign_at_a_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Set up"),
                    ("renamed", "Renamed"),
                    ("budget_set", "Budget set"),
                    ("summary_edited", "Summary edited"),
                    ("archived", "Archived"),
                    ("battle_recorded", "Battle recorded"),
                    ("battle_removed", "Battle removed"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles",
                        to="n26.campaign",
                    ),
                ),
                (
                    "gangs",
                    models.ManyToManyField(
                        blank=True, related_name="battles", to="n26.gang"
                    ),
                ),
            ],
            options={
                "verbose_name": "battle",
                "verbose_name_plural": "battles",
                "ordering": ["-date", "-created"],
            },
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="battle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="n26.battle",
            ),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="battle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gang_events",
                to="n26.battle",
            ),
        ),
        migrations.AddIndex(
            model_name="battle",
            index=models.Index(fields=["campaign", "-date"], name="battle_by_date_idx"),
        ),
    ]
