# Generated by Django 6.0.7 on 2026-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0035_a_campaign_records_the_battles_fought"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="budget",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="What a gang founded for this campaign has to spend on models and gear. Whatever is left goes to its stash, so this is what a gang is worth on the day it starts. Null means the campaign sets none.",
                null=True,
            ),
        ),
    ]
