# Generated by Django 6.0.7 on 2026-08-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0039_a_campaign_asks_people_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="budget",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How much a gang should be worth to join, counting its rating, stash and unspent credits. Nothing is refused for being over: a bigger gang joins and is marked. Null means the campaign sets none.",
                null=True,
            ),
        ),
    ]
