# Generated by Django 6.0.7 on 2026-08-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0040_campaign_budget_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gang",
            name="colour",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shown next to the gang's name wherever it is listed.",
                max_length=50,
            ),
        ),
    ]
