# Generated by Django 6.0.7 on 2026-09-04 14:22

import django.db.models.deletion
import ulid
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0041_colour_help_text_names_the_gangs_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                    ("action_opened", "Action started"),
                    ("action_closed", "Action completed"),
                    ("joined_campaign", "Joined a campaign"),
                    ("left_campaign", "Left a campaign"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("founding", "Found and equip gang"),
                            ("trading_post_visit", "Visit Trading Post"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "trade_points",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The Trade Points this action added to the gang. Empty for an action that adds none.",
                        null=True,
                    ),
                ),
                (
                    "closed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="n26.ledgerevent",
                    ),
                ),
                (
                    "gang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="n26.gang",
                    ),
                ),
                (
                    "opened",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="n26.ledgerevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "action",
                "verbose_name_plural": "actions",
                "ordering": ["created"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("closed__isnull", True)),
                        fields=("gang", "kind"),
                        name="one_open_action_of_each_kind",
                    )
                ],
            },
        ),
    ]
