# Generated by Django 6.0.7 on 2026-09-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0042_a_gang_opens_and_closes_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="action",
            field=models.ForeignKey(
                blank=True,
                help_text="The action this purchase counted against — a trip to the trading post, or founding the gang. Blank for a purchase made with no action open.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="n26.action",
            ),
        ),
        migrations.AlterField(
            model_name="gang",
            name="starting_trade_points",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="A copy of what the open Visit Trading Post action brought, kept beside it. Empty when no visit is open. The action itself holds the figure the screens read.",
                null=True,
            ),
        ),
    ]
