# Generated by Django 6.0.7 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0055_the_gang_stops_keeping_a_copy_of_the_visits_figure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("cloned", "Cloned"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                    ("action_opened", "Action started"),
                    ("action_closed", "Action completed"),
                    ("joined_campaign", "Joined a campaign"),
                    ("left_campaign", "Left a campaign"),
                ],
                max_length=20,
            ),
        ),
    ]
