# Generated by Django 6.0.7 on 2026-09-04 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0044_the_open_visit_becomes_an_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="spent_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The model whose Trade Points this purchase spent. Blank for a purchase that counted against no action, or one into the stash.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="n26.miniature",
            ),
        ),
    ]
