"""A roll on a roll table goes on the record the moment it is made.

One event kind for the roll itself, the figure and the die it came from
as columns, and the choice it was for; and a key from the pick that
followed to the roll it came from.
"""

# Generated by Django 6.0.7 on 2026-09-04 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0079_the_gangs_archetype_is_drawn_on_the_models_it_governs"),
        ("n26", "0055_the_gang_stops_keeping_a_copy_of_the_visits_figure"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="roll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="picks",
                to="n26.ledgerevent",
            ),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="dice",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="roll",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="library.slot",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                    ("action_opened", "Action started"),
                    ("action_closed", "Action completed"),
                    ("joined_campaign", "Joined a campaign"),
                    ("left_campaign", "Left a campaign"),
                    ("rolled", "Rolled"),
                ],
                max_length=20,
            ),
        ),
    ]
