# Generated by Django 6.0.7 on 2026-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0057_campaign_type_help_and_asset_event_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Set up"),
                    ("renamed", "Renamed"),
                    ("budget_set", "Budget set"),
                    ("summary_edited", "Summary edited"),
                    ("archived", "Archived"),
                    ("battle_recorded", "Battle recorded"),
                    ("battle_removed", "Battle removed"),
                    ("invited", "Invited somebody"),
                    ("invite_accepted", "Invitation accepted"),
                    ("invite_declined", "Invitation declined"),
                    ("participant_removed", "Participant removed"),
                    ("asset_added", "Asset copy added"),
                    ("asset_dropped", "Asset copy dropped"),
                    ("kind_added", "Asset kind added"),
                    ("asset_created", "Asset created"),
                    ("counter_added", "Counter added"),
                    ("label_added", "Label added"),
                ],
                max_length=20,
            ),
        ),
    ]
