"""A model has a status between battles.

The roster's In Recovery box and the states a lasting effect leaves a
model in, as one column on Miniature; and the event kind that records
every change to it.
"""

# Generated by Django 6.0.7 on 2026-09-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0060_the_gang_budget_says_what_the_number_does"),
    ]

    operations = [
        migrations.AddField(
            model_name="miniature",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("recovery", "In Recovery"),
                    ("critical", "Critically Injured"),
                    ("captured", "Captured"),
                    ("ransomed", "Ransomed"),
                    ("dead", "Dead"),
                ],
                default="active",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("cloned", "Cloned"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                    ("action_opened", "Action started"),
                    ("action_closed", "Action completed"),
                    ("joined_campaign", "Joined a campaign"),
                    ("left_campaign", "Left a campaign"),
                    ("status_set", "Status set"),
                    ("rolled", "Rolled"),
                    ("gained", "Gained"),
                    ("lost", "Lost"),
                ],
                max_length=20,
            ),
        ),
    ]
