"""A campaign records a roll on an asset table, and which tables it opens.

Four more kinds of campaign event: a roll on an asset table, a table
built into the campaign's additions, one taken out again, and one written
for the campaign. Choices only; the column is unchanged.

Reversible: the choices go back.
"""

# Generated by Django 6.0.7 on 2026-09-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0063_an_assignment_can_name_an_asset_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Set up"),
                    ("renamed", "Renamed"),
                    ("budget_set", "Budget set"),
                    ("summary_edited", "Summary edited"),
                    ("archived", "Archived"),
                    ("battle_recorded", "Battle recorded"),
                    ("battle_removed", "Battle removed"),
                    ("invited", "Invited a player"),
                    ("invite_accepted", "Invitation accepted"),
                    ("invite_declined", "Invitation declined"),
                    ("player_removed", "Player removed"),
                    ("asset_added", "Asset added"),
                    ("asset_removed", "Asset removed"),
                    ("asset_rolled", "Rolled"),
                    ("asset_type_added", "Asset type added"),
                    ("asset_created", "Asset created"),
                    ("counter_added", "Counter added"),
                    ("label_added", "Label added"),
                    ("table_opened", "Table opened"),
                    ("table_closed", "Table closed"),
                    ("table_created", "Table created"),
                ],
                max_length=20,
            ),
        ),
    ]
