# Generated by Django 6.0.7 on 2026-09-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0065_a_campaign_records_a_roll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gang",
            name="rating",
            field=models.IntegerField(
                default=0,
                help_text="Pinned. Rewritten at operation boundaries, checked by reconcile.",
            ),
        ),
        migrations.AlterField(
            model_name="miniature",
            name="rating",
            field=models.IntegerField(
                default=0,
                help_text="Pinned. Rewritten at operation boundaries, checked by reconcile.",
            ),
        ),
        migrations.AlterField(
            model_name="stash",
            name="rating",
            field=models.IntegerField(
                default=0,
                help_text="Pinned. Rewritten at operation boundaries, checked by reconcile.",
            ),
        ),
    ]
