# Generated by Django 6.0.7 on 2026-09-12 21:48

import django.db.models.deletion
import ulid
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0066_a_pinned_rating_may_be_below_zero"),
    ]

    operations = [
        migrations.CreateModel(
            name="DismissedOffer",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "slot_key",
                    models.CharField(
                        help_text="The slot's address: the card it is drawn on, the assignment carrying the offer, and the offer itself.",
                        max_length=200,
                    ),
                ),
                (
                    "gang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissed_offers",
                        to="n26.gang",
                    ),
                ),
            ],
            options={
                "verbose_name": "dismissed offer",
                "verbose_name_plural": "dismissed offers",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gang", "slot_key"),
                        name="dismissed_offer_unique_per_gang",
                    )
                ],
            },
        ),
    ]
