# Generated by Django 6.0.7 on 2026-09-13 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0067_an_offer_can_be_dismissed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="action",
            name="one_open_action_of_each_kind",
        ),
        migrations.RenameModel(
            old_name="Action",
            new_name="Activity",
        ),
        migrations.RenameField(
            model_name="ledgerentry",
            old_name="action",
            new_name="activity",
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["created"],
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="gang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="n26.gang",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="trade_points",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "The Trade Points this activity added to the gang. Empty for "
                    "an activity that adds none."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "The activity this purchase counted against — a trip to the "
                    "trading post, or founding the gang. Blank for a purchase "
                    "made with no activity open."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="n26.activity",
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed__isnull", True)),
                fields=("gang", "kind"),
                name="one_open_activity_of_each_kind",
            ),
        ),
    ]
