# Generated by Django 6.0.7 on 2026-09-13 22:26

import django.db.models.deletion
import django.db.models.expressions
import ulid
from django.conf import settings
from django.db import migrations, models

import n26.core.fields


def checkpoint_counter_values(apps, schema_editor):
    """Begin structured counter history at each existing pinned value."""
    CounterValue = apps.get_model("n26", "CounterValue")
    LedgerEvent = apps.get_model("n26", "LedgerEvent")
    alias = schema_editor.connection.alias

    events = []
    for counter_value in (
        CounterValue.objects.using(alias)
        .select_related("assignment")
        .iterator(chunk_size=500)
    ):
        events.append(
            LedgerEvent(
                assignment_id=counter_value.assignment_id,
                gang_id=counter_value.assignment.gang_root_id,
                kind="counter_checkpointed",
                counter_before=counter_value.value,
                counter_delta=0,
                counter_after=counter_value.value,
            )
        )
    LedgerEvent.objects.using(alias).bulk_create(events, batch_size=500)


def remove_counter_checkpoints(apps, schema_editor):
    LedgerEvent = apps.get_model("n26", "LedgerEvent")
    LedgerEvent.objects.using(schema_editor.connection.alias).filter(
        kind="counter_checkpointed"
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0111_remove_action_action_unique_per_pack_and_more"),
        ("n26", "0068_action_becomes_activity"),
        ("n26", "0068_remove_assignment_assignment_exactly_one_assignable_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancementSelection",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AugmentationSelection",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillSelection",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("select", "Select"), ("random", "Random")],
                        max_length=20,
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("any", "Any"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="after_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_events_after_pick",
                to="n26.assignment",
            ),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="before_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_events_before_pick",
                to="n26.assignment",
            ),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="counter_after",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="counter_before",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="counter_delta",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="payment_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="n26.ledgerevent",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("counter_opened", "Counter opened"),
                    ("counter_checkpointed", "Counter checkpointed"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("cloned", "Cloned"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                    ("action_opened", "Action started"),
                    ("action_closed", "Action completed"),
                    ("joined_campaign", "Joined a campaign"),
                    ("left_campaign", "Left a campaign"),
                    ("transferred", "Credits transferred"),
                    ("status_set", "Status set"),
                    ("rolled", "Rolled"),
                    ("gained", "Gained"),
                    ("lost", "Lost"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ActionAllowance",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("recruitment", "Recruitment"), ("rank", "Rank")],
                        max_length=20,
                    ),
                ),
                ("threshold", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allowances",
                        to="library.action",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_allowances",
                        to="n26.miniature",
                    ),
                ),
                (
                    "granted_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_allowances",
                        to="n26.ledgerevent",
                    ),
                ),
                (
                    "rank_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allowances",
                        to="library.ranktable",
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_allowances",
                        to="n26.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "action allowance",
                "verbose_name_plural": "action allowances",
            },
        ),
        migrations.CreateModel(
            name="ActionRecord",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("request_key", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                ("source", models.JSONField(blank=True, default=dict)),
                ("review", models.JSONField(blank=True, default=dict)),
                ("terms", models.JSONField(blank=True, default=dict)),
                ("payment_id", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="library.action",
                    ),
                ),
                (
                    "allowance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="n26.actionallowance",
                    ),
                ),
                (
                    "completed_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_action_records",
                        to="n26.ledgerevent",
                    ),
                ),
                (
                    "fighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_records",
                        to="n26.miniature",
                    ),
                ),
                (
                    "gang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_records",
                        to="n26.gang",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="library.outcome",
                    ),
                ),
                (
                    "source_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_action_records",
                        to="n26.assignment",
                    ),
                ),
                (
                    "started_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_action_records",
                        to="n26.ledgerevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "action record",
                "verbose_name_plural": "action records",
                "ordering": ["created"],
            },
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="action_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_events",
                to="n26.actionrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("counter_after__isnull", True),
                        ("counter_before__isnull", True),
                        ("counter_delta__isnull", True),
                    ),
                    models.Q(
                        ("counter_after__isnull", False),
                        ("counter_before__isnull", False),
                        ("counter_delta__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ledger_event_counter_movement_is_whole",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("counter_before__isnull", True),
                    (
                        "counter_after",
                        django.db.models.expressions.CombinedExpression(
                            models.F("counter_before"), "+", models.F("counter_delta")
                        ),
                    ),
                    _connector="OR",
                ),
                name="ledger_event_counter_movement_adds_up",
            ),
        ),
        migrations.RunPython(
            checkpoint_counter_values,
            remove_counter_checkpoints,
        ),
        migrations.AddField(
            model_name="advancementselection",
            name="action_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advancement_selection",
                to="n26.actionrecord",
            ),
        ),
        migrations.AddField(
            model_name="advancementselection",
            name="intended_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intended_action_advancements",
                to="library.pickable",
            ),
        ),
        migrations.AddField(
            model_name="advancementselection",
            name="pick_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_advancement_picks",
                to="n26.assignment",
            ),
        ),
        migrations.AddField(
            model_name="advancementselection",
            name="roll_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advancement_selections",
                to="n26.ledgerevent",
            ),
        ),
        migrations.AddField(
            model_name="advancementselection",
            name="slot_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_advancement_slots",
                to="n26.assignment",
            ),
        ),
        migrations.AddField(
            model_name="augmentationselection",
            name="action_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="augmentation_selection",
                to="n26.actionrecord",
            ),
        ),
        migrations.AddField(
            model_name="augmentationselection",
            name="intended_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intended_action_augmentations",
                to="library.pickable",
            ),
        ),
        migrations.AddField(
            model_name="augmentationselection",
            name="item_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_item_selections",
                to="n26.assignment",
            ),
        ),
        migrations.AddField(
            model_name="augmentationselection",
            name="new_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_new_tiers",
                to="n26.assignment",
            ),
        ),
        migrations.AddField(
            model_name="augmentationselection",
            name="previous_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_previous_tiers",
                to="n26.assignment",
            ),
        ),
        migrations.AddField(
            model_name="augmentationselection",
            name="slot_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_augmentation_slots",
                to="n26.assignment",
            ),
        ),
        migrations.AddField(
            model_name="skillselection",
            name="action_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_selection",
                to="n26.actionrecord",
            ),
        ),
        migrations.AddField(
            model_name="skillselection",
            name="selected_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_skill_results",
                to="library.skill",
            ),
        ),
        migrations.AddField(
            model_name="skillselection",
            name="skill_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_skill_assignments",
                to="n26.assignment",
            ),
        ),
        migrations.AddField(
            model_name="skillselection",
            name="skill_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_skill_selections",
                to="library.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionallowance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("rank_table__isnull", True),
                        ("source_kind", "recruitment"),
                        ("threshold__isnull", True),
                    ),
                    models.Q(
                        ("rank_table__isnull", False),
                        ("source_kind", "rank"),
                        ("threshold__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="action_allowance_source_is_whole",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionallowance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_kind", "recruitment")),
                fields=("action", "recruitment"),
                name="action_allowance_recruitment_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionallowance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_kind", "rank")),
                fields=("action", "recruitment", "threshold"),
                name="action_allowance_rank_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionrecord",
            constraint=models.UniqueConstraint(
                fields=("gang", "request_key"), name="action_record_request_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="actionrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["started", "completed"])),
                fields=("allowance",),
                name="action_record_reserves_allowance_once",
            ),
        ),
    ]
