# Generated by Django 6.0.7 on 2026-09-14 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0069_fighter_action_records_and_counter_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionrecord",
            name="allowance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="records",
                to="n26.actionallowance",
            ),
        ),
    ]
