# Generated by Django 6.0.7 on 2026-09-14 00:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0070_alter_actionrecord_allowance"),
        ("n26", "0071_fighter_action_correction_events"),
    ]

    operations = []
