# Generated by Django 6.0.7 on 2026-09-15 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0112_clarify_action_thresholds_and_tier_levels"),
        ("n26", "0070_alter_actionrecord_allowance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledgerevent",
            options={
                "ordering": ["created", "pk"],
                "verbose_name": "ledger event",
                "verbose_name_plural": "ledger events",
            },
        ),
        migrations.RemoveConstraint(
            model_name="actionallowance",
            name="action_allowance_source_is_whole",
        ),
        migrations.AddConstraint(
            model_name="actionallowance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("rank_table__isnull", True),
                        ("source_kind", "recruitment"),
                        ("threshold__isnull", True),
                    ),
                    models.Q(
                        ("rank_table__isnull", False),
                        ("source_kind", "rank"),
                        ("threshold__gt", 0),
                        ("threshold__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="action_allowance_source_is_whole",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("counter_after__isnull", True),
                        ("counter_before__isnull", True),
                        ("counter_delta__isnull", True),
                    ),
                    ("kind__in", ["counter_opened", "counter_checkpointed", "tallied"]),
                    _connector="OR",
                ),
                name="ledger_event_counter_movement_kind",
            ),
        ),
    ]
