# Generated by Django 6.0.7 on 2026-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0071_alter_ledgerevent_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterTracking",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "activation_run",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="counter_tracking_singleton"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("activated_at__isnull", True),
                                ("activation_run__isnull", True),
                            ),
                            models.Q(
                                ("activated_at__isnull", False),
                                ("activation_run__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="counter_tracking_activation_complete",
                    ),
                ],
            },
        ),
    ]
