# Generated by Django 6.0.7 on 2026-09-15 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0071_alter_ledgerevent_options_and_more"),
        ("n26", "0071_join_action_record_and_checkout_migrations"),
    ]

    operations = []
