# Generated by Django 6.0.7 on 2026-09-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0074_join_counter_audit_and_checkout"),
        ("n26", "0076_generic_action_record_names_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillselection",
            name="random_attempts",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
