# Generated by Django 6.0.7 on 2026-09-14 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0071_join_action_record_and_checkout_migrations"),
        ("n26", "0072_add_skill_random_attempts"),
    ]

    operations = []
