# Generated by Django 6.0.7 on 2026-09-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0071_fighter_action_correction_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillselection",
            name="random_attempts",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
