# Generated by Django 6.0.7 on 2026-09-16 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0072_counter_tracking_activation"),
        ("n26", "0073_join_counter_constraints_and_progression"),
    ]

    operations = []
