# Generated by Django 6.0.7 on 2026-09-16 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0112_clarify_action_thresholds_and_tier_levels"),
        ("n26", "0072_counter_tracking_activation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ledgerevent",
            name="ledger_event_counter_movement_kind",
        ),
        migrations.AddConstraint(
            model_name="ledgerevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("counter_after__isnull", True),
                        ("counter_before__isnull", True),
                        ("counter_delta__isnull", True),
                        models.Q(
                            ("kind__in", ["counter_opened", "counter_checkpointed"]),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ("counter_after__isnull", False),
                        ("counter_before__isnull", False),
                        ("counter_delta__isnull", False),
                        (
                            "kind__in",
                            ["counter_opened", "counter_checkpointed", "tallied"],
                        ),
                    ),
                    _connector="OR",
                ),
                name="ledger_event_counter_movement_kind_v2",
            ),
        ),
    ]
