# Generated by Django 6.0.7 on 2026-09-21 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0114_advancement_promotions"),
        ("n26", "0072_add_skill_random_attempts"),
        ("n26", "0076_battle_crews_and_post_battle_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancementselection",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selections",
                to="library.advancementpromotion",
            ),
        ),
        migrations.AddField(
            model_name="advancementselection",
            name="promotion_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_promotions",
                to="n26.assignment",
            ),
        ),
    ]
