# Generated by Django 6.0.7 on 2026-09-15 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0072_join_action_progression_migrations"),
        ("n26", "0072_join_counter_constraints_and_checkout"),
    ]

    operations = []
