# Generated by Django 6.0.7 on 2026-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0073_advancement_promotions"),
    ]

    operations = [
        migrations.AddField(
            model_name="printconfig",
            name="orientation",
            field=models.CharField(
                choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                default="portrait",
                help_text="Which way round the paper goes. Landscape prints three cards across.",
                max_length=20,
            ),
        ),
    ]
