# Generated by Django 6.0.7 on 2026-09-19 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0112_clarify_action_thresholds_and_tier_levels"),
        ("n26", "0073_require_structured_counter_baselines"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancementselection",
            name="intended_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intended_action_advancements",
                to="library.pickable",
            ),
        ),
        migrations.AlterField(
            model_name="augmentationselection",
            name="intended_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intended_action_augmentations",
                to="library.pickable",
            ),
        ),
        migrations.AlterField(
            model_name="skillselection",
            name="selected_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="action_skill_results",
                to="library.skill",
            ),
        ),
        migrations.AlterField(
            model_name="skillselection",
            name="skill_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="action_skill_selections",
                to="library.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("counter_before__isnull", True),
                    ("assignment__isnull", False),
                    _connector="OR",
                ),
                name="ledger_event_counter_has_assignment",
            ),
        ),
    ]
