# Generated by Django 6.0.7 on 2026-09-16 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0073_join_counter_activation_and_checkout"),
        ("n26", "0073_require_structured_counter_baselines"),
    ]

    operations = []
