# Generated by Django 6.0.7 on 2026-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0074_print_config_orientation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("counter_opened", "Counter opened"),
                    ("counter_checkpointed", "Counter checkpointed"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("cloned", "Cloned"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                    ("action_opened", "Action started"),
                    ("action_closed", "Action completed"),
                    ("use_started", "Action use started"),
                    ("use_completed", "Action use completed"),
                    ("use_cancelled", "Action use cancelled"),
                    ("use_paid", "Action use paid"),
                    ("use_corrected", "Action use corrected"),
                    ("joined_campaign", "Joined a campaign"),
                    ("left_campaign", "Left a campaign"),
                    ("transferred", "Credits transferred"),
                    ("status_set", "Status set"),
                    ("rolled", "Rolled"),
                    ("gained", "Gained"),
                    ("lost", "Lost"),
                    ("income", "Income"),
                    ("credits_adjusted", "Credits adjusted"),
                    ("post_battle", "Post-battle results"),
                ],
                max_length=20,
            ),
        ),
    ]
