# Generated by Django 6.0.7 on 2026-09-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0074_protect_action_selections_and_counter_assignments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancementselection",
            name="pick_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_advancement_picks",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="advancementselection",
            name="slot_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_advancement_slots",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="augmentationselection",
            name="item_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_item_selections",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="augmentationselection",
            name="new_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_new_tiers",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="augmentationselection",
            name="previous_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_previous_tiers",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="augmentationselection",
            name="slot_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_augmentation_slots",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="after_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="ledger_events_after_pick",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="before_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="ledger_events_before_pick",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="skillselection",
            name="skill_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_skill_assignments",
                to="n26.assignment",
            ),
        ),
    ]
