# Generated by Django 6.0.7 on 2026-09-16 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0074_join_checkout_and_progression_activation"),
        ("n26", "0074_join_counter_audit_and_checkout"),
    ]

    operations = []
