# Generated by Django 6.0.7 on 2026-09-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0074_join_counter_audit_and_checkout"),
        ("n26", "0076_generic_action_record_names_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="result",
            field=models.CharField(
                choices=[
                    ("not_recorded", "Not recorded"),
                    ("draw", "Draw"),
                    ("winners", "Winner or winners"),
                ],
                default="not_recorded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="battle",
            name="scenario",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="battle",
            name="winners",
            field=models.ManyToManyField(
                blank=True, related_name="battles_won", to="n26.gang"
            ),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Set up"),
                    ("renamed", "Renamed"),
                    ("budget_set", "Budget set"),
                    ("summary_edited", "Summary edited"),
                    ("archived", "Archived"),
                    ("battle_recorded", "Battle recorded"),
                    ("battle_edited", "Battle edited"),
                    ("battle_removed", "Battle removed"),
                    ("invited", "Invited a player"),
                    ("invite_accepted", "Invitation accepted"),
                    ("invite_declined", "Invitation declined"),
                    ("player_removed", "Player removed"),
                    ("asset_added", "Asset added"),
                    ("asset_removed", "Asset removed"),
                    ("asset_rolled", "Rolled"),
                    ("asset_type_added", "Asset type added"),
                    ("asset_created", "Asset created"),
                    ("counter_added", "Counter added"),
                    ("label_added", "Label added"),
                    ("table_opened", "Table opened"),
                    ("table_closed", "Table closed"),
                    ("table_created", "Table created"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="battle",
            constraint=models.CheckConstraint(
                condition=models.Q(("result__in", ["not_recorded", "draw", "winners"])),
                name="battle_result_is_known",
            ),
        ),
    ]
