# Generated by Django 6.0.7 on 2026-09-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0075_credits_adjusted_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("founding", "Spend built-in TP"),
                    ("trading_post_visit", "Visit Trading Post"),
                ],
                max_length=32,
            ),
        ),
    ]
