# Generated by Django 6.0.7 on 2026-09-20 11:01

import uuid

import django.db.models.deletion
import django.utils.timezone
import ulid
from django.conf import settings
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0075_battle_records"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerevent",
            name="post_battle_occurrence",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("counter_opened", "Counter opened"),
                    ("counter_checkpointed", "Counter checkpointed"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("cloned", "Cloned"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                    ("action_opened", "Action started"),
                    ("action_closed", "Action completed"),
                    ("use_started", "Action use started"),
                    ("use_completed", "Action use completed"),
                    ("use_cancelled", "Action use cancelled"),
                    ("use_paid", "Action use paid"),
                    ("use_corrected", "Action use corrected"),
                    ("joined_campaign", "Joined a campaign"),
                    ("left_campaign", "Left a campaign"),
                    ("transferred", "Credits transferred"),
                    ("status_set", "Status set"),
                    ("rolled", "Rolled"),
                    ("gained", "Gained"),
                    ("lost", "Lost"),
                    ("income", "Income"),
                    ("post_battle", "Post-battle results"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BattleCrew",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("confirmed", models.BooleanField(default=False)),
                ("draw_number", models.PositiveIntegerField(default=0)),
                ("last_draw", models.JSONField(blank=True, default=dict)),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crews",
                        to="n26.battle",
                    ),
                ),
                (
                    "gang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_crews",
                        to="n26.gang",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("miniature_name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("starting", "Starting crew"),
                            ("reserve", "Reinforcements"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Chosen"),
                            ("random", "Randomly selected"),
                            ("override", "Card overridden"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                (
                    "card_source",
                    models.CharField(
                        choices=[
                            ("manual", "Chosen"),
                            ("random", "Randomly selected"),
                            ("override", "Card overridden"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                ("eligibility_override", models.BooleanField(default=False)),
                ("card_name", models.CharField(max_length=200)),
                ("equipment_ids", models.JSONField(default=list)),
                ("rating", models.IntegerField(default=0)),
                (
                    "assignment_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crew_members",
                        to="n26.assignmentset",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="n26.battlecrew",
                    ),
                ),
                (
                    "miniature",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crew_memberships",
                        to="n26.miniature",
                    ),
                ),
            ],
            options={
                "ordering": ["miniature_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PostBattleReport",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("request_key", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("applied", "Applied")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("draft", models.JSONField(blank=True, default=dict)),
                ("generation", models.UUIDField(default=uuid.uuid4)),
                ("draft_revision", models.PositiveIntegerField(default=0)),
                ("latest_sequence", models.PositiveIntegerField(default=0)),
                (
                    "battle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="n26.battle",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_battle_reports",
                        to="n26.gang",
                    ),
                ),
                (
                    "last_editor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-modified", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PostBattleRevision",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("sequence", models.PositiveIntegerField()),
                ("submission_key", models.UUIDField(unique=True)),
                ("batch", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("inputs", models.JSONField(default=dict)),
                ("receipt", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="n26.postbattlereport",
                    ),
                ),
            ],
            options={
                "ordering": ["-sequence"],
            },
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="post_battle_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_events",
                to="n26.postbattlerevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="battlecrew",
            constraint=models.UniqueConstraint(
                fields=("battle", "gang"), name="one_crew_per_battle_gang"
            ),
        ),
        migrations.AddConstraint(
            model_name="crewmember",
            constraint=models.UniqueConstraint(
                fields=("crew", "miniature"), name="one_model_per_battle_crew"
            ),
        ),
        migrations.AddConstraint(
            model_name="crewmember",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["starting", "reserve"])),
                name="crew_member_valid_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="postbattlereport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("battle__isnull", False)),
                fields=("gang", "battle"),
                name="post_battle_once_per_gang",
            ),
        ),
        migrations.AddConstraint(
            model_name="postbattlereport",
            constraint=models.UniqueConstraint(
                fields=("gang", "request_key"), name="post_battle_start_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="postbattlereport",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["draft", "applied"])),
                name="post_battle_state_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="postbattlerevision",
            constraint=models.UniqueConstraint(
                fields=("report", "sequence"), name="post_battle_sequence_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="postbattlerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="post_battle_sequence_positive",
            ),
        ),
    ]
