# Generated by Django 6.0.7 on 2026-09-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0112_clarify_action_thresholds_and_tier_levels"),
        ("library", "0112_clarify_action_thresholds_and_tier_levels"),
        ("n26", "0075_retain_recorded_assignment_references"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AugmentationSelection",
            new_name="SlotSelection",
        ),
        migrations.RemoveConstraint(
            model_name="actionallowance",
            name="action_allowance_recruitment_once",
        ),
        migrations.RemoveConstraint(
            model_name="actionallowance",
            name="action_allowance_rank_once",
        ),
        migrations.RenameField(
            model_name="actionallowance",
            old_name="recruitment",
            new_name="source",
        ),
        migrations.AddConstraint(
            model_name="actionallowance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_kind", "recruitment")),
                fields=("action", "source"),
                name="action_allowance_recruitment_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionallowance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_kind", "rank")),
                fields=("action", "source", "threshold"),
                name="action_allowance_rank_once",
            ),
        ),
        migrations.AlterField(
            model_name="slotselection",
            name="action_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_selection",
                to="n26.actionrecord",
            ),
        ),
        migrations.AlterField(
            model_name="slotselection",
            name="intended_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intended_slot_selections",
                to="library.pickable",
            ),
        ),
        migrations.AlterField(
            model_name="slotselection",
            name="new_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_new_picks",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="slotselection",
            name="previous_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_previous_picks",
                to="n26.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="slotselection",
            name="slot_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="action_slot_selections",
                to="n26.assignment",
            ),
        ),
    ]
