# Generated by Django 6.0.7 on 2026-09-27 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0076_founding_activity_label_spend_built_in_tp"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="stake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staked_in",
                to="n26.campaignasset",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="stake_awarded_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stakes_awarded",
                to="n26.gang",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="stake_transfer_mark",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
