# Generated by Django 6.0.7 on 2026-10-02 17:47

import django.db.models.deletion
import ulid
from django.conf import settings
from django.db import migrations, models

import n26.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0077_battle_stake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Set up"),
                    ("renamed", "Renamed"),
                    ("budget_set", "Budget set"),
                    ("summary_edited", "Summary edited"),
                    ("archived", "Archived"),
                    ("dice_rolled", "Dice rolled"),
                    ("dice_roll_noted", "Dice roll noted"),
                    ("battle_recorded", "Battle recorded"),
                    ("battle_edited", "Battle edited"),
                    ("battle_removed", "Battle removed"),
                    ("invited", "Invited a player"),
                    ("invite_accepted", "Invitation accepted"),
                    ("invite_declined", "Invitation declined"),
                    ("player_removed", "Player removed"),
                    ("asset_added", "Asset added"),
                    ("asset_removed", "Asset removed"),
                    ("asset_rolled", "Rolled"),
                    ("asset_type_added", "Asset type added"),
                    ("asset_created", "Asset created"),
                    ("counter_added", "Counter added"),
                    ("label_added", "Label added"),
                    ("table_opened", "Table opened"),
                    ("table_closed", "Table closed"),
                    ("table_created", "Table created"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CampaignRoll",
            fields=[
                (
                    "id",
                    n26.core.fields.ULIDField(
                        default=ulid.ULID,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("request_key", models.UUIDField(editable=False)),
                ("reason", models.CharField(max_length=200)),
                (
                    "dice",
                    models.CharField(
                        choices=[("d3", "D3"), ("d6", "D6"), ("d66", "D66")],
                        max_length=3,
                    ),
                ),
                ("rolled", models.PositiveSmallIntegerField()),
                ("modifier", models.IntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("generated", "Rolled here"),
                            ("manual", "Physical dice"),
                        ],
                        max_length=9,
                    ),
                ),
                ("outcome", models.CharField(blank=True, default="", max_length=512)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="n26.battle",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dice_rolls",
                        to="n26.campaign",
                    ),
                ),
                (
                    "gang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="n26.gang",
                    ),
                ),
            ],
            options={
                "ordering": ["created", "id"],
            },
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="roll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="n26.campaignroll",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignroll",
            constraint=models.UniqueConstraint(
                fields=("campaign", "request_key"), name="campaign_roll_request_unique"
            ),
        ),
    ]
