# Generated by Django 6.0.7 on 2026-10-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0078_base_rating_changes_in_history"),
        ("n26", "0078_campaign_dice_rolls"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="chosen_for_status_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="miniature",
            name="status_revision",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
