# Generated by Django 6.0.7 on 2026-10-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0120_skill_or_power_offers"),
        ("n26", "0078_base_rating_changes_in_history"),
        ("n26", "0078_campaign_dice_rolls"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillselection",
            name="selected_power",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="action_power_results",
                to="library.power",
            ),
        ),
        migrations.AddConstraint(
            model_name="skillselection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("selected_skill__isnull", True),
                    ("selected_power__isnull", True),
                    _connector="OR",
                ),
                name="advancement_selects_one_skill_or_power",
            ),
        ),
    ]
