# Generated by Django 6.0.7 on 2026-10-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0078_base_rating_changes_in_history"),
        ("n26", "0078_campaign_dice_rolls"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="scenario_rolls",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Set up"),
                    ("renamed", "Renamed"),
                    ("budget_set", "Budget set"),
                    ("summary_edited", "Summary edited"),
                    ("archived", "Archived"),
                    ("dice_rolled", "Dice rolled"),
                    ("dice_roll_noted", "Dice roll noted"),
                    ("battle_recorded", "Battle recorded"),
                    ("battle_edited", "Battle edited"),
                    ("battle_removed", "Battle removed"),
                    ("invited", "Invited a player"),
                    ("invite_accepted", "Invitation accepted"),
                    ("invite_declined", "Invitation declined"),
                    ("player_removed", "Player removed"),
                    ("asset_added", "Asset added"),
                    ("asset_removed", "Asset removed"),
                    ("asset_rolled", "Rolled"),
                    ("asset_type_added", "Asset type added"),
                    ("asset_created", "Asset created"),
                    ("counter_added", "Counter added"),
                    ("label_added", "Label added"),
                    ("table_opened", "Table opened"),
                    ("table_closed", "Table closed"),
                    ("table_created", "Table created"),
                    ("scenario_saved", "Scenario saved"),
                ],
                max_length=20,
            ),
        ),
    ]
