# Generated by Django 6.0.7 on 2026-10-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0079_status_follow_up_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerevent",
            name="status_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
