# Generated by Django 6.0.7 on 2026-10-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0121_modifiers_can_replace_inherent_campaign_assets"),
        ("library", "0121_skill_power_roll_numbers"),
        ("n26", "0079_power_advancement_selections"),
        ("n26", "0080_status_choice_roll_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignasset",
            name="income_override",
            field=models.ForeignKey(
                blank=True,
                help_text="The income contribution used for this holding instead of its catalogue income.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="library.modifier",
            ),
        ),
    ]
