# Generated by Django 6.0.7 on 2026-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0121_modifiers_can_replace_inherent_campaign_assets"),
        ("library", "0121_skill_power_roll_numbers"),
        ("n26", "0079_power_advancement_selections"),
        ("n26", "0080_status_choice_roll_revision"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="actionrecord",
            name="action_record_reserves_allowance_once",
        ),
        migrations.AlterField(
            model_name="actionrecord",
            name="state",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("applied_by_hand", "Applied by hand"),
                ],
                db_index=True,
                default="started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("added", "Added"),
                    ("granted", "Granted"),
                    ("caught_up", "Caught up"),
                    ("moved", "Moved"),
                    ("tallied", "Tallied"),
                    ("counter_opened", "Counter opened"),
                    ("counter_checkpointed", "Counter checkpointed"),
                    ("amended", "Amended"),
                    ("repriced", "Repriced"),
                    ("removed", "Removed"),
                    ("refunded", "Refunded"),
                    ("sold", "Sold"),
                    ("took_away", "Took away"),
                    ("renamed", "Renamed"),
                    ("noted", "Notes edited"),
                    ("lore_edited", "Lore edited"),
                    ("image_set", "Picture set"),
                    ("image_cleared", "Picture removed"),
                    ("stat_set", "Characteristic set"),
                    ("stat_cleared", "Characteristic cleared"),
                    ("rating_set", "Base rating changed"),
                    ("rating_reset", "Base rating reset"),
                    ("cloned", "Cloned"),
                    ("budget_set", "Budget set"),
                    ("trade_points_set", "Trade Points set"),
                    ("visited_post", "Visited the trading post"),
                    ("action_opened", "Action started"),
                    ("action_closed", "Action completed"),
                    ("use_started", "Action use started"),
                    ("use_completed", "Action use completed"),
                    ("use_cancelled", "Action use cancelled"),
                    ("use_paid", "Action use paid"),
                    ("use_corrected", "Action use corrected"),
                    ("use_by_hand", "Action use applied by hand"),
                    ("use_reopened", "Action use reopened"),
                    ("joined_campaign", "Joined a campaign"),
                    ("left_campaign", "Left a campaign"),
                    ("transferred", "Credits transferred"),
                    ("status_set", "Status set"),
                    ("rolled", "Rolled"),
                    ("gained", "Gained"),
                    ("lost", "Lost"),
                    ("income", "Income"),
                    ("credits_adjusted", "Credits adjusted"),
                    ("post_battle", "Post-battle results"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="actionrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["started", "completed", "applied_by_hand"])
                ),
                fields=("allowance",),
                name="action_record_reserves_allowance_once",
            ),
        ),
    ]
