# Generated by Django 6.0.7 on 2026-10-10 17:43

from django.db import migrations, models

import n26.core.fields


def preserve_received_asset_types(apps, schema_editor):
    from django.db.models import OuterRef, Subquery

    holdings = apps.get_model("n26", "CampaignAsset")
    events = apps.get_model("n26", "LedgerEvent")
    using = schema_editor.connection.alias
    events.objects.using(using).filter(
        kind="gained", campaign_asset__isnull=False
    ).update(
        received_asset_type=Subquery(
            holdings.objects.using(using)
            .filter(pk=OuterRef("campaign_asset_id"))
            .values("asset__asset_type_id")[:1]
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0080_action_use_applied_by_hand"),
        ("n26", "0080_campaign_holdings_can_override_catalogue_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_campaign", "Pre-campaign"),
                    ("in_progress", "In progress"),
                    ("post_campaign", "Post-campaign"),
                ],
                default="pre_campaign",
                help_text="The campaign's current status, set by its arbitrator.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ledgerevent",
            name="received_asset_type",
            field=n26.core.fields.ULIDField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Set up"),
                    ("renamed", "Renamed"),
                    ("budget_set", "Budget set"),
                    ("summary_edited", "Summary edited"),
                    ("status_changed", "Status changed"),
                    ("archived", "Archived"),
                    ("dice_rolled", "Dice rolled"),
                    ("dice_roll_noted", "Dice roll noted"),
                    ("battle_recorded", "Battle recorded"),
                    ("battle_edited", "Battle edited"),
                    ("battle_removed", "Battle removed"),
                    ("invited", "Invited a player"),
                    ("invite_accepted", "Invitation accepted"),
                    ("invite_declined", "Invitation declined"),
                    ("player_removed", "Player removed"),
                    ("asset_added", "Asset added"),
                    ("asset_removed", "Asset removed"),
                    ("asset_rolled", "Rolled"),
                    ("asset_type_added", "Asset type added"),
                    ("asset_created", "Asset created"),
                    ("counter_added", "Counter added"),
                    ("label_added", "Label added"),
                    ("table_opened", "Table opened"),
                    ("table_closed", "Table closed"),
                    ("table_created", "Table created"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(preserve_received_asset_types, migrations.RunPython.noop),
    ]
