# Generated by Django 6.0.7 on 2026-10-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0080_action_use_applied_by_hand"),
        ("n26", "0080_campaign_holdings_can_override_catalogue_income"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activity",
            name="one_open_activity_of_each_kind",
        ),
        migrations.AddField(
            model_name="activity",
            name="miniature",
            field=models.ForeignKey(
                blank=True,
                help_text="The model spending its hire-time Trade Points. Empty for gang actions.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="n26.miniature",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("founding", "Spend founding TP"),
                    ("hire_time_tp", "Spend hire-time TP"),
                    ("trading_post_visit", "Visit Trading Post"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("closed__isnull", True), ("miniature__isnull", True)
                ),
                fields=("gang", "kind"),
                name="one_open_activity_of_each_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("closed__isnull", True), ("miniature__isnull", False)
                ),
                fields=("gang", "kind", "miniature"),
                name="one_open_activity_per_model_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "hire_time_tp"), ("miniature__isnull", False)),
                    models.Q(
                        ("miniature__isnull", True),
                        models.Q(("kind", "hire_time_tp"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="activity_target_matches_kind",
            ),
        ),
    ]
