# Generated by Django 6.0.7 on 2026-10-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0081_campaigns_have_an_explicit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="budget",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="What a gang should be worth to join, counting its rating, stash and unspent credits. A gang worth more than this can still join. Over-budget warnings appear only while the campaign status is Pre-campaign. Leave blank for no budget.",
                null=True,
            ),
        ),
    ]
