# Generated by Django 6.0.7 on 2026-10-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0081_campaigns_have_an_explicit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("created", "Set up"),
                    ("renamed", "Renamed"),
                    ("budget_set", "Budget set"),
                    ("summary_edited", "Summary edited"),
                    ("status_changed", "Status changed"),
                    ("archived", "Archived"),
                    ("dice_rolled", "Dice rolled"),
                    ("dice_roll_noted", "Dice roll noted"),
                    ("battle_recorded", "Battle recorded"),
                    ("battle_edited", "Battle edited"),
                    ("battle_removed", "Battle removed"),
                    ("invited", "Invited a player"),
                    ("invite_accepted", "Invitation accepted"),
                    ("invite_declined", "Invitation declined"),
                    ("player_removed", "Player removed"),
                    ("asset_added", "Asset added"),
                    ("asset_removed", "Asset removed"),
                    ("asset_rolled", "Rolled"),
                    ("asset_type_added", "Asset type added"),
                    ("asset_type_edited", "Asset type edited"),
                    ("asset_created", "Asset created"),
                    ("counter_added", "Counter added"),
                    ("label_added", "Label added"),
                    ("table_opened", "Table opened"),
                    ("table_closed", "Table closed"),
                    ("table_created", "Table created"),
                ],
                max_length=20,
            ),
        ),
    ]
