# Generated by Django 6.0.7 on 2026-10-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("n26", "0082_campaign_budget_pre_campaign_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignroll",
            name="count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="campaignroll",
            name="modifier_application",
            field=models.CharField(
                choices=[("total", "Total"), ("each", "Each die")],
                default="total",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="campaignroll",
            name="results",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
