# Generated by Django 6.0.7 on 2026-08-05 22:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Adopt Notification into the platform `gyrinxsite` app.

    State-only: db_table keeps core_notification and every index stays exactly
    where it is. Paired with the core migration that releases it from `core`'s
    state. There is no Historical* counterpart — this model deliberately does
    not declare HistoricalRecords.
    """

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("gyrinxsite", "0001_move_site_models_to_platform"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Notification",
                    fields=[
                        ("archived", models.BooleanField(db_index=True, default=False)),
                        ("archived_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created",
                            models.DateTimeField(auto_now_add=True, db_index=True),
                        ),
                        (
                            "modified",
                            models.DateTimeField(auto_now=True, db_index=True),
                        ),
                        ("subject", models.CharField(max_length=255)),
                        ("content", models.TextField(blank=True, default="")),
                        (
                            "notification_type",
                            models.CharField(
                                choices=[
                                    ("system", "System"),
                                    ("list", "List"),
                                    ("campaign", "Campaign"),
                                    ("general", "General"),
                                ],
                                db_index=True,
                                default="system",
                                max_length=20,
                            ),
                        ),
                        ("is_read", models.BooleanField(default=False)),
                        ("read_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "deleted_at",
                            models.DateTimeField(
                                blank=True,
                                help_text="Soft-delete timestamp. Deleted rows disappear from every inbox view.",
                                null=True,
                            ),
                        ),
                        ("target_object_id", models.UUIDField(blank=True, null=True)),
                        ("scope_object_id", models.UUIDField(blank=True, null=True)),
                        (
                            "show_as_banner",
                            models.BooleanField(
                                default=False,
                                help_text="Also show this on the target object's page as a banner.",
                            ),
                        ),
                        (
                            "banner_colour",
                            models.CharField(
                                blank=True,
                                default="info",
                                help_text="Bootstrap colour for the in-page banner (info/warning/success/danger).",
                                max_length=20,
                            ),
                        ),
                        (
                            "icon",
                            models.CharField(
                                blank=True,
                                default="",
                                help_text="Bootstrap icon class, e.g. 'bi-info-circle'.",
                                max_length=50,
                            ),
                        ),
                        (
                            "owner",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "scope_content_type",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="notification_scopes",
                                to="contenttypes.contenttype",
                            ),
                        ),
                        (
                            "sender",
                            models.ForeignKey(
                                blank=True,
                                help_text="User who caused this notification. Null for background/system jobs.",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="sent_notifications",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "target_content_type",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="notification_targets",
                                to="contenttypes.contenttype",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "core_notification",
                        "ordering": ["-created"],
                        "indexes": [
                            models.Index(
                                condition=models.Q(
                                    ("archived", False),
                                    ("deleted_at__isnull", True),
                                    ("is_read", False),
                                ),
                                fields=["owner"],
                                name="notif_unread_idx",
                            ),
                            models.Index(
                                fields=["owner", "-created"], name="notif_inbox_idx"
                            ),
                            models.Index(
                                fields=[
                                    "target_content_type",
                                    "target_object_id",
                                    "show_as_banner",
                                ],
                                name="notif_banner_target_idx",
                            ),
                            models.Index(
                                fields=[
                                    "scope_content_type",
                                    "scope_object_id",
                                    "show_as_banner",
                                ],
                                name="notif_banner_scope_idx",
                            ),
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
