# Generated by Django 6.0.7 on 2026-08-12 18:55

from django.db import migrations, models


def spread_live_to_both_sides(apps, schema_editor):
    """A banner live before the split stays live everywhere.

    Until now the one live banner showed on both editions, so the honest
    translation of ``is_live`` is both flags at once.
    """
    Banner = apps.get_model("gyrinxsite", "Banner")
    Banner.objects.filter(is_live=True).update(live_n23=True, live_n26=True)


class Migration(migrations.Migration):
    dependencies = [
        ("gyrinxsite", "0005_changelog_entry_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="live_n23",
            field=models.BooleanField(
                default=False,
                help_text="Whether this banner is currently live on the classic site. At most one banner can be live there at a time.",
                verbose_name="live on n23",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="live_n26",
            field=models.BooleanField(
                default=False,
                help_text="Whether this banner is currently live on the n26 edition. At most one banner can be live there at a time.",
                verbose_name="live on n26",
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="live_n23",
            field=models.BooleanField(
                default=False,
                help_text="Whether this banner is currently live on the classic site. At most one banner can be live there at a time.",
                verbose_name="live on n23",
            ),
        ),
        migrations.AddField(
            model_name="historicalbanner",
            name="live_n26",
            field=models.BooleanField(
                default=False,
                help_text="Whether this banner is currently live on the n26 edition. At most one banner can be live there at a time.",
                verbose_name="live on n26",
            ),
        ),
        migrations.RunPython(
            spread_live_to_both_sides, migrations.RunPython.noop, elidable=True
        ),
        migrations.RemoveField(
            model_name="banner",
            name="is_live",
        ),
        migrations.RemoveField(
            model_name="historicalbanner",
            name="is_live",
        ),
    ]
