# Generated by Django 6.0.7 on 2026-08-25 16:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("gyrinxsite", "0006_banner_live_per_edition"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="What the code asks for. Fixed once the row exists.",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What this feature is called on this page.",
                        max_length=100,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("off", "Off — nobody, whatever the group says"),
                            ("allowlist", "Allowlist — whoever is in the group"),
                            ("everyone", "Everyone — any signed-in reader"),
                        ],
                        default="off",
                        help_text="Off shuts the feature for everyone, the group included.",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What this feature is, for whoever finds this page later.",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who gets the feature while it is on the allowlist. Add and remove people here or on the group itself. No group means an empty allowlist, not an open door.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feature_flags",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "feature flag",
                "verbose_name_plural": "feature flags",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("availability__in", ["off", "allowlist", "everyone"])
                        ),
                        name="site_feature_flag_availability_known",
                    )
                ],
            },
        ),
    ]
