# Generated by Django 6.0.7 on 2026-09-16 08:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gyrinxsite", "0008_the_flags_an_edition_held_move_to_the_site"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WritePause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("scope", models.SlugField(max_length=64, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("PAUSED", "Paused")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("generation", models.PositiveBigIntegerField(default=0)),
                ("reason", models.TextField(blank=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("permitted_task_name", models.CharField(blank=True, max_length=255)),
                ("permitted_run_id", models.CharField(blank=True, max_length=255)),
                (
                    "paused_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="write_pauses_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scope"],
            },
        ),
    ]
