# Generated by Django 6.0.7 on 2026-08-04 22:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Adopt the event log into the analytics app.

    State-only: db_table stays core_event, so the existing rows and indexes
    are untouched. Paired with the core migration that releases it.
    """

    initial = True

    dependencies = [
        # State-only: this adopts core_event rather than making it, so the
        # core dependency is what holds the analytics chain back until the
        # table exists.
        ("core", "0204_move_site_models_to_platform"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Event",
                    fields=[
                        ("archived", models.BooleanField(db_index=True, default=False)),
                        ("archived_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created",
                            models.DateTimeField(auto_now_add=True, db_index=True),
                        ),
                        (
                            "modified",
                            models.DateTimeField(auto_now=True, db_index=True),
                        ),
                        (
                            "noun",
                            models.CharField(
                                choices=[
                                    ("list", "List"),
                                    ("list_fighter", "List Fighter"),
                                    ("campaign", "Campaign"),
                                    ("campaign_invitation", "Campaign Invitation"),
                                    ("battle", "Battle"),
                                    ("equipment_assignment", "Equipment Assignment"),
                                    ("skill_assignment", "Skill Assignment"),
                                    ("user", "User"),
                                    ("upload", "Upload"),
                                    ("fighter_advancement", "Fighter Advancement"),
                                    ("campaign_action", "Campaign Action"),
                                    ("campaign_resource", "Campaign Resource"),
                                    ("campaign_asset", "Campaign Asset"),
                                    ("banner", "Banner"),
                                    ("print_config", "Print Config"),
                                    ("content_pack", "Content Pack"),
                                ],
                                help_text="The type of object being acted upon",
                                max_length=50,
                            ),
                        ),
                        (
                            "verb",
                            models.CharField(
                                choices=[
                                    ("create", "Create"),
                                    ("update", "Update"),
                                    ("delete", "Delete"),
                                    ("view", "View"),
                                    ("archive", "Archive"),
                                    ("restore", "Restore"),
                                    ("submit", "Submit"),
                                    ("confirm", "Confirm"),
                                    ("join", "Join"),
                                    ("leave", "Leave"),
                                    ("assign", "Assign"),
                                    ("unassign", "Unassign"),
                                    ("activate", "Activate"),
                                    ("deactivate", "Deactivate"),
                                    ("approve", "Approve"),
                                    ("reject", "Reject"),
                                    ("import", "Import"),
                                    ("export", "Export"),
                                    ("add", "Add"),
                                    ("remove", "Remove"),
                                    ("clone", "Clone"),
                                    ("reset", "Reset"),
                                    ("login", "Login"),
                                    ("logout", "Logout"),
                                    ("signup", "Signup"),
                                    ("click", "Click"),
                                ],
                                help_text="The action being performed",
                                max_length=50,
                            ),
                        ),
                        (
                            "object_id",
                            models.UUIDField(
                                blank=True,
                                help_text="UUID of the object being acted upon",
                                null=True,
                            ),
                        ),
                        (
                            "ip_address",
                            models.GenericIPAddressField(
                                blank=True,
                                help_text="IP address of the user when the action was taken",
                                null=True,
                            ),
                        ),
                        (
                            "session_id",
                            models.CharField(
                                blank=True,
                                help_text="Session ID of the user when the action was taken",
                                max_length=40,
                                null=True,
                            ),
                        ),
                        (
                            "field",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("password", "Password"),
                                    ("email", "Email"),
                                    ("mfa", "Multi-Factor Authentication"),
                                    ("session", "Session"),
                                    ("info", "Info"),
                                    ("stats", "Stats"),
                                ],
                                help_text="The field being modified for UPDATE events",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "context",
                            models.JSONField(
                                blank=True,
                                default=dict,
                                help_text="Additional context data in JSON format",
                            ),
                        ),
                        (
                            "object_type",
                            models.ForeignKey(
                                blank=True,
                                help_text="Type of the object for generic relations",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="contenttypes.contenttype",
                            ),
                        ),
                        (
                            "owner",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "event",
                        "verbose_name_plural": "events",
                        "db_table": "core_event",
                        "ordering": ["-created"],
                        "indexes": [
                            models.Index(
                                fields=["-created"],
                                name="core_event_created_409a4e_idx",
                            ),
                            models.Index(
                                fields=["noun", "verb"],
                                name="core_event_noun_20866e_idx",
                            ),
                            models.Index(
                                fields=["owner"], name="core_event_owner_i_e0a4d8_idx"
                            ),
                            models.Index(
                                fields=["object_type", "object_id"],
                                name="core_event_object__934a15_idx",
                            ),
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
