# Generated by Django 5.2.4 on 2025-07-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial_analytics_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphconfiguration",
            name="time_division",
            field=models.CharField(
                choices=[
                    ("minute", "Minute"),
                    ("hour", "Hour"),
                    ("day", "Day"),
                    ("week", "Week"),
                    ("month", "Month"),
                ],
                default="day",
                help_text="How to group data on the x-axis",
                max_length=10,
            ),
        ),
    ]
