# Generated by Django 5.2.4 on 2025-07-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_add_time_division_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphconfiguration",
            name="graph_type",
            field=models.CharField(
                choices=[("line", "Line Chart"), ("bar", "Bar Chart")],
                default="line",
                max_length=20,
            ),
        ),
    ]
