# Generated by Django 5.2.4 on 2025-07-15 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_remove_pie_doughnut_types"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GraphConfiguration",
        ),
    ]
