"""What the override of the kit's tab strip must put in the HTML.

No database: a component is a template and a set of props, and everything
claimed here is decided before a request exists. The strip's tabs are
generated by Alpine from panels that register themselves, so what a rendered
string can prove is the scaffolding — which strips are present, which one the
switcher lives in, and that the segmented variant kept the kit's own shape —
not the tabs themselves, which exist only in a browser.
"""

from django.template import Context, Template
from django_cotton.compiler_regex import CottonCompiler

DEFAULT = """
<c-ui.tabs>
    <c-ui.tabs.tab name="Gangs">A table of gangs.</c-ui.tabs.tab>
    <c-ui.tabs.tab name="Campaigns">Nothing yet.</c-ui.tabs.tab>
</c-ui.tabs>
"""

SEGMENTED = """
<c-ui.tabs variant="segmented" size="sm" :fill="True">
    <c-ui.tabs.tab name="Card">The card.</c-ui.tabs.tab>
    <c-ui.tabs.tab name="Lore">The lore.</c-ui.tabs.tab>
</c-ui.tabs>
"""


def render(source: str, **context) -> str:
    """Compile a call site the way the template loader would, then render it.

    Cotton's `<c-…>` tags are rewritten by a loader, so a template built from a
    string never sees them. Running the compiler by hand is what lets a test
    write the call site it is testing.
    """
    return Template(CottonCompiler().process(source)).render(Context(context))


class TestTheDefaultStrip:
    """The default variant never wraps and never scrolls sideways: two strips
    switched at the sm breakpoint, the narrow one holding a switcher."""

    def test_both_strips_are_in_the_html_for_css_to_pick_between(self):
        html = render(DEFAULT)
        assert "sm:flex" in html
        assert "sm:hidden" in html

    def test_the_strip_no_longer_scrolls_under_a_hidden_bar(self):
        html = render(DEFAULT)
        # The scroll container is what grew a scrollbar under tabs that fit;
        # with a strip for each width there is nothing left to scroll.
        assert "no-scrollbar" not in html
        assert "overflow-x-auto" not in html

    def test_the_narrow_strip_holds_a_switcher_for_the_other_tabs(self):
        html = render(DEFAULT)
        assert "data-quick-switcher" in html
        # Three generated loops over the tabs: the wide strip's buttons,
        # then the switcher's rows drawn twice — once in its panel and once
        # in its noscript strip. One occurrence would mean the switcher
        # lost its copies.
        assert html.count('x-for="tab in tabs"') == 3
        # The rows report a choice the strip acts on rather than navigating.
        assert "$dispatch('quick-switcher-choose'" in html

    def test_the_panels_still_register_themselves(self):
        html = render(DEFAULT)
        assert html.count("register('Gangs'") + html.count('register("Gangs"') == 1

    def test_an_apostrophe_in_the_default_tab_cannot_break_the_script(self):
        html = render(
            """
            <c-ui.tabs default_tab="Psyker's">
                <c-ui.tabs.tab name="Psyker's">Powers.</c-ui.tabs.tab>
            </c-ui.tabs>
            """
        )
        # Written into a quoted JavaScript string, so the quote must arrive
        # escaped or the whole tab state fails to parse.
        assert "activeTab: 'Psyker\\u0027s'" in html


class TestTheSegmentedStrip:
    """The segmented variant keeps the kit's own single strip: its DOM shape
    is addressed by position from app.css, and its few short tabs share one
    row by construction."""

    def test_the_kit_scroll_container_is_kept(self):
        html = render(SEGMENTED)
        assert "no-scrollbar" in html
        assert "overflow-x-auto" in html

    def test_no_second_strip_and_no_switcher_appear(self):
        html = render(SEGMENTED)
        assert "sm:hidden" not in html
        assert "data-quick-switcher" not in html
