# Generated by Django 6.0.7 on 2026-08-04 22:10

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Adopt UserProfile into the platform `accounts` app.

    State-only. The tables (core_userprofile, core_historicaluserprofile) are
    pinned via db_table and already exist — this migration teaches Django that
    they now belong to `accounts`, and touches no data. Paired with
    core.0201, which drops them from `core`'s state the same way.
    """

    initial = True

    dependencies = [
        # State-only: this adopts core_userprofile rather than making it. Naming the
        # core migration the paired release depends on is what holds this
        # app's chain back until the table exists — #2231.
        ("core", "0202_migrate_stat_overrides_operation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="HistoricalUserProfile",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False
                            ),
                        ),
                        (
                            "created",
                            models.DateTimeField(
                                blank=True, db_index=True, editable=False
                            ),
                        ),
                        (
                            "modified",
                            models.DateTimeField(
                                blank=True, db_index=True, editable=False
                            ),
                        ),
                        (
                            "tos_agreed_at",
                            models.DateTimeField(
                                blank=True,
                                help_text="When the user agreed to the Terms of Service",
                                null=True,
                            ),
                        ),
                        (
                            "patreon_status",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("active", "Active"),
                                    ("former", "Former"),
                                    ("declined", "Declined"),
                                ],
                                default="",
                                help_text="Current Patreon membership status",
                                max_length=20,
                            ),
                        ),
                        (
                            "patreon_tier",
                            models.CharField(
                                blank=True,
                                default="",
                                help_text="Patreon tier title (e.g. Scummer)",
                                max_length=100,
                            ),
                        ),
                        (
                            "patreon_member_id",
                            models.CharField(
                                blank=True,
                                default="",
                                help_text="Patreon member UUID for deduplication",
                                max_length=100,
                            ),
                        ),
                        (
                            "patreon_email",
                            models.EmailField(
                                blank=True,
                                default="",
                                help_text="Email address from Patreon webhook",
                                max_length=254,
                            ),
                        ),
                        (
                            "selected_badge",
                            models.CharField(
                                blank=True,
                                default="",
                                help_text="Slug of the supporter badge the user has chosen to display (blank = no badge).",
                                max_length=50,
                            ),
                        ),
                        (
                            "history_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        ("history_date", models.DateTimeField(db_index=True)),
                        (
                            "history_change_reason",
                            models.CharField(max_length=100, null=True),
                        ),
                        (
                            "history_type",
                            models.CharField(
                                choices=[
                                    ("+", "Created"),
                                    ("~", "Changed"),
                                    ("-", "Deleted"),
                                ],
                                max_length=1,
                            ),
                        ),
                        (
                            "history_user",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                blank=True,
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "historical user profile",
                        "verbose_name_plural": "historical user profiles",
                        "db_table": "core_historicaluserprofile",
                        "ordering": ("-history_date", "-history_id"),
                        "get_latest_by": ("history_date", "history_id"),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.CreateModel(
                    name="UserProfile",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created",
                            models.DateTimeField(auto_now_add=True, db_index=True),
                        ),
                        (
                            "modified",
                            models.DateTimeField(auto_now=True, db_index=True),
                        ),
                        (
                            "tos_agreed_at",
                            models.DateTimeField(
                                blank=True,
                                help_text="When the user agreed to the Terms of Service",
                                null=True,
                            ),
                        ),
                        (
                            "patreon_status",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("active", "Active"),
                                    ("former", "Former"),
                                    ("declined", "Declined"),
                                ],
                                default="",
                                help_text="Current Patreon membership status",
                                max_length=20,
                            ),
                        ),
                        (
                            "patreon_tier",
                            models.CharField(
                                blank=True,
                                default="",
                                help_text="Patreon tier title (e.g. Scummer)",
                                max_length=100,
                            ),
                        ),
                        (
                            "patreon_member_id",
                            models.CharField(
                                blank=True,
                                default="",
                                help_text="Patreon member UUID for deduplication",
                                max_length=100,
                            ),
                        ),
                        (
                            "patreon_email",
                            models.EmailField(
                                blank=True,
                                default="",
                                help_text="Email address from Patreon webhook",
                                max_length=254,
                            ),
                        ),
                        (
                            "selected_badge",
                            models.CharField(
                                blank=True,
                                default="",
                                help_text="Slug of the supporter badge the user has chosen to display (blank = no badge).",
                                max_length=50,
                            ),
                        ),
                        (
                            "user",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="profile",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "user profile",
                        "verbose_name_plural": "user profiles",
                        "db_table": "core_userprofile",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
