# Generated by Django 6.0.7 on 2026-08-16 20:11

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_n26_testers_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Short name used internally and stored against anyone who picks this badge. Changing it later un-picks the badge for everybody displaying it, so choose it once.",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="What this badge is called, shown in the badge picker.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The one-line explanation shown when somebody hovers the badge. Write it for a reader who has never seen it before.",
                        max_length=200,
                    ),
                ),
                (
                    "artwork_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Address of the SVG drawn beside the username. Upload a drawing to fill this in, or paste the address of one already uploaded. Colours are kept as drawn. Leave blank and nothing is drawn.",
                        max_length=500,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        default=0,
                        help_text="Breaks the tie when somebody holds several badges and has not picked one. The supporter tiers rank 1 to 3 and staff ranks 100, so the default of 0 means a supporter keeps showing their supporter badge.",
                    ),
                ),
                (
                    "auto_display",
                    models.BooleanField(
                        default=False,
                        help_text="Show this badge to people who hold it without them choosing it. Leave off for anything granted widely — on, it would appear beside every holder's name the moment it is granted.",
                    ),
                ),
            ],
            options={
                "verbose_name": "badge",
                "verbose_name_plural": "badges",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBadge",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Short name used internally and stored against anyone who picks this badge. Changing it later un-picks the badge for everybody displaying it, so choose it once."
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="What this badge is called, shown in the badge picker.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The one-line explanation shown when somebody hovers the badge. Write it for a reader who has never seen it before.",
                        max_length=200,
                    ),
                ),
                (
                    "artwork_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Address of the SVG drawn beside the username. Upload a drawing to fill this in, or paste the address of one already uploaded. Colours are kept as drawn. Leave blank and nothing is drawn.",
                        max_length=500,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        default=0,
                        help_text="Breaks the tie when somebody holds several badges and has not picked one. The supporter tiers rank 1 to 3 and staff ranks 100, so the default of 0 means a supporter keeps showing their supporter badge.",
                    ),
                ),
                (
                    "auto_display",
                    models.BooleanField(
                        default=False,
                        help_text="Show this badge to people who hold it without them choosing it. Leave off for anything granted widely — on, it would appear beside every holder's name the moment it is granted.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical badge",
                "verbose_name_plural": "historical badges",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBadgeGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("user", "A single person"), ("everyone", "Everyone")],
                        default="user",
                        help_text="Who this grant covers. Granting to everyone adds the badge to every account's picker; it changes nobody's displayed badge unless the badge is set to show automatically.",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why this was granted. Internal note — never shown to anyone.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.badge",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The person granted the badge. Leave blank when granting to everyone.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical badge grant",
                "verbose_name_plural": "historical badge grants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="BadgeGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[("user", "A single person"), ("everyone", "Everyone")],
                        default="user",
                        help_text="Who this grant covers. Granting to everyone adds the badge to every account's picker; it changes nobody's displayed badge unless the badge is set to show automatically.",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why this was granted. Internal note — never shown to anyone.",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="accounts.badge",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="badges_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person granted the badge. Leave blank when granting to everyone.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "badge grant",
                "verbose_name_plural": "badge grants",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("audience", "user"), ("user__isnull", False)),
                            models.Q(("audience", "everyone"), ("user__isnull", True)),
                            _connector="OR",
                        ),
                        name="badgegrant_user_matches_audience",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("audience", "user")),
                        fields=("badge", "user"),
                        name="badgegrant_one_per_person",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("audience", "everyone")),
                        fields=("badge",),
                        name="badgegrant_one_everyone",
                    ),
                ],
            },
        ),
    ]
