# Generated by Django 6.0.7 on 2026-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_badge_and_badgegrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserprofile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone used when showing timestamps. Blank until detected from the browser or IP country, or chosen on the account page.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone used when showing timestamps. Blank until detected from the browser or IP country, or chosen on the account page.",
                max_length=64,
            ),
        ),
    ]
