from django.urls import path

import gyrinx.core.views

from .views import battle, campaign, list, print_config, vehicle

# Name new URLs like this:
# * Transaction pages: noun[-noun]-verb
# * Index pages should pluralize the noun: noun[-noun]s
# * Detail pages should be singular: noun[-noun]

app_name = "core"
urlpatterns = [
    path("", gyrinx.core.views.index, name="index"),
    path("accounts/", gyrinx.core.views.account_home, name="account_home"),
    path(
        "accounts/change-username/",
        gyrinx.core.views.change_username,
        name="change-username",
    ),
    path("dice/", gyrinx.core.views.dice, name="dice"),
    path("lists/", list.ListsListView.as_view(), name="lists"),
    path("lists/new", list.new_list, name="lists-new"),
    path("list/<id>", list.ListDetailView.as_view(), name="list"),
    path("list/<id>/perf", list.ListPerformanceView.as_view(), name="list-performance"),
    path("list/<id>/about", list.ListAboutDetailView.as_view(), name="list-about"),
    path("list/<id>/archive", list.archive_list, name="list-archive"),
    path("list/<id>/show-stash", list.show_stash, name="list-show-stash"),
    path("list/<id>/refresh-cost", list.refresh_list_cost, name="list-refresh-cost"),
    path("list/<id>/edit", list.edit_list, name="list-edit"),
    path("list/<id>/credits", list.edit_list_credits, name="list-credits-edit"),
    path("list/<id>/clone", list.clone_list, name="list-clone"),
    path("list/<id>/invitations", list.list_invitations, name="list-invitations"),
    path(
        "list/<id>/invitations/<invitation_id>/accept",
        list.accept_invitation,
        name="invitation-accept",
    ),
    path(
        "list/<id>/invitations/<invitation_id>/decline",
        list.decline_invitation,
        name="invitation-decline",
    ),
    path("list/<id>/fighters/new", list.new_list_fighter, name="list-fighter-new"),
    path("list/<id>/vehicles/new", vehicle.new_vehicle, name="list-vehicle-new"),
    path(
        "list/<id>/vehicles/new/select",
        vehicle.vehicle_select,
        name="list-vehicle-select",
    ),
    path("list/<id>/vehicles/new/crew", vehicle.vehicle_crew, name="list-vehicle-crew"),
    path(
        "list/<id>/vehicles/new/confirm",
        vehicle.vehicle_confirm,
        name="list-vehicle-confirm",
    ),
    path(
        "list/<id>/fighters/archived",
        list.ListArchivedFightersView.as_view(),
        name="list-archived-fighters",
    ),
    path(
        "list/<id>/fighter/<fighter_id>",
        list.edit_list_fighter,
        name="list-fighter-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/clone",
        list.clone_list_fighter,
        name="list-fighter-clone",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills",
        list.edit_list_fighter_skills,
        name="list-fighter-skills-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills/<skill_id>/toggle",
        list.toggle_list_fighter_skill,
        name="list-fighter-skill-toggle",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills/add",
        list.add_list_fighter_skill,
        name="list-fighter-skill-add",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills/<skill_id>/remove",
        list.remove_list_fighter_skill,
        name="list-fighter-skill-remove",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules",
        list.edit_list_fighter_rules,
        name="list-fighter-rules-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules/<rule_id>/toggle",
        list.toggle_list_fighter_rule,
        name="list-fighter-rule-toggle",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules/add",
        list.add_list_fighter_rule,
        name="list-fighter-rule-add",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules/<rule_id>/remove",
        list.remove_list_fighter_rule,
        name="list-fighter-rule-remove",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/powers",
        list.edit_list_fighter_powers,
        name="list-fighter-powers-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/narrative",
        list.edit_list_fighter_narrative,
        name="list-fighter-narrative-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/info",
        list.edit_list_fighter_info,
        name="list-fighter-info-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/stats",
        list.list_fighter_stats_edit,
        name="list-fighter-stats-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear",
        list.edit_list_fighter_equipment,
        name="list-fighter-gear-edit",
        kwargs=dict(
            is_weapon=False,
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/cost",
        list.edit_list_fighter_assign_cost,
        name="list-fighter-gear-cost-edit",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-cost-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/delete",
        list.delete_list_fighter_assign,
        name="list-fighter-gear-delete",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-delete",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/reassign",
        list.reassign_list_fighter_equipment,
        name="list-fighter-gear-reassign",
        kwargs=dict(
            is_weapon=False,
            back_name="core:list-fighter-gear-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/sell",
        list.sell_list_fighter_equipment,
        name="list-fighter-equipment-sell",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/upgrade",
        list.edit_list_fighter_weapon_upgrade,
        name="list-fighter-gear-upgrade-edit",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-upgrade-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/upgrade/<upgrade_id>/delete",
        list.delete_list_fighter_gear_upgrade,
        name="list-fighter-gear-upgrade-delete",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-upgrade-delete",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/disable",
        list.disable_list_fighter_default_assign,
        name="list-fighter-gear-default-disable",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-default-disable",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/convert",
        list.convert_list_fighter_default_assign,
        name="list-fighter-gear-default-convert",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-default-convert",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/disable",
        list.disable_list_fighter_default_assign,
        name="list-fighter-weapons-default-disable",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapons-default-disable",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/convert",
        list.convert_list_fighter_default_assign,
        name="list-fighter-weapons-default-convert",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapons-default-convert",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/archive",
        list.archive_list_fighter,
        name="list-fighter-archive",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/kill",
        list.kill_list_fighter,
        name="list-fighter-kill",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/resurrect",
        list.resurrect_list_fighter,
        name="list-fighter-resurrect",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/delete",
        list.delete_list_fighter,
        name="list-fighter-delete",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons",
        list.edit_list_fighter_equipment,
        name="list-fighter-weapons-edit",
        kwargs=dict(
            is_weapon=True,
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/cost",
        list.edit_list_fighter_assign_cost,
        name="list-fighter-weapon-cost-edit",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapon-cost-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/delete",
        list.delete_list_fighter_assign,
        name="list-fighter-weapon-delete",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapon-delete",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/reassign",
        list.reassign_list_fighter_equipment,
        name="list-fighter-weapon-reassign",
        kwargs=dict(
            is_weapon=True,
            back_name="core:list-fighter-weapons-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/accessories",
        list.edit_list_fighter_weapon_accessories,
        name="list-fighter-weapon-accessories-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/edit",
        list.edit_single_weapon,
        name="list-fighter-weapon-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/profile/<profile_id>/delete",
        list.delete_list_fighter_weapon_profile,
        name="list-fighter-weapon-profile-delete",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/accessory/<accessory_id>/delete",
        list.delete_list_fighter_weapon_accessory,
        name="list-fighter-weapon-accessory-delete",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/upgrade",
        list.edit_list_fighter_weapon_upgrade,
        name="list-fighter-weapon-upgrade-edit",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapon-upgrade-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/injuries",
        list.list_fighter_injuries_edit,
        name="list-fighter-injuries-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/xp",
        list.edit_list_fighter_xp,
        name="list-fighter-xp-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/mark-captured",
        list.mark_fighter_captured,
        name="list-fighter-mark-captured",
    ),
    # Fighter advancements
    path(
        "list/<id>/fighter/<fighter_id>/advancements/",
        list.list_fighter_advancements,
        name="list-fighter-advancements",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new",
        list.list_fighter_advancement_start,
        name="list-fighter-advancement-start",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/dice",
        list.list_fighter_advancement_dice_choice,
        name="list-fighter-advancement-dice-choice",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/type",
        list.list_fighter_advancement_type,
        name="list-fighter-advancement-type",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/select",
        list.list_fighter_advancement_select,
        name="list-fighter-advancement-select",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/other",
        list.list_fighter_advancement_other,
        name="list-fighter-advancement-other",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/confirm",
        list.list_fighter_advancement_confirm,
        name="list-fighter-advancement-confirm",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/<advancement_id>/delete",
        list.delete_list_fighter_advancement,
        name="list-fighter-advancement-delete",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/state/edit",
        list.list_fighter_state_edit,
        name="list-fighter-state-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/injury/add",
        list.list_fighter_add_injury,
        name="list-fighter-injury-add",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/injury/<injury_id>/remove",
        list.list_fighter_remove_injury,
        name="list-fighter-injury-remove",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/embed",
        list.embed_list_fighter,
        name="list-fighter-embed",
    ),
    path("list/<id>/print", list.ListPrintView.as_view(), name="list-print"),
    path(
        "list/<list_id>/print-configs",
        print_config.PrintConfigIndexView.as_view(),
        name="print-config-index",
    ),
    path(
        "list/<list_id>/print-configs/new",
        print_config.print_config_create,
        name="print-config-create",
    ),
    path(
        "list/<list_id>/print-configs/<config_id>/edit",
        print_config.print_config_edit,
        name="print-config-edit",
    ),
    path(
        "list/<list_id>/print-configs/<config_id>/delete",
        print_config.print_config_delete,
        name="print-config-delete",
    ),
    path(
        "list/<list_id>/print-configs/<config_id>/print",
        print_config.print_config_print,
        name="print-config-print",
    ),
    path(
        "list/<id>/attribute/<attribute_id>/edit",
        list.edit_list_attribute,
        name="list-attribute-edit",
    ),
    path(
        "list/<id>/campaign-clones",
        list.ListCampaignClonesView.as_view(),
        name="list-campaign-clones",
    ),
    # Users
    path("user/<slug_or_id>", gyrinx.core.views.user, name="user"),
    # Campaigns
    path("campaigns/", campaign.Campaigns.as_view(), name="campaigns"),
    path("campaigns/new/", campaign.new_campaign, name="campaigns-new"),
    path("campaign/<id>", campaign.CampaignDetailView.as_view(), name="campaign"),
    path("campaign/<id>/edit/", campaign.edit_campaign, name="campaign-edit"),
    path(
        "campaign/<id>/lists/add",
        campaign.campaign_add_lists,
        name="campaign-add-lists",
    ),
    path(
        "campaign/<id>/list/<list_id>/remove",
        campaign.campaign_remove_list,
        name="campaign-remove-list",
    ),
    path(
        "campaign/<id>/action/new",
        campaign.campaign_log_action,
        name="campaign-action-new",
    ),
    path(
        "campaign/<id>/action/<action_id>/outcome",
        campaign.campaign_action_outcome,
        name="campaign-action-outcome",
    ),
    path(
        "campaign/<id>/actions",
        campaign.CampaignActionList.as_view(),
        name="campaign-actions",
    ),
    path(
        "campaign/<id>/start",
        campaign.start_campaign,
        name="campaign-start",
    ),
    path(
        "campaign/<id>/end",
        campaign.end_campaign,
        name="campaign-end",
    ),
    path(
        "campaign/<id>/reopen",
        campaign.reopen_campaign,
        name="campaign-reopen",
    ),
    path(
        "campaign/<id>/archive",
        campaign.archive_campaign,
        name="campaign-archive",
    ),
    # Campaign Copy
    path(
        "campaign/<id>/copy-in",
        campaign.campaign_copy_from,
        name="campaign-copy-in",
    ),
    path(
        "campaign/<id>/copy-out",
        campaign.campaign_copy_to,
        name="campaign-copy-out",
    ),
    # Campaign Assets
    path(
        "campaign/<id>/assets",
        campaign.campaign_assets,
        name="campaign-assets",
    ),
    path(
        "campaign/<id>/assets/type/new",
        campaign.campaign_asset_type_new,
        name="campaign-asset-type-new",
    ),
    path(
        "campaign/<id>/assets/type/<type_id>/edit",
        campaign.campaign_asset_type_edit,
        name="campaign-asset-type-edit",
    ),
    path(
        "campaign/<id>/assets/type/<type_id>/remove",
        campaign.campaign_asset_type_remove,
        name="campaign-asset-type-remove",
    ),
    path(
        "campaign/<id>/assets/type/<type_id>/new",
        campaign.campaign_asset_new,
        name="campaign-asset-new",
    ),
    path(
        "campaign/<id>/assets/<asset_id>/edit",
        campaign.campaign_asset_edit,
        name="campaign-asset-edit",
    ),
    path(
        "campaign/<id>/assets/<asset_id>/transfer",
        campaign.campaign_asset_transfer,
        name="campaign-asset-transfer",
    ),
    path(
        "campaign/<id>/assets/<asset_id>/remove",
        campaign.campaign_asset_remove,
        name="campaign-asset-remove",
    ),
    # Campaign Sub-Assets
    path(
        "campaign/<id>/assets/<asset_id>/sub-asset/<sub_asset_type>/new",
        campaign.campaign_sub_asset_new,
        name="campaign-sub-asset-new",
    ),
    path(
        "campaign/<id>/assets/<asset_id>/sub-asset/<sub_asset_id>/edit",
        campaign.campaign_sub_asset_edit,
        name="campaign-sub-asset-edit",
    ),
    path(
        "campaign/<id>/assets/<asset_id>/sub-asset/<sub_asset_id>/remove",
        campaign.campaign_sub_asset_remove,
        name="campaign-sub-asset-remove",
    ),
    # Campaign Resources
    path(
        "campaign/<id>/resources",
        campaign.campaign_resources,
        name="campaign-resources",
    ),
    path(
        "campaign/<id>/resources/type/new",
        campaign.campaign_resource_type_new,
        name="campaign-resource-type-new",
    ),
    path(
        "campaign/<id>/resources/type/<type_id>/edit",
        campaign.campaign_resource_type_edit,
        name="campaign-resource-type-edit",
    ),
    path(
        "campaign/<id>/resources/type/<type_id>/remove",
        campaign.campaign_resource_type_remove,
        name="campaign-resource-type-remove",
    ),
    path(
        "campaign/<id>/resources/<resource_id>/modify",
        campaign.campaign_resource_modify,
        name="campaign-resource-modify",
    ),
    # Battles
    path(
        "campaign/<id>/battles",
        campaign.campaign_battles,
        name="campaign-battles",
    ),
    path(
        "battle/<id>",
        battle.BattleDetailView.as_view(),
        name="battle",
    ),
    path(
        "campaign/<campaign_id>/battles/new",
        battle.new_battle,
        name="battle-new",
    ),
    path(
        "battle/<id>/edit",
        battle.edit_battle,
        name="battle-edit",
    ),
    path(
        "battle/<battle_id>/notes/add",
        battle.add_battle_note,
        name="battle-note-add",
    ),
    # Captured fighters
    path(
        "campaign/<id>/captured-fighters",
        campaign.campaign_captured_fighters,
        name="campaign-captured-fighters",
    ),
    path(
        "campaign/<id>/fighter/<fighter_id>/sell-to-guilders",
        campaign.fighter_sell_to_guilders,
        name="fighter-sell-to-guilders",
    ),
    path(
        "campaign/<id>/fighter/<fighter_id>/return-to-owner",
        campaign.fighter_return_to_owner,
        name="fighter-return-to-owner",
    ),
    path(
        "campaign/<id>/fighter/<fighter_id>/release",
        campaign.fighter_release,
        name="fighter-release",
    ),
    # TinyMCE upload
    path(
        "tinymce/upload/",
        gyrinx.core.views.tinymce_upload,
        name="tinymce-upload",
    ),
    # Banner dismissal
    path(
        "banner/dismiss/",
        gyrinx.core.views.dismiss_banner,
        name="dismiss-banner",
    ),
    # Banner click tracking
    path(
        "banner/<id>/click/",
        gyrinx.core.views.track_banner_click,
        name="track-banner-click",
    ),
]
