from django.urls import path

from ..views.fighter import advancements as fighter_advancements
from ..views.fighter import counters as fighter_counters
from ..views.fighter import crud as fighter_crud
from ..views.fighter import equipment as fighter_equipment
from ..views.fighter import narrative as fighter_narrative
from ..views.fighter import powers as fighter_powers
from ..views.fighter import rules as fighter_rules
from ..views.fighter import skills as fighter_skills
from ..views.fighter import state as fighter_state
from ..views.fighter import stats as fighter_stats
from ..views.fighter import xp as fighter_xp

patterns = [
    path(
        "list/<id>/fighters/new", fighter_crud.new_list_fighter, name="list-fighter-new"
    ),
    path(
        "list/<id>/fighters/archived",
        fighter_crud.ListArchivedFightersView.as_view(),
        name="list-archived-fighters",
    ),
    path(
        "list/<id>/fighter/<fighter_id>",
        fighter_crud.edit_list_fighter,
        name="list-fighter-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/clone",
        fighter_crud.clone_list_fighter,
        name="list-fighter-clone",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills",
        fighter_skills.edit_list_fighter_skills,
        name="list-fighter-skills-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills/<skill_id>/toggle",
        fighter_skills.toggle_list_fighter_skill,
        name="list-fighter-skill-toggle",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills/add",
        fighter_skills.add_list_fighter_skill,
        name="list-fighter-skill-add",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/skills/<skill_id>/remove",
        fighter_skills.remove_list_fighter_skill,
        name="list-fighter-skill-remove",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules",
        fighter_rules.edit_list_fighter_rules,
        name="list-fighter-rules-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules/<rule_id>/toggle",
        fighter_rules.toggle_list_fighter_rule,
        name="list-fighter-rule-toggle",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules/add",
        fighter_rules.add_list_fighter_rule,
        name="list-fighter-rule-add",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/rules/<rule_id>/remove",
        fighter_rules.remove_list_fighter_rule,
        name="list-fighter-rule-remove",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/powers",
        fighter_powers.edit_list_fighter_powers,
        name="list-fighter-powers-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/narrative",
        fighter_narrative.edit_list_fighter_narrative,
        name="list-fighter-narrative-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/notes",
        fighter_narrative.edit_list_fighter_notes,
        name="list-fighter-notes-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/stats",
        fighter_stats.list_fighter_stats_edit,
        name="list-fighter-stats-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear",
        fighter_equipment.edit_list_fighter_equipment,
        name="list-fighter-gear-edit",
        kwargs=dict(
            is_weapon=False,
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/cost",
        fighter_equipment.edit_list_fighter_assign_cost,
        name="list-fighter-gear-cost-edit",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-cost-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/delete",
        fighter_equipment.delete_list_fighter_assign,
        name="list-fighter-gear-delete",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-delete",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/reassign",
        fighter_equipment.reassign_list_fighter_equipment,
        name="list-fighter-gear-reassign",
        kwargs=dict(
            is_weapon=False,
            back_name="core:list-fighter-gear-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/sell",
        fighter_equipment.sell_list_fighter_equipment,
        name="list-fighter-equipment-sell",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/upgrade",
        fighter_equipment.edit_list_fighter_weapon_upgrade,
        name="list-fighter-gear-upgrade-edit",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-upgrade-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/upgrade/<upgrade_id>/delete",
        fighter_equipment.delete_list_fighter_gear_upgrade,
        name="list-fighter-gear-upgrade-delete",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-upgrade-delete",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/disable",
        fighter_equipment.disable_list_fighter_default_assign,
        name="list-fighter-gear-default-disable",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-default-disable",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/gear/<assign_id>/convert",
        fighter_equipment.convert_list_fighter_default_assign,
        name="list-fighter-gear-default-convert",
        kwargs=dict(
            back_name="core:list-fighter-gear-edit",
            action_name="core:list-fighter-gear-default-convert",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/disable",
        fighter_equipment.disable_list_fighter_default_assign,
        name="list-fighter-weapons-default-disable",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapons-default-disable",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/convert",
        fighter_equipment.convert_list_fighter_default_assign,
        name="list-fighter-weapons-default-convert",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapons-default-convert",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/archive",
        fighter_crud.archive_list_fighter,
        name="list-fighter-archive",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/restore",
        fighter_crud.restore_list_fighter,
        name="list-fighter-restore",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/kill",
        fighter_crud.kill_list_fighter,
        name="list-fighter-kill",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/resurrect",
        fighter_crud.resurrect_list_fighter,
        name="list-fighter-resurrect",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/delete",
        fighter_crud.delete_list_fighter,
        name="list-fighter-delete",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons",
        fighter_equipment.edit_list_fighter_equipment,
        name="list-fighter-weapons-edit",
        kwargs=dict(
            is_weapon=True,
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/cost",
        fighter_equipment.edit_list_fighter_assign_cost,
        name="list-fighter-weapon-cost-edit",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapon-cost-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/delete",
        fighter_equipment.delete_list_fighter_assign,
        name="list-fighter-weapon-delete",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapon-delete",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/reassign",
        fighter_equipment.reassign_list_fighter_equipment,
        name="list-fighter-weapon-reassign",
        kwargs=dict(
            is_weapon=True,
            back_name="core:list-fighter-weapons-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/accessories",
        fighter_equipment.edit_list_fighter_weapon_accessories,
        name="list-fighter-weapon-accessories-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/edit",
        fighter_equipment.edit_single_weapon,
        name="list-fighter-weapon-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/profile/<profile_id>/delete",
        fighter_equipment.delete_list_fighter_weapon_profile,
        name="list-fighter-weapon-profile-delete",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/accessory/<accessory_id>/delete",
        fighter_equipment.delete_list_fighter_weapon_accessory,
        name="list-fighter-weapon-accessory-delete",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/weapons/<assign_id>/upgrade",
        fighter_equipment.edit_list_fighter_weapon_upgrade,
        name="list-fighter-weapon-upgrade-edit",
        kwargs=dict(
            back_name="core:list-fighter-weapons-edit",
            action_name="core:list-fighter-weapon-upgrade-edit",
        ),
    ),
    path(
        "list/<id>/fighter/<fighter_id>/injuries",
        fighter_state.list_fighter_injuries_edit,
        name="list-fighter-injuries-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/xp",
        fighter_xp.edit_list_fighter_xp,
        name="list-fighter-xp-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/counter/<counter_id>",
        fighter_counters.edit_list_fighter_counter,
        name="list-fighter-counter-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/mark-captured",
        fighter_state.mark_fighter_captured,
        name="list-fighter-mark-captured",
    ),
    # Fighter advancements
    path(
        "list/<id>/fighter/<fighter_id>/advancements/",
        fighter_advancements.list_fighter_advancements,
        name="list-fighter-advancements",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new",
        fighter_advancements.list_fighter_advancement_start,
        name="list-fighter-advancement-start",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/dice",
        fighter_advancements.list_fighter_advancement_dice_choice,
        name="list-fighter-advancement-dice-choice",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/type",
        fighter_advancements.list_fighter_advancement_type,
        name="list-fighter-advancement-type",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/select",
        fighter_advancements.list_fighter_advancement_select,
        name="list-fighter-advancement-select",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/other",
        fighter_advancements.list_fighter_advancement_other,
        name="list-fighter-advancement-other",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/new/confirm",
        fighter_advancements.list_fighter_advancement_confirm,
        name="list-fighter-advancement-confirm",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/advancements/<advancement_id>/delete",
        fighter_advancements.delete_list_fighter_advancement,
        name="list-fighter-advancement-delete",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/state/edit",
        fighter_state.list_fighter_state_edit,
        name="list-fighter-state-edit",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/injury/add",
        fighter_state.list_fighter_add_injury,
        name="list-fighter-injury-add",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/injury/<injury_id>/remove",
        fighter_state.list_fighter_remove_injury,
        name="list-fighter-injury-remove",
    ),
    path(
        "list/<id>/fighter/<fighter_id>/embed",
        fighter_crud.embed_list_fighter,
        name="list-fighter-embed",
    ),
]
