from django.urls import path

from ..views import pack as pack_views

patterns = [
    # Packs (Customisation)
    path("packs/", pack_views.PacksView.as_view(), name="packs"),
    path("packs/new/", pack_views.new_pack, name="packs-new"),
    path("pack/<id>", pack_views.PackDetailView.as_view(), name="pack"),
    path("pack/<id>/edit/", pack_views.edit_pack, name="pack-edit"),
    path(
        "pack/<id>/permissions/",
        pack_views.pack_permissions,
        name="pack-permissions",
    ),
    path("pack/<id>/lists/", pack_views.PackListsView.as_view(), name="pack-lists"),
    path("pack/<id>/campaigns/", pack_views.pack_campaigns, name="pack-campaigns"),
    path("pack/<id>/subscribe/", pack_views.subscribe_pack, name="pack-subscribe"),
    path(
        "pack/<id>/unsubscribe/", pack_views.unsubscribe_pack, name="pack-unsubscribe"
    ),
    path(
        "pack/<id>/campaign-subscribe/",
        pack_views.subscribe_pack_campaign,
        name="pack-campaign-subscribe",
    ),
    path(
        "pack/<id>/campaign-unsubscribe/",
        pack_views.unsubscribe_pack_campaign,
        name="pack-campaign-unsubscribe",
    ),
    path(
        "pack/<id>/activity/",
        pack_views.PackActivityView.as_view(),
        name="pack-activity",
    ),
    path(
        "pack/<id>/add/<content_type_slug>/",
        pack_views.add_pack_item,
        name="pack-add-item",
    ),
    path(
        "pack/<id>/add/weapon/mode/",
        pack_views.add_pack_weapon_mode,
        name="pack-add-weapon-mode",
    ),
    path(
        "pack/<id>/add/fighter/stats/",
        pack_views.add_pack_fighter_stats,
        name="pack-add-fighter-stats",
    ),
    path(
        "pack/<id>/item/<item_id>/edit/",
        pack_views.edit_pack_item,
        name="pack-edit-item",
    ),
    path(
        "pack/<id>/item/<item_id>/modifiers/",
        pack_views.pack_item_modifiers,
        name="pack-item-modifiers",
    ),
    path(
        "pack/<id>/item/<item_id>/equipment/",
        pack_views.pack_item_equipment,
        name="pack-item-equipment",
    ),
    # Aliases for backwards compatibility (redirects from old bookmarks, etc.)
    path(
        "pack/<id>/item/<item_id>/default-equipment/",
        pack_views.pack_item_equipment,
        name="pack-item-default-equipment",
    ),
    path(
        "pack/<id>/item/<item_id>/equipment-list/",
        pack_views.pack_item_equipment,
        name="pack-item-equipment-list",
    ),
    path(
        "pack/<id>/item/<item_id>/delete/",
        pack_views.delete_pack_item,
        name="pack-delete-item",
    ),
    path(
        "pack/<id>/item/<item_id>/restore/",
        pack_views.restore_pack_item,
        name="pack-restore-item",
    ),
    path(
        "pack/<id>/archived/<content_type_slug>/",
        pack_views.PackArchivedItemsView.as_view(),
        name="pack-archived-items",
    ),
    path(
        "pack/<id>/item/<item_id>/profile/add/",
        pack_views.add_weapon_profile,
        name="pack-add-weapon-profile",
    ),
    path(
        "pack/<id>/item/<item_id>/profile/<profile_id>/edit/",
        pack_views.edit_weapon_profile,
        name="pack-edit-weapon-profile",
    ),
    path(
        "pack/<id>/item/<item_id>/profile/<profile_id>/delete/",
        pack_views.delete_weapon_profile,
        name="pack-delete-weapon-profile",
    ),
    path(
        "pack/<id>/item/<item_id>/archived-profiles/",
        pack_views.archived_weapon_profiles,
        name="pack-archived-weapon-profiles",
    ),
    # Customise an existing (library) weapon — add pack-scoped profiles
    # without owning the equipment row.
    path(
        "pack/<id>/customise-weapon/",
        pack_views.customise_weapon_picker,
        name="pack-customise-weapon-picker",
    ),
    path(
        "pack/<id>/customise-weapon/<equipment_id>/",
        pack_views.customise_weapon,
        name="pack-customise-weapon",
    ),
    path(
        "pack/<id>/customise-weapon/<equipment_id>/profile/add/",
        pack_views.add_customised_weapon_profile,
        name="pack-customise-weapon-profile-add",
    ),
    path(
        "pack/<id>/customise-weapon/<equipment_id>/profile/<profile_id>/edit/",
        pack_views.edit_customised_weapon_profile,
        name="pack-customise-weapon-profile-edit",
    ),
    path(
        "pack/<id>/customise-weapon/<equipment_id>/profile/<profile_id>/delete/",
        pack_views.delete_customised_weapon_profile,
        name="pack-customise-weapon-profile-delete",
    ),
    path(
        "pack/<id>/customise-weapon/<equipment_id>/archived-profiles/",
        pack_views.archived_customised_weapon_profiles,
        name="pack-customise-weapon-archived-profiles",
    ),
    # House-rule mod applications
    path(
        "pack/<id>/house-rule/",
        pack_views.house_rule_picker,
        name="pack-house-rule-picker",
    ),
    path(
        "pack/<id>/house-rule/add/",
        pack_views.add_house_rule,
        name="pack-house-rule-add",
    ),
    path(
        "pack/<id>/house-rule/<item_id>/edit/",
        pack_views.edit_house_rule,
        name="pack-house-rule-edit",
    ),
    path(
        "pack/<id>/house-rule/<item_id>/delete/",
        pack_views.delete_house_rule,
        name="pack-house-rule-delete",
    ),
    # Attachments (supplementary files)
    path(
        "pack/<id>/attachments/add/",
        pack_views.add_pack_attachment,
        name="pack-attachment-add",
    ),
    path(
        "pack/<id>/attachments/<attachment_id>/delete/",
        pack_views.delete_pack_attachment,
        name="pack-attachment-delete",
    ),
    path(
        "pack/<id>/item/<item_id>/default-equipment/weapons/add/",
        pack_views.add_pack_fighter_default_weapon,
        name="pack-fighter-default-weapon-add",
    ),
    path(
        "pack/<id>/item/<item_id>/default-equipment/gear/add/",
        pack_views.add_pack_fighter_default_gear,
        name="pack-fighter-default-gear-add",
    ),
    path(
        "pack/<id>/item/<item_id>/default-equipment/<assignment_id>/remove/",
        pack_views.remove_pack_fighter_default_assignment,
        name="pack-fighter-default-assignment-remove",
    ),
    # Pack fighter default psyker powers
    path(
        "pack/<id>/item/<item_id>/default-psyker-powers/",
        pack_views.pack_fighter_default_psyker_powers,
        name="pack-fighter-default-psyker-powers",
    ),
    path(
        "pack/<id>/item/<item_id>/default-psyker-powers/add/",
        pack_views.add_pack_fighter_default_psyker_power,
        name="pack-fighter-default-psyker-power-add",
    ),
    path(
        "pack/<id>/item/<item_id>/default-psyker-powers/<assignment_id>/remove/",
        pack_views.remove_pack_fighter_default_psyker_power,
        name="pack-fighter-default-psyker-power-remove",
    ),
    # Equipment list (available equipment)
    path(
        "pack/<id>/item/<item_id>/equipment-list/weapons/add/",
        pack_views.add_pack_fighter_equipment_list_weapon,
        name="pack-fighter-equipment-list-weapon-add",
    ),
    path(
        "pack/<id>/item/<item_id>/equipment-list/gear/add/",
        pack_views.add_pack_fighter_equipment_list_gear,
        name="pack-fighter-equipment-list-gear-add",
    ),
    path(
        "pack/<id>/item/<item_id>/equipment-list/<eli_id>/remove/",
        pack_views.remove_pack_fighter_equipment_list_item,
        name="pack-fighter-equipment-list-item-remove",
    ),
    path(
        "pack/<id>/item/<item_id>/equipment-list/<eli_id>/edit/",
        pack_views.edit_pack_fighter_equipment_list_item,
        name="pack-fighter-equipment-list-edit",
    ),
    path(
        "pack/<id>/item/<item_id>/equipment-list/accessories/add/",
        pack_views.add_pack_fighter_equipment_list_accessory,
        name="pack-fighter-equipment-list-accessory-add",
    ),
    path(
        "pack/<id>/item/<item_id>/equipment-list/accessories/<acc_eli_id>/edit/",
        pack_views.edit_pack_fighter_equipment_list_accessory,
        name="pack-fighter-equipment-list-accessory-edit",
    ),
    path(
        "pack/<id>/item/<item_id>/equipment-list/accessories/<acc_eli_id>/remove/",
        pack_views.remove_pack_fighter_equipment_list_accessory,
        name="pack-fighter-equipment-list-accessory-remove",
    ),
]
