# Generated by Django 5.2.4 on 2025-07-18 10:16

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0122_add_hide_flags_to_contentfighter"),
        ("core", "0082_add_user_profile_for_tos_agreement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalListFighterStatOverride",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "value",
                    models.CharField(
                        help_text="The overridden stat value (e.g., '5\"', '12', '4+', '-')",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_stat",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The stat being overridden",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentstatlinetypestat",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list_fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The ListFighter this override applies to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical List Fighter Stat Override",
                "verbose_name_plural": "historical List Fighter Stat Overrides",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ListFighterStatOverride",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        help_text="The overridden stat value (e.g., '5\"', '12', '4+', '-')",
                        max_length=10,
                    ),
                ),
                (
                    "content_stat",
                    models.ForeignKey(
                        help_text="The stat being overridden",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.contentstatlinetypestat",
                    ),
                ),
                (
                    "list_fighter",
                    models.ForeignKey(
                        help_text="The ListFighter this override applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_overrides",
                        to="core.listfighter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "List Fighter Stat Override",
                "verbose_name_plural": "List Fighter Stat Overrides",
                "ordering": ["content_stat__position"],
                "unique_together": {("list_fighter", "content_stat")},
            },
        ),
    ]
