# Generated by Django 5.2.4 on 2025-07-23 22:19

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_alter_event_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.TextField(help_text="The main message text of the banner"),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        help_text="Call-to-action button text (e.g., 'Learn More')",
                        max_length=255,
                    ),
                ),
                (
                    "cta_url",
                    models.URLField(
                        blank=True, help_text="URL that the CTA button links to"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g., 'bi-info-circle')",
                        max_length=50,
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("primary", "Primary (Blue)"),
                            ("secondary", "Secondary (Gray)"),
                            ("success", "Success (Green)"),
                            ("danger", "Danger (Red)"),
                            ("warning", "Warning (Yellow)"),
                            ("info", "Info (Light Blue)"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="info",
                        help_text="Bootstrap colour/priority for the banner",
                        max_length=20,
                    ),
                ),
                (
                    "is_live",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this banner is currently live. Only one banner can be live at a time.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBanner",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "text",
                    models.TextField(help_text="The main message text of the banner"),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        help_text="Call-to-action button text (e.g., 'Learn More')",
                        max_length=255,
                    ),
                ),
                (
                    "cta_url",
                    models.URLField(
                        blank=True, help_text="URL that the CTA button links to"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g., 'bi-info-circle')",
                        max_length=50,
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("primary", "Primary (Blue)"),
                            ("secondary", "Secondary (Gray)"),
                            ("success", "Success (Green)"),
                            ("danger", "Danger (Red)"),
                            ("warning", "Warning (Yellow)"),
                            ("info", "Info (Light Blue)"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="info",
                        help_text="Bootstrap colour/priority for the banner",
                        max_length=20,
                    ),
                ),
                (
                    "is_live",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this banner is currently live. Only one banner can be live at a time.",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Banner",
                "verbose_name_plural": "historical Banners",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
