# Generated by Django 5.2.4 on 2025-08-01 13:25

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_add_banner_click_tracking_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPrintConfig",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this print configuration.",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "include_assets",
                    models.BooleanField(
                        default=True,
                        help_text="Include asset cards in the print output.",
                    ),
                ),
                (
                    "include_attributes",
                    models.BooleanField(
                        default=True,
                        help_text="Include attribute cards in the print output.",
                    ),
                ),
                (
                    "include_stash",
                    models.BooleanField(
                        default=True,
                        help_text="Include stash cards in the print output.",
                    ),
                ),
                (
                    "include_actions",
                    models.BooleanField(
                        default=False,
                        help_text="Include action cards in the print output.",
                    ),
                ),
                (
                    "include_dead_fighters",
                    models.BooleanField(
                        default=False,
                        help_text="Include dead fighters in the print output.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The list this print configuration belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.list",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Print Configuration",
                "verbose_name_plural": "historical Print Configurations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PrintConfig",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this print configuration.",
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "include_assets",
                    models.BooleanField(
                        default=True,
                        help_text="Include asset cards in the print output.",
                    ),
                ),
                (
                    "include_attributes",
                    models.BooleanField(
                        default=True,
                        help_text="Include attribute cards in the print output.",
                    ),
                ),
                (
                    "include_stash",
                    models.BooleanField(
                        default=True,
                        help_text="Include stash cards in the print output.",
                    ),
                ),
                (
                    "include_actions",
                    models.BooleanField(
                        default=False,
                        help_text="Include action cards in the print output.",
                    ),
                ),
                (
                    "include_dead_fighters",
                    models.BooleanField(
                        default=False,
                        help_text="Include dead fighters in the print output.",
                    ),
                ),
                (
                    "included_fighters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific fighters to include in the print output.",
                        related_name="print_configs",
                        to="core.listfighter",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        help_text="The list this print configuration belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_configs",
                        to="core.list",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Print Configuration",
                "verbose_name_plural": "Print Configurations",
                "ordering": ["name"],
            },
        ),
    ]
