# Generated by Django 5.2.4 on 2025-08-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_add_print_config_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprintconfig",
            name="include_actions",
            field=models.BooleanField(
                default=False, help_text="Include the action card in the print output."
            ),
        ),
        migrations.AlterField(
            model_name="historicalprintconfig",
            name="include_assets",
            field=models.BooleanField(
                default=True, help_text="Include asset card in the print output."
            ),
        ),
        migrations.AlterField(
            model_name="historicalprintconfig",
            name="include_attributes",
            field=models.BooleanField(
                default=True, help_text="Include attribute card in the print output."
            ),
        ),
        migrations.AlterField(
            model_name="historicalprintconfig",
            name="include_stash",
            field=models.BooleanField(
                default=True, help_text="Include the stash card in the print output."
            ),
        ),
        migrations.AlterField(
            model_name="printconfig",
            name="include_actions",
            field=models.BooleanField(
                default=False, help_text="Include the action card in the print output."
            ),
        ),
        migrations.AlterField(
            model_name="printconfig",
            name="include_assets",
            field=models.BooleanField(
                default=True, help_text="Include asset card in the print output."
            ),
        ),
        migrations.AlterField(
            model_name="printconfig",
            name="include_attributes",
            field=models.BooleanField(
                default=True, help_text="Include attribute card in the print output."
            ),
        ),
        migrations.AlterField(
            model_name="printconfig",
            name="include_stash",
            field=models.BooleanField(
                default=True, help_text="Include the stash card in the print output."
            ),
        ),
    ]
