# Generated by Django 5.2.6 on 2025-09-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0149_contentadvancementequipment_and_more"),
        ("core", "0103_remove_stat_choices_from_advancement"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighteradvancement",
            name="equipment_assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="For equipment advancements, which assignment configuration was selected.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="content.contentadvancementassignment",
            ),
        ),
        migrations.AddField(
            model_name="listfighteradvancement",
            name="equipment_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="For equipment advancements, which assignment configuration was selected.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.contentadvancementassignment",
            ),
        ),
        migrations.AlterField(
            model_name="historicallistfighteradvancement",
            name="advancement_type",
            field=models.CharField(
                choices=[
                    ("stat", "Characteristic Increase"),
                    ("skill", "New Skill"),
                    ("equipment", "New Equipment"),
                    ("other", "Other"),
                ],
                help_text="The type of advancement purchased.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="listfighteradvancement",
            name="advancement_type",
            field=models.CharField(
                choices=[
                    ("stat", "Characteristic Increase"),
                    ("skill", "New Skill"),
                    ("equipment", "New Equipment"),
                    ("other", "Other"),
                ],
                help_text="The type of advancement purchased.",
                max_length=10,
            ),
        ),
    ]
