# Generated by Django 5.2.5 on 2025-09-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_rename_linked_fighter_to_child_fighter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listfighterequipmentassignment",
            name="child_fighter",
            field=models.ForeignKey(
                blank=True,
                help_text="The ListFighter that this Equipment assignment is linked to (e.g. Exotic Beast, Vehicle).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_assignment",
                to="core.listfighter",
            ),
        ),
    ]
