# Generated by Django 5.2.6 on 2025-09-13 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_historicallistfighteradvancement_equipment_assignment_and_more"),
        ("core", "0105_alter_listfighterequipmentassignment_child_fighter"),
    ]

    operations = []
