# Generated by Django 5.2.6 on 2025-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0106_merge_20250913_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistfighteradvancement",
            name="advancement_choice",
            field=models.CharField(
                blank=True,
                help_text="The option selected in the advancement form",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listfighteradvancement",
            name="advancement_choice",
            field=models.CharField(
                blank=True,
                help_text="The option selected in the advancement form",
                max_length=100,
                null=True,
            ),
        ),
    ]
