# Generated by Django 5.2.7 on 2025-11-03 06:45

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0107_historicallistfighteradvancement_advancement_choice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallist",
            name="rating_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Current rating of the list"
            ),
        ),
        migrations.AddField(
            model_name="historicallist",
            name="stash_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Current stash value of the list"
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="rating_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Current rating of the list"
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="stash_current",
            field=models.PositiveIntegerField(
                default=0, help_text="Current stash value of the list"
            ),
        ),
        migrations.AlterField(
            model_name="historicallist",
            name="credits_current",
            field=models.IntegerField(default=0, help_text="Current credits available"),
        ),
        migrations.AlterField(
            model_name="list",
            name="credits_current",
            field=models.IntegerField(default=0, help_text="Current credits available"),
        ),
        migrations.CreateModel(
            name="HistoricalListAction",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("ADD_FIGHTER", "Add Fighter"),
                            ("REMOVE_FIGHTER", "Remove Fighter"),
                            ("UPDATE_FIGHTER", "Update Fighter"),
                            ("ADD_EQUIPMENT", "Add Equipment"),
                            ("REMOVE_EQUIPMENT", "Remove Equipment"),
                            ("UPDATE_EQUIPMENT", "Update Equipment"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "subject_app",
                    models.CharField(
                        blank=True,
                        help_text="The app that the model subject_type belongs to. First argument of apps.get_model.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        blank=True,
                        help_text="The model type of the subject involved in the action. Second argument of apps.get_model.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "subject_id",
                    models.UUIDField(
                        blank=True,
                        help_text="The UUID of the subject involved in the action.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A textual description of the action performed. May be user-facing.",
                        null=True,
                    ),
                ),
                (
                    "rating_delta",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Credits transacted during this action into list rating.",
                    ),
                ),
                (
                    "stash_delta",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Credits transacted during this action into list stash.",
                    ),
                ),
                (
                    "credits_delta",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Credits transacted during this action overall.",
                    ),
                ),
                (
                    "rating_before",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The list rating before this action was performed.",
                    ),
                ),
                (
                    "stash_before",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The list stash value before this action was performed.",
                    ),
                ),
                (
                    "credits_before",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The list credits before this action was performed.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.list",
                    ),
                ),
                (
                    "list_fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The ListFighter involved in this action, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighter",
                    ),
                ),
                (
                    "list_fighter_equipment_assignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The ListFighterEquipmentAssignment involved in this action, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighterequipmentassignment",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical list action",
                "verbose_name_plural": "historical list actions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ListAction",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("ADD_FIGHTER", "Add Fighter"),
                            ("REMOVE_FIGHTER", "Remove Fighter"),
                            ("UPDATE_FIGHTER", "Update Fighter"),
                            ("ADD_EQUIPMENT", "Add Equipment"),
                            ("REMOVE_EQUIPMENT", "Remove Equipment"),
                            ("UPDATE_EQUIPMENT", "Update Equipment"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "subject_app",
                    models.CharField(
                        blank=True,
                        help_text="The app that the model subject_type belongs to. First argument of apps.get_model.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        blank=True,
                        help_text="The model type of the subject involved in the action. Second argument of apps.get_model.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "subject_id",
                    models.UUIDField(
                        blank=True,
                        help_text="The UUID of the subject involved in the action.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A textual description of the action performed. May be user-facing.",
                        null=True,
                    ),
                ),
                (
                    "rating_delta",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Credits transacted during this action into list rating.",
                    ),
                ),
                (
                    "stash_delta",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Credits transacted during this action into list stash.",
                    ),
                ),
                (
                    "credits_delta",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Credits transacted during this action overall.",
                    ),
                ),
                (
                    "rating_before",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The list rating before this action was performed.",
                    ),
                ),
                (
                    "stash_before",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The list stash value before this action was performed.",
                    ),
                ),
                (
                    "credits_before",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The list credits before this action was performed.",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="core.list",
                    ),
                ),
                (
                    "list_fighter",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ListFighter involved in this action, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="core.listfighter",
                    ),
                ),
                (
                    "list_fighter_equipment_assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ListFighterEquipmentAssignment involved in this action, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="core.listfighterequipmentassignment",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "list action",
                "verbose_name_plural": "list actions",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["list_id", "-created", "-id"],
                        name="list_created_id_desc_idx",
                    )
                ],
            },
        ),
    ]
