# Generated by Django 5.2.7 on 2025-11-05 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0108_historicallist_rating_current_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The user who performed this action",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who performed this action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="list_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campaignaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who performed this action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
