# Generated by Django 5.2.7 on 2025-11-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_historicallistaction_user_listaction_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallistaction",
            name="applied",
            field=models.BooleanField(
                default=False,
                help_text="Whether this action has been applied to the list.",
            ),
        ),
        migrations.AddField(
            model_name="listaction",
            name="applied",
            field=models.BooleanField(
                default=False,
                help_text="Whether this action has been applied to the list.",
            ),
        ),
    ]
