# Generated by Django 5.2.7 on 2025-11-11 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0113_historicalprintconfig_blank_fighter_cards_and_more"),
        ("core", "0113_migrate_upgrade_to_upgrades_field"),
    ]

    operations = []
