# Generated by Django 6.0 on 2025-12-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0121_add_dirty_propagation_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="phase",
            field=models.CharField(
                blank=True,
                help_text="Current campaign phase (e.g., 'Occupation', 'Takeover', 'Dominion')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="phase_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about the current phase - special rules, conditions, etc.",
            ),
        ),
        migrations.AddField(
            model_name="campaignasset",
            name="properties",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom properties for this asset (e.g., boons, income, location)",
            ),
        ),
        migrations.AddField(
            model_name="campaignassettype",
            name="property_schema",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Schema defining available properties for assets of this type. Format: [{'key': 'boon', 'label': 'Boon'}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="phase",
            field=models.CharField(
                blank=True,
                help_text="Current campaign phase (e.g., 'Occupation', 'Takeover', 'Dominion')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaign",
            name="phase_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about the current phase - special rules, conditions, etc.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaignasset",
            name="properties",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom properties for this asset (e.g., boons, income, location)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaignassettype",
            name="property_schema",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Schema defining available properties for assets of this type. Format: [{'key': 'boon', 'label': 'Boon'}, ...]",
            ),
        ),
    ]
