# Generated by Django 5.2.8 on 2025-11-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0125_allow_negative_rating_for_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprintconfig",
            name="fighter_selection_mode",
            field=models.CharField(
                choices=[
                    ("all", "All current & future fighters"),
                    ("specific", "Specific fighters"),
                    ("none", "None"),
                ],
                default="all",
                help_text="How to select which fighters to include in the print output.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="printconfig",
            name="fighter_selection_mode",
            field=models.CharField(
                choices=[
                    ("all", "All current & future fighters"),
                    ("specific", "Specific fighters"),
                    ("none", "None"),
                ],
                default="all",
                help_text="How to select which fighters to include in the print output.",
                max_length=20,
            ),
        ),
    ]
