# Generated by Django 6.0.1 on 2026-02-06 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0126_add_fighter_selection_mode_to_print_config"),
        ("core", "0128_merge_20260206_0808"),
    ]

    operations = []
