# Generated by Django 6.0.2 on 2026-02-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0130_add_list_fighter_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="packs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Content packs subscribed to this list.",
                related_name="subscribed_lists",
                to="core.customcontentpack",
            ),
        ),
    ]
