# Generated by Django 6.0.2 on 2026-02-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0133_add_group_attribute_type_to_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="packs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Content packs allowed for this campaign. Empty means no restrictions.",
                related_name="campaigns",
                to="core.customcontentpack",
            ),
        ),
    ]
