# Generated by Django 6.0.2 on 2026-02-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0135_add_pack_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallist",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Notes about the gang in this list."
            ),
        ),
        migrations.AddField(
            model_name="list",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Notes about the gang in this list."
            ),
        ),
    ]
