# Generated by Django 6.0.6 on 2026-07-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0176_contentmod_unique_constraints"),
        ("core", "0152_component_pin_columns"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="listfighterequipmentassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("pinned_base_amount__isnull", True),
                        ("pinned_base_state", "unpinned"),
                    ),
                    models.Q(
                        models.Q(("pinned_base_state", "unpinned"), _negated=True),
                        ("pinned_base_amount__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="assignment_unpinned_iff_null_base_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="listfighterequipmentassignmentaccessory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("pin_state", "unpinned"), ("pinned_amount__isnull", True)
                    ),
                    models.Q(
                        models.Q(("pin_state", "unpinned"), _negated=True),
                        ("pinned_amount__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="accessory_row_unpinned_iff_null_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="listfighterequipmentassignmentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("pin_state", "unpinned"), ("pinned_amount__isnull", True)
                    ),
                    models.Q(
                        models.Q(("pin_state", "unpinned"), _negated=True),
                        ("pinned_amount__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="profile_row_unpinned_iff_null_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="listfighterequipmentassignmentupgrade",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("pin_state", "unpinned"), ("pinned_amount__isnull", True)
                    ),
                    models.Q(
                        models.Q(("pin_state", "unpinned"), _negated=True),
                        ("pinned_amount__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="upgrade_row_unpinned_iff_null_amount",
            ),
        ),
    ]
