# Generated by Django 6.0.6 on 2026-07-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0154_reconcile_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backfill",
            name="operation",
            field=models.CharField(
                choices=[
                    (
                        "migrate_persistent_stash",
                        "Migrate persistent stash items (#1825)",
                    ),
                    ("reconcile_lists", "Reconcile list cost caches (#1826 Phase 8)"),
                    ("backfill_pins", "Backfill acquisition receipts (#1826 Phase 8)"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="backfill",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="done",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbackfill",
            name="operation",
            field=models.CharField(
                choices=[
                    (
                        "migrate_persistent_stash",
                        "Migrate persistent stash items (#1825)",
                    ),
                    ("reconcile_lists", "Reconcile list cost caches (#1826 Phase 8)"),
                    ("backfill_pins", "Backfill acquisition receipts (#1826 Phase 8)"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbackfill",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="done",
                max_length=16,
            ),
        ),
    ]
