# Generated by Django 6.0.6 on 2026-07-05 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0155_backfill_pin_operations"),
        ("core", "0155_drop_stale_card_theme_column"),
    ]

    operations = []
