# Generated by Django 6.0.6 on 2026-07-06 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0160_add_notification_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalBackfill",
        ),
    ]
