# Generated by Django 6.0.6 on 2026-07-07 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0161_add_list_fighter_counter_spend"),
        ("core", "0161_drop_backfill_history"),
    ]

    operations = []
