# Generated by Django 6.0.6 on 2026-07-07 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0162_backfill_cancelled_status"),
        ("core", "0162_merge_20260707_2105"),
    ]

    operations = []
