# Generated by Django 6.0.7 on 2026-07-11 21:57, then hand-edited to make the
# participants M2M -> through(BattleParticipant) conversion data-safe.

import uuid

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def copy_participants_to_through(apps, schema_editor):
    """
    Copy existing (battle, list) rows from the implicit M2M table into the new
    BattleParticipant through model, so switching the M2M to a through model
    does not lose participants. Role is left unset.
    """
    Battle = apps.get_model("core", "Battle")
    BattleParticipant = apps.get_model("core", "BattleParticipant")

    for battle in Battle.objects.all().iterator():
        for lst in battle.participants.all():
            BattleParticipant.objects.get_or_create(
                battle=battle,
                list=lst,
                defaults={"owner_id": battle.owner_id},
            )


def set_existing_battles_post_battle(apps, schema_editor):
    """
    Existing battles are historical reports (already fought), so move them to
    the terminal post-battle state. New battles start at pre_battle.
    """
    Battle = apps.get_model("core", "Battle")
    Battle.objects.update(status="post_battle")


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0178_battle_roles"),
        ("core", "0163_merge_20260707_2141"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_battle", "Pre-battle"),
                    ("in_progress", "In progress"),
                    ("post_battle", "Post-battle"),
                ],
                db_index=True,
                default="pre_battle",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalbattle",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_battle", "Pre-battle"),
                    ("in_progress", "In progress"),
                    ("post_battle", "Post-battle"),
                ],
                db_index=True,
                default="pre_battle",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="The date of the battle (leave blank until it is scheduled or played)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="battle",
            name="winners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gangs that won the battle (leave empty for a draw)",
                related_name="battles_won",
                to="core.list",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbattle",
            name="date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="The date of the battle (leave blank until it is scheduled or played)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BattleStateTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("to_status", models.CharField(db_index=True, max_length=50)),
                (
                    "transitioned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_state_transitions",
                        to="core.battle",
                    ),
                ),
            ],
            options={
                "verbose_name": "battle state transition",
                "verbose_name_plural": "battle state transitions",
                "ordering": ["-transitioned_at"],
            },
        ),
        migrations.CreateModel(
            name="BattleParticipant",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "battle",
                    models.ForeignKey(
                        help_text="The battle this participant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_entries",
                        to="core.battle",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        help_text="The participating gang",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_participations",
                        to="core.list",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role_option",
                    models.ForeignKey(
                        blank=True,
                        help_text="The role this gang took in the battle (e.g. Attacker or Defender)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battle_participants",
                        to="content.contentbattleroleoption",
                    ),
                ),
            ],
            options={
                "ordering": ["role_option__name", "created"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBattleParticipant",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The battle this participant belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.battle",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The participating gang",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.list",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role_option",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The role this gang took in the battle (e.g. Attacker or Defender)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="content.contentbattleroleoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical battle participant",
                "verbose_name_plural": "historical battle participants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="battleparticipant",
            constraint=models.UniqueConstraint(
                fields=("battle", "list"), name="unique_battle_participant"
            ),
        ),
        # Copy existing participants into the through table BEFORE the M2M is
        # repointed, so no participant rows are lost.
        migrations.RunPython(
            copy_participants_to_through,
            migrations.RunPython.noop,
            elidable=True,
        ),
        # Repoint the participants M2M at the new through model as a STATE-ONLY
        # change. We deliberately do not touch the database here: the old
        # implicit `core_battle_participants` table is left in place (an
        # orphan) rather than renamed/dropped, which avoids any risk of losing
        # data during the switch. It can be dropped in a later migration once
        # the through model is confirmed good in production.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="battle",
                    name="participants",
                    field=models.ManyToManyField(
                        help_text="Gangs taking part in the battle",
                        related_name="battles_participated",
                        through="core.BattleParticipant",
                        to="core.list",
                    ),
                ),
            ],
            database_operations=[],
        ),
        # Existing battles are completed reports: move them to post-battle.
        migrations.RunPython(
            set_existing_battles_post_battle,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
