# Generated by Django 6.0.7 on 2026-07-12 10:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0165_list_cloning_in_progress_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonationLog",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the impersonation session ended (null while active).",
                        null=True,
                    ),
                ),
                (
                    "ended_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Stopped manually"),
                            ("logout", "Logged out"),
                            ("expired", "Timed out"),
                            ("revoked", "Ended automatically"),
                        ],
                        help_text="Why the impersonation session ended.",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who was impersonated.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impersonated_by_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "impersonation log",
                "verbose_name_plural": "impersonation logs",
                "ordering": ["-created"],
            },
        ),
    ]
