# Generated by Django 6.0.7 on 2026-07-12 13:06

import django.db.models.deletion
import n23.core.models.crew
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0167_campaign_admins"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for this crew.",
                        max_length=255,
                    ),
                ),
                (
                    "random_spec",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="How many random fighters to draw at battle start, in addition to the chosen ones. A number (6), a die (D3), or die + number (D3+4).",
                        max_length=20,
                        validators=[n23.core.models.crew.validate_selection_spec],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("locked", "Locked")],
                        default="draft",
                        help_text="Draft while being set up; locked once drawn at battle start.",
                        max_length=10,
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        help_text="The battle this crew fights in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crews",
                        to="core.battle",
                    ),
                ),
                (
                    "chosen_fighters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Fighters the player specifically picks for the crew.",
                        related_name="chosen_in_crews",
                        to="core.listfighter",
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        help_text="The gang this crew is drawn from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crews",
                        to="core.list",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crew",
                "verbose_name_plural": "Crews",
                "ordering": ["list__name", "created"],
            },
        ),
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "was_random",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this fighter was drawn randomly (audit of the draw).",
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        help_text="The crew this member belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.crew",
                    ),
                ),
                (
                    "equipment_set",
                    models.ForeignKey(
                        blank=True,
                        help_text="The equipment set (loadout) this fighter brings to the battle. Blank means their full kit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crew_memberships",
                        to="core.listfighterequipmentset",
                    ),
                ),
                (
                    "list_fighter",
                    models.ForeignKey(
                        help_text="The fighter attending the battle.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_memberships",
                        to="core.listfighter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crew Member",
                "verbose_name_plural": "Crew Members",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="CrewLineItem",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "label",
                    models.CharField(
                        help_text="What this is (e.g. 'Tactics card: Ambush').",
                        max_length=255,
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        default=0, help_text="Credits value of this item."
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("credits", "Gang credits"),
                            ("free", "Free"),
                            ("allowance", "Allowance"),
                        ],
                        default="credits",
                        help_text="How this is paid for (descriptive; no credits are moved).",
                        max_length=12,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Why, when free or from an allowance.",
                        max_length=255,
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        help_text="The crew this line item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="core.crew",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="The crew member this item is attached to, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="core.crewmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crew Line Item",
                "verbose_name_plural": "Crew Line Items",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCrew",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for this crew.",
                        max_length=255,
                    ),
                ),
                (
                    "random_spec",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="How many random fighters to draw at battle start, in addition to the chosen ones. A number (6), a die (D3), or die + number (D3+4).",
                        max_length=20,
                        validators=[n23.core.models.crew.validate_selection_spec],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("locked", "Locked")],
                        default="draft",
                        help_text="Draft while being set up; locked once drawn at battle start.",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The battle this crew fights in.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.battle",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The gang this crew is drawn from.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.list",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Crew",
                "verbose_name_plural": "historical Crews",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCrewLineItem",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="What this is (e.g. 'Tactics card: Ambush').",
                        max_length=255,
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        default=0, help_text="Credits value of this item."
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("credits", "Gang credits"),
                            ("free", "Free"),
                            ("allowance", "Allowance"),
                        ],
                        default="credits",
                        help_text="How this is paid for (descriptive; no credits are moved).",
                        max_length=12,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Why, when free or from an allowance.",
                        max_length=255,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The crew this line item belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.crew",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The crew member this item is attached to, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.crewmember",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Crew Line Item",
                "verbose_name_plural": "historical Crew Line Items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCrewMember",
            fields=[
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "was_random",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this fighter was drawn randomly (audit of the draw).",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The crew this member belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.crew",
                    ),
                ),
                (
                    "equipment_set",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The equipment set (loadout) this fighter brings to the battle. Blank means their full kit.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighterequipmentset",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "list_fighter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The fighter attending the battle.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.listfighter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Crew Member",
                "verbose_name_plural": "historical Crew Members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="crew",
            constraint=models.UniqueConstraint(
                fields=("battle", "list"), name="unique_crew_per_gang_per_battle"
            ),
        ),
        migrations.AddConstraint(
            model_name="crewmember",
            constraint=models.UniqueConstraint(
                fields=("crew", "list_fighter"), name="unique_fighter_per_crew"
            ),
        ),
    ]
