# Generated by Django 6.0.7 on 2026-07-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0173_drop_crew_member_was_random"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="rating_locked",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The crew's rating at the moment it was locked. Blank on a draft, and on crews locked before snapshotting existed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crewmember",
            name="rating_locked",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="This member's contribution to the crew's rating at the moment the crew was locked. Blank until then.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcrew",
            name="rating_locked",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The crew's rating at the moment it was locked. Blank on a draft, and on crews locked before snapshotting existed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcrewmember",
            name="rating_locked",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="This member's contribution to the crew's rating at the moment the crew was locked. Blank until then.",
                null=True,
            ),
        ),
    ]
