# Generated by Django 6.0.7 on 2026-07-19 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0177_crew_rating_selected_and_played"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="crew",
            name="unique_crew_per_gang_per_battle",
        ),
        migrations.AddConstraint(
            model_name="crew",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived", False)),
                fields=("battle", "list"),
                name="unique_crew_per_gang_per_battle",
            ),
        ),
    ]
