# Generated by Django 6.0.7 on 2026-07-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0178_crew_archived_unique_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewmember",
            name="source",
            field=models.CharField(
                choices=[
                    ("chosen", "Chosen"),
                    ("random", "Drawn at random"),
                    ("linked", "Linked to owner"),
                ],
                default="chosen",
                help_text="How this fighter joined the crew (audit of the draw).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcrewmember",
            name="source",
            field=models.CharField(
                choices=[
                    ("chosen", "Chosen"),
                    ("random", "Drawn at random"),
                    ("linked", "Linked to owner"),
                ],
                default="chosen",
                help_text="How this fighter joined the crew (audit of the draw).",
                max_length=10,
            ),
        ),
    ]
