# Generated by Django 6.0.7 on 2026-07-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0187_campaign_default_gang_sort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crew",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("locked", "Membership locked")],
                default="draft",
                help_text="Draft while being set up; locked once drawn at battle start.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcrew",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("locked", "Membership locked")],
                default="draft",
                help_text="Draft while being set up; locked once drawn at battle start.",
                max_length=10,
            ),
        ),
    ]
