# Generated by Django 6.0.7 on 2026-07-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0192_crew_line_item_label_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="crewlineitem",
            name="rating_value",
            field=models.PositiveIntegerField(
                default=0,
                help_text="What this adds to the crew's rating. Independent of what it cost: a hired gun taken for free still fights, so it still counts.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcrewlineitem",
            name="rating_value",
            field=models.PositiveIntegerField(
                default=0,
                help_text="What this adds to the crew's rating. Independent of what it cost: a hired gun taken for free still fights, so it still counts.",
            ),
        ),
        migrations.AlterField(
            model_name="crewlineitem",
            name="cost",
            field=models.PositiveIntegerField(
                default=0,
                help_text="What the gang pays for it, from whichever source ``payment`` names. Zero for a free entry.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcrewlineitem",
            name="cost",
            field=models.PositiveIntegerField(
                default=0,
                help_text="What the gang pays for it, from whichever source ``payment`` names. Zero for a free entry.",
            ),
        ),
    ]
