# Generated by Django 6.0.7 on 2026-07-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0197_print_config_include_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprintconfig",
            name="include_lore_notes",
            field=models.BooleanField(
                default=False,
                help_text="Include a Lore & Notes card for the gang and for each fighter who has either, printed alongside the Fighter cards.",
            ),
        ),
        migrations.AddField(
            model_name="printconfig",
            name="include_lore_notes",
            field=models.BooleanField(
                default=False,
                help_text="Include a Lore & Notes card for the gang and for each fighter who has either, printed alongside the Fighter cards.",
            ),
        ),
    ]
