# Generated by Django 6.0.7 on 2026-07-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0198_print_config_include_lore_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignaction",
            name="template_campaign",
            field=models.ForeignKey(
                blank=True,
                help_text="The template campaign this action refers to, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_campaign_actions",
                to="core.campaign",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaignaction",
            name="template_campaign",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The template campaign this action refers to, if any",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.campaign",
            ),
        ),
    ]
