# Generated by Django 6.0.7 on 2026-08-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0200_add_fix_stat_advancements_backfill_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backfill",
            name="operation",
            field=models.CharField(
                choices=[
                    (
                        "migrate_persistent_stash",
                        "Migrate persistent stash items (#1825)",
                    ),
                    ("reconcile_lists", "Reconcile list cost caches (#1826 Phase 8)"),
                    ("backfill_pins", "Backfill acquisition receipts (#1826 Phase 8)"),
                    (
                        "fix_stat_advancements",
                        "Finish the stat-advancement cleanup (#2070)",
                    ),
                    (
                        "normalise_stat_formats",
                        "Normalise legacy stat-column formats (#1861 C0)",
                    ),
                    (
                        "materialise_statlines",
                        "Materialise statlines for legacy templates (#1861 C1)",
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
