# Generated by Django 6.0.7 on 2026-08-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0201_statline_backfill_operations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backfill",
            name="operation",
            field=models.CharField(
                choices=[
                    (
                        "migrate_persistent_stash",
                        "Migrate persistent stash items (#1825)",
                    ),
                    ("reconcile_lists", "Reconcile list cost caches (#1826 Phase 8)"),
                    ("backfill_pins", "Backfill acquisition receipts (#1826 Phase 8)"),
                    (
                        "fix_stat_advancements",
                        "Finish the stat-advancement cleanup (#2070)",
                    ),
                    (
                        "normalise_stat_formats",
                        "Normalise legacy stat-column formats (#1861 Track C1)",
                    ),
                    (
                        "materialise_statlines",
                        "Materialise statlines for legacy templates (#1861 Track C1)",
                    ),
                    (
                        "migrate_stat_overrides",
                        "Migrate fighter stat overrides to the override store (#1861 Track C2)",
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
