# Generated by Django 6.0.7 on 2026-08-04 22:20

from django.db import migrations


MOVED = ["banner", "historicalbanner", "impersonationlog"]


def content_types_to_platform(apps, schema_editor):
    """Carry the ContentType rows over rather than letting post_migrate make new
    ones — same ids means attached permissions follow automatically."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="core", model__in=MOVED).update(
        app_label="gyrinxsite"
    )


def content_types_to_core(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="gyrinxsite", model__in=MOVED).update(
        app_label="core"
    )


class Migration(migrations.Migration):
    """Release Banner and ImpersonationLog from `core` — state only."""

    dependencies = [
        ("core", "0203_move_userprofile_to_accounts"),
        ("gyrinxsite", "0001_move_site_models_to_platform"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="historicalbanner",
                    name="history_user",
                ),
                migrations.RemoveField(
                    model_name="historicalbanner",
                    name="owner",
                ),
                migrations.RemoveField(
                    model_name="impersonationlog",
                    name="owner",
                ),
                migrations.RemoveField(
                    model_name="impersonationlog",
                    name="target",
                ),
                migrations.DeleteModel(
                    name="Banner",
                ),
                migrations.DeleteModel(
                    name="HistoricalBanner",
                ),
                migrations.DeleteModel(
                    name="ImpersonationLog",
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(content_types_to_platform, content_types_to_core),
    ]
