# Generated by Django 6.0.7 on 2026-08-04 22:20

from django.db import migrations

MOVED = ["banner", "historicalbanner", "impersonationlog"]


def _move_content_types(apps, from_label, to_label, models):
    """Carry ContentType rows between app labels, in place and idempotently.

    In place so the id survives: every permission grant and generic reference
    points at that id, and minting a new row would orphan them.

    The stray-clearing step is what makes a rollback survivable. Unapplying this
    migration leaves the model in the migration state, so post_migrate mints a
    fresh row under the label we are moving *to*; without clearing it first, the
    update below collides on the (app_label, model) unique constraint the next
    time this runs. Its permissions are auto-created and referenced by nothing —
    the real grants hang off the original row — so they go with it.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    for model in models:
        original = ContentType.objects.filter(app_label=from_label, model=model).first()
        if original is None:
            continue  # already moved, or never existed — nothing to carry

        stray = ContentType.objects.filter(app_label=to_label, model=model).exclude(
            pk=original.pk
        )
        Permission.objects.filter(content_type__in=stray).delete()
        stray.delete()

        ContentType.objects.filter(pk=original.pk).update(app_label=to_label)


def content_types_to_platform(apps, schema_editor):
    """Carry the ContentType rows over rather than letting post_migrate make new
    ones — same ids means attached permissions follow automatically."""
    _move_content_types(apps, "core", "gyrinxsite", MOVED)


def content_types_to_core(apps, schema_editor):
    _move_content_types(apps, "gyrinxsite", "core", MOVED)


class Migration(migrations.Migration):
    """Release Banner and ImpersonationLog from `core` — state only."""

    dependencies = [
        ("core", "0203_move_userprofile_to_accounts"),
        ("gyrinxsite", "0001_move_site_models_to_platform"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="historicalbanner",
                    name="history_user",
                ),
                migrations.RemoveField(
                    model_name="historicalbanner",
                    name="owner",
                ),
                migrations.RemoveField(
                    model_name="impersonationlog",
                    name="owner",
                ),
                migrations.RemoveField(
                    model_name="impersonationlog",
                    name="target",
                ),
                migrations.DeleteModel(
                    name="Banner",
                ),
                migrations.DeleteModel(
                    name="HistoricalBanner",
                ),
                migrations.DeleteModel(
                    name="ImpersonationLog",
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(content_types_to_platform, content_types_to_core),
    ]
