# Generated by Django 6.0.7 on 2026-08-04 22:26

from django.db import migrations


def _move_content_types(apps, from_label, to_label, models):
    """Carry ContentType rows between app labels, in place and idempotently.

    In place so the id survives: every permission grant and generic reference
    points at that id, and minting a new row would orphan them.

    The stray-clearing step is what makes a rollback survivable. Unapplying this
    migration leaves the model in the migration state, so post_migrate mints a
    fresh row under the label we are moving *to*; without clearing it first, the
    update below collides on the (app_label, model) unique constraint the next
    time this runs. Its permissions are auto-created and referenced by nothing —
    the real grants hang off the original row — so they go with it.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    for model in models:
        original = ContentType.objects.filter(app_label=from_label, model=model).first()
        if original is None:
            continue  # already moved, or never existed — nothing to carry

        stray = ContentType.objects.filter(app_label=to_label, model=model).exclude(
            pk=original.pk
        )
        Permission.objects.filter(content_type__in=stray).delete()
        stray.delete()

        ContentType.objects.filter(pk=original.pk).update(app_label=to_label)


def content_type_to_analytics(apps, schema_editor):
    """Carry the ContentType row over in place, keeping its id so attached
    permissions and any GenericForeignKey referencing it stay valid."""
    _move_content_types(apps, "core", "analytics", ["event"])


def content_type_to_core(apps, schema_editor):
    _move_content_types(apps, "analytics", "core", ["event"])


class Migration(migrations.Migration):
    """Release Event from `core` — state only, table and indexes untouched."""

    dependencies = [
        ("core", "0204_move_site_models_to_platform"),
        ("analytics", "0001_move_event_to_analytics"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="event",
                    name="core_event_created_409a4e_idx",
                ),
                migrations.RemoveIndex(
                    model_name="event",
                    name="core_event_noun_20866e_idx",
                ),
                migrations.RemoveIndex(
                    model_name="event",
                    name="core_event_owner_i_e0a4d8_idx",
                ),
                migrations.RemoveIndex(
                    model_name="event",
                    name="core_event_object__934a15_idx",
                ),
                migrations.DeleteModel(
                    name="Event",
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(content_type_to_analytics, content_type_to_core),
    ]
