# Generated by Django 6.0.7 on 2026-08-04 22:26

from django.db import migrations


def content_type_to_analytics(apps, schema_editor):
    """Carry the ContentType row over in place, keeping its id so attached
    permissions and any GenericForeignKey referencing it stay valid."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="core", model="event").update(
        app_label="analytics"
    )


def content_type_to_core(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="analytics", model="event").update(
        app_label="core"
    )


class Migration(migrations.Migration):
    """Release Event from `core` — state only, table and indexes untouched."""

    dependencies = [
        ("core", "0204_move_site_models_to_platform"),
        ("analytics", "0001_move_event_to_analytics"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="event",
                    name="core_event_created_409a4e_idx",
                ),
                migrations.RemoveIndex(
                    model_name="event",
                    name="core_event_noun_20866e_idx",
                ),
                migrations.RemoveIndex(
                    model_name="event",
                    name="core_event_owner_i_e0a4d8_idx",
                ),
                migrations.RemoveIndex(
                    model_name="event",
                    name="core_event_object__934a15_idx",
                ),
                migrations.DeleteModel(
                    name="Event",
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(content_type_to_analytics, content_type_to_core),
    ]
