# Generated by Django 6.0.7 on 2026-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0206_retire_stat_advancement_cleanup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="attacks_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="ballistic_skill_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="cool_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="initiative_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="intelligence_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="leadership_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="movement_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="strength_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="toughness_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="weapon_skill_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="willpower_override",
        ),
        migrations.RemoveField(
            model_name="historicallistfighter",
            name="wounds_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="attacks_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="ballistic_skill_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="cool_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="initiative_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="intelligence_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="leadership_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="movement_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="strength_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="toughness_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="weapon_skill_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="willpower_override",
        ),
        migrations.RemoveField(
            model_name="listfighter",
            name="wounds_override",
        ),
        migrations.AlterField(
            model_name="backfill",
            name="operation",
            field=models.CharField(
                choices=[
                    (
                        "migrate_persistent_stash",
                        "Migrate persistent stash items (#1825)",
                    ),
                    ("reconcile_lists", "Reconcile list cost caches (#1826 Phase 8)"),
                    ("backfill_pins", "Backfill acquisition receipts (#1826 Phase 8)"),
                    (
                        "fix_stat_advancements",
                        "Finish the stat-advancement cleanup (#2070, retired)",
                    ),
                    (
                        "normalise_stat_formats",
                        "Normalise legacy stat-column formats (#1861 Track C1)",
                    ),
                    (
                        "materialise_statlines",
                        "Materialise statlines for legacy templates (#1861 Track C1)",
                    ),
                    (
                        "migrate_stat_overrides",
                        "Migrate fighter stat overrides to the override store (#1861 Track C2, retired)",
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
