# Generated by Django 6.0.7 on 2026-08-05 22:08

from django.db import migrations


def content_type_to_platform(apps, schema_editor):
    """Carry the ContentType row over in place, keeping its id so attached
    permissions and any GenericForeignKey referencing it stay valid."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="core", model="notification").update(
        app_label="gyrinxsite"
    )


def content_type_to_core(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="gyrinxsite", model="notification").update(
        app_label="core"
    )


class Migration(migrations.Migration):
    """Release Notification from `core` — state only, table and indexes untouched.

    Unlike the earlier model moves there is no parallel Historical* table to
    pin: this model deliberately declares no HistoricalRecords.
    """

    dependencies = [
        ("core", "0211_drop_notification_related_columns"),
        ("gyrinxsite", "0002_move_notification_to_platform"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="notification",
                    name="notif_unread_idx",
                ),
                migrations.RemoveIndex(
                    model_name="notification",
                    name="notif_inbox_idx",
                ),
                migrations.RemoveIndex(
                    model_name="notification",
                    name="notif_banner_target_idx",
                ),
                migrations.RemoveIndex(
                    model_name="notification",
                    name="notif_banner_scope_idx",
                ),
                migrations.DeleteModel(
                    name="Notification",
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(content_type_to_platform, content_type_to_core),
    ]
