# Generated by Django 6.0.7 on 2026-08-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0212_move_notification_to_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallistfighteradvancement",
            name="uses_mod_system",
            field=models.BooleanField(
                default=True,
                help_text="If True (all new advancements), a stat advancement is applied by the mod system, computed when the card is rendered. If False, the advancement predates that system: it applies nothing, and the improvement it bought is held as a stat override on the fighter.",
            ),
        ),
        migrations.AlterField(
            model_name="listfighteradvancement",
            name="uses_mod_system",
            field=models.BooleanField(
                default=True,
                help_text="If True (all new advancements), a stat advancement is applied by the mod system, computed when the card is rendered. If False, the advancement predates that system: it applies nothing, and the improvement it bought is held as a stat override on the fighter.",
            ),
        ),
    ]
