# Generated by Django 6.0.7 on 2026-09-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0215_remove_stray_notification_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignresourcetype",
            name="can_go_negative",
            field=models.BooleanField(
                default=False,
                help_text="Gangs can hold a negative amount of this resource.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcampaignresourcetype",
            name="can_go_negative",
            field=models.BooleanField(
                default=False,
                help_text="Gangs can hold a negative amount of this resource.",
            ),
        ),
        migrations.AlterField(
            model_name="campaignlistresource",
            name="amount",
            field=models.IntegerField(
                default=0, help_text="Current amount of this resource"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcampaignlistresource",
            name="amount",
            field=models.IntegerField(
                default=0, help_text="Current amount of this resource"
            ),
        ),
    ]
