# Generated by Django 6.0.7 on 2026-09-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0216_campaign_resource_can_go_negative"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprintconfig",
            name="orientation",
            field=models.CharField(
                choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                default="portrait",
                help_text="Which way round the paper goes.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="printconfig",
            name="orientation",
            field=models.CharField(
                choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                default="portrait",
                help_text="Which way round the paper goes.",
                max_length=20,
            ),
        ),
    ]
