# Generated by Django 6.0.7 on 2026-09-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0216_campaign_resource_can_go_negative"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprintconfig",
            name="orientation",
            field=models.CharField(
                choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                default="portrait",
                help_text="Which way round the paper goes.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="printconfig",
            name="orientation",
            field=models.CharField(
                choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                default="portrait",
                help_text="Which way round the paper goes.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprintconfig",
            name="card_style",
            field=models.CharField(
                choices=[
                    ("web", "Web cards (standard)"),
                    ("classic", "Classic cards (grimdark, fixed size)"),
                ],
                default="web",
                help_text="Which card style to print.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="printconfig",
            name="card_style",
            field=models.CharField(
                choices=[
                    ("web", "Web cards (standard)"),
                    ("classic", "Classic cards (grimdark, fixed size)"),
                ],
                default="web",
                help_text="Which card style to print.",
                max_length=20,
            ),
        ),
    ]
