# Generated by Django 5.1.5 on 2025-01-25 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=150)),
                ("event", models.CharField(blank=True, max_length=150)),
                ("payload", models.JSONField()),
                ("signature", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
