# Generated by Django 5.1.5 on 2025-01-26 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhookrequest",
            options={
                "verbose_name": "webhook request",
                "verbose_name_plural": "webhook requests",
            },
        ),
    ]
