# Generated by Django 5.1.5 on 2025-02-08 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_webhookrequest_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhookrequest",
            options={
                "ordering": ["-created"],
                "verbose_name": "webhook request",
                "verbose_name_plural": "webhook requests",
            },
        ),
    ]
