# Generated by Django 5.2.4 on 2025-08-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_webhookrequest_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookrequest",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="webhookrequest",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
