"""
List and fighter views package.

This package re-exports all symbols from both the list/ and fighter/ subdirectories
for backward compatibility.
"""

from gyrinx.core.views import make_query_params_str

# List views
from gyrinx.core.views.list.attributes import edit_list_attribute
from gyrinx.core.views.list.common import get_clean_list_or_404
from gyrinx.core.views.list.invitations import (
    accept_invitation,
    decline_invitation,
    list_invitations,
)
from gyrinx.core.views.list.views import (
    ListAboutDetailView,
    ListCampaignClonesView,
    ListDetailView,
    ListPerformanceView,
    ListPrintView,
    ListsListView,
    archive_list,
    clone_list,
    edit_list,
    edit_list_credits,
    new_list,
    refresh_list_cost,
    show_stash,
)

# Fighter views - re-exported for backward compatibility
from gyrinx.core.views.fighter import (
    AdvancementBaseParams,
    AdvancementFlowParams,
    ListArchivedFightersView,
    add_list_fighter_rule,
    add_list_fighter_skill,
    apply_skill_advancement,
    archive_list_fighter,
    can_fighter_roll_dice_for_advancement,
    clone_list_fighter,
    convert_list_fighter_default_assign,
    delete_list_fighter,
    delete_list_fighter_advancement,
    delete_list_fighter_assign,
    delete_list_fighter_gear_upgrade,
    delete_list_fighter_weapon_accessory,
    delete_list_fighter_weapon_profile,
    disable_list_fighter_default_assign,
    edit_list_fighter,
    edit_list_fighter_assign_cost,
    edit_list_fighter_equipment,
    edit_list_fighter_info,
    edit_list_fighter_narrative,
    edit_list_fighter_powers,
    edit_list_fighter_rules,
    edit_list_fighter_skills,
    edit_list_fighter_weapon_accessories,
    edit_list_fighter_weapon_upgrade,
    edit_list_fighter_xp,
    edit_single_weapon,
    embed_list_fighter,
    filter_equipment_assignments_for_duplicates,
    kill_list_fighter,
    list_fighter_add_injury,
    list_fighter_advancement_confirm,
    list_fighter_advancement_dice_choice,
    list_fighter_advancement_other,
    list_fighter_advancement_select,
    list_fighter_advancement_start,
    list_fighter_advancement_type,
    list_fighter_advancements,
    list_fighter_injuries_edit,
    list_fighter_remove_injury,
    list_fighter_state_edit,
    list_fighter_stats_edit,
    mark_fighter_captured,
    new_list_fighter,
    reassign_list_fighter_equipment,
    remove_list_fighter_rule,
    remove_list_fighter_skill,
    restore_list_fighter,
    resurrect_list_fighter,
    sell_list_fighter_equipment,
    toggle_list_fighter_rule,
    toggle_list_fighter_skill,
)

__all__ = [
    # common.py
    "get_clean_list_or_404",
    # attributes.py
    "edit_list_attribute",
    # invitations.py
    "list_invitations",
    "accept_invitation",
    "decline_invitation",
    # views.py (list views)
    "ListsListView",
    "ListDetailView",
    "ListPerformanceView",
    "ListAboutDetailView",
    "ListPrintView",
    "ListCampaignClonesView",
    "new_list",
    "edit_list",
    "edit_list_credits",
    "archive_list",
    "show_stash",
    "refresh_list_cost",
    "clone_list",
    "make_query_params_str",
    # Fighter views (re-exported for backward compatibility)
    "new_list_fighter",
    "edit_list_fighter",
    "clone_list_fighter",
    "archive_list_fighter",
    "restore_list_fighter",
    "kill_list_fighter",
    "resurrect_list_fighter",
    "delete_list_fighter",
    "embed_list_fighter",
    "ListArchivedFightersView",
    "edit_list_fighter_skills",
    "add_list_fighter_skill",
    "remove_list_fighter_skill",
    "toggle_list_fighter_skill",
    "edit_list_fighter_powers",
    "edit_list_fighter_narrative",
    "edit_list_fighter_info",
    "list_fighter_stats_edit",
    "edit_list_fighter_equipment",
    "edit_list_fighter_assign_cost",
    "delete_list_fighter_assign",
    "delete_list_fighter_gear_upgrade",
    "edit_list_fighter_weapon_accessories",
    "edit_single_weapon",
    "delete_list_fighter_weapon_profile",
    "delete_list_fighter_weapon_accessory",
    "edit_list_fighter_weapon_upgrade",
    "disable_list_fighter_default_assign",
    "convert_list_fighter_default_assign",
    "reassign_list_fighter_equipment",
    "sell_list_fighter_equipment",
    "list_fighter_injuries_edit",
    "list_fighter_state_edit",
    "mark_fighter_captured",
    "list_fighter_add_injury",
    "list_fighter_remove_injury",
    "edit_list_fighter_xp",
    "AdvancementBaseParams",
    "AdvancementFlowParams",
    "can_fighter_roll_dice_for_advancement",
    "filter_equipment_assignments_for_duplicates",
    "apply_skill_advancement",
    "list_fighter_advancements",
    "delete_list_fighter_advancement",
    "list_fighter_advancement_start",
    "list_fighter_advancement_dice_choice",
    "list_fighter_advancement_type",
    "list_fighter_advancement_confirm",
    "list_fighter_advancement_select",
    "list_fighter_advancement_other",
    "edit_list_fighter_rules",
    "toggle_list_fighter_rule",
    "add_list_fighter_rule",
    "remove_list_fighter_rule",
]
